// front/univents/src/features/profile/ui/profile-header.tsx
import { Link } from "@tanstack/react-router";
import { Calendar, Mail, Pencil, Settings } from "lucide-react";
import { cn } from "@/shared/lib/utils";
import { Avatar, AvatarFallback, AvatarImage } from "@/shared/ui/shadcn/avatar";
import { buttonVariants } from "@/shared/ui/shadcn/button";
import type { UniventsProfile } from "../model/profile-data";
import { ProfileShareDialog } from "./profile-share-dialog";

interface ProfileHeaderProps {
  profile: UniventsProfile;
  name: string;
  handle?: string;
  ownProfile: boolean;
  profileUrl: string;
  activeTab: "about" | "badges" | "certificates" | "purchases";
  onTabChange: (tab: "about" | "badges" | "certificates" | "purchases") => void;
}

export function ProfileHeader({
  profile,
  name,
  handle,
  ownProfile,
  profileUrl,
  activeTab,
  onTabChange,
}: ProfileHeaderProps) {
  const bannerStyle = profile.bannerUrl
    ? {
        backgroundImage: `url(${profile.bannerUrl})`,
        backgroundSize: "cover",
        backgroundPosition: "center",
      }
    : undefined;

  return (
    <section className="relative w-full border-b border-border bg-card shadow-md">
      <div
        className={cn(
          "h-40 w-full bg-background bg-linear-to-br",
          "from-primary/40 via-primary/15 to-muted sm:h-48 md:h-56",
        )}
        style={bannerStyle}
      />

      <div className="md:hidden">
        {ownProfile && (
          <ProfileShareDialog
            profileUrl={profileUrl}
            className="absolute right-4 top-4"
          />
        )}
        <div className="relative mx-auto px-4">
          <div className="flex -mt-12 flex-col items-center">
            <ProfileAvatar
              name={name}
              imageUrl={profile.pfpUrl}
              size="mobile"
            />
          </div>
          <div className="mt-3 pb-4 text-center">
            <div className="flex items-baseline justify-center gap-2">
              <h1 className="text-2xl font-semibold text-card-foreground">
                {name}
              </h1>
              {profile.pronouns && (
                <span className="text-sm text-muted-foreground">
                  {profile.pronouns}
                </span>
              )}
            </div>
            {handle && (
              <p className="text-sm text-muted-foreground">
                @{handle.replace(/^@/, "")}
              </p>
            )}
            {profile.legalName &&
              profile.legalName !== name &&
              profile.visibility?.hideLegalName === false && (
                <p className="text-sm text-muted-foreground">
                  {profile.legalName}
                </p>
              )}
            {(profile.role || profile.organization) && (
              <p className="mt-1 text-sm text-muted-foreground">
                {[profile.role, profile.organization]
                  .filter(Boolean)
                  .join(" · ")}
              </p>
            )}
            <MemberSince createdAt={profile.createdAt} centered />
            {profile.contactEmail && (
              <a
                href={`mailto:${profile.contactEmail}`}
                className="mt-1 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
              >
                <Mail className="size-3.5" />
                {profile.contactEmail}
              </a>
            )}
          </div>
          {ownProfile && (
            <div className="mb-4 flex gap-2">
              <Link
                to="/profile/edit"
                search={{ returnTo: undefined }}
                className={buttonVariants({
                  className: "h-11 flex-1 rounded-lg shadow-sm",
                })}
              >
                <Pencil className="mr-2 size-4" />
                Editar perfil
              </Link>
              <Link
                to="/profile/config"
                className={buttonVariants({
                  variant: "outline",
                  size: "icon",
                  className: "size-11 shrink-0 rounded-lg shadow-sm",
                })}
                aria-label="Configurações do perfil"
              >
                <Settings className="size-4" />
              </Link>
            </div>
          )}
        </div>
      </div>

      <div className="mx-auto hidden max-w-7xl px-4 md:block">
        <div className="relative pb-6">
          <div className="absolute -top-16">
            <ProfileAvatar
              name={name}
              imageUrl={profile.pfpUrl}
              size="desktop"
            />
          </div>
          {ownProfile && <DesktopActions profileUrl={profileUrl} />}
          <div className="pt-18">
            <div className="flex items-baseline gap-2">
              <h1 className="text-3xl font-semibold tracking-tight text-card-foreground">
                {name}
              </h1>
              {profile.pronouns && (
                <span className="text-sm text-muted-foreground">
                  {profile.pronouns}
                </span>
              )}
            </div>
            {handle && (
              <p className="text-sm text-muted-foreground">
                @{handle.replace(/^@/, "")}
              </p>
            )}
            {profile.legalName &&
              profile.legalName !== name &&
              profile.visibility?.hideLegalName === false && (
                <p className="text-sm text-muted-foreground">
                  {profile.legalName}
                </p>
              )}
            {(profile.role || profile.organization) && (
              <p className="text-[15px] text-muted-foreground">
                {[profile.role, profile.organization]
                  .filter(Boolean)
                  .join(" · ")}
              </p>
            )}
            <MemberSince createdAt={profile.createdAt} />
          </div>
        </div>
      </div>
      <div className="relative mx-auto max-w-7xl">
        <nav className="flex overflow-x-auto px-4 pr-12 sm:pr-4">
          {(
            [
              ["about", "Sobre"],
              ["badges", "Crachás"],
              ...(ownProfile
                ? ([
                    ["certificates", "Certificados"],
                    ["purchases", "Compras"],
                  ] as const)
                : []),
            ] as Array<
              ["about" | "badges" | "certificates" | "purchases", string]
            >
          ).map(([tab, label]) => (
            <button
              key={tab}
              type="button"
              onClick={() => onTabChange(tab)}
              className={cn(
                "shrink-0 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium transition-colors",
                activeTab === tab
                  ? "border-primary text-primary"
                  : "border-transparent text-muted-foreground hover:text-foreground",
              )}
            >
              {label}
            </button>
          ))}
        </nav>
        {ownProfile ? (
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-y-0 right-0 w-12 bg-linear-to-r from-transparent to-card sm:hidden"
          />
        ) : null}
      </div>
    </section>
  );
}

function MemberSince({
  createdAt,
  centered = false,
}: {
  createdAt?: string;
  centered?: boolean;
}) {
  return (
    <p
      className={cn(
        "mt-1 flex items-center gap-1.5 text-sm text-muted-foreground",
        centered && "justify-center",
      )}
    >
      <Calendar className="size-3.5" />
      Membro desde {createdAt ? formatMemberSince(createdAt) : "—"}
    </p>
  );
}

function formatMemberSince(iso: string) {
  return new Date(iso).toLocaleDateString("pt-BR", {
    month: "long",
    year: "numeric",
  });
}

function ProfileAvatar({
  name,
  imageUrl,
  size,
}: {
  name: string;
  imageUrl?: string | null;
  size: "mobile" | "desktop";
}) {
  return (
    <Avatar
      className={cn(
        "border-4 border-background bg-background shadow-xl",
        size === "mobile" ? "size-24" : "size-32",
      )}
    >
      <AvatarImage src={imageUrl ?? undefined} alt={name} />
      <AvatarFallback className="text-2xl font-semibold">
        {name.slice(0, 2).toUpperCase()}
      </AvatarFallback>
    </Avatar>
  );
}

function DesktopActions({ profileUrl }: { profileUrl: string }) {
  return (
    <div className="absolute right-0 top-4 flex gap-2">
      <ProfileShareDialog
        profileUrl={profileUrl}
        className="size-10 rounded-md shadow-sm"
      />
      <Link
        to="/profile/edit"
        search={{ returnTo: undefined }}
        className={buttonVariants({
          className: "h-10 rounded-md px-4 shadow-sm",
        })}
      >
        <Pencil className="size-4" />
        Editar perfil
      </Link>
      <Link
        to="/profile/config"
        className={buttonVariants({
          variant: "outline",
          size: "icon",
          className: "size-10 rounded-md shadow-sm",
        })}
        aria-label="Configurações"
      >
        <Settings className="size-4" />
      </Link>
    </div>
  );
}

// front/univents-solid/src/features/profile/ui/ProfileHeader.tsx
import type { JSX } from "@solidjs/web";
import { untrack } from "solid-js";
import { Link } from "@tanstack/solid-router";
import CalendarIcon from "~icons/lucide/calendar";
import MailIcon from "~icons/lucide/mail";
import PencilIcon from "~icons/lucide/pencil";
import SettingsIcon from "~icons/lucide/settings";
import type { UniventsProfile } from "../model/profile-data";
import { ProfileShareButton } from "./ProfileShareButton";

const Calendar = CalendarIcon as unknown as (p: {
  class?: string;
}) => JSX.Element;
const Mail = MailIcon as unknown as (p: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (p: { class?: string }) => JSX.Element;
const Settings = SettingsIcon as unknown as (p: {
  class?: string;
}) => JSX.Element;
type Tab = "about" | "badges" | "certificates" | "purchases";

export function ProfileHeader(props: {
  profile: UniventsProfile;
  name: string;
  handle?: string;
  ownProfile: boolean;
  profileUrl: string;
  activeTab: Tab;
  onTabChange: (tab: Tab) => void;
}) {
  return (
    <section class="relative w-full border-b border-border bg-card shadow-md">
      <div class="h-40 w-full overflow-hidden bg-background bg-linear-to-br from-primary/40 via-primary/15 to-muted sm:h-48 md:h-56">
        {props.profile.bannerUrl && (
          <img
            src={props.profile.bannerUrl}
            alt=""
            class="size-full object-cover object-center"
          />
        )}
      </div>
      <div class="md:hidden">
        {props.ownProfile && (
          <ProfileShareButton
            name={props.name}
            url={props.profileUrl}
            class="absolute right-4 top-4 flex!"
          />
        )}
        <div class="relative mx-auto px-4">
          <div class="relative z-10 -mt-12 flex flex-col items-center">
            <Avatar
              name={props.name}
              imageUrl={props.profile.pfpUrl}
              size="mobile"
            />
          </div>
          <div class="mt-3 pb-4 text-center">
            <Identity
              profile={props.profile}
              name={props.name}
              handle={props.handle}
              centered
            />
            <MemberSince createdAt={props.profile.createdAt} centered />
            {props.profile.contactEmail && (
              <a
                href={`mailto:${props.profile.contactEmail}`}
                class="mt-1 inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"
              >
                <Mail class="size-3.5" />
                {props.profile.contactEmail}
              </a>
            )}
          </div>
          {props.ownProfile && <Actions mobile />}
        </div>
      </div>
      <div class="mx-auto hidden max-w-7xl px-4 md:block">
        <div class="relative pb-6">
          <div class="absolute left-0 -top-16">
            <Avatar
              name={props.name}
              imageUrl={props.profile.pfpUrl}
              size="desktop"
            />
          </div>
          {props.ownProfile && (
            <Actions name={props.name} profileUrl={props.profileUrl} />
          )}
          <div class="pt-18">
            <Identity
              profile={props.profile}
              name={props.name}
              handle={props.handle}
            />
            <MemberSince createdAt={props.profile.createdAt} />
          </div>
        </div>
      </div>
      <div class="relative mx-auto max-w-7xl">
        <nav class="flex overflow-x-auto px-4 pr-12 sm:pr-4">
          {tabs(props.ownProfile).map(([tab, label]) => (
            <button
              type="button"
              class={`shrink-0 whitespace-nowrap border-b-2 px-4 py-3 text-sm font-medium transition-colors ${props.activeTab === tab ? "border-primary text-primary" : "border-transparent text-muted-foreground hover:text-foreground"}`}
              onClick={() => props.onTabChange(tab)}
            >
              {label}
            </button>
          ))}
        </nav>
        {props.ownProfile && (
          <div
            aria-hidden="true"
            class="pointer-events-none absolute inset-y-0 right-0 w-12 bg-linear-to-r from-transparent to-card sm:hidden"
          />
        )}
      </div>
    </section>
  );
}

function tabs(own: boolean): [Tab, string][] {
  return [
    ["about", "Sobre"],
    ["badges", "Crachás"],
    ...(own
      ? [
        ["certificates", "Certificados"],
        ["purchases", "Compras"],
      ]
      : []),
  ] as [Tab, string][];
}

function Identity(props: {
  profile: UniventsProfile;
  name: string;
  handle?: string;
  centered?: boolean;
}) {
  return (
    <div class={props.centered ? "text-center" : "text-left"}>
      <div
        class={`flex items-baseline gap-2 ${props.centered ? "justify-center" : ""}`}
      >
        <h1
          class={`${props.centered ? "text-2xl" : "text-3xl"} font-semibold tracking-tight text-card-foreground`}
        >
          {props.name}
        </h1>
        {props.profile.pronouns && (
          <span class="text-sm text-muted-foreground">
            {props.profile.pronouns}
          </span>
        )}
      </div>
      {props.handle && (
        <p class="text-sm text-muted-foreground">
          @{props.handle.replace(/^@/, "")}
        </p>
      )}
      {props.profile.legalName &&
        props.profile.legalName !== props.name &&
        props.profile.visibility?.hideLegalName === false && (
          <p class="text-sm text-muted-foreground">{props.profile.legalName}</p>
        )}
      {(props.profile.role || props.profile.organization) && (
        <p
          class={
            props.centered
              ? "mt-1 text-sm text-muted-foreground"
              : "text-[15px] text-muted-foreground"
          }
        >
          {[props.profile.role, props.profile.organization]
            .filter(Boolean)
            .join(" · ")}
        </p>
      )}
    </div>
  );
}

function MemberSince(props: { createdAt?: string; centered?: boolean }) {
  return (
    <p
      class={`mt-1 flex items-center gap-1.5 text-sm text-muted-foreground ${props.centered ? "justify-center" : ""}`}
    >
      <Calendar class="size-3.5" />
      Membro desde{" "}
      {props.createdAt
        ? new Date(props.createdAt).toLocaleDateString("pt-BR", {
          month: "long",
          year: "numeric",
        })
        : "—"}
    </p>
  );
}

function Avatar(props: {
  name: string;
  imageUrl?: string | null;
  size: "mobile" | "desktop";
}) {
  return (
    <div
      class={`relative shrink-0 ${props.size === "mobile" ? "size-24" : "size-32"} flex items-center justify-center overflow-hidden rounded-full border-4 border-background bg-background text-2xl font-semibold shadow-xl`}
    >
      {props.imageUrl ? (
        <img
          src={props.imageUrl}
          alt={props.name}
          class="size-full object-cover"
        />
      ) : (
        <span class="flex size-full items-center justify-center rounded-full bg-muted text-muted-foreground">
          {props.name.slice(0, 2).toUpperCase()}
        </span>
      )}
    </div>
  );
}

function Actions(props: {
  mobile?: boolean;
  name?: string;
  profileUrl?: string;
}) {
  const mobile = untrack(() => props.mobile);
  if (mobile)
    return (
      <div class="mb-4 flex gap-2">
        <Link
          to="/profile/edit"
          class="inline-flex h-11 flex-1 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm text-primary-foreground shadow-sm"
        >
          <Pencil class="size-4" />
          Editar perfil
        </Link>
        <Link
          to="/profile/config"
          class="inline-flex size-11 shrink-0 items-center justify-center rounded-lg border border-border bg-background shadow-sm"
          aria-label="Configurações do perfil"
        >
          <Settings class="size-4" />
        </Link>
      </div>
    );
  return (
    <div class="absolute right-0 top-4 flex gap-2">
      <ProfileShareButton
        name={props.name ?? ""}
        url={props.profileUrl ?? ""}
        class="flex! size-10 rounded-md shadow-sm"
      />
      <Link
        to="/profile/edit"
        class="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm text-primary-foreground shadow-sm"
      >
        <Pencil class="size-4" />
        Editar perfil
      </Link>
      <Link
        to="/profile/config"
        class="inline-flex size-10 items-center justify-center rounded-md border border-border bg-background shadow-sm"
        aria-label="Configurações"
      >
        <Settings class="size-4" />
      </Link>
    </div>
  );
}
