// front/univents/src/features/profile/ui/profile-editor.tsx
import type { JsonValue, ProfileData } from "@trieoh/identityx-sdk-ts";
import { ArrowLeft, CircleAlert, Globe, MapPin, Save } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { preprocessImageUpload } from "@/features/storage/api";
import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/shadcn/button";
import { Input } from "@/shared/ui/shadcn/input";
import { Label } from "@/shared/ui/shadcn/label";
import { Skeleton } from "@/shared/ui/shadcn/skeleton";
import type { ProfileSchemaNode } from "../model/profile-data";
import {
  applyProfileSchemaDefaults,
  asUniventsProfile,
  SYSTEM_PROFILE_FIELDS,
  socialHref,
  withProfileTimestamps,
} from "../model/profile-data";
import { ProfileImageInput } from "./profile-image-input";
import { TimezoneCombobox } from "./timezone-combobox";

type ProfileImageField = "pfpUrl" | "bannerUrl";
type PendingImages = Partial<Record<ProfileImageField, File>>;

export interface ProfileEditorProps {
  load: () => Promise<{
    schema: {
      success: boolean;
      data?: { schema: ProfileSchemaNode };
      message?: string;
    };
    profile: {
      success: boolean;
      data?: { profile: ProfileData };
      message?: string;
    };
  }>;
  save: (profile: ProfileData) => Promise<{
    success: boolean;
    data?: { profile: ProfileData };
    message?: string;
  }>;
  onCancel: () => void;
  onSaved: (profile: ProfileData) => void;
}

export function ProfileEditor({
  load,
  save,
  onCancel,
  onSaved,
}: ProfileEditorProps) {
  const [schema, setSchema] = useState<ProfileSchemaNode>();
  const [original, setOriginal] = useState<ProfileData>({});
  const [values, setValues] = useState<ProfileData>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string>();
  const [pendingImages, setPendingImages] = useState<PendingImages>({});

  useEffect(() => {
    let active = true;
    setError(undefined);
    load()
      .then(({ schema: schemaResult, profile }) => {
        if (!active) return;
        if (!schemaResult.success || !schemaResult.data) {
          setError(
            schemaResult.message ||
              "Não foi possível carregar o schema do perfil.",
          );
        } else {
          setSchema(schemaResult.data.schema);
        }
        if (profile.success && profile.data) {
          setOriginal(profile.data.profile);
          setValues(
            schemaResult.data
              ? applyProfileSchemaDefaults(
                  schemaResult.data.schema,
                  profile.data.profile,
                )
              : profile.data.profile,
          );
        } else if (schemaResult.data) {
          setValues(applyProfileSchemaDefaults(schemaResult.data.schema, {}));
        }
      })
      .catch((cause: unknown) => {
        if (!active) return;
        setError(
          cause instanceof Error
            ? cause.message
            : "Não foi possível carregar o perfil.",
        );
      })
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, [load]);

  if (loading)
    return (
      <main className="min-h-dvh bg-background pb-32">
        <Skeleton className="h-40 w-full sm:h-48 md:h-56" />
        <div className="mx-auto max-w-7xl px-4">
          <Skeleton className="-mt-12 size-24 rounded-full border-4 border-background md:-mt-16 md:size-32" />
          <div className="mt-4 grid gap-4 md:grid-cols-2">
            <Skeleton className="h-28 rounded-md" />
            <Skeleton className="h-28 rounded-md" />
          </div>
        </div>
        <div className="mx-auto mt-5 grid max-w-7xl gap-5 px-4 md:grid-cols-[minmax(0,1fr)_360px]">
          <Skeleton className="h-80 rounded-md" />
          <Skeleton className="h-64 rounded-md" />
        </div>
      </main>
    );
  if (error || !schema)
    return (
      <main className="mx-auto max-w-3xl px-4 py-16 md:px-6">
        <ProfileWarning message={error || "Schema de perfil indisponível."} />
        <div className="mt-4 flex justify-center">
          <Button type="button" variant="outline" onClick={onCancel}>
            <ArrowLeft className="size-4" />
            Voltar ao perfil
          </Button>
        </div>
      </main>
    );

  return (
    <main className="min-h-dvh bg-background pb-32">
      <form
        onSubmit={async (event) => {
          event.preventDefault();
          setSaving(true);
          try {
            const imageEntries = Object.entries(pendingImages) as [
              ProfileImageField,
              File,
            ][];
            const uploadResults = await Promise.allSettled(
              imageEntries.map(async ([field, file]) => ({
                field,
                url: await preprocessImageUpload(
                  file,
                  "profiles/images",
                  crypto.randomUUID(),
                ),
              })),
            );
            const nextValues = normalizeProfileLinks(values);
            const failedImages: string[] = [];
            uploadResults.forEach((result, index) => {
              const [field] = imageEntries[index] ?? [];
              if (!field) return;
              if (result.status === "fulfilled") {
                nextValues[result.value.field] = result.value.url;
              } else {
                const label = field === "pfpUrl" ? "foto do perfil" : "banner";
                const reason =
                  result.reason instanceof Error
                    ? result.reason.message
                    : "falha no upload ou na moderação";
                failedImages.push(`${label} (${reason})`);
              }
            });
            const response = await save(
              withProfileTimestamps(original, nextValues),
            );
            if (!response.success)
              throw new Error(
                response.message || "Não foi possível salvar o perfil.",
              );
            toast.success("Perfil atualizado");
            if (failedImages.length > 0) {
              toast.warning(
                `As outras informações foram salvas, mas houve erro em: ${failedImages.join("; ")}.`,
              );
            }
            onSaved(nextValues);
          } catch (cause) {
            toast.error(
              cause instanceof Error
                ? cause.message
                : "Não foi possível salvar o perfil.",
            );
          } finally {
            setSaving(false);
          }
        }}
      >
        <InlineProfileEditor
          schema={schema}
          values={values}
          onChange={setValues}
          onCancel={onCancel}
          pendingImages={pendingImages}
          onImageSelect={(field, file) =>
            setPendingImages((current) => ({ ...current, [field]: file }))
          }
        />
        <div className="fixed inset-x-0 bottom-0 z-60 border-t border-border bg-background/95 p-3 shadow-[0_-8px_30px_rgb(0_0_0/0.08)] backdrop-blur">
          <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-1 md:px-4">
            <Button
              type="button"
              variant="ghost"
              className="h-8 rounded-sm"
              disabled={saving}
              onClick={onCancel}
            >
              <ArrowLeft className="size-4" />
              Cancelar
            </Button>
            <p className="hidden text-sm text-muted-foreground sm:block">
              Revise a prévia antes de salvar.
            </p>
            <Button type="submit" disabled={saving} className="h-8 rounded-sm">
              <Save className="size-4" />
              {saving ? "Salvando…" : "Salvar alterações"}
            </Button>
          </div>
        </div>
      </form>
    </main>
  );
}

function InlineProfileEditor({
  schema,
  values,
  onChange,
  onCancel,
  pendingImages,
  onImageSelect,
}: {
  schema: ProfileSchemaNode;
  values: ProfileData;
  onChange: (values: ProfileData) => void;
  onCancel: () => void;
  pendingImages: PendingImages;
  onImageSelect: (field: ProfileImageField, file: File) => void;
}) {
  const profile = asUniventsProfile(values);
  return (
    <>
      <section className="relative border-b border-border bg-card shadow-md">
        <ProfileImageInput
          label="Banner"
          currentUrl={profile.bannerUrl}
          file={pendingImages.bannerUrl}
          onSelect={(file) => onImageSelect("bannerUrl", file)}
          variant="banner"
          className={cn(
            "relative h-40 bg-linear-to-br sm:h-48 md:h-56",
            "from-primary/40 via-primary/15 to-muted",
          )}
        />
        <div className="pointer-events-none absolute inset-x-4 top-4 z-20 mx-auto max-w-7xl">
          <div className="pointer-events-auto w-fit">
            <Button
              type="button"
              variant="secondary"
              size="icon"
              className="rounded-full shadow-lg"
              onClick={onCancel}
              aria-label="Voltar ao perfil"
            >
              <ArrowLeft className="size-4" />
            </Button>
          </div>
        </div>
        <div className="mx-auto max-w-7xl px-4">
          <div className="relative pb-5 md:pb-6">
            <ProfileImageInput
              label="Foto do perfil"
              currentUrl={profile.pfpUrl}
              file={pendingImages.pfpUrl}
              onSelect={(file) => onImageSelect("pfpUrl", file)}
              variant="avatar"
              className="-mt-12 md:-mt-16"
            />
            <div className="mt-3">
              <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["preferredName"]}
                />
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["legalName"]}
                />
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["role"]}
                />
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["organization"]}
                />
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["pronouns"]}
                />
                <EditorField
                  schema={schema}
                  values={values}
                  onChange={onChange}
                  path={["tagline"]}
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className="mx-auto mt-4 grid max-w-7xl gap-4 px-4 md:mt-5 md:grid-cols-[minmax(0,1fr)_360px] md:gap-5">
        <div className="space-y-5">
          <EditorCard title="Sobre mim">
            <EditorField
              schema={schema}
              values={values}
              onChange={onChange}
              path={["aboutMe"]}
              compact
            />
          </EditorCard>
          <EditorCard title="Especializações">
            <EditorField
              schema={schema}
              values={values}
              onChange={onChange}
              path={["specializations"]}
              compact
            />
            {!schema.properties?.specializations && (
              <EditorField
                schema={schema}
                values={values}
                onChange={onChange}
                path={["languages"]}
                compact
              />
            )}
          </EditorCard>
          <EditorCard title="Contato" icon={<Globe className="size-4" />}>
            <div className="grid gap-4 sm:grid-cols-2">
              <EditorField
                schema={schema}
                values={values}
                onChange={onChange}
                path={["website"]}
              />
              <EditorField
                schema={schema}
                values={values}
                onChange={onChange}
                path={["contactEmail"]}
              />
            </div>
            <EditorObject
              schema={schema}
              values={values}
              onChange={onChange}
              name="socials"
            />
          </EditorCard>
        </div>

        <aside className="space-y-5">
          <EditorCard title="Localização" icon={<MapPin className="size-4" />}>
            <EditorObject
              schema={schema}
              values={values}
              onChange={onChange}
              name="location"
            />
          </EditorCard>
          <EditorCard title="Privacidade">
            <EditorObject
              schema={schema}
              values={values}
              onChange={onChange}
              name="visibility"
            />
          </EditorCard>
          <EditorCard title="Outros detalhes">
            <EditorField
              schema={schema}
              values={values}
              onChange={onChange}
              path={["timezone"]}
              compact
            />
          </EditorCard>
        </aside>
      </div>
    </>
  );
}

function EditorCard({
  title,
  icon,
  compact = false,
  children,
}: {
  title: string;
  icon?: React.ReactNode;
  compact?: boolean;
  children: React.ReactNode;
}) {
  return (
    <section
      className={cn(
        "rounded-md border border-border bg-card shadow-md shadow-foreground/5",
        compact ? "p-3" : "p-5",
      )}
    >
      <h2
        className={cn(
          "flex items-center gap-2 font-semibold",
          compact ? "mb-2 text-sm" : "mb-4 text-base",
        )}
      >
        {icon}
        {title}
      </h2>
      <div className="space-y-4">{children}</div>
    </section>
  );
}

function EditorObject({
  schema,
  values,
  onChange,
  name,
}: {
  schema: ProfileSchemaNode;
  values: ProfileData;
  onChange: (values: ProfileData) => void;
  name: string;
}) {
  const field = schema.properties?.[name];
  if (!field)
    return (
      <p className="text-sm text-muted-foreground">
        Campo indisponível no schema.
      </p>
    );
  return (
    <SchemaFields
      schema={field}
      values={values}
      onChange={onChange}
      path={[name]}
    />
  );
}

function EditorField({
  schema,
  values,
  onChange,
  path,
  compact = false,
}: {
  schema: ProfileSchemaNode;
  values: ProfileData;
  onChange: (values: ProfileData) => void;
  path: string[];
  compact?: boolean;
}) {
  const field = findSchemaField(schema, path);
  if (!field) return null;
  const id = `profile-${path.join("-")}`;
  const value = readValue(values, path);
  const type = Array.isArray(field.type)
    ? field.type.find((item) => item !== "null")
    : field.type;
  return (
    <div className={cn("space-y-2", compact && "space-y-1.5")}>
      <Label htmlFor={id} className="text-sm font-medium">
        {fieldLabel(path.at(-1) ?? "", field)}
      </Label>
      <SchemaInput
        id={id}
        field={field}
        type={type}
        value={value}
        required={
          path.length === 1 && Boolean(schema.required?.includes(path[0] ?? ""))
        }
        onChange={(next) => onChange(writeValue(values, path, next))}
      />
    </div>
  );
}

function findSchemaField(schema: ProfileSchemaNode, path: string[]) {
  let current: ProfileSchemaNode | undefined = schema;
  for (const segment of path) current = current?.properties?.[segment];
  return current;
}

function ProfileWarning({ message }: { message: string }) {
  return (
    <div
      role="alert"
      className="mx-auto flex max-w-xl gap-3 rounded-2xl border border-amber-500/30 bg-amber-500/10 p-5 text-amber-950 dark:text-amber-100"
    >
      <CircleAlert className="mt-0.5 size-5 shrink-0" />
      <div>
        <p className="font-medium">Não foi possível abrir a edição</p>
        <p className="mt-1 text-sm opacity-80">{message}</p>
      </div>
    </div>
  );
}

function SchemaFields({
  schema,
  values,
  onChange,
  path = [],
}: {
  schema: ProfileSchemaNode;
  values: ProfileData;
  onChange: (values: ProfileData) => void;
  path?: string[];
}) {
  const required = new Set(schema.required ?? []);
  return (
    <div className={path.length ? "grid gap-3" : "space-y-6"}>
      {Object.entries(schema.properties ?? {}).map(([name, field]) => {
        if (SYSTEM_PROFILE_FIELDS.has(name)) return null;
        const fieldPath = [...path, name];
        const value = readValue(values, fieldPath);
        const fieldType = Array.isArray(field.type)
          ? field.type.find((type) => type !== "null")
          : field.type;
        if (fieldType === "object") {
          return (
            <fieldset
              key={fieldPath.join(".")}
              className="space-y-4 rounded-xl border p-4 md:col-span-2"
            >
              <legend className="px-2 font-semibold">
                {fieldLabel(name, field)}
              </legend>
              <SchemaFields
                schema={field}
                values={values}
                onChange={onChange}
                path={fieldPath}
              />
            </fieldset>
          );
        }
        const id = fieldPath.join("-");
        const isRequired = required.has(name);
        return (
          <div
            key={id}
            className={cn(
              fieldType === "boolean"
                ? "flex min-w-0 items-center justify-between gap-4 rounded-md border border-border bg-background p-3"
                : "space-y-2",
            )}
          >
            <div>
              <Label htmlFor={id}>
                {fieldLabel(name, field)}
                {isRequired ? " *" : ""}
              </Label>
            </div>
            <SchemaInput
              id={id}
              field={field}
              type={fieldType}
              value={value}
              required={isRequired}
              onChange={(next) => onChange(writeValue(values, fieldPath, next))}
            />
          </div>
        );
      })}
    </div>
  );
}

function SchemaInput({
  id,
  field,
  type,
  value,
  required,
  onChange,
}: {
  id: string;
  field: ProfileSchemaNode;
  type?: string;
  value: JsonValue | undefined;
  required: boolean;
  onChange: (value: JsonValue) => void;
}) {
  if (type === "boolean")
    return (
      <label className="relative inline-flex shrink-0 cursor-pointer items-center">
        <input
          id={id}
          type="checkbox"
          checked={value === true}
          onChange={(event) => onChange(event.target.checked)}
          className="peer sr-only"
        />
        <span className="h-6 w-11 rounded-full bg-input transition-colors peer-checked:bg-primary peer-focus-visible:ring-2 peer-focus-visible:ring-ring peer-focus-visible:ring-offset-2 after:absolute after:left-0.5 after:top-0.5 after:size-5 after:rounded-full after:bg-background after:shadow-sm after:transition-transform peer-checked:after:translate-x-5" />
      </label>
    );
  if (type === "array")
    return (
      <ArrayDraftInput
        id={id}
        required={required}
        value={Array.isArray(value) ? value : []}
        placeholder={fieldPlaceholder(nameFromId(id))}
        onChange={onChange}
      />
    );
  if (nameFromId(id) === "timezone") {
    const selectedTimezone = typeof value === "string" ? value : "";
    const timezoneOptions = Array.from(
      new Set([selectedTimezone, ...TIMEZONES].filter(Boolean)),
    ).map((timezone) => ({
      value: timezone,
      label: timezoneLabel(timezone),
    }));
    return (
      <TimezoneCombobox
        id={id}
        value={selectedTimezone}
        options={timezoneOptions}
        onChange={onChange}
      />
    );
  }
  if (field.enum)
    return (
      <select
        id={id}
        required={required}
        value={
          typeof value === "string" || typeof value === "number"
            ? String(value)
            : ""
        }
        onChange={(event) => onChange(event.target.value)}
        className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        <option value="">Selecione…</option>
        {field.enum.map((option) => (
          <option key={String(option)} value={String(option)}>
            {String(option)}
          </option>
        ))}
      </select>
    );
  if (nameFromId(id) === "aboutMe")
    return (
      <textarea
        id={id}
        required={required}
        value={typeof value === "string" ? value : ""}
        placeholder={fieldPlaceholder("aboutMe")}
        onChange={(event) => onChange(event.target.value)}
        className="min-h-32 w-full resize-y rounded-md border border-input bg-background px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring"
      />
    );
  const inputType =
    type === "number" || type === "integer"
      ? "number"
      : field.format === "email"
        ? "email"
        : field.format === "uri"
          ? "url"
          : "text";
  const fieldName = nameFromId(id);
  const isSocial = id.startsWith("socials-");
  const displayType = fieldName === "website" || isSocial ? "text" : inputType;
  const stringValue =
    typeof value === "string" || typeof value === "number" ? String(value) : "";
  const normalizedSocial = isSocial
    ? normalizeSocialProfile(fieldName, stringValue)
    : "";
  return (
    <div className="min-w-0 space-y-1.5">
      <Input
        id={id}
        type={displayType}
        inputMode={fieldName === "website" || isSocial ? "url" : undefined}
        required={required}
        placeholder={fieldPlaceholder(fieldName)}
        className="h-10 bg-background"
        value={stringValue}
        onChange={(event) => {
          const next = event.target.value;
          onChange(
            isSocial && /^https?:\/\//i.test(next)
              ? normalizeSocialProfile(fieldName, next)
              : inputValue(field, inputType, next),
          );
        }}
        onBlur={() => {
          if (fieldName === "website") onChange(normalizeWebsite(stringValue));
          else if (isSocial)
            onChange(normalizeSocialProfile(fieldName, stringValue));
        }}
      />
      {normalizedSocial && (
        <p
          className="truncate text-right text-xs text-muted-foreground"
          title={socialHref(fieldName, normalizedSocial)}
        >
          {socialHref(fieldName, normalizedSocial)}
        </p>
      )}
    </div>
  );
}

function ArrayDraftInput({
  id,
  value,
  placeholder,
  required,
  onChange,
}: {
  id: string;
  value: JsonValue[];
  placeholder: string;
  required: boolean;
  onChange: (value: JsonValue) => void;
}) {
  const canonical = value.map(String).join(", ");
  const [draft, setDraft] = useState(canonical);

  useEffect(() => setDraft(canonical), [canonical]);

  const commit = () => {
    const items = draft
      .split(/[,;\n]+/)
      .map((item) => item.trim())
      .filter(Boolean);
    onChange(items);
    setDraft(items.join(", "));
  };

  return (
    <Input
      id={id}
      required={required}
      value={draft}
      placeholder={placeholder}
      className="h-10 bg-background"
      onChange={(event) => setDraft(event.target.value)}
      onBlur={commit}
      onKeyDown={(event) => {
        if (event.key === "Enter") {
          event.preventDefault();
          commit();
        }
      }}
    />
  );
}

function inputValue(
  field: ProfileSchemaNode,
  inputType: string,
  value: string,
): JsonValue {
  if (inputType === "number") return Number(value);
  if (!value && Array.isArray(field.type) && field.type.includes("null")) {
    return null;
  }
  return value;
}

function readValue(values: ProfileData, path: string[]): JsonValue | undefined {
  let current: JsonValue = values;
  for (const segment of path) {
    if (!current || Array.isArray(current) || typeof current !== "object")
      return undefined;
    current = current[segment] as JsonValue;
  }
  return current;
}

function writeValue(
  values: ProfileData,
  path: string[],
  value: JsonValue,
): ProfileData {
  const next = structuredClone(values);
  let current: Record<string, JsonValue> = next;
  path.forEach((segment, index) => {
    if (index === path.length - 1) current[segment] = value;
    else {
      const child = current[segment];
      if (!child || Array.isArray(child) || typeof child !== "object")
        current[segment] = {};
      current = current[segment] as Record<string, JsonValue>;
    }
  });
  return next;
}

function humanize(value: string): string {
  return value
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/^./, (letter) => letter.toUpperCase());
}

const FIELD_LABELS: Record<string, string> = {
  preferredName: "Nome de exibição",
  legalName: "Nome completo",
  pronouns: "Pronomes",
  tagline: "Frase de apresentação",
  aboutMe: "Sobre mim",
  role: "Função",
  organization: "Organização",
  contactEmail: "E-mail de contato",
  website: "Site",
  socials: "Redes sociais",
  city: "Cidade",
  region: "Estado ou região",
  country: "País",
  countryCode: "Código do país",
  languages: "Idiomas ou especializações",
  specializations: "Especializações",
  timezone: "Fuso horário",
  hideSocials: "Ocultar redes sociais",
  hideLocation: "Ocultar localização",
  hideLegalName: "Ocultar nome completo",
  hideContactEmail: "Ocultar e-mail de contato",
  hideOrganization: "Ocultar organização",
};

const FIELD_PLACEHOLDERS: Record<string, string> = {
  preferredName: "Como você quer ser chamado",
  legalName: "Digite seu nome completo",
  pronouns: "Ex.: ela/dela",
  tagline: "Uma frase curta sobre você",
  aboutMe: "Conte um pouco sobre você, sua experiência e seus interesses…",
  role: "Ex.: Desenvolvedor de software",
  organization: "Ex.: Univents",
  contactEmail: "voce@exemplo.com",
  website: "https://seusite.com",
  city: "Ex.: São Paulo",
  region: "Ex.: São Paulo",
  country: "Ex.: Brasil",
  countryCode: "Ex.: BR",
  languages: "Ex.: Português, Inglês",
  specializations: "Ex.: Tecnologia, Eventos",
  x: "Ex.: @univents ou x.com/univents",
  twitter: "Ex.: @univents ou twitter.com/univents",
  instagram: "Ex.: @univents ou instagram.com/univents",
  linkedin: "Ex.: trieoh ou linkedin.com/in/trieoh",
  github: "Ex.: trieoh ou github.com/trieoh",
  twitch: "Ex.: univents ou twitch.tv/univents",
  bluesky: "Ex.: univents.bsky.social",
  youtube: "Ex.: @univents ou youtube.com/@univents",
};

const TIMEZONES = [
  "America/Sao_Paulo",
  "America/Manaus",
  "America/Cuiaba",
  "America/Rio_Branco",
  "America/Noronha",
  "America/New_York",
  "America/Los_Angeles",
  "Europe/Lisbon",
  "Europe/London",
  "Europe/Paris",
  "UTC",
];

function fieldLabel(name: string, field: ProfileSchemaNode): string {
  return FIELD_LABELS[name] ?? field.title ?? humanize(name);
}

function fieldPlaceholder(name: string): string {
  return FIELD_PLACEHOLDERS[name] ?? "Ex.: seu perfil ou informação";
}

function normalizeWebsite(value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return "";
  return `https://${trimmed.replace(/^https?:\/\//i, "").replace(/^\/+/, "")}`;
}

function normalizeSocialProfile(network: string, value: string): string {
  const trimmed = value.trim();
  if (!trimmed) return "";
  const withoutProtocol = trimmed.replace(/^https?:\/\//i, "");
  if (!withoutProtocol.includes("/")) return withoutProtocol.replace(/^@/, "");

  try {
    const url = new URL(`https://${withoutProtocol}`);
    const parts = url.pathname.split("/").filter(Boolean);
    const prefixIndex =
      network === "linkedin"
        ? parts.indexOf("in")
        : network === "bluesky"
          ? parts.indexOf("profile")
          : -1;
    const profile = prefixIndex >= 0 ? parts[prefixIndex + 1] : parts.at(0);
    return (profile ?? trimmed).replace(/^@/, "").replace(/\/$/, "");
  } catch {
    return trimmed.replace(/^@/, "").replace(/\/$/, "");
  }
}

function normalizeProfileLinks(values: ProfileData): ProfileData {
  const next = structuredClone(values);
  if (typeof next.website === "string") {
    next.website = normalizeWebsite(next.website);
  }
  const socials = next.socials;
  if (socials && !Array.isArray(socials) && typeof socials === "object") {
    for (const [network, value] of Object.entries(socials)) {
      if (typeof value === "string") {
        socials[network] = normalizeSocialProfile(network, value);
      }
    }
  }
  return next;
}

function timezoneLabel(timezone: string): string {
  const labels: Record<string, string> = {
    "America/Sao_Paulo": "Brasília — São Paulo (UTC−03:00)",
    "America/Manaus": "Manaus (UTC−04:00)",
    "America/Cuiaba": "Cuiabá (UTC−04:00)",
    "America/Rio_Branco": "Rio Branco (UTC−05:00)",
    "America/Noronha": "Fernando de Noronha (UTC−02:00)",
    UTC: "UTC (tempo universal)",
  };
  return labels[timezone] ?? timezone.replaceAll("_", " ");
}

function nameFromId(id: string): string {
  return id.split("-").at(-1) ?? id;
}

// front/univents-solid/src/features/profile/ui/ProfileEditor.tsx
import { Show, createSignal, onSettled, untrack } from "solid-js";
import type { JSX } from "@solidjs/web";
import ArrowLeftIcon from "~icons/lucide/arrow-left";
import CircleUserIcon from "~icons/lucide/circle-user-round";
import GlobeIcon from "~icons/lucide/globe";
import LanguagesIcon from "~icons/lucide/languages";
import LockKeyholeIcon from "~icons/lucide/lock-keyhole";
import Settings2Icon from "~icons/lucide/settings-2";
import InstagramIcon from "~icons/simple-icons/instagram";
import LinkedinIcon from "~icons/simple-icons/linkedin";
import GithubIcon from "~icons/simple-icons/github";
import YoutubeIcon from "~icons/simple-icons/youtube";
import XIcon from "~icons/simple-icons/x";
import TwitterIcon from "~icons/simple-icons/twitter";
import TwitchIcon from "~icons/simple-icons/twitch";
import BlueskyIcon from "~icons/simple-icons/bluesky";
import DiscordIcon from "~icons/simple-icons/discord";
import SaveIcon from "~icons/lucide/save";
import { toast } from "@/shared/ui/toast";
import { Combobox } from "@/shared/ui/Combobox";
import { ProfileImageInput } from "./ProfileImageInput";
import { uploadProfileImagesBatch } from "@/features/storage/api";
import {
  asUniventsProfile,
  socialHref,
  type UniventsProfile,
} from "../model/profile-data";

const ArrowLeft =
  ArrowLeftIcon as unknown as () => JSX.Element;
const Save = SaveIcon as unknown as () => JSX.Element;
const CircleUser = CircleUserIcon as unknown as () => JSX.Element;
const Globe = GlobeIcon as unknown as () => JSX.Element;
const Languages = LanguagesIcon as unknown as () => JSX.Element;
const LockKeyhole = LockKeyholeIcon as unknown as () => JSX.Element;
const Settings2 = Settings2Icon as unknown as () => JSX.Element;
const SocialIcons: Record<string, () => JSX.Element> = {
  instagram: InstagramIcon as unknown as () => JSX.Element,
  linkedin: LinkedinIcon as unknown as () => JSX.Element,
  github: GithubIcon as unknown as () => JSX.Element,
  youtube: YoutubeIcon as unknown as () => JSX.Element,
  x: XIcon as unknown as () => JSX.Element,
  twitter: TwitterIcon as unknown as () => JSX.Element,
  twitch: TwitchIcon as unknown as () => JSX.Element,
  bluesky: BlueskyIcon as unknown as () => JSX.Element,
  discord: DiscordIcon as unknown as () => JSX.Element,
};

export function ProfileEditor(props: {
  load: () => Promise<{
    profile: {
      success: boolean;
      data?: { handle?: string | null; pfp_url?: string | null; profile?: Record<string, unknown> };
      message?: string;
    };
  }>;
  save: (
    profile: Record<string, unknown>,
    handle?: string,
  ) => Promise<{ success: boolean; message?: string }>;
  onCancel: () => void;
  onSaved: () => void;
}) {
  const [profile, setProfile] = createSignal<UniventsProfile>({});
  const [handle, setHandle] = createSignal("");
  const [loading, setLoading] = createSignal(true);
  const [saving, setSaving] = createSignal(false);
  const [pendingImages, setPendingImages] = createSignal<Partial<Record<"pfpUrl" | "bannerUrl", File>>>({});
  const [error, setError] = createSignal<string>();

  onSettled(() => {
    void props
      .load()
      .then((result) => {
        if (!result.profile.success || !result.profile.data) {
          setError(
            result.profile.message ?? "Não foi possível carregar o perfil.",
          );
          return;
        }
        setProfile(asUniventsProfile({
          ...result.profile.data.profile,
          ...(result.profile.data.pfp_url !== undefined && {
            pfpUrl: result.profile.data.pfp_url,
          }),
        }));
        setHandle(result.profile.data.handle ?? "");
      })
      .catch((cause) =>
        setError(
          cause instanceof Error
            ? cause.message
            : "Não foi possível carregar o perfil.",
        ),
      )
      .finally(() => setLoading(false));
  });

  const update = (field: string, value: unknown) =>
    setProfile((current) => ({ ...current, [field]: value }));
  const submit = async (event: SubmitEvent) => {
    event.preventDefault();
    setSaving(true);
    try {
      const nextProfile = untrack(() => ({ ...profile() }));
      const uploads = untrack(() => Object.entries(pendingImages())) as ["pfpUrl" | "bannerUrl", File][];
      const { uploaded, failed } = await uploadProfileImagesBatch(uploads);
      Object.assign(nextProfile, uploaded);
      const result = await props.save(
        nextProfile,
        handle().trim().replace(/^@/, ""),
      );
      if (!result.success)
        throw new Error(result.message ?? "Não foi possível salvar o perfil.");
      toast.success("Perfil atualizado");
      if (failed.length) toast.warning(`Perfil salvo, mas falhou o upload de: ${failed.join(" e ")}.`);
      props.onSaved();
    } catch (cause) {
      toast.error(
        cause instanceof Error
          ? cause.message
          : "Não foi possível salvar o perfil.",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <Show
      when={!loading()}
      fallback={<div class="min-h-dvh animate-pulse bg-muted" />}
    >
      <Show
        when={!error()}
        fallback={
          <main class="mx-auto max-w-3xl px-4 py-16 text-center text-muted-foreground">
            {error()}
          </main>
        }
      >
        <form onSubmit={submit} class="min-h-dvh bg-background pb-28">
          <section class="border-b border-border bg-card shadow-md">
            <div class="relative h-40 overflow-hidden bg-linear-to-br from-primary/40 via-primary/15 to-muted sm:h-48 md:h-56">
              <ProfileImageInput
                label="Banner"
                currentUrl={profile().bannerUrl}
                variant="banner"
                onSelect={(file) => setPendingImages((value) => ({ ...value, bannerUrl: file }))}
              />
              <button
                type="button"
                onClick={() => props.onCancel()}
                class="absolute left-4 top-4 inline-flex size-10 items-center justify-center rounded-full bg-background shadow-lg"
                aria-label="Voltar ao perfil"
              >
                <ArrowLeft />
              </button>
            </div>
            <div class="mx-auto max-w-7xl px-4">
              <div class="relative pb-5 md:pb-6">
                <div class="-mt-12 md:-mt-16">
                  <ProfileImageInput
                    label="Foto do perfil"
                    currentUrl={profile().pfpUrl}
                    variant="avatar"
                    onSelect={(file) => setPendingImages((value) => ({ ...value, pfpUrl: file }))}
                  />
                </div>
                <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
                  <Field
                    label="Nome de usuário"
                    value={handle()}
                    onInput={setHandle}
                    placeholder="Escolha um nome de usuário único"
                    autocomplete="username"
                  />
                  <Field
                    label="Nome Social"
                    value={profile().preferredName ?? ""}
                    onInput={(value) => update("preferredName", value)}
                    placeholder="Como você prefere ser chamado?"
                    autocomplete="nickname"
                  />
                  <Field
                    label="Nome Civil"
                    value={profile().legalName ?? ""}
                    onInput={(value) => update("legalName", value)}
                    autocomplete="name"
                    placeholder="Digite seu nome civil completo"
                  />
                  <Field
                    label="Função"
                    value={profile().role ?? ""}
                    onInput={(value) => update("role", value)}
                    placeholder="Ex.: Organizador de eventos"
                    autocomplete="organization-title"
                  />
                  <Field
                    label="Organização"
                    value={profile().organization ?? ""}
                    onInput={(value) => update("organization", value)}
                    placeholder="Ex.: Univents"
                    autocomplete="organization"
                  />
                  <PronounsField
                    label="Pronomes"
                    value={profile().pronouns ?? ""}
                    onInput={(value) => update("pronouns", value)}
                  />
                </div>
              </div>
            </div>
          </section>
          <div class="mx-auto mt-4 grid max-w-7xl gap-4 px-4 md:mt-5 md:grid-cols-[minmax(0,1fr)_360px] md:gap-5">
            <div class="space-y-5">
              <Card title="Sobre mim" icon={<CircleUser />}>
                <textarea
                  value={profile().aboutMe ?? ""}
                  onInput={(event) =>
                    update("aboutMe", event.currentTarget.value)
                  }
                  placeholder="Conte um pouco sobre você, sua experiência e seus interesses…"
                  class="min-h-32 w-full resize-y rounded-md border border-border bg-background p-3 text-sm outline-none focus:border-primary"
                />
              </Card>
              <Card title="Idiomas" icon={<Languages />}>
                <LanguagesField
                  value={(profile().languages ?? []).join(", ")}
                  onChange={(value) => update("languages", value)}
                />
              </Card>
              <Card title="Contato" icon={<Globe />}>
                <div class="grid gap-4 sm:grid-cols-2">
                  <Field
                    label="Website"
                    value={profile().website ?? ""}
                    onInput={(value) => update("website", value)}
                    onBlur={(value) => {
                      const trimmed = value.trim();
                      if (trimmed && !/^https?:\/\//i.test(trimmed)) {
                        update("website", `https://${trimmed}`);
                      }
                    }}
                    placeholder="https://seusite.com"
                    type="url"
                  />
                  <Field
                    label="E-mail"
                    value={profile().contactEmail ?? ""}
                    onInput={(value) => update("contactEmail", value)}
                    placeholder="voce@exemplo.com"
                    type="email"
                    autocomplete="email"
                  />
                </div>
                <SocialFields
                  value={profile().socials ?? {}}
                  onChange={(value) => update("socials", value)}
                />
              </Card>
            </div>
            <aside class="space-y-5">
              <Card title="Privacidade" icon={<LockKeyhole />}>
                <Toggle
                  label="Ocultar nome legal"
                  checked={profile().visibility?.hideLegalName === true}
                  onChange={(checked) =>
                    update("visibility", {
                      ...profile().visibility,
                      hideLegalName: checked,
                    })
                  }
                />
              </Card>
              <Card title="Outros detalhes" icon={<Settings2 />}>
                <TimezoneField
                  value={String(profile().timezone ?? "")}
                  onInput={(value) => update("timezone", value)}
                />
              </Card>
            </aside>
          </div>
          <div class="fixed inset-x-0 bottom-0 z-50 border-t border-border bg-background/95 p-3 shadow-[0_-8px_30px_rgb(0_0_0/0.08)] backdrop-blur">
            <div class="mx-auto flex max-w-7xl justify-between gap-3 px-1 md:px-4">
              <button
                type="button"
                onClick={() => props.onCancel()}
                class="inline-flex h-10 items-center gap-2 rounded-md px-4 text-sm hover:bg-muted"
              >
                <ArrowLeft />
                Cancelar
              </button>
              <button
                type="submit"
                disabled={saving()}
                class="inline-flex h-10 items-center gap-2 rounded-md bg-primary px-5 text-sm text-primary-foreground disabled:opacity-50"
              >
                <Save />
                {saving() ? "Salvando..." : "Salvar alterações"}
              </button>
            </div>
          </div>
        </form>
      </Show>
    </Show>
  );
}

function Card(props: { title: string; icon?: JSX.Element; children: unknown }) {
  return (
    <section class="rounded-md border border-border bg-card p-5 shadow-md shadow-foreground/5">
      <h2 class="mb-4 flex items-center gap-2 text-base font-semibold [&>svg]:size-4 [&>svg]:text-muted-foreground">
        {props.icon}
        {props.title}
      </h2>
      {props.children}
    </section>
  );
}
function Field(props: {
  label: string;
  value: string;
  onInput: (value: string) => void;
  onBlur?: (value: string) => void;
  placeholder?: string;
  autocomplete?: string;
  type?: "text" | "url" | "email";
}) {
  return (
    <label class="block space-y-2.5 text-sm font-medium">
      {props.label}
      <input
        type={props.type ?? "text"}
        value={props.value}
        placeholder={props.placeholder}
        autocomplete={props.autocomplete}
        onInput={(event) => props.onInput(event.currentTarget.value)}
        onBlur={(event) => props.onBlur?.(event.currentTarget.value)}
        class="h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none focus:border-primary"
      />
    </label>
  );
}

function PronounsField(props: {
  label: string;
  value: string;
  onInput: (value: string) => void;
}) {
  const options = [
    "Ele/dele",
    "Ela/dela",
    "Elu/delu",
    "Eles/deles",
    "Ela/ele",
    "Prefiro não informar",
    "Outros",
  ].map((value) => ({ value, label: value }));
  const initialValue = untrack(() => props.value);
  const [custom, setCustom] = createSignal(
    options.some((option) => option.value === initialValue) ? "" : initialValue,
  );
  const [otherSelected, setOtherSelected] = createSignal(
    initialValue === "Outros" ||
    !options.some((option) => option.value === initialValue),
  );
  return (
    <label class="block space-y-2.5 text-sm font-medium">
      {props.label}
      <Combobox
        value={otherSelected() ? "Outros" : props.value}
        options={options}
        placeholder="Selecione seus pronomes"
        onChange={(value) => {
          if (value === "Outros") {
            setOtherSelected(true);
            props.onInput(custom() || "Outros");
          } else {
            setOtherSelected(false);
            props.onInput(value);
          }
        }}
      />
      <Show when={otherSelected()}>
        <input
          value={custom()}
          placeholder="Digite seus pronomes"
          onInput={(event) => {
            setCustom(event.currentTarget.value);
            props.onInput(event.currentTarget.value || "Outros");
          }}
          class="h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none focus:border-primary"
        />
      </Show>
    </label>
  );
}

function LanguagesField(props: {
  value: string;
  onChange: (value: string[]) => void;
}) {
  const [draft, setDraft] = createSignal("");
  const items = () =>
    props.value
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  const add = (value: string) => {
    const item = value.trim();
    if (!item) return;
    props.onChange([...items(), item]);
    setDraft("");
  };
  const input = (value: string) => {
    const parts = value.split(/[,;\n]+/);
    if (parts.length > 1) {
      parts.slice(0, -1).forEach(add);
      setDraft(parts.at(-1) ?? "");
    } else setDraft(value);
  };
  return (
    <div class="space-y-2.5">
      <Show when={items().length > 0}>
        <div class="flex flex-wrap gap-1.5">
          {items().map((item, index) => (
            <button
              type="button"
              class="rounded-full border border-border bg-muted px-2.5 py-1 text-xs"
              onClick={() =>
                props.onChange(
                  items().filter((_, entryIndex) => entryIndex !== index),
                )
              }
              title="Remover idioma"
            >
              {item} ×
            </button>
          ))}
        </div>
      </Show>
      <input
        value={draft()}
        placeholder="Digite um idioma e pressione Enter"
        autocomplete="off"
        onInput={(event) => input(event.currentTarget.value)}
        onBlur={() => add(draft())}
        onKeyDown={(event) => {
          if (event.key === "Enter") {
            event.preventDefault();
            add(draft());
          }
        }}
        class="h-10 w-full rounded-md border border-border bg-background px-3 text-sm outline-none placeholder:text-muted-foreground focus:border-primary"
      />
    </div>
  );
}

function SocialFields(props: {
  value: Record<string, string | null | undefined>;
  onChange: (value: Record<string, string>) => void;
}) {
  const networks = [
    ["instagram", "Instagram", "Ex.: @univents ou instagram.com/univents"],
    ["linkedin", "LinkedIn", "Ex.: trieoh ou linkedin.com/in/trieoh"],
    ["github", "GitHub", "Ex.: trieoh ou github.com/trieoh"],
    ["youtube", "YouTube", "Ex.: @univents ou youtube.com/@univents"],
    ["x", "X", "Ex.: @univents ou x.com/univents"],
    ["twitter", "Twitter", "Ex.: @univents ou twitter.com/univents"],
    ["twitch", "Twitch", "Ex.: univents ou twitch.tv/univents"],
    ["bluesky", "Bluesky", "Ex.: univents.bsky.social"],
    ["discord", "Discord", "Ex.: seu ID ou discord.com/users/seu-id"],
  ];
  const updateNetwork = (network: string, value: string) => {
    props.onChange({
      ...props.value,
      [network]: value,
    } as Record<string, string>);
  };
  const normalize = (value: string) =>
    value
      .trim()
      .replace(/^https?:\/\//i, "")
      .replace(/^@/, "")
      .replace(/\/$/, "");
  return (
    <div class="space-y-3">
      <div class="mt-5 grid gap-3 sm:grid-cols-2">
        {networks.map(([key, label, placeholder]) => (
          <label class="min-w-0 space-y-1.5">
            <div class="relative">
              <span class="pointer-events-none absolute inset-y-0 left-0 flex w-10 items-center justify-center rounded-l-md border border-border bg-primary text-xs font-bold text-primary-foreground [&>svg]:size-4">
                {renderSocialIcon(key, label)}
              </span>
              <input
                value={props.value[key] ?? ""}
                placeholder={placeholder}
                autocomplete="off"
                aria-label={label}
                onInput={(event) =>
                  updateNetwork(key, event.currentTarget.value)
                }
                onBlur={(event) =>
                  updateNetwork(key, normalize(event.currentTarget.value))
                }
                class="h-10 w-full min-w-0 rounded-md border border-border bg-background pl-12 pr-3 text-sm outline-none focus:border-primary"
              />
            </div>
            {props.value[key] && (
              <p
                class="truncate text-right text-xs text-muted-foreground"
                title={socialHref(key, normalize(props.value[key] ?? ""))}
              >
                {socialHref(key, normalize(props.value[key] ?? ""))}
              </p>
            )}
          </label>
        ))}
      </div>
    </div>
  );
}

function renderSocialIcon(key: string, label: string) {
  const Icon = SocialIcons[key];
  return Icon ? <Icon /> : label.slice(0, 2).toUpperCase();
}

function Toggle(props: {
  label: string;
  checked: boolean;
  onChange: (checked: boolean) => void;
}) {
  return (
    <label class="flex items-center justify-between gap-4 rounded-md border border-border bg-background p-3 text-sm">
      <span>{props.label}</span>
      <input
        type="checkbox"
        checked={props.checked}
        onChange={(event) => props.onChange(event.currentTarget.checked)}
        class="size-4 accent-primary"
      />
    </label>
  );
}

function TimezoneField(props: {
  value: string;
  onInput: (value: string) => void;
}) {
  const zones =
    typeof Intl.supportedValuesOf === "function"
      ? Intl.supportedValuesOf("timeZone")
      : ["America/Sao_Paulo", "UTC"];
  const options = zones.map((zone) => ({
    value: zone,
    label: zone.replaceAll("_", " "),
  }));
  return (
    <label class="block space-y-1.5 text-sm font-medium">
      Fuso horário
      <Combobox
        value={props.value}
        options={options}
        placeholder="Selecione o fuso horário"
        searchPlaceholder="Buscar cidade ou fuso…"
        onChange={props.onInput}
      />
    </label>
  );
}
