// front/univents-solid/src/features/upload-queue/ui/upload-queue-provider.tsx
import type { JSX } from "@solidjs/web";
import { useNavigate } from "@tanstack/solid-router";
import { useAuth } from "@trieoh/identityx-sdk-ts-solid";
import { createEffect, onCleanup } from "solid-js";
import { toast } from "@/shared/ui/toast";
import { useUploadQueue } from "../hooks/use-upload-queue";
import { uploadQueueProcessor } from "../lib/processor";
import { uploadQueueStore } from "../lib/store";
import type { UploadTaskStatus } from "../model/types";

const notificationStatuses = new Set<UploadTaskStatus>([
  "completed",
  "failed",
  "rejected",
]);

export function UploadQueueProvider(props: { children?: JSX.Element }): JSX.Element {
  const navigate = useNavigate();
  const { auth, isAuthenticated } = useAuth();
  const accountId = () => (isAuthenticated() ? auth.profile()?.id : undefined);
  const queue = useUploadQueue();
  const previousStatuses = new Map<string, UploadTaskStatus>();
  let notificationAccountId: string | undefined;

  onCleanup(() => {
    uploadQueueProcessor.stop();
    uploadQueueStore.setActiveAccount(undefined);
  });

  createEffect(
    () => accountId(),
    (id) => {
      uploadQueueStore.setActiveAccount(id);
      previousStatuses.clear();

      if (!id) {
        uploadQueueProcessor.stop();
        return;
      }

      void uploadQueueProcessor.start();
    },
  );

  createEffect(
    () => ({ id: accountId(), initialized: queue.initialized, tasks: queue.tasks }),
    ({ id, initialized, tasks }) => {
      if (!initialized || !id) return;

      if (notificationAccountId !== id) {
        notificationAccountId = id;
        previousStatuses.clear();
        for (const task of tasks) {
          previousStatuses.set(task.id, task.status);
        }
        return;
      }

      if (previousStatuses.size === 0) {
        for (const task of tasks) {
          previousStatuses.set(task.id, task.status);
        }
        return;
      }

      for (const task of tasks) {
        const prevStatus = previousStatuses.get(task.id);
        if (prevStatus === task.status || !notificationStatuses.has(task.status)) {
          continue;
        }

        if (task.status === "completed") {
          toast.success(`${task.label} foi enviada com sucesso.`);
          continue;
        }

        if (task.status === "rejected" || task.error?.requiresReplacement) {
          toast.error(
            task.error?.message ?? `É necessário substituir ${task.label}.`,
            {
              action: {
                label: "Corrigir imagem",
                onClick: () => {
                  if (task.correctionPath) {
                    void navigate({ to: task.correctionPath });
                  } else {
                    void navigate({
                      to: "/admin/uploads",
                      search: { task: task.id },
                    });
                  }
                },
              },
            },
          );
          continue;
        }

        toast.error(
          task.error?.message ?? `Não foi possível enviar ${task.label}.`,
          {
            action: task.error?.retryable
              ? {
                  label: "Tentar novamente",
                  onClick: () => void queue.retry(task.id),
                }
              : {
                  label: "Ver detalhes",
                  onClick: () =>
                    void navigate({
                      to: "/admin/uploads",
                      search: { task: task.id },
                    }),
                },
          },
        );
      }

      previousStatuses.clear();
      for (const task of tasks) {
        previousStatuses.set(task.id, task.status);
      }
    },
  );

  return <>{props.children}</>;
}

// front/univents/src/features/upload-queue/ui/upload-queue-provider.tsx
import { useNavigate } from "@tanstack/react-router";
import { useAuth } from "@trieoh/identityx-sdk-ts/react";
import { useEffect, useRef } from "react";
import { toast } from "sonner";
import { useUploadQueue } from "../hooks/use-upload-queue";
import { uploadQueueProcessor } from "../lib/processor";
import { uploadQueueStore } from "../lib/store";
import type { UploadTaskStatus } from "../model/types";

const notificationStatuses = new Set<UploadTaskStatus>([
  "completed",
  "failed",
  "rejected",
]);

export function UploadQueueProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const navigate = useNavigate();
  const { auth, isAuthenticated } = useAuth();
  const accountId = isAuthenticated ? auth.profile()?.id : undefined;
  const { tasks, initialized, retry } = useUploadQueue();
  const previousStatuses = useRef(new Map<string, UploadTaskStatus>());
  const notificationAccountId = useRef<string | undefined>(undefined);

  useEffect(() => {
    uploadQueueStore.setActiveAccount(accountId);
    previousStatuses.current.clear();

    if (!accountId) {
      uploadQueueProcessor.stop();
      return;
    }

    void uploadQueueProcessor.start();
    return () => {
      uploadQueueProcessor.stop();
      uploadQueueStore.setActiveAccount(undefined);
    };
  }, [accountId]);

  useEffect(() => {
    if (!initialized || !accountId) return;

    if (notificationAccountId.current !== accountId) {
      notificationAccountId.current = accountId;
      previousStatuses.current = new Map(
        tasks.map((task) => [task.id, task.status]),
      );
      return;
    }

    if (previousStatuses.current.size === 0) {
      previousStatuses.current = new Map(
        tasks.map((task) => [task.id, task.status]),
      );
      return;
    }

    for (const task of tasks) {
      const previousStatus = previousStatuses.current.get(task.id);
      if (
        previousStatus === task.status ||
        !notificationStatuses.has(task.status)
      )
        continue;

      if (task.status === "completed") {
        toast.success(`${task.label} foi enviada com sucesso.`, {
          id: `upload-${task.id}`,
        });
        continue;
      }

      if (task.status === "rejected" || task.error?.requiresReplacement) {
        toast.error(
          task.error?.message ?? `É necessário substituir ${task.label}.`,
          {
            id: `upload-${task.id}`,
            action: {
              label: "Corrigir imagem",
              onClick: () => {
                if (task.correctionPath) {
                  void navigate({ to: task.correctionPath });
                } else {
                  void navigate({
                    to: "/admin/uploads",
                    search: { task: task.id },
                  });
                }
              },
            },
          },
        );
        continue;
      }

      toast.error(
        task.error?.message ?? `Não foi possível enviar ${task.label}.`,
        {
          id: `upload-${task.id}`,
          action: task.error?.retryable
            ? {
                label: "Tentar novamente",
                onClick: () => void retry(task.id),
              }
            : {
                label: "Ver detalhes",
                onClick: () =>
                  void navigate({
                    to: "/admin/uploads",
                    search: { task: task.id },
                  }),
              },
        },
      );
    }

    previousStatuses.current = new Map(
      tasks.map((task) => [task.id, task.status]),
    );
  }, [accountId, initialized, navigate, retry, tasks]);

  return children;
}
