// front/univents/src/features/purchases/ui/purchases-content.tsx
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ShoppingBag } from "lucide-react";
import { myPurchasesQueryOptions } from "../api";
import { resolvePurchaseCatalog } from "../api/purchase-catalog";
import { type Order, OrderCard, orderIcons } from "./order-card";

const money = (cents: number, currency: string) =>
  new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(
    cents / 100,
  );

export function PurchasesContent() {
  const { data, error, isPending } = useQuery(myPurchasesQueryOptions());
  const purchases = data?.purchases ?? [];
  const catalogItems = purchases.flatMap((purchase) =>
    purchase.items.map((item) => ({
      ...item,
      edition_id: purchase.edition_id,
    })),
  );
  const { data: catalog = {} } = useQuery({
    queryKey: [
      "purchase-catalog",
      catalogItems.map((item) => `${item.item_type}:${item.item_id}`).join(","),
    ],
    queryFn: () => resolvePurchaseCatalog(catalogItems),
    enabled: catalogItems.some((item) => item.item_id.includes("-")),
  });
  const orders: Order[] = purchases.map((purchase) => ({
    purchaseId: purchase.purchase_id,
    status:
      purchase.status === "approved" || purchase.status === "pending"
        ? purchase.status
        : purchase.status === "refunded"
          ? "refunded"
          : "cancelled",
    paymentIcon:
      purchase.payment_method === "pix"
        ? orderIcons.Zap
        : orderIcons.CreditCard,
    paymentText:
      purchase.payment_method === "pix" ? "Pix" : "Cartão de crédito",
    date: new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(
      new Date(purchase.created_at ?? purchase.expires_at),
    ),
    total: money(purchase.total_cents, purchase.currency),
    items: purchase.items.map((item) => {
      const details = catalog[`${item.item_type}:${item.item_id}`];
      return {
        icon:
          item.item_type === "ticket"
            ? orderIcons.Ticket
            : item.item_type === "product"
              ? orderIcons.Wallet
              : orderIcons.FileText,
        image: details?.image ?? undefined,
        title: details?.name ?? "Item não identificado",
        description:
          details?.description ??
          `${item.quantity} unidade${item.quantity > 1 ? "s" : ""}`,
        price: money(item.unit_price_cents * item.quantity, purchase.currency),
      };
    }),
  }));

  if (isPending) {
    return <p className="text-sm text-muted-foreground">Carregando compras…</p>;
  }

  if (error || orders.length === 0) {
    return (
      <div className="flex min-h-64 flex-col items-center justify-center border border-dashed border-border text-center">
        <ShoppingBag className="mb-3 size-10 text-muted-foreground" />
        <p className="font-medium">
          {error
            ? "Não foi possível carregar suas compras."
            : "Você ainda não possui compras."}
        </p>
      </div>
    );
  }
  return (
    <div className="grid gap-4 lg:grid-cols-2">
      {orders.map((order) => (
        <Link
          key={order.purchaseId}
          to="/checkouts/$purchaseId"
          params={{ purchaseId: order.purchaseId }}
          className="block h-full"
        >
          <OrderCard order={order} />
        </Link>
      ))}
    </div>
  );
}

// front/univents-solid/src/features/purchases/ui/PurchasesContent.tsx
import { For, Loading, Show, createMemo } from "solid-js";
import type { JSX } from "@solidjs/web";
import type { Purchase } from "@trieoh/univents-api/schemas";
import { Link } from "@tanstack/solid-router";
import { useQuery } from "@trieoh/front-core-solid";
import { myPurchasesQueryOptions } from "../api";
import ShoppingBagIcon from "~icons/lucide/shopping-bag";

const ShoppingBag = ShoppingBagIcon as unknown as () => JSX.Element;

const money = (cents: number, currency: string) =>
  new Intl.NumberFormat("pt-BR", { style: "currency", currency }).format(cents / 100);

const status: Record<string, [string, string]> = {
  approved: ["Sucesso", "text-emerald-600 dark:text-emerald-500"],
  pending: ["Pendente", "text-amber-600 dark:text-amber-500"],
  refunded: ["Reembolsado", "text-violet-600 dark:text-violet-500"],
  cancelled: ["Cancelado", "text-muted-foreground"],
  expired: ["Expirado", "text-muted-foreground"],
  failed: ["Falhou", "text-destructive"],
  rejected: ["Recusado", "text-destructive"],
};

export function PurchasesContent() {
  const purchasesQuery = useQuery(myPurchasesQueryOptions());
  const data = createMemo(() => purchasesQuery().data);

  return (
    <Loading
      fallback={
        <div class="grid gap-3">
          <div class="h-17 animate-pulse rounded-md bg-muted" />
          <div class="h-17 animate-pulse rounded-md bg-muted" />
        </div>
      }
    >
      <Show when={data()}>
        {(loaded) => (
          <Show
            when={loaded().purchases.length}
            fallback={
              <div class="rounded-md border border-dashed border-border p-10 text-center">
                <h2 class="font-semibold">Você ainda não possui compras</h2>
                <p class="mt-2 text-sm text-muted-foreground">
                  Ingressos, produtos e atividades aparecerão aqui.
                </p>
              </div>
            }
          >
            <div class="grid gap-3 sm:grid-cols-2">
              <For each={loaded().purchases}>
                {(purchase) => <OrderCard purchase={purchase} />}
              </For>
            </div>
          </Show>
        )}
      </Show>
    </Loading>
  );
}

function OrderCard(props: { purchase: Purchase }) {
  const tone = () =>
    status[props.purchase.status] ?? [props.purchase.status, "text-muted-foreground"];

  const date = () =>
    new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", year: "numeric" }).format(
      new Date(props.purchase.created_at ?? props.purchase.expires_at)
    );

  const payment = () =>
    props.purchase.payment_method === "pix" ? "Pix" : props.purchase.total_cents === 0 ? "" : "Cartão";

  const itemCount = () =>
    `${props.purchase.items.length} ${props.purchase.items.length === 1 ? "item" : "itens"}`;

  const isFree = () => props.purchase.total_cents === 0;

  return (
    <Link
      to="/checkouts/$purchaseId"
      params={{ purchaseId: props.purchase.purchase_id }}
      class="block"
    >
      <article class="flex gap-3 rounded-md border border-border bg-card p-3 shadow-sm transition hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-md sm:p-4">
        <span class="flex size-9 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary">
          <ShoppingBag />
        </span>

        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-2">
            <h3 class="min-w-0 flex-1 truncate text-sm font-semibold text-foreground">
              {date()}
            </h3>
            <span class={`shrink-0 text-xs font-medium ${tone()[1]}`}>{tone()[0]}</span>
          </div>

          <div class="mt-1 flex items-center justify-between gap-2">
            <p class="min-w-0 truncate text-xs text-muted-foreground">
              {itemCount()}
              {payment() && ` · ${payment()}`}
            </p>
            <Show
              when={!isFree()}
              fallback={<span class="shrink-0 text-xs font-medium text-muted-foreground">Gratuito</span>}
            >
              <strong class="shrink-0 text-sm text-primary">
                {money(props.purchase.total_cents, props.purchase.currency)}
              </strong>
            </Show>
          </div>
        </div>
      </article>
    </Link>
  );
}
