// sdk/ts/identityx-solid/src/solid/components/Modern/ModernSignUp.tsx
import { createSignal } from "solid-js";
import { useAuth } from "../../AuthProvider";
import { Button, FormError, FormInput } from "./Shared";
import { ArrowRight, Loader2 } from "./Shared/Icons";

export interface ModernSignUpProps {
  onSuccess?: (message?: string) => Promise<void>;
  onFailed?: (message: string, trace?: string[]) => Promise<void>;
  signInRedirect?: () => void;
}

export function ModernSignUp(props: ModernSignUpProps) {
  const { auth } = useAuth();
  const [email, setEmail] = createSignal("");
  const [password, setPassword] = createSignal("");
  const [confirm, setConfirm] = createSignal("");
  const [emailError, setEmailError] = createSignal("");
  const [passwordError, setPasswordError] = createSignal("");
  const [confirmError, setConfirmError] = createSignal("");
  const [loading, setLoading] = createSignal(false);

  const submit = async (event: SubmitEvent) => {
    event.preventDefault();
    setEmailError(email() ? "" : "E-mail inválido");
    setPasswordError(password().length >= 8 ? "" : "A senha deve ter pelo menos 8 caracteres");
    setConfirmError(password() === confirm() ? "" : "As senhas não coincidem");
    if (!email() || password().length < 8 || password() !== confirm()) {
      return;
    }
    setLoading(true);
    try {
      const result = await auth.register(email(), password());
      if (result.success) await props.onSuccess?.(result.message);
      else await props.onFailed?.(result.message, result.trace);
    } catch {
      await props.onFailed?.("Ocorreu um erro inesperado");
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={submit} class="space-y-4">
      <div class="space-y-1">
        <FormInput
          label="E-mail"
          name="email"
          type="email"
          autocomplete="email"
          value={email()}
          error={!!emailError()}
          onInput={(e) => setEmail(e.currentTarget.value)}
        />
        <FormError id="email-error" message={emailError()} />
      </div>
      <div class="space-y-1">
        <FormInput
          label="Senha"
          name="password"
          type="password"
          autocomplete="new-password"
          value={password()}
          error={!!passwordError()}
          onInput={(e) => setPassword(e.currentTarget.value)}
        />
        <FormError id="password-error" message={passwordError()} />
      </div>
      <div class="space-y-1">
        <FormInput
          label="Confirmar senha"
          name="confirmPassword"
          type="password"
          autocomplete="new-password"
          value={confirm()}
          error={!!confirmError()}
          onInput={(e) => setConfirm(e.currentTarget.value)}
        />
        <FormError id="confirmPassword-error" message={confirmError()} />
      </div>

      <Button
        type="submit"
        disabled={loading()}
        class="w-full flex items-center justify-center gap-2"
      >
        {loading() ? (
          <Loader2 class="w-5 h-5 animate-spin" />
        ) : (
          <>
            Criar conta
            <ArrowRight class="w-4 h-4" />
          </>
        )}
      </Button>
    </form>
  );
}

// sdk/ts/identityx/src/react/components/Modern/ModernSignUp.tsx
import { useState } from 'react';
import { toast } from 'sonner';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { ArrowRight, Loader2 } from 'lucide-react';
import { useAuth } from "../../AuthProvider";
import FormInput from './Shared/FormInput';
import FormError from './Shared/FormError';
import { Button } from './Shared/Button';

const signUpSchema = z.object({
  email: z.email("E-mail inválido"),
  password: z.string().min(6, "A senha deve ter pelo menos 6 caracteres"),
  confirmPassword: z.string(),
}).refine((data) => data.password === data.confirmPassword, {
  message: "As senhas não coincidem",
  path: ["confirmPassword"],
});

type SignUpFormValues = z.infer<typeof signUpSchema>;

export interface ModernSignUpProps {
  onSuccess?: (message?: string) => Promise<void>;
  onFailed?: (message: string, trace?: string[]) => Promise<void>;
  signInRedirect?: () => void;
}

export function ModernSignUp({
  onSuccess,
  onFailed,
  signInRedirect,
}: ModernSignUpProps) {
  const [isLoading, setIsLoading] = useState(false);
  const { auth } = useAuth();

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<SignUpFormValues>({
    resolver: zodResolver(signUpSchema),
    defaultValues: { email: '', password: '', confirmPassword: '' },
  });

  const onSubmit = async (data: SignUpFormValues) => {
    setIsLoading(true);
    try {
      const response = await auth.register(data.email, data.password);
      if (response.success) {
        if (onSuccess) await onSuccess(response.message);
        else {
          toast.success("Conta criada com sucesso!");
          if (signInRedirect) signInRedirect();
        }
      } else {
        if (onFailed) await onFailed(response.message, response.trace);
        else toast.error(response.message || 'Erro ao criar conta');
      }
    } catch {
      toast.error('Ocorreu um erro inesperado');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <form
      onSubmit={handleSubmit(onSubmit)}
      className="space-y-4"
    >
      <div className="space-y-1">
        <FormInput
          label="E-mail"
          type="email"
          autoComplete="email"
          error={!!errors.email}
          {...register('email')}
        />
        <FormError message={errors.email?.message} />
      </div>

      <div className="space-y-1">
        <FormInput
          label="Senha"
          type="password"
          autoComplete="new-password"
          error={!!errors.password}
          {...register('password')}
        />
        <FormError message={errors.password?.message} />
      </div>

      <div className="space-y-1">
        <FormInput
          label="Confirmar Senha"
          type="password"
          autoComplete="new-password"
          error={!!errors.confirmPassword}
          {...register('confirmPassword')}
        />
        <FormError message={errors.confirmPassword?.message} />
      </div>

      <Button
        type="submit"
        disabled={isLoading}
        className="w-full flex items-center justify-center gap-2"
      >
        {isLoading ? <Loader2 className="w-5 h-5 animate-spin" /> : (
          <>
            Criar Conta
            <ArrowRight className="w-4 h-4" />
          </>
        )}
      </Button>
    </form>
  );
}
