// sdk/ts/identityx-solid/src/solid/components/Modern/ModernVerifyEmail.tsx
import { createSignal, onSettled } from "solid-js";
import { useAuth } from "../../AuthProvider";
import { Button } from "./Shared";
import { Loader2, CheckCircle2, XCircle, ArrowRight } from "./Shared/Icons";

export interface ModernVerifyEmailProps {
  token: string;
  onSuccess?: (message?: string) => Promise<void>;
  onFailed?: (message: string, trace?: string[]) => Promise<void>;
}

export function ModernVerifyEmail(props: ModernVerifyEmailProps) {
  const { auth } = useAuth();
  const [status, setStatus] = createSignal<"loading" | "success" | "error">("loading");
  const [message, setMessage] = createSignal("Verificando seu e-mail...");

  const verify = async () => {
    setStatus("loading");
    setMessage("Verificando seu e-mail...");
    try {
      const result = await auth.verifyEmail(props.token);
      if (result.success) {
        setStatus("success");
        setMessage(result.message || "E-mail verificado com sucesso!");
        await props.onSuccess?.(result.message);
      } else {
        setStatus("error");
        setMessage(result.message || "Falha ao verificar e-mail.");
        await props.onFailed?.(result.message, result.trace);
      }
    } catch {
      setStatus("error");
      setMessage("Ocorreu um erro inesperado.");
    }
  };

  onSettled(() => {
    if (props.token) {
      void verify();
    } else {
      setStatus("error");
      setMessage("Token de verificação inválido ou ausente.");
    }
  });

  return (
    <div class="text-center flex flex-col items-center gap-6">
        {status() === "loading" && (
          <div class="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center text-primary">
            <Loader2 class="w-8 h-8 animate-spin" />
          </div>
        )}

        {status() === "success" && (
          <div class="w-16 h-16 rounded-full bg-emerald-500/10 flex items-center justify-center text-emerald-600">
            <CheckCircle2 class="w-8 h-8" />
          </div>
        )}

        {status() === "error" && (
          <div class="w-16 h-16 rounded-full bg-destructive/10 flex items-center justify-center text-destructive">
            <XCircle class="w-8 h-8" />
          </div>
        )}

        <div class="space-y-2">
          <h1 class="font-heading text-2xl font-bold tracking-tight">
            {status() === "loading" ? "Verificando..."
              : status() === "success" ? "Tudo certo!"
                : "Ops, algo deu errado"}
          </h1>
          <p class="text-muted-foreground text-sm max-w-62.5 mx-auto">
            {message()}
          </p>
        </div>

        {status() === "error" && (
          <Button
            onClick={verify}
            class="w-full mt-2 flex items-center justify-center gap-2"
          >
            Tentar novamente
            <ArrowRight class="w-4 h-4" />
          </Button>
        )}
      </div>
  );
}

// sdk/ts/identityx/src/react/components/Modern/ModernVerifyEmail.tsx
import { useState, useEffect, useRef } from 'react';
import { motion } from "motion/react";
import { Loader2, CheckCircle2, XCircle, ArrowRight } from 'lucide-react';
import { useAuth } from "../../AuthProvider";
import { Button } from './Shared/Button';

export interface ModernVerifyEmailProps {
  token: string;
  onSuccess?: (message?: string) => Promise<void>;
  onFailed?: (message: string, trace?: string[]) => Promise<void>;
  signInRedirect?: () => void;
}

type VerifyStatus = "verifying" | "success" | "error" | "already_verified";

export function ModernVerifyEmail({
  token,
  onSuccess,
  onFailed,
  signInRedirect,
}: ModernVerifyEmailProps) {
  const [status, setStatus] = useState<VerifyStatus>("verifying");
  const [message, setMessage] = useState("Verificando seu e-mail...");
  const [isLoading, setIsLoading] = useState(true);
  const { auth } = useAuth();
  const hasAttempted = useRef(false);

  const handleVerify = async () => {
    if (hasAttempted.current) return;
    hasAttempted.current = true;

    setIsLoading(true);
    setStatus("verifying");

    try {
      const res = await auth.verifyEmail(token);

      if (res.success) {
        await auth.refresh();
        setStatus("success");
        setMessage(res.message || "E-mail verificado com sucesso!");
        if (onSuccess) await onSuccess(res.message);
      } else {
        setStatus("error");
        setMessage(res.message || "Falha na verificação do e-mail.");
        if (onFailed) await onFailed(res.message, res.trace);
      }
    } catch (error) {
      setStatus("error");
      setMessage("Ocorreu um erro inesperado durante a verificação.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    if (token && !hasAttempted.current) {
      void handleVerify();
    }
  }, [token]);

  return (
    <div className="w-full max-w-md z-10 flex flex-col antialiased selection:bg-primary/10 selection:text-primary">
      <div className="text-center mb-6">
        <motion.div
          initial={{ scale: 0.8, opacity: 0 }}
          animate={{ scale: 1, opacity: 1 }}
          className="flex justify-center mb-4"
        >
          {status === "verifying" && <Loader2 className="w-12 h-12 text-primary animate-spin" />}
          {(status === "success" || status === "already_verified") && <CheckCircle2 className="w-12 h-12 text-green-500" />}
          {status === "error" && <XCircle className="w-12 h-12 text-destructive" />}
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="font-heading text-3xl font-bold tracking-tight mb-2"
        >
          {status === "verifying" ? "Verificando..." :
            status === "error" ? "Falha na verificação" : "E-mail Verificado!"}
        </motion.h1>
        <p className="text-muted-foreground text-sm mb-6">
          {message}
        </p>

        {status === "error" && (
          <Button
            onClick={() => {
              hasAttempted.current = false;
              void handleVerify();
            }}
            disabled={isLoading}
            className="w-full flex items-center justify-center gap-2"
          >
            Tentar novamente
          </Button>
        )}

        {(status === "success" || status === "already_verified") && (
          <div className="space-y-4">
            <p className="text-xs text-muted-foreground">
              Você já pode continuar navegando em sua conta.
            </p>
            {signInRedirect && (
              <Button
                onClick={signInRedirect}
                className="w-full flex items-center justify-center gap-2"
              >
                Ir para o login
                <ArrowRight className="w-4 h-4" />
              </Button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
