// sdk/ts/identityx/src/react/components/Modern/Shared/AuthLayout.tsx
import { cn } from "../../../../utils/cn";

interface AuthLayoutProps {
  children: React.ReactNode;
  className?: string;
}

export function AuthLayout({ children, className }: AuthLayoutProps) {
  return (
    <main className={cn(
      "bg-background h-full text-foreground min-h-screen relative overflow-hidden",
      "flex justify-center items-center px-4",
      "antialiased selection:bg-primary/10 selection:text-primary",
      className
    )}>
      {/* Decorative background elements */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-primary/20 rounded-full blur-3xl pointer-events-none" />

      {children}
    </main>
  );
}

// sdk/ts/identityx-solid/src/solid/components/Modern/Shared/AuthLayout.tsx
import type { ParentProps } from "solid-js";
export interface AuthLayoutProps extends ParentProps {
  class?: string;
  backLink?: ParentProps["children"];
}
export function AuthLayout(props: AuthLayoutProps) {
  return (
    <main
      class={`bg-background h-full text-foreground min-h-screen relative overflow-hidden flex flex-col px-4 antialiased ${props.class ?? ""}`}
    >
      <div class="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      <div class="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-primary/20 rounded-full blur-3xl pointer-events-none" />
      {props.backLink && <div class="relative z-10 pt-4">{props.backLink}</div>}
      <div class="relative z-10 flex-1 flex justify-center items-center">
        {props.children}
      </div>
    </main>
  );
}
