// front/univents/src/features/tickets/ui/TicketCard.tsx
import type { MyTicket } from "@trieoh/univents-api/schemas";
import { ArrowUp, Check, ShoppingCart, Star, TicketCheck } from "lucide-react";
import { useCart } from "@/features/products/hooks/use-cart";
import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/shadcn/button";
import type { TicketI } from "../model";

function formatPrice(cents: number): string {
  if (cents === 0) return "Gratuito";
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
    minimumFractionDigits: 0,
  }).format(cents / 100);
}

interface TicketCardProps {
  ticket: TicketI;
  isFeatured?: boolean;
  editionId?: string;
  heldTicket?: MyTicket | null;
  stock?: number | null;
}

export function TicketCard({
  ticket,
  isFeatured,
  editionId,
  heldTicket = null,
  stock,
}: TicketCardProps) {
  const { addItem, items } = useCart(editionId ?? "");
  const inCart = items.find(
    (item) => item.id === ticket.id && item.type === "ticket",
  );
  const anotherTicketInCart = items.some(
    (item) => item.type === "ticket" && item.id !== ticket.id,
  );
  const isFree = ticket.price_cents === 0;
  const isOutOfStock =
    stock !== undefined
      ? stock === 0
      : ticket.max_quantity != null && ticket.max_quantity <= 0;

  const isHeld = heldTicket?.ticket_type.id === ticket.id;
  const hasHeldTicket = !!heldTicket;
  const isUpgrade =
    hasHeldTicket &&
    !isHeld &&
    ticket.access_level > (heldTicket?.ticket_type.access_level ?? -1) &&
    ticket.price_cents > (heldTicket?.ticket_type.price_cents ?? 0);
  const buttonLabel = isHeld
    ? "Ingresso atual"
    : isUpgrade
      ? "Upgrade em breve"
      : hasHeldTicket
        ? "Você já possui um ingresso"
        : anotherTicketInCart
          ? "Limite de 1 ingresso"
          : isOutOfStock
            ? "Esgotado"
            : inCart
              ? "Adicionado"
              : "Adicionar ao carrinho";

  return (
    <div
      className={cn(
        "relative flex flex-col w-72 h-56 rounded-2xl border overflow-hidden transition-all duration-300 p-5",
        isFeatured
          ? "bg-card border-border/60 lg:scale-105 lg:bg-primary/4 lg:border-primary/25 lg:shadow-lg lg:shadow-primary/5 lg:z-10 hover:border-border hover:shadow-md"
          : "bg-card border-border/60 hover:border-border hover:shadow-md",
      )}
    >
      {/* Badge */}
      <div className="absolute top-0 right-0">
        {isHeld ? (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-bl-xl rounded-tr-2xl bg-amber-500 text-white text-[10px] font-bold tracking-wide uppercase">
            <TicketCheck className="w-3 h-3" />
            Seu ingresso
          </span>
        ) : isUpgrade ? (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-bl-xl rounded-tr-2xl bg-primary text-primary-foreground text-[10px] font-bold tracking-wide uppercase">
            <ArrowUp className="w-3 h-3" />
            Upgrade
          </span>
        ) : isFree ? (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-bl-xl rounded-tr-2xl bg-emerald-500 text-white text-[10px] font-bold tracking-wide uppercase">
            <Check className="w-3 h-3" />
            Gratuito
          </span>
        ) : (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-bl-xl rounded-tr-2xl bg-primary text-primary-foreground text-[10px] font-bold tracking-wide uppercase">
            <Star className="w-3 h-3 fill-current" />
            Pago
          </span>
        )}
      </div>

      {/* Name */}
      <h3 className="font-semibold text-foreground leading-tight pr-16 text-base">
        {ticket.name}
      </h3>

      {/* Price */}
      <div className="mt-2">
        <span
          className={cn(
            "text-2xl font-bold",
            isFree
              ? "text-emerald-600 dark:text-emerald-400"
              : isFeatured
                ? "text-foreground lg:text-primary"
                : "text-foreground",
          )}
        >
          {formatPrice(ticket.price_cents)}
        </span>
        {isUpgrade && heldTicket && (
          <span className="ml-2 text-xs text-muted-foreground">
            +
            {formatPrice(
              ticket.price_cents - heldTicket.ticket_type.price_cents,
            )}
          </span>
        )}
      </div>
      {stock !== undefined && (
        <p className="mt-1 text-xs text-muted-foreground">
          {stock === null
            ? "Estoque ilimitado"
            : isOutOfStock
              ? "Esgotado"
              : `${stock} disponível${stock === 1 ? "" : "is"}`}
        </p>
      )}

      {/* Description */}
      {ticket.description && (
        <p className="mt-3 line-clamp-3 text-sm leading-relaxed whitespace-pre-line text-muted-foreground">
          {ticket.description}
        </p>
      )}
      {editionId && (
        <Button
          size="sm"
          variant={inCart ? "secondary" : "default"}
          disabled={
            isOutOfStock || anotherTicketInCart || isHeld || hasHeldTicket
          }
          className="mt-auto h-9 w-full gap-2 text-xs font-semibold shadow-sm"
          onClick={() =>
            addItem(
              {
                id: ticket.id,
                type: "ticket",
                name: ticket.name,
                price_cents: ticket.price_cents,
                inventory_remaining: ticket.max_quantity ?? 999,
                has_inventory: ticket.max_quantity !== null,
              },
              1,
            )
          }
        >
          {isOutOfStock ? (
            <TicketCheck className="h-4 w-4" />
          ) : isHeld ? (
            <TicketCheck className="h-4 w-4" />
          ) : isUpgrade ? (
            <ArrowUp className="h-4 w-4" />
          ) : inCart ? (
            <Check className="h-4 w-4" />
          ) : (
            <ShoppingCart className="h-4 w-4" />
          )}
          {buttonLabel}
        </Button>
      )}
    </div>
  );
}

// front/univents-solid/src/features/tickets/ui/TicketCard.tsx
import type { MyTicket, TicketType } from "@trieoh/univents-api/schemas";
import type { JSX } from "@solidjs/web";
import { untrack } from "solid-js";
import CheckIcon from "~icons/lucide/check";
import StarIcon from "~icons/lucide/star";
import TicketIcon from "~icons/lucide/ticket-check";
import { useCart } from "@/features/products/hooks/use-cart";

const Check = CheckIcon as unknown as () => JSX.Element;
const Star = StarIcon as unknown as () => JSX.Element;
const Ticket = TicketIcon as unknown as () => JSX.Element;

const price = (cents: number) =>
  cents === 0
    ? "Grátis"
    : new Intl.NumberFormat("pt-BR", {
      style: "currency",
      currency: "BRL",
    }).format(cents / 100);

export function TicketCard(props: {
  ticket: TicketType;
  featured?: boolean;
  stock?: number | null;
  editionId: string;
  heldTicket?: MyTicket | null;
}) {
  const cart = useCart(untrack(() => props.editionId));
  const free = () => props.ticket.price_cents === 0;
  const soldOut = () =>
    props.stock === 0 ||
    (props.stock === undefined && props.ticket.max_quantity === 0);
  const held = () => props.heldTicket?.ticket_type.id === props.ticket.id;
  const inCart = () =>
    cart
      .items()
      .some((item) => item.type === "ticket" && item.id === props.ticket.id);
  const anotherTicket = () =>
    cart
      .items()
      .some((item) => item.type === "ticket" && item.id !== props.ticket.id);

  return (
    <article
      class={`relative flex h-64 w-72 flex-col overflow-hidden rounded-2xl border p-5 transition-all duration-300 hover:border-border hover:shadow-md ${props.featured
        ? "border-primary/25 bg-primary/4 shadow-lg shadow-primary/5 lg:scale-105"
        : "border-border/60 bg-card"
        }`}
    >
      <span
        class={`absolute right-0 top-0 inline-flex items-center gap-1 rounded-bl-xl rounded-tr-2xl px-3 py-1 text-[10px] font-bold uppercase tracking-wide ${held()
          ? "bg-amber-500 text-white"
          : free()
            ? "bg-emerald-500 text-white"
            : "bg-primary text-primary-foreground"
          }`}
      >
        <span class="size-3 [&>svg]:size-3 [&>svg]:fill-current">
          {held() || free() ? <Check /> : <Star />}
        </span>
        {held() ? "Seu ingresso" : free() ? "Gratuito" : "Pago"}
      </span>
      <h3 class="pr-16 text-base font-semibold leading-tight text-foreground">
        {props.ticket.name}
      </h3>
      <p
        class={`mt-2 text-2xl font-bold ${free() ? "text-emerald-600 dark:text-emerald-400" : "text-foreground"
          }`}
      >
        {price(props.ticket.price_cents)}
      </p>
      {props.stock !== undefined && (
        <p class="mt-1 text-xs text-muted-foreground">
          {props.stock === null
            ? "Estoque ilimitado"
            : soldOut()
              ? "Esgotado"
              : `${props.stock} disponível${props.stock === 1 ? "" : "is"}`}
        </p>
      )}
      {props.ticket.description && (
        <p class="mt-3 line-clamp-3 whitespace-pre-line text-sm leading-relaxed text-muted-foreground">
          {props.ticket.description}
        </p>
      )}
      <button
        type="button"
        disabled={soldOut() || held() || anotherTicket()}
        class={`mt-auto inline-flex h-9 w-full items-center justify-center gap-2 rounded-md px-3 text-xs font-semibold ${soldOut() || held() || anotherTicket()
          ? "bg-muted text-muted-foreground"
          : "bg-primary text-primary-foreground"
          }`}
        onClick={() =>
          untrack(() =>
            cart.add({
              id: props.ticket.id,
              type: "ticket",
              name: props.ticket.name,
              price_cents: props.ticket.price_cents,
              stock: props.stock ?? props.ticket.max_quantity ?? null,
            })
          )
        }
      >
        <span class="size-4">
          <Ticket />
        </span>
        {held()
          ? "Ingresso atual"
          : anotherTicket()
            ? "Limite de 1 ingresso"
            : soldOut()
              ? "Esgotado"
              : inCart()
                ? "Adicionado"
                : "Adicionar ao carrinho"}
      </button>
    </article>
  );
}
