// front/univents/src/features/tickets/ui/TicketsSection.tsx
import { Link } from "@tanstack/react-router";
import type { MyTicket } from "@trieoh/univents-api/schemas";
import { ArrowRight } from "lucide-react";
import { cn } from "@/shared/lib/utils";
import type { TicketI } from "../model";
import { TicketCard } from "./TicketCard";

interface TicketsSectionProps {
  tickets: TicketI[];
  eventSlug: string;
  editionId?: string;
  heldTicket?: MyTicket | null;
}

export function TicketsSection({
  tickets,
  eventSlug,
  editionId,
  heldTicket = null,
}: TicketsSectionProps) {
  if (tickets.length === 0) return null;

  const sortedTickets = [...tickets]
    .sort((a, b) => b.access_level - a.access_level)
    .slice(0, 3);

  const visibilityClasses = ["", "hidden sm:block", "hidden lg:block"];

  return (
    <section className="w-full py-10">
      <div className="px-4">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-semibold text-foreground tracking-tight">
            Ingressos
          </h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed max-w-xl mx-auto">
            Escolha o tipo de ingresso que melhor se encaixa na sua experiência
            no evento.
          </p>
        </div>

        <div className="flex justify-center gap-4 max-w-5xl mx-auto">
          {sortedTickets.map((ticket, index) => (
            <div
              key={ticket.id}
              className={cn("shrink-0", visibilityClasses[index])}
            >
              <TicketCard
                ticket={ticket}
                isFeatured={index === 1}
                editionId={editionId}
                heldTicket={heldTicket}
              />
            </div>
          ))}
        </div>

        <div className="mt-6 text-center">
          <Link
            to="/events/$slug/store"
            search={{ tab: "tickets" }}
            params={{ slug: eventSlug }}
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:gap-2.5 transition-all duration-200"
          >
            Ver todos os ingressos
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </section>
  );
}

// front/univents-solid/src/features/tickets/ui/TicketsSection.tsx
import type {
  MyTicket,
  StoreStockItem,
  TicketType,
} from "@trieoh/univents-api/schemas";
import { For, Show, createMemo } from "solid-js";
import { Link } from "@tanstack/solid-router";
import { TicketCard } from "./TicketCard";

export function TicketsSection(props: {
  tickets: TicketType[];
  stock: StoreStockItem[];
  eventSlug: string;
  editionId: string;
  heldTicket: MyTicket | null;
}) {
  const stock = createMemo(
    () => new Map(props.stock.map((item) => [item.id, item.stock])),
  );
  return (
    <Show when={props.tickets.length > 0}>
      <section class="w-full py-10">
        <div class="mb-8 text-center">
          <h2 class="text-3xl font-semibold tracking-tight text-foreground">
            Ingressos
          </h2>
          <p class="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">
            Escolha o tipo de ingresso que melhor se encaixa na sua experiência
            no evento.
          </p>
        </div>
        <div class="mx-auto flex max-w-5xl justify-center gap-4">
          <For each={props.tickets.slice(0, 3)}>
            {(ticket, index) => (
              <div
                class={
                  index() === 1
                    ? "hidden shrink-0 sm:block"
                    : index() === 2
                      ? "hidden shrink-0 lg:block"
                      : "shrink-0"
                }
              >
                <TicketCard
                  ticket={ticket}
                  editionId={props.editionId}
                  stock={stock().get(ticket.id)}
                  featured={props.tickets.length > 2 && index() === 1}
                  heldTicket={props.heldTicket}
                />
              </div>
            )}
          </For>
        </div>
        <div class="mt-6 text-center">
          <Link
            class="text-sm font-semibold text-primary"
            to="/events/$slug/store"
            params={{ slug: props.eventSlug }}
            search={{ tab: "tickets" }}
          >
            Ver todos os ingressos →
          </Link>
        </div>
      </section>
    </Show>
  );
}
