// front/univents-solid/src/routes/profile/setup.tsx
import type { JSX } from "@solidjs/web";
import { createFileRoute } from "@tanstack/solid-router";
import { useAuth } from "@trieoh/identityx-sdk-ts-solid";
import { Show, createMemo, createSignal } from "solid-js";
import SaveIcon from "~icons/lucide/save";
import UserPenIcon from "~icons/lucide/user-pen";
import z from "zod";

import { requireAuth } from "@/features/auths/lib/route-guard";
import { useProfileSetupMutation } from "@/features/profile/api/mutations";
import { ProfileImageInput } from "@/features/profile/ui/ProfileImageInput";
import { toast } from "@/shared/ui/toast";

const Save = SaveIcon as unknown as (props: { class?: string }) => JSX.Element;
const UserPen = UserPenIcon as unknown as (props: {
  class?: string;
}) => JSX.Element;

export const Route = createFileRoute("/profile/setup")({
  beforeLoad: requireAuth,
  validateSearch: z.object({ returnTo: z.string().optional() }),
  component: ProfileSetup,
});

function ProfileSetup(): JSX.Element {
  const { auth } = useAuth();
  const navigate = Route.useNavigate();
  const search = Route.useSearch();
  const [photo, setPhoto] = createSignal<File>();
  const [handle, setHandle] = createSignal("");
  const [legalName, setLegalName] = createSignal("");
  const [preferredName, setPreferredName] = createSignal("");
  const [saving, setSaving] = createSignal(false);
  const setupMutation = useProfileSetupMutation();
  const complete = createMemo(() =>
    Boolean(handle().trim() && legalName().trim()),
  );

  const save = async (personalizeMore: boolean) => {
    const actorId = auth.profile()?.id;
    const submittedHandle = handle().trim().replace(/^@/, "");
    if (!actorId || !complete()) return;
    if (
      /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(submittedHandle)
    ) {
      toast.error("Escolha um nome de usuário que não seja um UUID.");
      return;
    }
    setSaving(true);
    try {
      await setupMutation.mutateAsync({
        actorId,
        auth,
        handle: submittedHandle,
        legalName: legalName().trim(),
        preferredName: preferredName().trim(),
        photo: photo(),
      });
      toast.success("Perfil criado");
      if (search().returnTo && !personalizeMore) {
        window.location.assign(search().returnTo!);
      } else {
        void navigate(
          personalizeMore
            ? { to: "/profile/edit", search: { returnTo: search().returnTo } }
            : { to: "/profile", search: { tab: "about" } },
        );
      }
    } catch (error) {
      toast.error(
        error instanceof Error
          ? error.message
          : "Não foi possível salvar o perfil.",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <main class="mx-auto flex min-h-dvh w-full max-w-xl flex-col justify-center px-5 py-12 pb-32 sm:px-8">
      <div class="mb-8 text-center">
        <h1 class="text-3xl font-bold">Configure seu perfil</h1>
        <p class="mt-2 text-sm text-muted-foreground">
          Preencha o básico para começar a usar o Univents.
        </p>
      </div>
      <form
        class="flex flex-col gap-5"
        onSubmit={(event) => {
          event.preventDefault();
          void save(false);
        }}
      >
        <div class="flex justify-center py-1">
          <ProfileImageInput
            label="Foto do perfil"
            variant="avatar"
            onSelect={setPhoto}
          />
        </div>
        <SetupField label="Nome de usuário" htmlFor="setup-handle">
          <input
            id="setup-handle"
            required
            pattern="[^\\s/]+"
            autocomplete="username"
            placeholder="seu username"
            class="w-full rounded-md border border-input bg-background px-3 py-2"
            value={handle()}
            onInput={(event) => setHandle(event.currentTarget.value)}
          />
        </SetupField>
        <SetupField label="Nome civil" htmlFor="setup-legal-name">
          <input
            id="setup-legal-name"
            required
            autocomplete="name"
            placeholder="Seu nome completo"
            class="w-full rounded-md border border-input bg-background px-3 py-2"
            value={legalName()}
            onInput={(event) => setLegalName(event.currentTarget.value)}
          />
        </SetupField>
        <SetupField
          label="Nome social (opcional)"
          htmlFor="setup-preferred-name"
        >
          <input
            id="setup-preferred-name"
            placeholder="Como prefere ser chamado"
            class="w-full rounded-md border border-input bg-background px-3 py-2"
            value={preferredName()}
            onInput={(event) => setPreferredName(event.currentTarget.value)}
          />
        </SetupField>
        <div class="mt-3 flex flex-col gap-3">
          <button
            type="submit"
            disabled={!complete() || saving()}
            class="flex h-12 items-center justify-center gap-2 rounded-md bg-primary text-base text-primary-foreground disabled:opacity-50"
          >
            <Save class="size-4" />
            {saving() ? "Salvando…" : "Salvar"}
          </button>
          <Show when={complete()}>
            <button
              type="button"
              disabled={saving()}
              class="flex h-12 items-center justify-center gap-2 rounded-md border border-input text-base disabled:opacity-50"
              onClick={() => void save(true)}
            >
              <UserPen class="size-5" />
              Personalizar mais
            </button>
          </Show>
        </div>
      </form>
    </main>
  );
}

function SetupField(props: {
  label: string;
  htmlFor: string;
  children: JSX.Element;
}): JSX.Element {
  return (
    <label class="space-y-2 text-sm font-medium" for={props.htmlFor}>
      {props.label}
      {props.children}
    </label>
  );
}

// front/univents/src/routes/profile/setup.tsx
import { useQueryClient } from "@tanstack/react-query";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import type { ProfileData } from "@trieoh/identityx-sdk-ts";
import { useAuth } from "@trieoh/identityx-sdk-ts/react";
import { Save, UserPen } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { requireAuth } from "@/features/auths/lib/route-guard";
import { invalidateProfileCaches } from "@/features/profile/api/cache";
import {
  isInitialProfileComplete,
  withProfileTimestamps,
} from "@/features/profile/model/profile-data";
import { ProfileImageInput } from "@/features/profile/ui/profile-image-input";
import { preprocessImageUpload } from "@/features/storage/api";
import { Button } from "@/shared/ui/shadcn/button";
import { Input } from "@/shared/ui/shadcn/input";
import { Label } from "@/shared/ui/shadcn/label";

export const Route = createFileRoute("/profile/setup")({
  beforeLoad: requireAuth,
  validateSearch: (search: Record<string, unknown>) => ({
    returnTo: typeof search.returnTo === "string" ? search.returnTo : undefined,
  }),
  component: InitialProfileSetup,
});

function InitialProfileSetup() {
  const { auth } = useAuth();
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const { returnTo } = Route.useSearch();
  const [photo, setPhoto] = useState<File>();
  const [handle, setHandle] = useState("");
  const [legalName, setLegalName] = useState("");
  const [preferredName, setPreferredName] = useState("");
  const [saving, setSaving] = useState(false);
  const complete = isInitialProfileComplete({
    handle,
    legalName,
  });

  const save = async (personalizeMore: boolean) => {
    const actorId = auth.profile()?.id;
    const submittedHandle = handle.trim().replace(/^@/, "");
    if (!actorId || !complete) return;
    if (
      /^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(submittedHandle)
    ) {
      toast.error("Escolha um nome de usuário que não seja um UUID.");
      return;
    }

    setSaving(true);
    try {
      const pfpUrl = photo
        ? await preprocessImageUpload(
            photo,
            "profiles/images",
            crypto.randomUUID(),
          )
        : undefined;
      const profile = withProfileTimestamps({}, {
        legalName: legalName.trim(),
        preferredName: preferredName.trim() || legalName.trim(),
        ...(pfpUrl ? { pfpUrl } : {}),
      } as ProfileData);
      const response = await auth.upsertActorProfile(actorId, {
        handle: submittedHandle,
        pfp_url: pfpUrl ?? null,
        profile: Object.fromEntries(
          Object.entries(profile).filter(([key]) => key !== "pfpUrl"),
        ),
      });
      if (!response.success) {
        throw new Error(
          response.message || "Não foi possível salvar o perfil.",
        );
      }
      await invalidateProfileCaches(queryClient);
      toast.success("Perfil criado");
      if (returnTo && !personalizeMore) {
        window.location.assign(returnTo);
      } else {
        await navigate(
          personalizeMore
            ? { to: "/profile/edit", search: { returnTo } }
            : { to: "/profile", search: { tab: "about" } },
        );
      }
    } catch (error) {
      toast.error(
        error instanceof Error
          ? error.message
          : "Não foi possível salvar o perfil.",
      );
    } finally {
      setSaving(false);
    }
  };

  return (
    <main className="mx-auto flex min-h-dvh w-full max-w-xl flex-col justify-center px-5 py-12 pb-32 sm:px-8">
      <div className="mb-8 text-center">
        <h1 className="text-3xl font-bold">Configure seu perfil</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Preencha o básico para começar a usar o Univents.
        </p>
      </div>

      <form
        className="flex flex-col gap-5"
        onSubmit={(event) => {
          event.preventDefault();
          void save(false);
        }}
      >
        <div className="flex justify-center py-1">
          <ProfileImageInput
            label="Foto do perfil"
            file={photo}
            onSelect={setPhoto}
            variant="avatar"
            className="rounded-full ring-2 ring-border ring-offset-4 ring-offset-background"
          />
        </div>

        <SetupField label="Nome de usuário" htmlFor="setup-handle">
          <Input
            id="setup-handle"
            required
            value={handle}
            pattern={"[^\\s/]+"}
            autoCapitalize="none"
            autoComplete="username"
            placeholder="seu username"
            onChange={(event) => setHandle(event.target.value)}
          />
        </SetupField>
        <SetupField label="Nome civil" htmlFor="setup-legal-name">
          <Input
            id="setup-legal-name"
            required
            value={legalName}
            autoComplete="name"
            placeholder="Seu nome completo"
            onChange={(event) => setLegalName(event.target.value)}
          />
        </SetupField>
        <SetupField
          label="Nome social (opcional)"
          htmlFor="setup-preferred-name"
        >
          <Input
            id="setup-preferred-name"
            value={preferredName}
            placeholder="Como prefere ser chamado"
            onChange={(event) => setPreferredName(event.target.value)}
          />
        </SetupField>

        <div className="mt-3 flex flex-col gap-3">
          <Button
            type="submit"
            className="h-12 text-base"
            disabled={!complete || saving}
          >
            <Save className="size-4" />
            {saving ? "Salvando…" : "Salvar"}
          </Button>
          {complete && (
            <Button
              type="button"
              variant="outline"
              className="h-12 text-base"
              disabled={saving}
              onClick={() => void save(true)}
            >
              <UserPen className="size-5" />
              Personalizar mais
            </Button>
          )}
        </div>
      </form>
    </main>
  );
}

function SetupField({
  label,
  htmlFor,
  children,
}: {
  label: string;
  htmlFor: string;
  children: React.ReactNode;
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={htmlFor}>{label}</Label>
      {children}
    </div>
  );
}
