// front/univents/src/widgets/sidebar/hooks/use-sidebar.tsx
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
} from "react";

interface SidebarContextValue {
  /** Sidebar collapsed (icon-only mode) — only applies to screens >= lg */
  collapsed: boolean;
  setCollapsed: (value: boolean) => void;
  toggleCollapsed: () => void;
  /** Drawer open — only applies to screens < lg */
  mobileOpen: boolean;
  setMobileOpen: (value: boolean) => void;
  toggleMobileOpen: () => void;
}

const SidebarContext = createContext<SidebarContextValue | null>(null);

const DESKTOP_BREAKPOINT = 1024; // px, matches Tailwind's "lg" breakpoint

export function SidebarProvider({ children }: { children: React.ReactNode }) {
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);

  const toggleCollapsed = useCallback(() => setCollapsed((v) => !v), []);
  const toggleMobileOpen = useCallback(() => setMobileOpen((v) => !v), []);

  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      const isToggleShortcut =
        (e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "b";

      // Ctrl/Cmd + B toggles the sidebar: drawer on mobile, collapse on desktop
      if (isToggleShortcut) {
        e.preventDefault();
        if (window.innerWidth < DESKTOP_BREAKPOINT) {
          setMobileOpen((v) => !v);
        } else {
          setCollapsed((v) => !v);
        }
        return;
      }

      // ESC always closes the mobile drawer, if it's open
      if (e.key === "Escape") {
        setMobileOpen((v) => (v ? false : v));
      }
    }

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Prevents the drawer from staying "open" if the viewport grows into desktop size
  useEffect(() => {
    function handleResize() {
      if (window.innerWidth >= DESKTOP_BREAKPOINT) setMobileOpen(false);
    }
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const value = useMemo<SidebarContextValue>(
    () => ({
      collapsed,
      setCollapsed,
      toggleCollapsed,
      mobileOpen,
      setMobileOpen,
      toggleMobileOpen,
    }),
    [collapsed, mobileOpen, toggleCollapsed, toggleMobileOpen],
  );

  return (
    <SidebarContext.Provider value={value}>
      {" "}
      {children}{" "}
    </SidebarContext.Provider>
  );
}

export function useSidebar() {
  const ctx = useContext(SidebarContext);
  if (!ctx) {
    throw new Error("useSidebar precisa ser usado dentro de <SidebarProvider>");
  }
  return ctx;
}

// front/univents-solid/src/widgets/sidebar/use-sidebar.tsx
import {
  createComponent,
  createContext,
  createSignal,
  onCleanup,
  onSettled,
  useContext,
  type ParentProps,
} from "solid-js";

export interface SidebarContextValue {
  /** Icon-only mode. Only applies from `lg` up. */
  collapsed: () => boolean;
  toggleCollapsed: () => void;
  /** Drawer state. Only applies below `lg`. */
  mobileOpen: () => boolean;
  setMobileOpen: (open: boolean) => void;
}

const SidebarContext = createContext<SidebarContextValue>();

/** Matches Tailwind's `lg`, which is where the drawer becomes a rail. */
const DESKTOP_BREAKPOINT = 1024;

/**
 * Mode is split the same way as the React admin shell: a drawer under `lg`, a
 * collapsible rail above it, Ctrl/Cmd+B toggling whichever applies, Escape
 * closing the drawer.
 */
export function SidebarProvider(props: ParentProps) {
  const [collapsed, setCollapsed] = createSignal(false);
  const [mobileOpen, setMobileOpen] = createSignal(false);

  const onKeyDown = (event: KeyboardEvent) => {
    if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "b") {
      event.preventDefault();
      if (window.innerWidth < DESKTOP_BREAKPOINT) {
        setMobileOpen((open) => !open);
      } else {
        setCollapsed((value) => !value);
      }
      return;
    }

    if (event.key === "Escape") setMobileOpen(false);
  };

  const onResize = () => {
    if (window.innerWidth >= DESKTOP_BREAKPOINT) setMobileOpen(false);
  };

  // Listeners are attached after mount and cleaned up on the owner, never
  // `onCleanup` inside a callback (`NO_OWNER_CLEANUP`).
  onSettled(() => {
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("resize", onResize);
  });

  onCleanup(() => {
    window.removeEventListener("keydown", onKeyDown);
    window.removeEventListener("resize", onResize);
  });

  return createComponent(SidebarContext, {
    value: {
      collapsed,
      toggleCollapsed: () => setCollapsed((value) => !value),
      mobileOpen,
      setMobileOpen,
    },
    get children() {
      return props.children;
    },
  });
}

export function useSidebar(): SidebarContextValue {
  const context = useContext(SidebarContext);
  if (!context) {
    throw new Error("useSidebar precisa ser usado dentro de <SidebarProvider>");
  }
  return context;
}
