// front/univents-solid/src/features/certifications/ui/UserCertificationsSection.tsx
import type { JSX } from "@solidjs/web";
import { Link } from "@tanstack/solid-router";
import { useQuery } from "@trieoh/front-core-solid";
import { EmptyState } from "@trieoh/ui-solid";
import { For, Show, createMemo } from "solid-js";
import FileCheck2Icon from "~icons/lucide/file-check-2";

import { allPublicEventsQueryOptions } from "@/features/events/api";
import type { EventI } from "@/features/events/model";
import {
  certificationTemplateQueryOptions,
  myCertificationsQueryOptions,
} from "../api";
import { getCertificationTemplateOrDefault } from "../default-template";
import { DEFAULT_CERTIFICATE_CANVAS } from "../editor/constants";
import type { CertificateVariableValues } from "../editor/variables";
import type { CertificationI, CertificationTemplateI } from "../model";
import { CertificateTemplateStaticView } from "./CertViewer";

const FileCheck2 = FileCheck2Icon as unknown as (props: { class?: string }) => JSX.Element;

export interface UserCertificationsSectionProps {
  participantName: string;
  certifications?: CertificationI[];
}

export function UserCertificationsSection(
  props: UserCertificationsSectionProps,
): JSX.Element {
  const certsQuery = useQuery(() => ({
    ...myCertificationsQueryOptions(),
    enabled: props.certifications === undefined,
  }));

  const certifications = createMemo<CertificationI[]>(() => {
    if (props.certifications !== undefined) {
      return props.certifications;
    }
    return (certsQuery().data ?? []) as CertificationI[];
  });

  const isLoading = createMemo(() => {
    if (props.certifications !== undefined) return false;
    return certsQuery().isLoading;
  });

  const eventsQuery = useQuery(() => allPublicEventsQueryOptions());
  const events = createMemo<EventI[]>(() => (eventsQuery().data ?? []) as EventI[]);

  return (
    <Show
      when={!isLoading()}
      fallback={
        <div class="flex flex-wrap items-start justify-center gap-3 sm:justify-start">
          <For each={[1, 2, 3]}>
            {() => (
              <div
                class="animate-pulse rounded-lg border border-border/40 bg-muted/40"
                style={{
                  width: "320px",
                  height: "226px",
                  "max-width": "100%",
                }}
              />
            )}
          </For>
        </div>
      }
    >
      <Show
        when={certifications().length > 0}
        fallback={
          <EmptyState
            icon={<FileCheck2 class="size-6 text-foreground/70" />}
            title="Nenhum certificado emitido"
            description="Seus certificados aparecerão aqui quando forem liberados."
          />
        }
      >
        <div class="flex flex-wrap items-start justify-center gap-3 sm:justify-start">
          <For each={certifications()}>
            {(certification) => (
              <CertificateProfileCard
                certification={certification}
                participantName={props.participantName}
                events={events()}
              />
            )}
          </For>
        </div>
      </Show>
    </Show>
  );
}

function CertificateProfileCard(props: {
  certification: CertificationI;
  participantName: string;
  events: EventI[];
}): JSX.Element {
  const templateQuery = useQuery(() => ({
    ...certificationTemplateQueryOptions(props.certification.template_id ?? ""),
    enabled: Boolean(props.certification.template_id),
  }));

  const template = createMemo(() =>
    getCertificationTemplateOrDefault(templateQuery().data as CertificationTemplateI | undefined),
  );

  const eventName = createMemo(() => {
    const matched = props.events.find(
      (ev) => ev.id === props.certification.edition_id,
    );
    return matched?.full_name ?? "Univents";
  });

  const scopeName = createMemo(() => "Certificado de Participação");

  const canvas = createMemo(
    () => template().design_data?.canvas ?? DEFAULT_CERTIFICATE_CANVAS,
  );

  const width = 320;
  const height = createMemo(() => (width * canvas().height) / canvas().width);

  const variables = createMemo<CertificateVariableValues>(() => {
    const origin = typeof window !== "undefined" ? window.location.origin : "";
    return {
      participant_name: props.participantName || "Participante",
      event_name: eventName(),
      edition_name: "Edição",
      activity_name: scopeName(),
      participation_type: props.certification.program_id ? "atividade" : "edição",
      location: "",
      certified_at: new Date(props.certification.issued_at).toLocaleDateString("pt-BR"),
      cert_hash: props.certification.verification_hash,
      verify_url: `${origin}/verify/${props.certification.verification_hash}`,
    };
  });

  return (
    <Link
      to="/verify/$hash"
      params={{ hash: props.certification.verification_hash }}
      class="block max-w-full cursor-pointer transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded-lg overflow-hidden shadow-xs hover:shadow-md"
      style={{
        width: `${width}px`,
        height: `${height()}px`,
        "max-width": "100%",
      }}
      aria-label={`Abrir certificado de ${scopeName()}`}
    >
      <CertificateTemplateStaticView
        template={template()}
        variables={variables()}
      />
    </Link>
  );
}

// front/univents/src/features/certifications/ui/UserCertificationsSection.tsx
import { useQueries, useQuery } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { FileCheck2 } from "lucide-react";
import { allPublicEditionsQueryOptions } from "@/features/editions/api";
import type { EditionI } from "@/features/editions/model";
import { allPublicEventsQueryOptions } from "@/features/events/api";
import { programsQueryOptions } from "@/features/programs/api";
import type { ProgramI } from "@/features/programs/model";
import { Skeleton } from "@/shared/ui/shadcn/skeleton";
import {
  certificationsByUserQueryOptions,
  certificationTemplateQueryOptions,
} from "../api";
import { getCertificationTemplateOrDefault } from "../default-template";
import { DEFAULT_CERTIFICATE_CANVAS } from "../editor/constants";
import type { CertificationI } from "../model";
import { CertificateTemplateStaticView } from "./CertViewer";

export function UserCertificationsSection({
  participantName,
}: {
  participantName: string;
}) {
  const certifications = useQuery(certificationsByUserQueryOptions());
  const { data: events = [] } = useQuery(allPublicEventsQueryOptions());
  const editionQueries = useQueries({
    queries: events.map((event) => allPublicEditionsQueryOptions(event.id)),
  });
  const editions = editionQueries.flatMap((query) => query.data ?? []);
  const programQueries = useQueries({
    queries: editions.map((edition) => programsQueryOptions(edition.id)),
  });
  const programs = programQueries.flatMap((query) => query.data ?? []);

  if (certifications.isLoading) {
    return (
      <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
        {[0, 1, 2].map((item) => (
          <Skeleton key={item} className="aspect-[1.35] rounded-xl" />
        ))}
      </div>
    );
  }

  if (!certifications.data?.length) {
    return (
      <div className="grid min-h-64 place-items-center rounded-xl border border-dashed bg-card/40 p-8 text-center">
        <div>
          <FileCheck2 className="mx-auto size-9 text-muted-foreground" />
          <h2 className="mt-3 font-semibold">Nenhum certificado emitido</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Seus certificados aparecerão aqui quando forem liberados.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-wrap items-start justify-center gap-3 sm:justify-start!">
      {certifications.data.map((certification) => {
        const edition = editions.find(
          (item) => item.id === certification.edition_id,
        );
        return (
          <CertificateProfileCard
            key={certification.id}
            certification={certification}
            participantName={participantName}
            eventName={
              events.find((event) => event.id === edition?.event_id)
                ?.full_name ?? "Evento"
            }
            edition={edition}
            program={programs.find(
              (program) => program.id === certification.program_id,
            )}
          />
        );
      })}
    </div>
  );
}

function CertificateProfileCard({
  certification,
  participantName,
  eventName,
  edition,
  program,
}: {
  certification: CertificationI;
  participantName: string;
  eventName: string;
  edition?: EditionI;
  program?: ProgramI;
}) {
  const { data: linkedTemplate } = useQuery({
    ...certificationTemplateQueryOptions(certification.template_id ?? ""),
    enabled: Boolean(certification.template_id),
  });
  const template = getCertificationTemplateOrDefault(linkedTemplate);
  const scopeName = program?.name ?? edition?.name ?? "Participação";
  const canvas = template.design_data.canvas ?? DEFAULT_CERTIFICATE_CANVAS;
  const width = 320;
  const height = (width * canvas.height) / canvas.width;
  const navigate = useNavigate();

  const openCertificate = () => {
    void navigate({
      to: "/verify/$hash",
      params: { hash: certification.verification_hash },
    });
  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLDivElement>) => {
    if (event.key === "Enter" || event.key === " ") {
      event.preventDefault();
      openCertificate();
    }
  };

  return (
    <div
      role="link"
      tabIndex={0}
      onClick={openCertificate}
      onKeyDown={handleKeyDown}
      className="block max-w-full cursor-pointer transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
      style={{ width, height, maxWidth: "100%" }}
      aria-label={`Abrir certificado de ${scopeName}`}
    >
      <CertificateTemplateStaticView
        template={template}
        variables={{
          participant_name: participantName,
          event_name: eventName,
          edition_name: edition?.name ?? "",
          activity_name: scopeName,
          participation_type: program ? "atividade" : "edição",
          location: edition?.location_name ?? "",
          certified_at: new Date(certification.issued_at).toLocaleDateString(
            "pt-BR",
          ),
          cert_hash: certification.verification_hash,
          verify_url: `${window.location.origin}/verify/${certification.verification_hash}`,
        }}
      />
    </div>
  );
}
