// front/univents-solid/src/shared/ui/loader/WaveText.tsx
import { mergeProps } from "@solidjs/web";
import { For, onSettled, untrack } from "solid-js";

interface WaveTextProps {
  text?: string;
  duration?: number;
  delay?: number;
  lift?: number;
  waveWidth?: number;
}

export default function WaveText(props: WaveTextProps) {
  const merged = mergeProps(
    {
      text: "Processando pagamento...",
      duration: 1400,
      delay: 500,
      lift: 12,
      waveWidth: 20,
    },
    props,
  );

  const spans: (HTMLSpanElement | undefined)[] = [];

  let raf: number | undefined;
  let timeout: ReturnType<typeof setTimeout> | undefined;
  let startTime: number | undefined;

  function frame(ts: number) {
    startTime ??= ts;

    const halfW = Math.max(merged.waveWidth / 100 / 2, 0.0001);

    const t = Math.min(
      (ts - startTime) / merged.duration,
      1,
    );

    const waveCenter =
      -halfW + t * (1 + 2 * halfW);

    const n = Math.max(spans.length - 1, 1);
    const dimBase = 0.18;

    for (let i = 0; i < spans.length; i++) {
      const el = spans[i];

      if (!el) continue;

      const pos = i / n;
      const dist = (pos - waveCenter) / halfW;

      let sineVal = 0;

      if (dist >= -1 && dist <= 1) {
        sineVal = Math.sin(
          dist * Math.PI * 0.5 + Math.PI * 0.5,
        );
      }

      el.style.transform =
        `translateY(${(-merged.lift * sineVal).toFixed(2)}px)`;

      el.style.opacity = (
        dimBase +
        (1 - dimBase) * sineVal
      ).toFixed(3);
    }

    if (t < 1) {
      raf = requestAnimationFrame(frame);
    } else {
      timeout = setTimeout(restart, merged.delay);
    }
  }

  function restart() {
    if (raf !== undefined) {
      cancelAnimationFrame(raf);
    }

    if (timeout !== undefined) {
      clearTimeout(timeout);
    }

    startTime = undefined;
    raf = requestAnimationFrame(frame);
  }

  onSettled(() => {
    raf = requestAnimationFrame(frame);

    return () => {
      if (raf !== undefined) {
        cancelAnimationFrame(raf);
      }

      if (timeout !== undefined) {
        clearTimeout(timeout);
      }
    };
  });

  return (
    <span class="inline-flex font-bold text-lg text-primary">
      <For each={merged.text.split("")}>
        {(char, index) => (
          <span
            ref={(el) => {
              // One-time snapshot on purpose: the rAF loop animates by
              // DOM position, so the index is only meaningful at creation.
              spans[untrack(index)] = el;
            }}
            class="inline-block"
            style="white-space: pre;"
          >
            {char}
          </span>
        )}
      </For>
    </span>
  );
}

// front/univents/src/shared/ui/loader/WaveText.tsx
import { useCallback, useRef } from "react";

interface WaveTextProps {
  text?: string;
  duration?: number;
  delay?: number;
  lift?: number;
  waveWidth?: number;
}

export default function WaveText({
  text = "Processando pagamento...",
  duration = 1400,
  delay = 500,
  lift = 12,
  waveWidth = 20,
}: WaveTextProps) {
  const spans = useRef<(HTMLSpanElement | null)[]>([]);
  const raf = useRef<number | null>(null);
  const timeout = useRef<ReturnType<typeof setTimeout> | null>(null);
  const startTime = useRef<number | null>(null);
  const mounted = useRef(false);

  const props = useRef({ duration, delay, lift, waveWidth });
  props.current = { duration, delay, lift, waveWidth };

  const frame = useCallback((ts: number) => {
    startTime.current ??= ts;

    const p = props.current;

    const halfW = p.waveWidth / 100 / 2;
    const t = Math.min((ts - startTime.current) / p.duration, 1);
    const waveCenter = -halfW + t * (1 + 2 * halfW);
    const els = spans.current;
    const n = els.length - 1;
    const dimBase = 0.18;

    for (let i = 0; i < els.length; i++) {
      const el = els[i];
      if (!el) continue;
      const pos = i / n;
      const dist = (pos - waveCenter) / halfW;
      let sineVal = 0;
      if (dist >= -1 && dist <= 1) {
        sineVal = Math.sin(dist * Math.PI * 0.5 + Math.PI * 0.5);
      }
      el.style.transform = `translateY(${(-lift * sineVal).toFixed(2)}px)`;
      el.style.opacity = (dimBase + (1 - dimBase) * sineVal).toFixed(3);
    }

    if (t < 1) {
      raf.current = requestAnimationFrame(frame);
    } else {
      timeout.current = setTimeout(restart, delay);
    }
  }, []);

  const restart = useCallback(() => {
    if (raf.current) cancelAnimationFrame(raf.current);
    if (timeout.current) clearTimeout(timeout.current);
    startTime.current = null;
    raf.current = requestAnimationFrame(frame);
  }, []);

  const containerRef = useCallback((node: HTMLSpanElement | null) => {
    if (node && !mounted.current) {
      mounted.current = true;
      raf.current = requestAnimationFrame(frame);
    }
    if (!node) {
      if (raf.current) cancelAnimationFrame(raf.current);
      if (timeout.current) clearTimeout(timeout.current);
      mounted.current = false;
    }
  }, []);

  return (
    <span
      ref={containerRef}
      className="inline-flex font-bold text-lg text-primary"
    >
      {text.split("").map((char, i) => (
        <span
          key={`wc-${i}-${char}`}
          ref={(el) => {
            spans.current[i] = el;
          }}
          className="inline-block"
          style={{ whiteSpace: "pre" }}
        >
          {char}
        </span>
      ))}
    </span>
  );
}
