// lib/ts/ui-solid/src/paginated-container.tsx
import type { JSX } from "@solidjs/web";
import { For, Show, createMemo, createSignal, onCleanup } from "solid-js";
import { cn } from "./lib/cn";

export type SortDirection = "asc" | "desc";

export interface SortField<T> {
  key: keyof T;
  label: string;
  comparator?: (a: T, b: T) => number;
}

export interface SortState<T> {
  field: keyof T;
  direction: SortDirection;
}

export type LayoutMode = "grid" | "list" | "custom";
export type GapSize = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "8" | "10";

const GAP_CLASS: Record<GapSize, string> = {
  "0": "gap-0",
  "1": "gap-1",
  "2": "gap-2",
  "3": "gap-3",
  "4": "gap-4",
  "5": "gap-5",
  "6": "gap-6",
  "8": "gap-8",
  "10": "gap-10",
};

export interface PaginatedContainerProps<T> {
  /** Full dataset — filter it yourself; this sorts and paginates. */
  items: T[];
  defaultPage?: number;
  /** Sortable fields. When present this component sorts; callers only filter. */
  sortFields?: Array<SortField<T>>;
  /** Controlled sort, paired with `onSortChange`. */
  sort?: SortState<T>;
  onSortChange?: (sort: SortState<T>) => void;
  filterValue?: string;
  onFilterChange?: (value: string) => void;
  filterPlaceholder?: string;
  /** Noun used in the footer counter, e.g. "eventos". */
  itemLabel?: string;
  /**
   * Renders one page. `animate` is false for the rows that appear because a
   * resize grew the page — the list re-sliced, nothing was navigated to.
   */
  renderItems: (slice: T[], options: { animate: boolean }) => JSX.Element;
  emptyState?: JSX.Element;
  headerActions?: JSX.Element;
  class?: string;
  layout?: LayoutMode;
  gap?: GapSize;
  /** Grid minimum item width, e.g. "16rem". The column count follows the width. */
  minItemWidth?: string;
  /**
   * Rows per page. With the measured column count this decides how many items
   * fit on screen, so callers do not have to guess a page size.
   */
  maxRows?: number;
  /** Hard override for the page size; ignores `maxRows` and the measurement. */
  pageSize?: number;
}

function defaultComparator<T>(a: T, b: T, key: keyof T): number {
  const left = a[key];
  const right = b[key];
  if (typeof left === "number" && typeof right === "number") return left - right;
  return String(left).localeCompare(String(right));
}

/** Same windowing algorithm as the React container, ellipsis included. */
function buildPageNumbers(
  current: number,
  total: number,
  maxVisible: number,
): Array<number | "…"> {
  const visible = Math.max(3, Math.min(maxVisible, total));
  if (total <= visible) return Array.from({ length: total }, (_, index) => index + 1);

  const middleCount = visible - 2;
  let start = current - Math.floor(middleCount / 2);
  let end = start + middleCount - 1;

  if (start < 2) {
    end += 2 - start;
    start = 2;
  }
  if (end > total - 1) {
    start -= end - (total - 1);
    end = total - 1;
  }

  start = Math.max(2, start);
  end = Math.min(total - 1, end);

  const pages: Array<number | "…"> = [1];
  if (start > 2) pages.push("…");
  for (let page = start; page <= end; page += 1) pages.push(page);
  if (end < total - 1) pages.push("…");
  pages.push(total);
  return pages;
}

/**
 * Toolbar + page + footer around a list, mirroring `@trieoh/ui-react`'s
 * PaginatedContainer: same sorting rules, same pagination windowing, same
 * footer wording, same pill/active colours. Icons are inline SVG — this package
 * carries no icon dependency on purpose.
 *
 * The page size is measured, not configured: it observes how many columns the
 * grid actually renders at the current width and multiplies that by `maxRows`.
 * Cells are equal because the tracks are equal, and a narrow viewport simply gets
 * fewer columns instead of a page that overflows the screen.
 */
export function PaginatedContainer<T>(props: PaginatedContainerProps<T>) {
  const [page, setPage] = createSignal(props.defaultPage ?? 1);
  const [internalSort, setInternalSort] = createSignal<SortState<T> | undefined>(
    props.sortFields?.length
      ? { field: props.sortFields[0]!.key, direction: "asc" }
      : undefined,
  );
  const [sortOpen, setSortOpen] = createSignal(false);
  const [columns, setColumns] = createSignal(1);
  const [resized, setResized] = createSignal(false);
  const [measured, setMeasured] = createSignal(false);

  let grid: HTMLDivElement | undefined;
  let resizeObserver: ResizeObserver | undefined;
  let settleTimer: ReturnType<typeof setTimeout> | undefined;
  let measuredOnce = false;

  const activeSort = () => props.sort ?? internalSort();

  /** Reads the resolved tracks off the grid itself: unit-agnostic, no parsing. */
  const measureColumns = () => {
    if (!grid) return;
    const tracks = getComputedStyle(grid)
      .gridTemplateColumns.split(" ")
      .filter((track) => track !== "" && track !== "none");

    // Only trust a resolved list: without layout (jsdom, an unsupported value)
    // this returns the specified `repeat(...)`, which is not a column count.
    const usable = tracks.length > 0 && tracks.every((track) => /^[\d.]+px$/.test(track));

    // Same count: leave the signal alone, so the page is not re-sliced.
    if (tracks.length !== columns() && usable) {
      setColumns(tracks.length);
      // A later change is the viewport moving, not the user navigating: the
      // rows it adds are not a page entrance.
      if (measuredOnce) setResized(true);
    }

    measuredOnce = true;
    setMeasured(true);
  };

  /**
   * Resizes here are usually an animation — the admin rail takes 300ms to
   * collapse — and every frame that changes the column count re-slices the page,
   * which reads as the items flickering. Wait for the width to settle instead.
   */
  const scheduleMeasure = () => {
    clearTimeout(settleTimer);
    settleTimer = setTimeout(measureColumns, 150);
  };

  /** Called by Solid with the element on mount, and with `undefined` on removal. */
  const observeGrid = (element: HTMLDivElement | undefined) => {
    grid = element;
    resizeObserver?.disconnect();
    resizeObserver = undefined;
    if (!element) return;

    // The first measurement is immediate: waiting would show the wrong page size.
    measureColumns();
    if (typeof ResizeObserver === "undefined") return;

    resizeObserver = new ResizeObserver(scheduleMeasure);
    resizeObserver.observe(element);
  };

  onCleanup(() => {
    resizeObserver?.disconnect();
    clearTimeout(settleTimer);
  });

  const pageSize = () =>
    props.pageSize ?? Math.max(1, columns() * (props.maxRows ?? 2));

  const sorted = createMemo(() => {
    const sort = activeSort();
    const fields = props.sortFields;
    if (!sort || !fields?.length) return props.items;

    const field = fields.find((candidate) => candidate.key === sort.field);
    const direction = sort.direction === "desc" ? -1 : 1;

    return [...props.items].sort((a, b) => {
      const result = field?.comparator
        ? field.comparator(a, b)
        : defaultComparator(a, b, sort.field);
      return result * direction;
    });
  });

  const totalPages = createMemo(() => Math.max(1, Math.ceil(sorted().length / pageSize())));
  const currentPage = createMemo(() => Math.min(Math.max(page(), 1), totalPages()));
  const slice = createMemo(() => {
    const size = pageSize();
    const start = (currentPage() - 1) * size;
    return sorted().slice(start, start + size);
  });
  const range = createMemo(() => {
    const count = sorted().length;
    if (count === 0) return { start: 0, end: 0 };
    return {
      start: (currentPage() - 1) * pageSize() + 1,
      end: Math.min(currentPage() * pageSize(), count),
    };
  });

  const goTo = (next: number) => setPage(Math.min(Math.max(next, 1), totalPages()));
  const changeSort = (next: SortState<T>) => {
    if (!props.sort) setInternalSort(next);
    props.onSortChange?.(next);
  };
  const activeSortLabel = () => {
    const sort = activeSort();
    if (!sort) return null;
    return props.sortFields?.find((field) => field.key === sort.field)?.label ?? null;
  };

  return (
    <div class={cn("flex w-full flex-col gap-4", props.class)}>
      <header class="flex flex-wrap items-center gap-2">
        <Show when={props.onFilterChange}>
          <div class="relative min-w-56 flex-1 sm:max-w-xs">
            <svg
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              aria-hidden="true"
              class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"
            >
              <circle cx="11" cy="11" r="8" />
              <path d="m21 21-4.3-4.3" stroke-linecap="round" />
            </svg>
            <input
              type="search"
              value={props.filterValue ?? ""}
              placeholder={props.filterPlaceholder ?? "Filtrar…"}
              aria-label={props.filterPlaceholder ?? "Filtrar"}
              onInput={(event) => props.onFilterChange?.(event.currentTarget.value)}
              class="h-9 w-full rounded-md border border-border bg-background py-1 pl-9 pr-3 text-sm placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            />
          </div>
        </Show>

        <Show when={props.sortFields?.length}>
          <div class="relative">
            <button
              type="button"
              aria-expanded={sortOpen() ? "true" : "false"}
              aria-haspopup="dialog"
              onClick={() => setSortOpen((open) => !open)}
              class={cn(
                "inline-flex h-9 items-center gap-1.5 rounded-md border border-border px-3 text-sm transition-colors hover:bg-muted hover:text-foreground",
                activeSortLabel() ? "text-foreground" : "text-muted-foreground",
              )}
            >
              <svg
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                aria-hidden="true"
                class="size-4"
              >
                <path
                  d="m3 16 4 4 4-4M7 20V4M21 8l-4-4-4 4M17 4v16"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <Show when={activeSortLabel()} fallback={<>Ordenar</>}>
                {(label) => (
                  <>
                    {label()}
                    <span aria-hidden="true">
                      {activeSort()?.direction === "desc" ? "↓" : "↑"}
                    </span>
                  </>
                )}
              </Show>
            </button>

            <Show when={sortOpen()}>
              <div
                role="dialog"
                aria-label="Opções de ordenação"
                class="absolute right-0 top-[calc(100%+6px)] z-50 w-52 rounded-md border border-border bg-card p-2 shadow-lg shadow-black/5"
              >
                <div class="mb-1 flex flex-col gap-0.5">
                  <For each={props.sortFields}>
                    {(field) => {
                      const isActive = () => activeSort()?.field === field.key;
                      return (
                        <button
                          type="button"
                          onClick={() =>
                            changeSort({
                              field: field.key,
                              direction:
                                isActive() && activeSort()?.direction === "asc" ? "desc" : "asc",
                            })}
                          class={cn(
                            "flex w-full cursor-pointer items-center justify-between rounded-md border px-2.5 py-2 text-left text-sm transition-colors select-none",
                            isActive()
                              ? "border-primary/20 bg-primary/10 font-medium text-primary"
                              : "border-transparent text-foreground hover:bg-muted",
                          )}
                        >
                          <span>{field.label}</span>
                          <span class={isActive() ? "text-primary" : "text-muted-foreground/40"}>
                            {isActive() ? (activeSort()?.direction === "asc" ? "↑" : "↓") : "—"}
                          </span>
                        </button>
                      );
                    }}
                  </For>
                </div>

                <div class="grid grid-cols-2 gap-1.5 border-t border-border pt-2">
                  <For each={["asc", "desc"] as const}>
                    {(direction) => (
                      <button
                        type="button"
                        onClick={() => {
                          const sort = activeSort();
                          if (sort) changeSort({ ...sort, direction });
                        }}
                        class={cn(
                          "flex items-center justify-center gap-1.5 rounded-md border py-1.5 text-xs font-medium transition-colors",
                          activeSort()?.direction === direction
                            ? "border-primary/30 bg-primary/10 text-primary"
                            : "border-border text-muted-foreground hover:bg-muted hover:text-foreground",
                        )}
                      >
                        {direction === "asc" ? "Asc" : "Desc"}
                      </button>
                    )}
                  </For>
                </div>
              </div>
            </Show>
          </div>
        </Show>

        <div class="ml-auto flex items-center gap-2">{props.headerActions}</div>
      </header>

      <Show when={sorted().length > 0} fallback={props.emptyState}>
        <Show when={props.layout !== "custom"}>
          <div
            ref={observeGrid}
            class={cn(
              props.layout === "list"
                ? "flex w-full flex-col"
                : "grid w-full",
              GAP_CLASS[props.gap ?? "3"],
            )}
            style={
              props.layout === "grid"
                ? {
                  "grid-template-columns": `repeat(auto-fill, minmax(${props.minItemWidth ?? "200px"}, 1fr))`,
                }
                : undefined
            }
          >
            {/*
              Items wait for the first measurement: rendering them at the
              default page size and correcting one frame later makes every card
              mount twice, and an entrance animation plays for nothing.
            */}
            <Show when={measured()}>
              {props.renderItems(slice(), { animate: !resized() })}
            </Show>
          </div>
        </Show>

        <Show when={props.layout === "custom"}>
          {props.renderItems(slice(), { animate: !resized() })}
        </Show>

        <footer class="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-3">
          <p class="text-xs text-muted-foreground">
            Mostrando {range().start}–{range().end} de {sorted().length}{" "}
            {props.itemLabel ?? "itens"}
          </p>

          <div class="flex flex-wrap items-center gap-1">
            <PageButton label="Primeira página" disabled={currentPage() === 1} onClick={() => goTo(1)}>
              <path d="m11 17-5-5 5-5M18 17l-5-5 5-5" stroke-linecap="round" stroke-linejoin="round" />
            </PageButton>
            <PageButton
              label="Página anterior"
              disabled={currentPage() === 1}
              onClick={() => goTo(currentPage() - 1)}
            >
              <path d="m15 18-6-6 6-6" stroke-linecap="round" stroke-linejoin="round" />
            </PageButton>

            <div class="hidden items-center gap-1 sm:flex">
              <For each={buildPageNumbers(currentPage(), totalPages(), 7)}>
                {(entry) => (
                  <Show
                    when={typeof entry === "number"}
                    fallback={<span class="px-1 text-xs text-muted-foreground">…</span>}
                  >
                    <button
                      type="button"
                      aria-current={entry === currentPage() ? "page" : undefined}
                      aria-label={`Página ${entry}`}
                      onClick={() => goTo(Number(entry))}
                      class={cn(
                        "flex h-7 min-w-7 items-center justify-center rounded-sm border px-1.5 text-xs font-medium transition-colors select-none",
                        entry === currentPage()
                          ? "border-primary/30 bg-primary/10 text-primary"
                          : "border-border text-muted-foreground hover:bg-muted hover:text-foreground",
                      )}
                    >
                      {entry}
                    </button>
                  </Show>
                )}
              </For>
            </div>

            <PageButton
              label="Próxima página"
              disabled={currentPage() === totalPages()}
              onClick={() => goTo(currentPage() + 1)}
            >
              <path d="m9 18 6-6-6-6" stroke-linecap="round" stroke-linejoin="round" />
            </PageButton>
            <PageButton
              label="Última página"
              disabled={currentPage() === totalPages()}
              onClick={() => goTo(totalPages())}
            >
              <path d="m13 17 5-5-5-5M6 17l5-5-5-5" stroke-linecap="round" stroke-linejoin="round" />
            </PageButton>
          </div>
        </footer>
      </Show>
    </div>
  );
}

function PageButton(props: {
  label: string;
  disabled: boolean;
  onClick: () => void;
  children: JSX.Element;
}) {
  return (
    <button
      type="button"
      aria-label={props.label}
      disabled={props.disabled}
      onClick={() => props.onClick()}
      class="flex size-7 items-center justify-center rounded-sm border border-border text-muted-foreground transition-colors hover:bg-muted hover:text-foreground disabled:cursor-not-allowed disabled:opacity-35"
    >
      <svg
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        aria-hidden="true"
        class="size-3.5"
      >
        {props.children}
      </svg>
    </button>
  );
}

// lib/ts/ui-base/src/paginated-container.tsx
import { useState, useRef, useEffect, useMemo } from "react";
import type { ReactNode, KeyboardEvent } from "react";
import {
  Search,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  Minus,
  X,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";

export type SortDirection = "asc" | "desc";

export interface SortField<T> {
  key: keyof T;
  label: string;
  comparator?: (a: T, b: T) => number;
}

export interface SortState<T> {
  field: keyof T;
  direction: SortDirection;
}

export interface PaginationInfo {
  page: number;
  totalPages: number;
  pageSize: number;
  start: number;
  end: number;
  count: number;
}

/**
 * Layout modes for the items wrapper.
 *
 * "grid"   - CSS grid with auto-fill columns. Control minimum item width via
 *            `minItemWidth` prop (default: "200px"). Items stretch to fill
 *            the row evenly - no gap on the right side.
 *
 * "list"   - `flex flex-col`, one item per row, full width.
 *
 * "custom" - No wrapper is rendered at all. Your `renderItems` receives the
 *            slice and you mount whatever container you want:
 *
 *            renderItems={(slice) => (
 *              <div className="grid grid-cols-4 gap-3">
 *                {slice.map(item => <MyCard key={item.id} item={item} />)}
 *              </div>
 *            )}
 */
export type LayoutMode = "grid" | "list" | "custom";

/**
 * Tailwind gap size applied to the items wrapper.
 * Maps to `gap-{n}` utility classes.
 */
export type GapSize = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "8" | "10";

export interface PaginatedContainerProps<T> {
  /** Full dataset - filter externally before passing. */
  items: T[];
  /** Items per page (default: 8). */
  pageSize?: number;
  /** Starting page (default: 1). */
  defaultPage?: number;

  /**
   * Sortable field definitions. When provided a Sort button appears in the
   * header that opens a dropdown panel (field picker + direction toggle).
   */
  sortFields?: SortField<T>[];
  /**
   * Controlled sort state. Pair with `onSortChange` for external control.
   * Leave unset to let the component manage sort internally.
   */
  sort?: SortState<T>;
  onSortChange?: (sort: SortState<T>) => void;

  /**
   * Controlled filter value. The component renders the search input and
   * calls `onFilterChange` on every keystroke - the actual filtering is
   * done by you so you can match any fields you want.
   */
  filterValue?: string;
  onFilterChange?: (value: string) => void;
  /** Placeholder for the filter input (default: "Filter…"). */
  filterPlaceholder?: string;

  /**
   * Item noun used in the footer counter.
   * E.g. "namespaces" → "Showing 1–4 of 24 namespaces"
   */
  itemLabel?: string;
  /** Render the current page slice. */
  renderItems: (slice: T[]) => ReactNode;
  /** Shown when the item list is empty after filtering. */
  emptyState?: ReactNode;
  /** Extra content placed in the header to the right of the Sort button. */
  headerActions?: ReactNode;
  className?: string;

  /**
   * Layout mode for the items wrapper (default: "grid").
   *
   * "grid"   - CSS grid auto-fill; items stretch to fill available width.
   * "list"   - flex-col; one item per row.
   * "custom" - no wrapper; you own the container inside `renderItems`.
   */
  layout?: LayoutMode;
  /**
   * Gap between items (default: "3").
   * Maps to Tailwind's `gap-{n}` utility.
   */
  gap?: GapSize;
  /**
   * Minimum width for each item in grid layout (default: "200px").
   * The grid will fit as many columns as possible at this minimum width,
   * then stretch items to fill the row - no empty space on the right.
   *
   * Examples: "160px", "12rem", "240px"
   */
  minItemWidth?: string;
}

const GAP_CLASS: Record<GapSize, string> = {
  "0": "gap-0",
  "1": "gap-1",
  "2": "gap-2",
  "3": "gap-3",
  "4": "gap-4",
  "5": "gap-5",
  "6": "gap-6",
  "8": "gap-8",
  "10": "gap-10",
};

interface ItemsWrapperProps {
  layout: LayoutMode;
  gap: GapSize;
  minItemWidth: string;
  children: ReactNode;
}

function ItemsWrapper({
  layout,
  gap,
  minItemWidth,
  children,
}: ItemsWrapperProps) {
  const gapClass = GAP_CLASS[gap];

  if (layout === "custom") return <>{children}</>;

  if (layout === "list") {
    return <div className={`flex flex-col w-full ${gapClass}`}>{children}</div>;
  }

  // "grid" - auto-fill columns that stretch to fill the row.
  return (
    <div
      className={`w-full grid justify-center justify-items-center ${gapClass}`}
      style={{
        gridTemplateColumns: `repeat(auto-fill, minmax(${minItemWidth}, 1fr))`,
      }}
    >
      {children}
    </div>
  );
}

function buildPageNumbers(
  current: number,
  total: number,
  maxVisible: number,
): (number | "…")[] {
  const visible = Math.max(3, Math.min(maxVisible, total));
  if (total <= visible) return Array.from({ length: total }, (_, i) => i + 1);

  const middleCount = visible - 2;
  let start = current - Math.floor(middleCount / 2);
  let end = start + middleCount - 1;

  if (start < 2) {
    end += 2 - start;
    start = 2;
  }

  if (end > total - 1) {
    start -= end - (total - 1);
    end = total - 1;
  }

  start = Math.max(2, start);
  end = Math.min(total - 1, end);

  const pages: (number | "…")[] = [1];

  if (start > 2) pages.push("…");
  for (let page = start; page <= end; page += 1) pages.push(page);
  if (end < total - 1) pages.push("…");

  pages.push(total);
  return pages;
}

function defaultComparator<T>(a: T, b: T, key: keyof T): number {
  const av = a[key];
  const bv = b[key];
  if (typeof av === "number" && typeof bv === "number") return av - bv;
  return String(av).localeCompare(String(bv));
}

function applySorting<T>(
  items: T[],
  sort: SortState<T>,
  fields: SortField<T>[],
): T[] {
  const field = fields.find((f) => f.key === sort.field);
  const dir = sort.direction === "desc" ? -1 : 1;
  return [...items].sort((a, b) => {
    const result = field?.comparator
      ? field.comparator(a, b)
      : defaultComparator(a, b, sort.field);
    return result * dir;
  });
}

interface SortPanelProps<T> {
  fields: SortField<T>[];
  sort: SortState<T>;
  onChange: (sort: SortState<T>) => void;
  onClose: () => void;
}

function SortPanel<T>({ fields, sort, onChange, onClose }: SortPanelProps<T>) {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) onClose();
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, [onClose]);

  const handleFieldClick = (key: keyof T) => {
    onChange({
      field: key,
      direction:
        sort.field === key && sort.direction === "asc" ? "desc" : "asc",
    });
  };

  const handleFieldKeyDown = (
    e: KeyboardEvent<HTMLDivElement>,
    key: keyof T,
  ) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      handleFieldClick(key);
    }
  };

  return (
    <div
      ref={ref}
      role="dialog"
      aria-label="Sort options"
      className="absolute right-0 top-[calc(100%+6px)] z-50 w-52 rounded-md border border-border bg-card shadow-lg shadow-black/5 p-2"
    >
      {/* Header */}
      <div className="flex items-center justify-between px-2 pb-2 mb-1">
        <span className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground">
          Sort by
        </span>
        <button
          onClick={onClose}
          aria-label="Close sort panel"
          className="flex h-5 w-5 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
        >
          <X size={12} />
        </button>
      </div>

      {/* Field list */}
      <div className="flex flex-col gap-0.5 mb-2">
        {fields.map((f) => {
          const isActive = sort.field === f.key;
          return (
            <div
              key={String(f.key)}
              role="button"
              tabIndex={0}
              onClick={() => handleFieldClick(f.key)}
              onKeyDown={(e) => handleFieldKeyDown(e, f.key)}
              className={[
                "flex cursor-pointer items-center justify-between rounded-md px-2.5 py-2 text-sm transition-colors select-none border",
                isActive
                  ? "bg-primary/10 text-primary border-primary/20 font-medium"
                  : "text-foreground hover:bg-muted border-transparent",
              ].join(" ")}
            >
              <span>{f.label}</span>
              <span
                className={
                  isActive ? "text-primary" : "text-muted-foreground/40"
                }
              >
                {isActive ? (
                  sort.direction === "asc" ? (
                    <ArrowUp size={13} />
                  ) : (
                    <ArrowDown size={13} />
                  )
                ) : (
                  <Minus size={13} />
                )}
              </span>
            </div>
          );
        })}
      </div>

      {/* Direction toggle */}
      <div className="grid grid-cols-2 gap-1.5 border-t border-border pt-2">
        {(["asc", "desc"] as const).map((dir) => (
          <button
            key={dir}
            onClick={() => onChange({ ...sort, direction: dir })}
            className={[
              "flex items-center justify-center gap-1.5 rounded-md border py-1.5 text-xs font-medium transition-colors",
              sort.direction === dir
                ? "border-primary/30 bg-primary/10 text-primary"
                : "border-border text-muted-foreground hover:bg-muted hover:text-foreground",
            ].join(" ")}
          >
            {dir === "asc" ? <ArrowUp size={11} /> : <ArrowDown size={11} />}
            {dir === "asc" ? "Asc" : "Desc"}
          </button>
        ))}
      </div>
    </div>
  );
}

interface PaginationButtonProps {
  onClick: () => void;
  disabled?: boolean;
  active?: boolean;
  title?: string;
  "aria-current"?: "page" | undefined;
  children: ReactNode;
}

function PaginationButton({
  onClick,
  disabled = false,
  active = false,
  children,
  ...rest
}: PaginationButtonProps) {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={[
        "flex h-7 min-w-7 items-center justify-center rounded-sm border px-1.5 text-xs font-medium transition-colors select-none",
        "disabled:cursor-not-allowed disabled:opacity-35",
        active
          ? "border-primary/30 bg-primary/10 text-primary"
          : "border-border bg-transparent text-muted-foreground hover:bg-muted hover:text-foreground",
      ].join(" ")}
      {...rest}
    >
      {children}
    </button>
  );
}

function useElementWidth<T extends HTMLElement>() {
  const ref = useRef<T | null>(null);
  const [width, setWidth] = useState(0);

  useEffect(() => {
    const element = ref.current;
    if (!element) return;

    const update = () => {
      setWidth(element.getBoundingClientRect().width);
    };

    update();

    const observer = new ResizeObserver(() => update());
    observer.observe(element);

    return () => observer.disconnect();
  }, []);

  return [ref, width] as const;
}

export function PaginatedContainer<T>({
  items,
  pageSize = 8,
  defaultPage = 1,
  sortFields,
  sort: controlledSort,
  onSortChange,
  filterValue,
  onFilterChange,
  filterPlaceholder = "Filter…",
  itemLabel = "items",
  renderItems,
  emptyState,
  headerActions,
  className,
  layout = "grid",
  gap = "3",
  minItemWidth = "200px",
}: PaginatedContainerProps<T>) {
  const [page, setPage] = useState(defaultPage);
  const [internalSort, setInternalSort] = useState<SortState<T> | null>(
    sortFields ? { field: sortFields[0].key, direction: "asc" } : null,
  );
  const [sortOpen, setSortOpen] = useState(false);
  const [paginationRef, paginationWidth] = useElementWidth<HTMLDivElement>();

  const activeSort = controlledSort ?? internalSort;

  const handleSortChange = (next: SortState<T>) => {
    onSortChange?.(next);
    if (!controlledSort) setInternalSort(next);
  };

  const processedItems =
    activeSort && sortFields
      ? applySorting(items, activeSort, sortFields)
      : items;

  const totalPages = Math.max(1, Math.ceil(processedItems.length / pageSize));
  const safePage = Math.min(page, totalPages);
  const start = (safePage - 1) * pageSize;
  const slice = processedItems.slice(start, start + pageSize);
  const responsivePageCount = useMemo(() => {
    if (paginationWidth < 300) return 3;
    if (paginationWidth < 360) return 5;
    if (paginationWidth < 520) return 5;
    if (paginationWidth < 720) return 7;
    return 9;
  }, [paginationWidth]);
  const responsivePageNums = buildPageNumbers(
    safePage,
    totalPages,
    responsivePageCount,
  );
  const showBoundaryButtons = paginationWidth >= 320;
  const compactPagination = paginationWidth < 320;

  const go = (p: number) => setPage(Math.max(1, Math.min(totalPages, p)));

  const activeSortLabel =
    activeSort && sortFields
      ? sortFields.find((f) => f.key === activeSort.field)?.label
      : null;

  const hasHeader = onFilterChange !== undefined || sortFields || headerActions;

  return (
    <div
      className={[
        "w-full overflow-visible rounded-md border border-border bg-card",
        className ?? "",
      ].join(" ")}
    >
      {/* Header */}
      {hasHeader && (
        <div className="flex flex-wrap items-center justify-between gap-2.5 border-b border-border px-4 py-3">
          {onFilterChange !== undefined && (
            <div className="relative min-w-[220px] w-full sm:flex-1 sm:max-w-sm">
              <span className="pointer-events-none absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground flex items-center">
                <Search size={13} />
              </span>
              <input
                type="text"
                name="table-filter"
                value={filterValue ?? ""}
                onChange={(e) => {
                  onFilterChange(e.target.value);
                  setPage(1);
                }}
                placeholder={filterPlaceholder}
                aria-label={filterPlaceholder}
                className="h-9 min-w-[220px] w-full rounded-md border border-border bg-muted/50 pl-8 pr-3 text-sm text-foreground placeholder:text-muted-foreground outline-none transition-colors focus:border-ring focus:bg-background"
              />
            </div>
          )}

          <div className="flex flex-wrap items-center gap-2 sm:ml-auto">
            {headerActions}

            {sortFields && activeSort && (
              <div className="relative">
                <button
                  onClick={() => setSortOpen((v) => !v)}
                  aria-expanded={sortOpen}
                  aria-haspopup="dialog"
                  className={[
                    "flex h-9 items-center gap-1.5 rounded-md border px-3 text-sm transition-colors",
                    sortOpen
                      ? "border-ring/50 bg-muted text-foreground"
                      : "border-border text-muted-foreground hover:border-border/80 hover:bg-muted hover:text-foreground",
                  ].join(" ")}
                >
                  <ArrowUpDown size={13} />
                  <span>Sort</span>
                  {activeSortLabel && (
                    <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-medium text-primary">
                      {activeSortLabel}
                      {" · "}
                      {activeSort.direction === "asc" ? "↑" : "↓"}
                    </span>
                  )}
                </button>

                {sortOpen && (
                  <SortPanel
                    fields={sortFields}
                    sort={activeSort}
                    onChange={(s) => {
                      handleSortChange(s);
                      setPage(1);
                    }}
                    onClose={() => setSortOpen(false)}
                  />
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {/* Content */}
      <div className="p-4">
        {slice.length === 0 ? (
          (emptyState ?? (
            <p className="py-10 text-center text-sm text-muted-foreground">
              No {itemLabel} found.
            </p>
          ))
        ) : (
          <ItemsWrapper layout={layout} gap={gap} minItemWidth={minItemWidth}>
            {renderItems(slice)}
          </ItemsWrapper>
        )}
      </div>

      {/* Footer */}
      <div
        ref={paginationRef}
        className="flex flex-col gap-2.5 border-t border-border px-4 py-2.5 sm:flex-row sm:items-center sm:justify-between"
      >
        <span className="min-w-0 text-xs text-muted-foreground">
          {processedItems.length === 0 ? (
            `0 ${itemLabel}`
          ) : (
            <>
              Showing{" "}
              <span className="font-medium text-foreground">
                {start + 1}–{Math.min(start + pageSize, processedItems.length)}
              </span>{" "}
              of{" "}
              <span className="font-medium text-foreground">
                {processedItems.length}
              </span>{" "}
              {itemLabel}
            </>
          )}
        </span>

        <nav
          aria-label="Pagination"
          className="flex max-w-full flex-nowrap items-center gap-0.5 overflow-hidden sm:justify-end"
        >
          {showBoundaryButtons && (
            <PaginationButton
              onClick={() => go(1)}
              disabled={safePage === 1}
              title="First page"
            >
              <ChevronFirst size={14} />
            </PaginationButton>
          )}
          <PaginationButton
            onClick={() => go(safePage - 1)}
            disabled={safePage === 1}
            title="Previous page"
          >
            <ChevronLeft size={14} />
          </PaginationButton>

          {responsivePageNums.map((p, i) =>
            p === "…" ? (
              <span
                key={`ellipsis-${i}`}
                className={
                  compactPagination
                    ? "flex h-7 w-4 items-center justify-center text-xs text-muted-foreground"
                    : "flex h-7 w-6 items-center justify-center text-xs text-muted-foreground"
                }
              >
                …
              </span>
            ) : (
              <PaginationButton
                key={p}
                onClick={() => go(p)}
                active={p === safePage}
                aria-current={p === safePage ? "page" : undefined}
                title={`Page ${p}`}
              >
                {p}
              </PaginationButton>
            ),
          )}

          <PaginationButton
            onClick={() => go(safePage + 1)}
            disabled={safePage === totalPages}
            title="Next page"
          >
            <ChevronRight size={14} />
          </PaginationButton>
          {showBoundaryButtons && (
            <PaginationButton
              onClick={() => go(totalPages)}
              disabled={safePage === totalPages}
              title="Last page"
            >
              <ChevronLast size={14} />
            </PaginationButton>
          )}
        </nav>
      </div>
    </div>
  );
}
