// lib/ts/ui-solid/src/multi-step/fields/money-field.tsx
import type { JSX } from "@solidjs/web";
import { createMemo, Show } from "solid-js";
import { Input, Label } from "../../input";
import type { MoneyMultiStepField } from "../types";

export interface MultiStepMoneyFieldProps<T = Record<string, unknown>> {
  field: MoneyMultiStepField<T>;
  value?: unknown;
  error?: string;
  onChange?: (value: number) => void;
}

function toCents(val: unknown): number {
  if (typeof val === "number" && Number.isFinite(val)) return Math.round(val);
  if (typeof val === "string") {
    const digits = val.replace(/\D/g, "");
    return digits ? parseInt(digits, 10) : 0;
  }
  return 0;
}

export function MultiStepMoneyField<T = Record<string, unknown>>(
  props: MultiStepMoneyFieldProps<T>,
): JSX.Element {
  let inputRef: HTMLInputElement | undefined;

  const id = `field-${props.field.name}`;
  const errorId = `${id}-error`;
  const hintId = `${id}-hint`;

  const describedBy = () => {
    if (props.error) return errorId;
    if (props.field.hint) return hintId;
    return undefined;
  };

  const currency = () => props.field.currency ?? "BRL";
  const locale = () => props.field.locale ?? "pt-BR";

  const cents = () => toCents(props.value);

  const formatter = createMemo(() => {
    return new Intl.NumberFormat(locale(), {
      style: "currency",
      currency: currency(),
    });
  });

  const display = () => formatter().format(cents() / 100);

  const commit = (nextCents: number) => {
    let result = nextCents;
    if (typeof props.field.minCents === "number") {
      result = Math.max(result, props.field.minCents);
    }
    if (typeof props.field.maxCents === "number") {
      result = Math.min(result, props.field.maxCents);
    }
    props.onChange?.(result);
  };

  const handleInput = (
    event: InputEvent & { currentTarget: HTMLInputElement },
  ) => {
    const target =
      (event.target as HTMLInputElement) ??
      (event.currentTarget as HTMLInputElement);
    const raw = (target?.value ?? "").replace(/\D/g, "");
    const parsed = raw ? parseInt(raw, 10) : 0;
    commit(parsed);
  };

  const handleKeyDown = (
    event: KeyboardEvent & { currentTarget: HTMLInputElement },
  ) => {
    if (event.key === "Backspace") {
      event.preventDefault();
      const current = cents();
      const nextCents = Math.trunc(current / 10);
      commit(nextCents);
    }
  };

  const handleFocus = () => {
    requestAnimationFrame(() => {
      const len = inputRef?.value.length ?? 0;
      inputRef?.setSelectionRange(len, len);
    });
  };

  return (
    <div class="flex flex-col gap-1.5">
      <Label for={id}>
        {props.field.label}
        <Show when={props.field.required}>
          <span aria-hidden="true" class="ml-0.5 text-destructive">
            *
          </span>
        </Show>
      </Label>

      <Input
        ref={(el) => (inputRef = el)}
        id={id}
        name={props.field.name}
        type="text"
        inputmode="numeric"
        aria-describedby={describedBy()}
        aria-invalid={props.error ? "true" : undefined}
        value={display()}
        disabled={props.field.disabled}
        autocomplete="off"
        onInput={handleInput}
        onKeyDown={handleKeyDown}
        onFocus={handleFocus}
      />

      <Show
        when={props.error}
        fallback={
          <Show when={props.field.hint}>
            <p id={hintId} class="text-xs text-muted-foreground">
              {props.field.hint}
            </p>
          </Show>
        }
      >
        <p id={errorId} role="alert" class="text-xs font-medium text-destructive">
          {props.error}
        </p>
      </Show>
    </div>
  );
}

// front/univents/src/widgets/multi-step-form/ui/fields/money-field.tsx
import { useMemo, useRef, useState } from "react";
import type { FieldValues } from "react-hook-form";
import type { FieldConfig, FieldFormApi } from "../../model/types";
import { getFieldError } from "../../utils/get-field-error";

export interface MoneyFieldRendererProps<TFieldValues extends FieldValues> {
  field: FieldConfig<TFieldValues>;
  form: FieldFormApi<TFieldValues>;
}

function toCentsNumber(value: unknown): number {
  if (typeof value === "bigint") return Number(value);
  if (typeof value === "number" && Number.isFinite(value)) return value;
  return 0;
}

function clamp(cents: number, min?: number, max?: number): number {
  let result = cents;
  if (typeof min === "number") result = Math.max(result, min);
  if (typeof max === "number") result = Math.min(result, max);
  return result;
}

/** Keeps only the digits typed so far — this is what makes new digits
 * "shift in from the right" instead of being parsed positionally. */
function digitsToCents(raw: string): number {
  const digitsOnly = raw.replace(/\D/g, "");
  if (digitsOnly.length === 0) return 0;
  return parseInt(digitsOnly, 10);
}

export function MoneyFieldRenderer<TFieldValues extends FieldValues>({
  field,
  form,
}: MoneyFieldRendererProps<TFieldValues>) {
  if (field.kind !== "money") return null;

  const inputRef = useRef<HTMLInputElement>(null);
  const error = getFieldError(form.formState.errors, field.name);
  const currency = field.currency ?? "BRL";
  const locale = field.locale ?? "pt-BR";
  const valueType = field.valueType ?? "number";

  const [cents, setCents] = useState<number>(() =>
    toCentsNumber(form.getValues(field.name)),
  );

  const formatter = useMemo(
    () => new Intl.NumberFormat(locale, { style: "currency", currency }),
    [locale, currency],
  );

  const display = formatter.format(cents / 100);

  const commit = (nextCents: number) => {
    const clamped = clamp(nextCents, field.minCents, field.maxCents);
    setCents(clamped);
    const nextValue = valueType === "bigint" ? BigInt(clamped) : clamped;
    form.setValue(field.name, nextValue as never, {
      shouldDirty: true,
      shouldValidate: true,
    });
  };

  return (
    <div className="space-y-1.5">
      <label
        htmlFor={field.name}
        className="text-xs font-semibold uppercase tracking-wide text-muted-foreground"
      >
        {field.label}
        {field.optional ? (
          <span className="ml-1 font-normal normal-case text-muted-foreground/70">
            (opcional)
          </span>
        ) : null}
      </label>

      <input
        ref={inputRef}
        id={field.name}
        type="text"
        inputMode="numeric"
        disabled={field.disabled}
        aria-invalid={Boolean(error)}
        value={display}
        onChange={(event) => commit(digitsToCents(event.target.value))}
        onKeyDown={(event) => {
          // Backspace should drop the last digit even though the field
          // is fully controlled/re-formatted on every keystroke.
          if (event.key === "Backspace") {
            event.preventDefault();
            commit(Math.trunc(cents / 10));
          }
        }}
        onFocus={() => {
          requestAnimationFrame(() => {
            const length = inputRef.current?.value.length ?? 0;
            inputRef.current?.setSelectionRange(length, length);
          });
        }}
        className={
          "flex h-10 w-full rounded-md border bg-transparent px-3 py-2 text-left text-sm outline-none " +
          "tabular-nums focus-visible:ring-2 focus-visible:ring-ring " +
          (error
            ? "border-destructive focus-visible:ring-destructive"
            : "border-input")
        }
      />

      {field.description ? (
        <p className="text-xs text-muted-foreground">{field.description}</p>
      ) : null}
      {error ? <p className="text-xs text-destructive">{error}</p> : null}
    </div>
  );
}
