// front/univents/src/features/products/ui/AdminVariantCard.tsx
import { MoreVertical, Pencil, Trash2 } from "lucide-react";
import { motion } from "motion/react";
import { Button } from "@/shared/ui/shadcn/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/shared/ui/shadcn/dropdown-menu";
import type { VariantI } from "../model";
import { VariantGalleryActions } from "./VariantGalleryActions";

export function AdminVariantCard({
  variant,
  index,
  onEdit,
  onDelete,
}: {
  variant: VariantI;
  index: number;
  onEdit: () => void;
  onDelete: () => void;
}) {
  const image = variant.gallery_urls?.[0];
  return (
    <motion.article
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04, duration: 0.3 }}
      className="group flex min-w-0 flex-col overflow-hidden rounded-2xl bg-card text-left shadow-xs ring-1 ring-foreground/10 transition-all hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm"
    >
      <div className="relative aspect-video overflow-hidden bg-muted">
        {image ? (
          <img
            src={image}
            alt={variant.name}
            className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
          />
        ) : (
          <div className="flex h-full items-center justify-center bg-linear-to-br from-muted via-background to-muted/40">
            <span className="text-3xl font-semibold text-muted-foreground/30">
              {variant.name.charAt(0).toUpperCase()}
            </span>
          </div>
        )}
        <div className="absolute inset-0 bg-linear-to-t from-black/70 via-transparent to-transparent" />
        <div className="absolute left-3 top-3 rounded-full border border-white/30 bg-black/75 px-2.5 py-1 text-[11px] font-semibold text-white shadow-sm">
          {variant.gallery_urls?.length ?? 0}{" "}
          {(variant.gallery_urls?.length ?? 0) === 1 ? "imagem" : "imagens"}
        </div>
        <div className="absolute right-3 top-3">
          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <button
                  type="button"
                  className="inline-flex size-8 items-center justify-center rounded-full bg-background/90 shadow-sm"
                  aria-label="Abrir ações da variante"
                >
                  <MoreVertical className="size-4" />
                </button>
              }
            />
            <DropdownMenuContent align="end">
              <DropdownMenuItem onClick={onEdit}>
                <Pencil className="size-4" />
                Editar
              </DropdownMenuItem>
              <DropdownMenuItem variant="destructive" onClick={onDelete}>
                <Trash2 className="size-4" />
                Excluir
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </div>
      <div className="flex min-w-0 flex-1 flex-col gap-3 p-4">
        <div className="min-w-0">
          <h3 className="truncate text-base font-semibold text-foreground">
            {variant.name}
          </h3>
          <p className="truncate text-xs text-muted-foreground">
            Código: {variant.vendor_code}
          </p>
        </div>
        {variant.description ? (
          <p className="line-clamp-2 min-h-10 text-sm text-muted-foreground">
            {variant.description}
          </p>
        ) : (
          <div className="min-h-10" />
        )}
        <div className="flex items-end justify-between gap-3">
          <div>
            <p className="text-sm font-bold text-foreground">
              R$ {(variant.price / 100).toFixed(2)}
            </p>
            <p className="text-xs text-muted-foreground">
              {variant.stock === null
                ? "Ilimitado"
                : `${variant.stock} em estoque`}
            </p>
          </div>
          <VariantGalleryActions variant={variant} />
        </div>
        <Button
          type="button"
          variant="outline"
          className="w-full"
          onClick={onEdit}
        >
          Editar variante
        </Button>
      </div>
    </motion.article>
  );
}

// front/univents-solid/src/features/products/ui/AdminVariantCard.tsx
import type { JSX } from "@solidjs/web";
import { Show } from "solid-js";

import BoxesIcon from "~icons/lucide/boxes";
import ImagePlusIcon from "~icons/lucide/image-plus";
import InfinityIcon from "~icons/lucide/infinity";
import PencilIcon from "~icons/lucide/pencil";
import TrashIcon from "~icons/lucide/trash";

import { Button, cn } from "@trieoh/ui-solid";
import { Reveal } from "@/shared/ui/Reveal";
import type { VariantI } from "../model";

const Boxes = BoxesIcon as unknown as (props: { class?: string }) => JSX.Element;
const ImagePlus = ImagePlusIcon as unknown as (props: { class?: string }) => JSX.Element;
const InfinityLucide = InfinityIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const Trash = TrashIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminVariantCardProps {
  variant: VariantI;
  index?: number;
  animate?: boolean;
  onEdit: (variant: VariantI) => void;
  onDelete: (variant: VariantI) => void;
  onManageGallery?: (variant: VariantI) => void;
}

function formatPrice(cents: number): string {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}

export function AdminVariantCard(props: AdminVariantCardProps): JSX.Element {
  const isDeleted = () => props.variant.deleted_at !== null;
  const imageCount = () => props.variant.gallery_urls?.length ?? 0;
  const coverImage = () => props.variant.gallery_urls?.[0];

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div
        role="region"
        aria-label={`Variação ${props.variant.name}`}
        class={cn(
          "group relative flex h-full w-full min-w-0 flex-col justify-between overflow-hidden rounded-xl border border-border border-t-[3px] border-t-primary bg-card bg-linear-to-b from-primary/[0.04] via-card to-card p-4 text-left shadow-xs transition-all duration-200",
          "hover:-translate-y-0.5 hover:border-foreground/20 hover:border-t-primary hover:shadow-md",
          "focus-within:ring-2 focus-within:ring-ring",
          isDeleted() && "opacity-60 grayscale",
        )}
      >
        <div class="space-y-2">
          {/* Header with thumbnail, name, code and actions */}
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-center gap-2.5 min-w-0 flex-1">
              <div class="relative flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-border/70 bg-muted/60 transition-transform group-hover:scale-105">
                <Show
                  when={coverImage()}
                  fallback={
                    <div class="flex size-full items-center justify-center bg-primary/10 text-primary font-bold uppercase select-none">
                      {props.variant.name.charAt(0) || "V"}
                    </div>
                  }
                >
                  {(url) => (
                    <img
                      src={url()}
                      alt={props.variant.name}
                      class="size-full object-cover"
                    />
                  )}
                </Show>
              </div>

              <div class="min-w-0 flex-1">
                <h3
                  class="truncate text-sm font-semibold tracking-tight text-foreground transition-colors group-hover:text-primary"
                  title={props.variant.name}
                >
                  {props.variant.name}
                </h3>
                <div class="mt-0.5 flex items-center gap-1.5 text-xs text-muted-foreground">
                  <span class="truncate font-mono" title={props.variant.vendor_code}>
                    {props.variant.vendor_code}
                  </span>
                  <span>•</span>
                  <span class="shrink-0 text-[11px]">
                    {imageCount()} {imageCount() === 1 ? "foto" : "fotos"}
                  </span>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div class="flex items-center gap-0.5 shrink-0">
              <Show when={props.onManageGallery}>
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  aria-label={`Galeria de ${props.variant.name}`}
                  title="Gerenciar fotos da galeria"
                  onClick={() => props.onManageGallery?.(props.variant)}
                  class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-muted hover:text-foreground group-hover:opacity-100 cursor-pointer"
                >
                  <ImagePlus class="size-3.5" />
                </Button>
              </Show>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Editar ${props.variant.name}`}
                title="Editar variação"
                onClick={() => props.onEdit(props.variant)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-muted hover:text-foreground group-hover:opacity-100 cursor-pointer"
              >
                <Pencil class="size-3.5" />
              </Button>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Excluir ${props.variant.name}`}
                title="Excluir variação"
                onClick={() => props.onDelete(props.variant)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-destructive/15 hover:text-destructive group-hover:opacity-100 cursor-pointer"
              >
                <Trash class="size-3.5" />
              </Button>
            </div>
          </div>

          <p
            class="line-clamp-2 text-xs leading-relaxed text-muted-foreground min-h-[2rem]"
            title={props.variant.description ?? ""}
          >
            {props.variant.description || "Nenhuma descrição fornecida para esta variação."}
          </p>
        </div>

        {/* Specs footer: Price and Stock */}
        <div class="mt-3 flex items-center justify-between border-t border-border/60 pt-2.5 text-[11px] text-muted-foreground">
          <div class="flex items-center gap-1.5 font-semibold text-foreground">
            <span>{formatPrice(props.variant.price)}</span>
          </div>

          <div class="flex items-center gap-1.5">
            <Show
              when={props.variant.stock != null}
              fallback={
                <span class="inline-flex items-center gap-1 text-emerald-600 dark:text-emerald-400 font-medium">
                  <InfinityLucide class="size-3" />
                  <span>Ilimitado</span>
                </span>
              }
            >
              <span class="inline-flex items-center gap-1 text-foreground/80 font-medium">
                <Boxes class="size-3 text-muted-foreground shrink-0" />
                <span>{props.variant.stock} un. em estoque</span>
              </span>
            </Show>
          </div>
        </div>
      </div>
    </Reveal>
  );
}
