// front/univents-solid/src/features/products/ui/AdminProductCard.tsx
import type { JSX } from "@solidjs/web";
import { Show } from "solid-js";

import CalendarIcon from "~icons/lucide/calendar";
import LayersIcon from "~icons/lucide/layers";
import PackageIcon from "~icons/lucide/package";
import PencilIcon from "~icons/lucide/pencil";
import ShieldCheckIcon from "~icons/lucide/shield-check";
import TrashIcon from "~icons/lucide/trash";

import { Button, cn } from "@trieoh/ui-solid";
import { Reveal } from "@/shared/ui/Reveal";
import type { ProductI, VariantI } from "../model";

const Calendar = CalendarIcon as unknown as (props: { class?: string }) => JSX.Element;
const Layers = LayersIcon as unknown as (props: { class?: string }) => JSX.Element;
const Package = PackageIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const ShieldCheck = ShieldCheckIcon as unknown as (props: { class?: string }) => JSX.Element;
const Trash = TrashIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminProductCardProps {
  product: ProductI;
  variants?: VariantI[];
  coverImage?: string | null;
  index?: number;
  animate?: boolean;
  onEdit: (product: ProductI) => void;
  onDelete: (product: ProductI) => void;
  onManageVariants: (product: ProductI) => void;
}

function formatDate(iso: string): string {
  try {
    return new Intl.DateTimeFormat("pt-BR", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }).format(new Date(iso));
  } catch {
    return "";
  }
}

export function AdminProductCard(props: AdminProductCardProps): JSX.Element {
  const isDeleted = () => props.product.deleted_at !== null;

  const firstImage = () => {
    if (props.coverImage) return props.coverImage;
    if (props.variants) {
      for (const v of props.variants) {
        if (v.gallery_urls && v.gallery_urls.length > 0 && v.gallery_urls[0]) {
          return v.gallery_urls[0];
        }
      }
    }
    return null;
  };

  const variantsCount = () => props.variants?.length;

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div
        role="region"
        aria-label={`Produto ${props.product.vendor_code}`}
        class={cn(
          "group relative flex h-full w-full min-w-0 flex-col justify-between overflow-hidden rounded-xl border border-border border-t-[3px] border-t-primary bg-card bg-linear-to-b from-primary/[0.04] via-card to-card p-4 text-left shadow-xs transition-all duration-200",
          "hover:-translate-y-0.5 hover:border-foreground/20 hover:border-t-primary hover:shadow-md",
          "focus-within:ring-2 focus-within:ring-ring",
          isDeleted() && "opacity-60 grayscale",
        )}
      >
        <div class="space-y-3">
          {/* Header with thumbnail, code, badges and actions */}
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-center gap-2.5 min-w-0 flex-1">
              <div class="relative flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-border/70 bg-muted/60 transition-transform group-hover:scale-105">
                <Show
                  when={firstImage()}
                  fallback={
                    <div class="flex size-full items-center justify-center bg-primary/10 text-primary">
                      <Package class="size-5" />
                    </div>
                  }
                >
                  {(url) => (
                    <img
                      src={url()}
                      alt={props.product.vendor_code}
                      class="size-full object-cover"
                    />
                  )}
                </Show>
              </div>

              <div class="min-w-0 flex-1">
                <h3
                  class="truncate text-sm font-bold font-mono tracking-tight text-foreground transition-colors group-hover:text-primary"
                  title={props.product.vendor_code}
                >
                  {props.product.vendor_code}
                </h3>
                <div class="mt-0.5 flex flex-wrap items-center gap-1.5">
                  <Show
                    when={props.product.requires_registration}
                    fallback={
                      <span class="inline-flex items-center text-[10px] font-medium text-muted-foreground">
                        Livre
                      </span>
                    }
                  >
                    <span class="inline-flex items-center gap-1 text-[10px] font-medium text-primary">
                      <ShieldCheck class="size-3 shrink-0" />
                      Exige cadastro
                    </span>
                  </Show>

                  <Show when={variantsCount() != null && variantsCount()! > 0}>
                    <span class="text-[10px] text-muted-foreground/60">•</span>
                    <span class="inline-flex items-center gap-1 text-[10px] font-medium text-muted-foreground">
                      <Layers class="size-2.5" />
                      {variantsCount()} {variantsCount() === 1 ? "variação" : "variações"}
                    </span>
                  </Show>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div class="flex items-center gap-0.5 shrink-0">
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Editar ${props.product.vendor_code}`}
                title="Editar produto"
                onClick={() => props.onEdit(props.product)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-muted hover:text-foreground group-hover:opacity-100 cursor-pointer"
              >
                <Pencil class="size-3.5" />
              </Button>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Excluir ${props.product.vendor_code}`}
                title="Excluir produto"
                onClick={() => props.onDelete(props.product)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-destructive/15 hover:text-destructive group-hover:opacity-100 cursor-pointer"
              >
                <Trash class="size-3.5" />
              </Button>
            </div>
          </div>

          <div class="flex items-center justify-between text-[11px] text-muted-foreground min-h-[1.25rem]">
            <span class="inline-flex items-center gap-1.5">
              <Calendar class="size-3 shrink-0 opacity-70" />
              <span>Criado em {formatDate(props.product.created_at)}</span>
            </span>
          </div>
        </div>

        {/* Footer: Manage Variants button */}
        <div class="mt-3 border-t border-border/60 pt-2.5">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => props.onManageVariants(props.product)}
            class="w-full gap-1.5 text-xs font-medium cursor-pointer hover:bg-accent hover:text-accent-foreground"
          >
            <Layers class="size-3.5 text-muted-foreground" />
            Gerenciar variações
          </Button>
        </div>
      </div>
    </Reveal>
  );
}

// front/univents/src/features/products/ui/AdminProductCard.tsx
import type React from 'react'
import { motion } from 'motion/react'
import { MoreVertical, Tag, Trash2, Pencil, Package, Layers, ShieldCheck } from 'lucide-react'
import type { ProductI } from '@/features/products/model'
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from '@/shared/ui/shadcn/context-menu'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from '@/shared/ui/shadcn/dropdown-menu'
import { cn } from '@/shared/lib/utils'

interface AdminProductCardProps {
  product: ProductI
  index: number
  onEdit: (product: ProductI) => void
  onDelete: (product: ProductI) => void
  onManageVariants: (product: ProductI) => void
}

function MenuItems({
  isContext = false,
  onEdit,
  onDelete,
  onManageVariants,
}: {
  isContext?: boolean
  onEdit: () => void
  onDelete: () => void
  onManageVariants: () => void
}) {
  const Item = isContext ? ContextMenuItem : DropdownMenuItem
  const Separator = isContext ? ContextMenuSeparator : DropdownMenuSeparator
  const stop = (action: () => void) => (e: React.MouseEvent | React.KeyboardEvent) => {
    e.preventDefault()
    e.stopPropagation()
    action()
  }

  return (
    <>
      <Item onClick={stop(onEdit)}>
        <Pencil className="size-4" />
        <span>Editar</span>
      </Item>
      <Item onClick={stop(onManageVariants)}>
        <Layers className="size-4" />
        <span>Variações</span>
      </Item>
      <Separator />
      <Item onClick={stop(onDelete)}>
        <Trash2 className="size-4" />
        <span>Excluir</span>
      </Item>
    </>
  )
}

function getRandomGradient(index: number): string {
  const gradients = [
    'from-violet-500/20 via-fuchsia-500/10 to-background',
    'from-emerald-500/20 via-teal-500/10 to-background',
    'from-amber-500/20 via-orange-500/10 to-background',
    'from-blue-500/20 via-cyan-500/10 to-background',
    'from-rose-500/20 via-pink-500/10 to-background',
    'from-indigo-500/20 via-purple-500/10 to-background',
  ]
  return gradients[index % gradients.length]
}

export function AdminProductCard({
  product,
  index,
  onEdit,
  onDelete,
  onManageVariants,
}: AdminProductCardProps) {
  const handleAction = (type: 'edit' | 'delete' | 'variants') => {
    if (type === 'edit') onEdit(product)
    if (type === 'delete') onDelete(product)
    if (type === 'variants') onManageVariants(product)
  }

  const isDeleted = product.deleted_at !== null

  const article = (
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05, duration: 0.35, ease: [0.25, 0.1, 0.25, 1] }}
      className={cn(
        'group relative flex w-full min-w-0 flex-col overflow-hidden rounded-2xl bg-card text-left',
        'ring-1 ring-foreground/10 shadow-xs',
        'transform-gpu will-change-transform',
        'transition-all duration-300 ease-out',
        'hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm',
        'focus:outline-none focus-visible:outline-none focus-visible:ring-0',
        isDeleted && 'opacity-60 grayscale',
      )}
      role="button"
      tabIndex={0}
      onClick={() => handleAction('edit')}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault()
          handleAction('edit')
        }
      }}
    >
      <div className={cn(
        'relative aspect-video overflow-hidden',
        'bg-linear-to-br',
        getRandomGradient(index),
      )}>
        <div className="flex h-full w-full items-center justify-center">
          <div className="flex size-18 items-center justify-center rounded-full border border-border/70 bg-background/80 shadow-sm backdrop-blur-sm">
            <Tag className="size-7 text-muted-foreground/40" />
          </div>
        </div>

        <div className="absolute inset-0 bg-linear-to-t from-background/90 via-background/35 to-transparent" />

        <div className="absolute left-3 top-3 flex flex-wrap items-center gap-1.5">
          <span className={cn(
            'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium backdrop-blur-sm',
            isDeleted
              ? 'border-rose-500/20 bg-rose-500/10 text-rose-700'
              : 'border-emerald-500/20 bg-emerald-500/10 text-emerald-700',
          )}>
            <span className={cn(
              'size-1.5 rounded-full',
              isDeleted ? 'bg-rose-500' : 'bg-emerald-500',
            )} />
            <span className="max-w-28 truncate">
              {isDeleted ? 'Excluído' : 'Ativo'}
            </span>
          </span>
        </div>

        <div className="absolute right-3 top-3">
          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <button
                  type="button"
                  onClick={(e) => e.stopPropagation()}
                  className={cn(
                    'inline-flex size-9 items-center justify-center rounded-full',
                    'bg-background/85 text-foreground shadow-sm backdrop-blur-sm',
                    'transition-colors hover:bg-background',
                  )}
                  aria-label={`Abrir ações de ${product.vendor_code}`}
                >
                  <MoreVertical className="size-4" />
                </button>
              }
            />
            <DropdownMenuContent align="end" className="w-56">
              <MenuItems
                onEdit={() => handleAction('edit')}
                onDelete={() => handleAction('delete')}
                onManageVariants={() => handleAction('variants')}
              />
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        <div className="absolute inset-x-0 bottom-0 flex items-end justify-between gap-3 p-4 sm:p-5">
          <div className="min-w-0 space-y-1">
            <h3 className="line-clamp-1 text-balance text-lg font-semibold leading-snug text-foreground transition-colors duration-300 group-hover:text-primary sm:text-xl">
              {product.vendor_code}
            </h3>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between gap-3 p-4 pt-3 sm:p-5 sm:pt-4">
        <div className="min-w-0 flex-1 space-y-1.5">
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Package className="size-3.5 shrink-0" />
            <span className="truncate font-mono text-xs">{product.vendor_code}</span>
          </div>

          {product.requires_registration && (
            <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
              <ShieldCheck className="size-3.5 shrink-0" />
              <span className="truncate">Exige cadastro</span>
            </div>
          )}
        </div>
      </div>
    </motion.article>
  )

  return (
    <ContextMenu>
      <ContextMenuTrigger render={article} />
      <ContextMenuContent className="w-56">
        <MenuItems
          isContext
          onEdit={() => handleAction('edit')}
          onDelete={() => handleAction('delete')}
          onManageVariants={() => handleAction('variants')}
        />
      </ContextMenuContent>
    </ContextMenu>
  )
}
