// front/univents-solid/src/features/products/ui/ProductsSection.tsx
import type {
  Product,
  ProductVariant,
  StoreStockItem,
} from "@trieoh/univents-api/schemas";
import { For, Show, createMemo } from "solid-js";
import { Link } from "@tanstack/solid-router";
import { ProductCard } from "./ProductCard";

export function ProductsSection(props: {
  products: { product: Product; variants: ProductVariant[] }[];
  stock: StoreStockItem[];
  eventSlug: string;
  editionId: string;
}) {
  const products = createMemo(() =>
    props.products.filter(({ variants }) => variants.length > 0),
  );
  const stock = createMemo(
    () => new Map(props.stock.map((item) => [item.id, item.stock])),
  );

  return (
    <Show when={products().length > 0}>
      <section class="w-full py-5">
        <div class="mb-8 text-center">
          <h2 class="text-3xl font-semibold tracking-tight text-foreground">
            Produtos
          </h2>
          <p class="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">
            Itens exclusivos disponíveis para esta edição do evento.
          </p>
        </div>
        <div class="mx-auto flex max-w-6xl flex-wrap justify-start gap-5">
          <For each={products().slice(0, 3)}>
            {({ product, variants }) => (
              <ProductCard
                product={product}
                variants={variants}
                stock={stock()}
                editionId={props.editionId}
              />
            )}
          </For>
        </div>
        <div class="mt-6 text-center">
          <Link
            class="text-sm font-semibold text-primary"
            to="/events/$slug/store"
            params={{ slug: props.eventSlug }}
            search={{ tab: "products" }}
          >
            Ver todos os produtos →
          </Link>
        </div>
      </section>
    </Show>
  );
}

// front/univents/src/features/products/ui/ProductsSection.tsx
import { useQueries, useSuspenseQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import {
  productsByEditionQueryOptions,
  productVariantsQueryOptions,
} from "../api";
import { ProductCard } from "./ProductCard";

interface ProductsSectionProps {
  editionId?: string;
  eventSlug: string;
}

export function ProductsSection({
  editionId,
  eventSlug,
}: ProductsSectionProps) {
  if (!editionId) return null;

  const { data: products } = useSuspenseQuery(
    productsByEditionQueryOptions(editionId),
  );

  const variantsResults = useQueries({
    queries: products.map((product) => productVariantsQueryOptions(product.id)),
  });

  const productsWithVariants = products
    .map((product, i) => ({
      product,
      variants: variantsResults[i].data ?? [],
    }))
    .filter(({ variants }) => variants.length > 0);

  if (productsWithVariants.length === 0) return null;

  return (
    <section className="w-full py-5">
      <div className="px-4">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-semibold text-foreground tracking-tight">
            Produtos
          </h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed max-w-xl mx-auto">
            Itens exclusivos disponíveis para esta edição do evento.
          </p>
        </div>

        <div className="flex flex-wrap justify-start gap-5 max-w-6xl mx-auto">
          {productsWithVariants.slice(0, 3).map(({ product, variants }) => (
            <ProductCard
              key={product.id}
              product={product}
              variants={variants}
              maxVariants={3}
              editionId={editionId}
            />
          ))}
        </div>

        <div className="mt-6 text-center">
          <Link
            to="/events/$slug/store"
            search={{ tab: "products" }}
            params={{ slug: eventSlug }}
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary transition-all duration-200 hover:gap-2.5"
          >
            Ver todos os produtos
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>
    </section>
  );
}
