// front/univents-solid/src/routes/auth_/$provider/callback.tsx
import { createFileRoute } from "@tanstack/solid-router";
import type { JSX } from "@solidjs/web";
import { useAuth } from "@trieoh/identityx-sdk-ts-solid";
import { createEffect, createSignal } from "solid-js";
import Loader2Icon from "~icons/lucide/loader-2";
import z from "zod";

import {
  clearAuthReturnTo,
  readAuthReturnTo,
} from "@/features/auths/lib/auth-path";
import { toast } from "@/shared/ui/toast";

const Loader2 = Loader2Icon as unknown as (props: {
  class?: string;
}) => JSX.Element;

const providerSchema = z.enum(["google", "github"]);

export const Route = createFileRoute("/auth_/$provider/callback")({
  params: {
    parse: (params) => ({
      provider: providerSchema.parse(params.provider),
    }),
  },
  validateSearch: z.object({
    code: z.string().optional(),
    state: z.string().optional(),
  }),
  component: OAuthCallbackPage,
});

function OAuthCallbackPage() {
  const params = Route.useParams();
  const search = Route.useSearch();
  const navigate = Route.useNavigate();
  const { auth } = useAuth();
  const [result, setResult] = createSignal<string>();
  let called = false;

  createEffect(
    () => ({ search: search(), provider: params().provider }),
    ({ search: currentSearch, provider: currentProvider }) => {
      const { code, state } = currentSearch;
      if (called) return;
      called = true;
      if (!code || !state) {
        setResult("Callback OAuth inválido: code ou state ausente.");
        return;
      }
      void auth
        .completeProviderLogin(currentProvider, code, state)
        .then((response) => {
          if (!response.success)
            throw new Error(
              response.message || "Não foi possível concluir o login",
            );
          toast.success("Login realizado com sucesso");
          const destination = readAuthReturnTo(localStorage) || "/profile";
          clearAuthReturnTo(localStorage);
          window.location.assign(destination);
        })
        .catch((error) => {
          const message =
            error instanceof Error
              ? error.message
              : "Falha na autenticação OAuth";
          setResult(message);
          toast.error(message);
        });
    },
  );

  return (
    <main class="flex min-h-dvh items-center justify-center bg-background">
      <div class="max-w-md space-y-4 text-center">
        {!result() && (
          <Loader2 class="mx-auto size-12 animate-spin text-primary" />
        )}
        <h1 class="text-lg font-semibold">
          {result() ? "Resultado da autenticação" : "Entrando…"}
        </h1>
        <p class="text-sm text-muted-foreground">
          {result() || "Aguarde enquanto concluímos sua autenticação."}
        </p>
        {result() && (
          <button
            type="button"
            class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground"
            onClick={() =>
              void navigate({
                to: "/profile",
                search: { tab: "about" },
                replace: true,
              })
            }
          >
            Continuar
          </button>
        )}
      </div>
    </main>
  );
}

// front/identityx/src/routes/auth/$provider/callback.tsx
import { createFileRoute, useRouter } from "@tanstack/react-router";
import { useAuth } from "@trieoh/identityx-sdk-ts-react";
import { useEffect, useRef } from "react";
import { toast } from "sonner";
import z from "zod";

const callbackSearchSchema = z.object({
  code: z.string().optional(),
  state: z.string().optional(),
});

const providerSchema = z.enum(["google", "github"]);

export const Route = createFileRoute("/auth/$provider/callback")({
  component: CallbackPage,
  validateSearch: callbackSearchSchema,
  params: {
    parse: (params) => ({
      provider: providerSchema.parse(params.provider),
    }),
  },
});

function CallbackPage() {
  const navigate = Route.useNavigate();
  const { provider } = Route.useParams();
  const { code, state } = Route.useSearch();
  const router = useRouter();
  const { auth } = useAuth();
  const calledRef = useRef(false);

  useEffect(() => {
    if (calledRef.current) return;
    calledRef.current = true;

    async function authenticate() {
      if (!code || !state) {
        navigate({ to: "/auth" });
        return;
      }
      try {
        const res = await auth.completeProviderLogin(provider, code, state);
        if (res.success) {
          await navigate({ to: "/admin" });
          toast.success(res.message ?? "Login successful!");
          router.options.context.queryClient.invalidateQueries();
          return;
        }
        toast.error(res.message ?? "Auth Initialization Failed");
        navigate({ to: "/auth" });
      } catch {
        navigate({ to: "/auth" });
      }
    }

    authenticate();
  }, [provider, code, state, navigate, auth, router]);

  return (
    <div className="flex min-h-screen items-center justify-center">
      <div className="text-center">
        <div className="mb-4 h-12 w-12 animate-spin rounded-full border-4 border-secondary border-t-primary mx-auto" />
        <h1 className="text-lg font-semibold text-primary">Entrando...</h1>
        <p className="text-sm text-muted-foreground">
          Aguarde enquanto concluímos sua autenticação.
        </p>
      </div>
    </div>
  );
}
