// front/univents/src/features/calendar/ui/CalendarEditor.tsx
import {
  closestCenter,
  DndContext,
  type DragEndEvent,
  DragOverlay,
  PointerSensor,
  useSensor,
  useSensors,
} from "@dnd-kit/core";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import {
  ArrowLeft,
  ChevronLeft,
  ChevronRight,
  Monitor,
  Plus,
} from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import {
  occurrencesQueryOptions,
  programsQueryOptions,
} from "@/features/programs/api";
import {
  useDeleteOccurrenceMutation,
  useOccurrenceMutation,
} from "@/features/programs/api/mutations";
import { Button } from "@/shared/ui/shadcn/button";
import { addDays, formatMonthYear, startOfDay, toISODate } from "../lib/date";
import type { CalendarView, EventColor, OccurrenceI, ProgramI } from "../model";
import { CalendarCombobox } from "./CalendarCombobox";
import { DayView } from "./DayView";
import { EventModal } from "./EventModal";
import { MiniCalendar } from "./MiniCalendar";
import { MonthView } from "./MonthView";
import { ProgramList } from "./ProgramList";
import { WeekView } from "./WeekView";
import { YearView } from "./YearView";

const COLORS: EventColor[] = [
  {
    bg: "oklch(0.85 0.08 264.05 / 0.25)",
    border: "oklch(0.55 0.15 264.05)",
    text: "var(--foreground)",
  },
  {
    bg: "oklch(0.85 0.08 150 / 0.25)",
    border: "oklch(0.5 0.15 150)",
    text: "var(--foreground)",
  },
  {
    bg: "oklch(0.85 0.08 30 / 0.25)",
    border: "oklch(0.6 0.15 30)",
    text: "var(--foreground)",
  },
  {
    bg: "oklch(0.85 0.08 280 / 0.25)",
    border: "oklch(0.55 0.15 280)",
    text: "var(--foreground)",
  },
  {
    bg: "oklch(0.85 0.08 200 / 0.25)",
    border: "oklch(0.55 0.15 200)",
    text: "var(--foreground)",
  },
];

const VIEW_LABELS: Record<CalendarView, string> = {
  day: "Dia",
  week: "Semana",
  month: "Mês",
  year: "Ano",
};

export function CalendarEditor({
  eventId,
  editionId,
}: {
  eventId: string;
  editionId: string;
}) {
  const navigate = useNavigate();
  const today = useMemo(() => startOfDay(new Date()), []);
  const [currentDate, setCurrentDate] = useState<Date>(new Date(today));
  const [view, setView] = useState<CalendarView>("week");
  const { data: loadedPrograms = [] } = useQuery(
    programsQueryOptions(editionId),
  );
  const { data: loadedOccurrences = [] } = useQuery(
    occurrencesQueryOptions(editionId),
  );
  const occurrenceMutation = useOccurrenceMutation();
  const deleteOccurrenceMutation = useDeleteOccurrenceMutation();
  const [occurrences, setOccurrences] = useState<OccurrenceI[]>([]);
  const programs = loadedPrograms as ProgramI[];
  const visibleOccurrences = loadedOccurrences.length
    ? loadedOccurrences
    : occurrences;
  const [modalOpen, setModalOpen] = useState(false);
  const [modalMode, setModalMode] = useState<"create" | "edit">("create");
  const [modalOccurrence, setModalOccurrence] = useState<OccurrenceI | null>(
    null,
  );
  const [modalInitial, setModalInitial] = useState<{
    programId?: string;
    date?: string;
    hour?: number;
  }>({});
  const [activeDragId, setActiveDragId] = useState<string | null>(null);

  const programColors = useMemo(() => {
    const map: Record<string, EventColor> = {};
    programs.forEach((p, i) => {
      map[p.id] = COLORS[i % COLORS.length];
    });
    return map;
  }, [programs]);

  const titleText = useMemo(() => {
    if (view === "day") return formatMonthYear(currentDate);
    if (view === "week") {
      const days = Array.from({ length: 7 }, (_, i) => addDays(currentDate, i));
      return `${formatMonthYear(days[0])} – ${formatMonthYear(days[6])}`;
    }
    if (view === "month") return formatMonthYear(currentDate);
    return String(currentDate.getFullYear());
  }, [currentDate, view]);

  const sensors = useSensors(
    useSensor(PointerSensor, {
      activationConstraint: { distance: 5 },
    }),
  );

  const handlePrev = useCallback(() => {
    setCurrentDate((d) => {
      const nd = new Date(d);
      if (view === "day") nd.setDate(nd.getDate() - 1);
      else if (view === "week") nd.setDate(nd.getDate() - 7);
      else if (view === "month") nd.setMonth(nd.getMonth() - 1);
      else if (view === "year") nd.setFullYear(nd.getFullYear() - 1);
      return nd;
    });
  }, [view]);

  const handleNext = useCallback(() => {
    setCurrentDate((d) => {
      const nd = new Date(d);
      if (view === "day") nd.setDate(nd.getDate() + 1);
      else if (view === "week") nd.setDate(nd.getDate() + 7);
      else if (view === "month") nd.setMonth(nd.getMonth() + 1);
      else if (view === "year") nd.setFullYear(nd.getFullYear() + 1);
      return nd;
    });
  }, [view]);

  const handleToday = useCallback(() => {
    setCurrentDate(new Date(today));
  }, [today]);

  const handleMiniPrevMonth = useCallback(() => {
    setCurrentDate((d) => {
      const nd = new Date(d);
      nd.setMonth(nd.getMonth() - 1);
      return nd;
    });
  }, []);

  const handleMiniNextMonth = useCallback(() => {
    setCurrentDate((d) => {
      const nd = new Date(d);
      nd.setMonth(nd.getMonth() + 1);
      return nd;
    });
  }, []);

  const handleMiniDateClick = useCallback((date: Date) => {
    setCurrentDate(date);
  }, []);

  const handleYearDateClick = useCallback((date: Date) => {
    setCurrentDate(date);
    setView("month");
  }, []);

  const handleMonthDateClick = useCallback((date: Date) => {
    setCurrentDate(date);
    setView("week");
  }, []);

  const handleWeekDateClick = useCallback((date: Date) => {
    setCurrentDate(date);
    setView("day");
  }, []);

  const handleDragEnd = useCallback(
    (event: DragEndEvent) => {
      const { active, over } = event;
      setActiveDragId(null);

      if (!over) return;

      const activeData = active.data.current;
      const overData = over.data.current;

      if (!activeData || !overData) return;

      if (activeData.type === "program" && overData.date !== undefined) {
        const [year, month, day] = String(overData.date).split("-").map(Number);
        const start = new Date(
          year,
          month - 1,
          day,
          Number(overData.hour),
          0,
          0,
          0,
        );
        const end = new Date(start.getTime() + 60 * 60 * 1000);
        occurrenceMutation.mutate({
          programId: activeData.programId as string,
          data: { starts_at: start.toISOString(), ends_at: end.toISOString() },
        });
        setOccurrences((prev) => [
          ...prev,
          {
            id: `oc_${Math.random().toString(36).slice(2, 9)}`,
            program_id: activeData.programId as string,
            edition_id: "e1",
            starts_at: start.toISOString(),
            ends_at: end.toISOString(),
            max_capacity: null,
            created_at: new Date().toISOString(),
            updated_at: null,
            deleted_at: null,
          },
        ]);
      } else if (
        activeData.type === "occurrence" &&
        overData.date !== undefined
      ) {
        const occurrenceId = activeData.occurrenceId as string;
        const occurrence = visibleOccurrences.find(
          (oc) => oc.id === occurrenceId,
        );
        if (!occurrence) return;
        const durMs =
          new Date(occurrence.ends_at).getTime() -
          new Date(occurrence.starts_at).getTime();
        const [year, month, day] = String(overData.date).split("-").map(Number);
        const hour = Math.max(0, Math.min(23, Number(overData.hour)));
        const currentStart = new Date(occurrence.starts_at);
        if (
          toISODate(currentStart) === String(overData.date) &&
          currentStart.getHours() === hour
        ) {
          return;
        }
        const newStart = new Date(year, month - 1, day, hour, 0, 0, 0);
        const newEnd = new Date(newStart.getTime() + durMs);
        occurrenceMutation.mutate({
          id: occurrenceId,
          data: {
            starts_at: newStart.toISOString(),
            ends_at: newEnd.toISOString(),
          },
        });
        setOccurrences((prev) =>
          prev.map((oc) => {
            if (oc.id !== occurrenceId) return oc;
            return {
              ...oc,
              starts_at: newStart.toISOString(),
              ends_at: newEnd.toISOString(),
              updated_at: new Date().toISOString(),
            };
          }),
        );
      }
    },
    [occurrenceMutation],
  );

  const handleSlotClick = useCallback(
    (date: string, hour: number) => {
      setModalMode("create");
      setModalInitial({ programId: programs[0]?.id, date, hour });
      setModalOccurrence(null);
      setModalOpen(true);
    },
    [programs],
  );

  const handleCardClick = useCallback(
    (occurrenceId: string) => {
      const oc = visibleOccurrences.find((o) => o.id === occurrenceId);
      if (!oc) return;
      setModalMode("edit");
      setModalOccurrence(oc);
      setModalInitial({});
      setModalOpen(true);
    },
    [visibleOccurrences],
  );

  const handleModalSave = useCallback(
    (data: {
      program_id: string;
      starts_at: string;
      ends_at: string;
      max_capacity?: number;
      id?: string;
    }) => {
      if (modalMode === "edit" && data.id) {
        occurrenceMutation.mutate({ id: data.id, data });
        setOccurrences((prev) =>
          prev.map((oc) =>
            oc.id === data.id
              ? {
                  ...oc,
                  program_id: data.program_id,
                  starts_at: data.starts_at,
                  ends_at: data.ends_at,
                  max_capacity: data.max_capacity ?? null,
                  updated_at: new Date().toISOString(),
                }
              : oc,
          ),
        );
      } else {
        occurrenceMutation.mutate({ programId: data.program_id, data });
        setOccurrences((prev) => [
          ...prev,
          {
            id: `oc_${Math.random().toString(36).slice(2, 9)}`,
            program_id: data.program_id,
            edition_id: "e1",
            starts_at: data.starts_at,
            ends_at: data.ends_at,
            max_capacity: data.max_capacity ?? null,
            created_at: new Date().toISOString(),
            updated_at: null,
            deleted_at: null,
          },
        ]);
      }
      setModalOpen(false);
    },
    [modalMode, occurrenceMutation],
  );

  const handleModalDelete = useCallback(
    (occurrenceId: string) => {
      deleteOccurrenceMutation.mutate(occurrenceId);
      setOccurrences((prev) =>
        prev.map((oc) =>
          oc.id === occurrenceId
            ? { ...oc, deleted_at: new Date().toISOString() }
            : oc,
        ),
      );
      setModalOpen(false);
    },
    [deleteOccurrenceMutation],
  );

  const activeDragProgram = useMemo(() => {
    if (!activeDragId?.startsWith("program-")) return null;
    const pid = activeDragId.replace("program-", "");
    return programs.find((p) => p.id === pid);
  }, [activeDragId, programs]);

  const activeDragOccurrence = useMemo(() => {
    if (!activeDragId?.startsWith("event-")) return null;
    const oid = activeDragId.replace("event-", "");
    return visibleOccurrences.find((o) => o.id === oid);
  }, [activeDragId, visibleOccurrences]);

  const activeDragOccurrenceProgram = useMemo(() => {
    if (!activeDragOccurrence) return null;
    return programs.find((p) => p.id === activeDragOccurrence.program_id);
  }, [activeDragOccurrence, programs]);

  const activeDragOccurrenceColor = useMemo(() => {
    if (!activeDragOccurrence) return null;
    return programColors[activeDragOccurrence.program_id];
  }, [activeDragOccurrence, programColors]);

  const activeOccurrences = useMemo(
    () => visibleOccurrences.filter((oc) => !oc.deleted_at),
    [visibleOccurrences],
  );

  return (
    <div className="h-dvh min-h-0 bg-background text-foreground">
      <div className="flex h-full flex-col items-center justify-center gap-3 px-6 text-center lg:hidden!">
        <Monitor className="size-10 text-muted-foreground" />
        <p className="max-w-xs text-sm text-muted-foreground">
          O calendário foi desenvolvido para telas maiores. Abra esta página em
          um computador para acessar a agenda completa.
        </p>
      </div>

      <div className="hidden h-full min-h-0 min-w-0 flex-col overflow-hidden bg-background lg:flex">
        <DndContext
          sensors={sensors}
          collisionDetection={closestCenter}
          onDragStart={(e) => setActiveDragId(e.active.id as string)}
          onDragEnd={handleDragEnd}
        >
          {/* Toolbar */}
          <div className="flex items-center gap-2 px-4 py-2.5 border-b border-border h-14 shrink-0 bg-background">
            <Button
              type="button"
              variant="ghost"
              className="h-9 gap-2 px-3"
              onClick={() =>
                void navigate({
                  to: "/admin/events/$eventId/editions/$editionId/programs",
                  params: { eventId, editionId },
                })
              }
            >
              <ArrowLeft className="size-4" />
              Voltar
            </Button>

            <div className="flex items-center gap-0.5 ml-1">
              <button
                type="button"
                className="w-9 h-9 flex items-center justify-center rounded-full hover:bg-muted transition-colors text-foreground"
                onClick={handlePrev}
              >
                <ChevronLeft size={18} />
              </button>
              <button
                type="button"
                className="w-9 h-9 flex items-center justify-center rounded-full hover:bg-muted transition-colors text-foreground"
                onClick={handleNext}
              >
                <ChevronRight size={18} />
              </button>
            </div>

            <button
              type="button"
              className="px-4 py-2 border border-border rounded-full text-sm font-medium text-foreground hover:bg-muted transition-colors"
              onClick={handleToday}
            >
              Hoje
            </button>

            <div className="text-[22px] font-normal text-foreground ml-4 whitespace-nowrap tracking-tight">
              {titleText}
            </div>

            <div className="flex-1" />

            <CalendarCombobox
              value={view}
              onChange={(value) => setView(value as CalendarView)}
              options={(Object.keys(VIEW_LABELS) as CalendarView[]).map(
                (v) => ({ value: v, label: VIEW_LABELS[v] }),
              )}
              placeholder="Visualização"
              compact
            />
          </div>

          {/* Body */}
          <div className="flex min-w-0 flex-1 min-h-0 overflow-hidden">
            {/* Sidebar */}
            <div className="w-65 shrink-0 border-r border-border flex flex-col overflow-hidden p-3 gap-4 bg-background">
              <MiniCalendar
                currentDate={currentDate}
                onDateClick={handleMiniDateClick}
                onPrevMonth={handleMiniPrevMonth}
                onNextMonth={handleMiniNextMonth}
              />
              <button
                type="button"
                className="inline-flex items-center justify-center gap-1.5 px-4 py-2 rounded-full text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 transition-opacity shadow-sm"
                onClick={() => {
                  setModalMode("create");
                  setModalInitial({
                    programId: programs[0]?.id,
                    date: toISODate(currentDate),
                    hour: 9,
                  });
                  setModalOccurrence(null);
                  setModalOpen(true);
                }}
              >
                <Plus size={16} /> Criar ocorrência
              </button>
              <div className="calendar-scroll flex-1 overflow-y-auto">
                <ProgramList
                  programs={programs}
                  programColors={programColors}
                />
              </div>
            </div>

            {/* Views */}
            {view === "day" && (
              <DayView
                currentDate={currentDate}
                today={today}
                occurrences={activeOccurrences}
                programs={programs}
                programColors={programColors}
                onSlotClick={handleSlotClick}
                onCardClick={handleCardClick}
                onDelete={handleModalDelete}
              />
            )}
            {view === "week" && (
              <WeekView
                currentDate={currentDate}
                today={today}
                occurrences={activeOccurrences}
                programs={programs}
                programColors={programColors}
                onSlotClick={handleSlotClick}
                onDayClick={handleWeekDateClick}
                onCardClick={handleCardClick}
                onDelete={handleModalDelete}
              />
            )}
            {view === "month" && (
              <MonthView
                currentDate={currentDate}
                today={today}
                occurrences={activeOccurrences}
                programs={programs}
                programColors={programColors}
                onDateClick={handleMonthDateClick}
                onCardClick={handleCardClick}
              />
            )}
            {view === "year" && (
              <YearView
                currentDate={currentDate}
                today={today}
                occurrences={activeOccurrences}
                programColors={programColors}
                onDateClick={handleYearDateClick}
                onCardClick={handleCardClick}
              />
            )}
          </div>

          {/* Drag Overlay */}
          <DragOverlay>
            {activeDragProgram && (
              <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-card border border-border shadow-xl text-sm text-foreground opacity-90">
                <span
                  className="w-2.5 h-2.5 rounded-full"
                  style={{
                    background: programColors[activeDragProgram.id]?.border,
                  }}
                />
                <span>{activeDragProgram.name}</span>
              </div>
            )}
            {activeDragOccurrence &&
              activeDragOccurrenceProgram &&
              activeDragOccurrenceColor && (
                <div
                  className="rounded-md px-3 py-2 shadow-xl opacity-90 min-w-30"
                  style={{
                    background: activeDragOccurrenceColor.bg,
                    borderLeft: `3px solid ${activeDragOccurrenceColor.border}`,
                    color: activeDragOccurrenceColor.text,
                  }}
                >
                  <div className="text-xs font-semibold">
                    {activeDragOccurrenceProgram.name}
                  </div>
                </div>
              )}
          </DragOverlay>
        </DndContext>

        {/* Modal */}
        {modalOpen && (
          <EventModal
            mode={modalMode}
            programs={programs}
            occurrence={modalOccurrence}
            initialProgramId={modalInitial.programId}
            initialDate={modalInitial.date}
            initialHour={modalInitial.hour}
            onSave={handleModalSave}
            onDelete={handleModalDelete}
            onClose={() => setModalOpen(false)}
          />
        )}
      </div>
    </div>
  );
}

// front/univents-solid/src/features/calendar/ui/CalendarEditor.tsx
import type { JSX } from "@solidjs/web";
import { useQuery, useQueryClient } from "@trieoh/front-core-solid";
import { useNavigate } from "@tanstack/solid-router";
import { For, Show, createMemo, createSignal } from "solid-js";

import ArrowLeftIcon from "~icons/lucide/arrow-left";
import ChevronLeftIcon from "~icons/lucide/chevron-left";
import ChevronRightIcon from "~icons/lucide/chevron-right";
import GripVerticalIcon from "~icons/lucide/grip-vertical";
import PlusIcon from "~icons/lucide/plus";

import { occurrencesQueryOptions, programsQueryOptions } from "@/features/programs/api";
import {
  useCreateOccurrenceMutation,
  useDeleteOccurrenceMutation,
  useUpdateOccurrenceMutation,
} from "@/features/programs/api/mutations";
import type { OccurrenceCreateOutput } from "@/features/programs/model";
import { programKeys } from "@/features/programs/api/query-keys";
import { DesktopOnly } from "@/shared/ui/DesktopOnly";
import { toast } from "@/shared/ui/toast";
import { addDays, formatMonthYear, isSameDay, startOfDay } from "../lib/date";
import { endCalendarDrag, startCalendarDrag } from "../lib/drag-state";
import type { CalendarDragData, CalendarView, EventColor, OccurrenceI, ProgramI } from "../model";
import { EVENT_COLORS, FALLBACK_EVENT_COLOR } from "../model";
import { DayView } from "./DayView";
import { ManageOccurrenceDialog } from "./ManageOccurrenceDialog";
import { MiniCalendar } from "./MiniCalendar";
import { MonthView } from "./MonthView";
import { WeekView } from "./WeekView";
import { YearView } from "./YearView";

const ArrowLeft = ArrowLeftIcon as unknown as (props: { class?: string }) => JSX.Element;
const ChevronLeft = ChevronLeftIcon as unknown as (props: { class?: string }) => JSX.Element;
const ChevronRight = ChevronRightIcon as unknown as (props: { class?: string }) => JSX.Element;
const GripVertical = GripVerticalIcon as unknown as (props: { class?: string }) => JSX.Element;
const Plus = PlusIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface CalendarEditorProps {
  eventId: string;
  editionId: string;
  initialProgramId?: string;
}

export function CalendarEditor(props: CalendarEditorProps): JSX.Element {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [currentDate, setCurrentDate] = createSignal<Date>(startOfDay(new Date()));
  const [view, setView] = createSignal<CalendarView>("week");

  // Queries
  const programsQuery = useQuery(() => programsQueryOptions(props.editionId));
  const occurrencesQuery = useQuery(() => occurrencesQueryOptions(props.editionId));

  const programs = createMemo(() => (programsQuery().data ?? []) as ProgramI[]);
  const occurrences = createMemo(() => (occurrencesQuery().data ?? []) as OccurrenceI[]);

  // Mutations
  const createMutation = useCreateOccurrenceMutation(() => props.editionId);
  const updateMutation = useUpdateOccurrenceMutation(() => props.editionId);
  const deleteMutation = useDeleteOccurrenceMutation(() => props.editionId);

  // Dialog State
  const [dialogOpen, setDialogOpen] = createSignal(false);
  const [selectedOccurrence, setSelectedOccurrence] = createSignal<OccurrenceI | null>(null);
  const [newOccurrenceSlot, setNewOccurrenceSlot] = createSignal<{
    dateStr: string;
    hour: number;
  } | null>(null);

  // Filter by program
  const [selectedProgramFilter, setSelectedProgramFilter] = createSignal<string | null>(
    props.initialProgramId ?? null,
  );

  // Program color map
  const programColors = createMemo(() => {
    const map: Record<string, EventColor> = {};
    programs().forEach((p, i) => {
      map[p.id] = EVENT_COLORS[i % EVENT_COLORS.length] ?? FALLBACK_EVENT_COLOR;
    });
    return map;
  });

  // Filtered occurrences
  const visibleOccurrences = createMemo(() => {
    if (!selectedProgramFilter()) return occurrences();
    return occurrences().filter((oc) => oc.program_id === selectedProgramFilter());
  });

  // Navigation handlers
  const handlePrev = () => {
    setCurrentDate((d) => {
      switch (view()) {
        case "day":
          return addDays(d, -1);
        case "week":
          return addDays(d, -7);
        case "month": {
          const nd = new Date(d);
          nd.setMonth(nd.getMonth() - 1);
          return nd;
        }
        case "year": {
          const nd = new Date(d);
          nd.setFullYear(nd.getFullYear() - 1);
          return nd;
        }
      }
    });
  };

  const handleNext = () => {
    setCurrentDate((d) => {
      switch (view()) {
        case "day":
          return addDays(d, 1);
        case "week":
          return addDays(d, 7);
        case "month": {
          const nd = new Date(d);
          nd.setMonth(nd.getMonth() + 1);
          return nd;
        }
        case "year": {
          const nd = new Date(d);
          nd.setFullYear(nd.getFullYear() + 1);
          return nd;
        }
      }
    });
  };

  const handleToday = () => {
    setCurrentDate(startOfDay(new Date()));
  };

  // Title text based on current view
  const titleText = createMemo(() => {
    const d = currentDate();
    switch (view()) {
      case "day":
        return d.toLocaleDateString("pt-BR", {
          weekday: "long",
          day: "numeric",
          month: "long",
          year: "numeric",
        });
      case "week": {
        const start = new Date(d);
        start.setDate(d.getDate() - d.getDay());
        const end = new Date(start);
        end.setDate(start.getDate() + 6);
        return `${start.toLocaleDateString("pt-BR", {
          day: "numeric",
          month: "short",
        })} - ${end.toLocaleDateString("pt-BR", {
          day: "numeric",
          month: "short",
          year: "numeric",
        })}`;
      }
      case "month":
        return formatMonthYear(d);
      case "year":
        return `${d.getFullYear()}`;
    }
  });

  // Dialog actions
  const openNewOccurrence = (dateStr?: string, hour?: number) => {
    setSelectedOccurrence(null);
    if (dateStr && hour !== undefined) {
      setNewOccurrenceSlot({ dateStr, hour });
    } else {
      setNewOccurrenceSlot(null);
    }
    setDialogOpen(true);
  };

  const openEditOccurrence = (occurrence: OccurrenceI) => {
    setNewOccurrenceSlot(null);
    setSelectedOccurrence(occurrence);
    setDialogOpen(true);
  };

  const handleSaveOccurrence = async (data: {
    programId: string;
    occurrenceData: OccurrenceCreateOutput;
    id?: string;
  }): Promise<boolean> => {
    try {
      if (data.id) {
        await updateMutation.mutateAsync({
          id: data.id,
          data: data.occurrenceData,
        });
        toast.success("Horário atualizado com sucesso!");
      } else {
        await createMutation.mutateAsync({
          programId: data.programId,
          data: data.occurrenceData,
        });
        toast.success("Horário criado com sucesso!");
      }
      void queryClient.invalidateQueries({
        queryKey: programKeys.occurrences(props.editionId),
      });
      void queryClient.invalidateQueries({
        queryKey: programKeys.byEdition(props.editionId),
      });
      return true;
    } catch {
      toast.error("Erro ao salvar horário.");
      return false;
    }
  };

  const handleDeleteOccurrenceModal = async (occurrenceId: string): Promise<boolean> => {
    try {
      await deleteMutation.mutateAsync(occurrenceId);
      void queryClient.invalidateQueries({
        queryKey: programKeys.occurrences(props.editionId),
      });
      void queryClient.invalidateQueries({
        queryKey: programKeys.byEdition(props.editionId),
      });
      toast.success("Horário excluído!");
      return true;
    } catch {
      toast.error("Erro ao excluir horário.");
      return false;
    }
  };

  const handleDeleteOccurrence = async (occurrenceId: string) => {
    await handleDeleteOccurrenceModal(occurrenceId);
  };

  // Drag & drop handlers
  const handleDropSlot = async (
    dateStr: string,
    hour: number,
    minute: number,
    data: CalendarDragData,
  ) => {
    try {
      if (data.type === "program") {
        const [year, month, day] = dateStr.split("-").map(Number);
        const start = new Date(year, (month || 1) - 1, day || 1, hour, minute, 0, 0);
        const end = new Date(start.getTime() + 60 * 60 * 1000); // 1 hora padrão

        await createMutation.mutateAsync({
          programId: data.programId,
          data: {
            starts_at: start.toISOString(),
            ends_at: end.toISOString(),
          },
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.occurrences(props.editionId),
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.byEdition(props.editionId),
        });
        toast.success("Horário adicionado com sucesso!");
      } else if (data.type === "occurrence") {
        const oc = occurrences().find((o) => o.id === data.occurrenceId);
        if (!oc) return;

        const currentStart = new Date(oc.starts_at);
        const durMs = Math.max(
          new Date(oc.ends_at).getTime() - currentStart.getTime(),
          15 * 60 * 1000,
        );
        const [year, month, day] = dateStr.split("-").map(Number);
        const newStart = new Date(year, (month || 1) - 1, day || 1, hour, minute, 0, 0);
        const newEnd = new Date(newStart.getTime() + durMs);

        // Don't update if same start time
        if (currentStart.getTime() === newStart.getTime()) {
          return;
        }

        await updateMutation.mutateAsync({
          id: oc.id,
          data: {
            starts_at: newStart.toISOString(),
            ends_at: newEnd.toISOString(),
            max_capacity: oc.max_capacity ?? undefined,
          },
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.occurrences(props.editionId),
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.byEdition(props.editionId),
        });
        toast.success("Horário reagendado!");
      }
    } catch {
      toast.error("Erro ao salvar horário.");
    }
  };

  const handleDropDay = async (day: Date, data: CalendarDragData) => {
    try {
      if (data.type === "program") {
        const start = new Date(day);
        start.setHours(9, 0, 0, 0);
        const end = new Date(start.getTime() + 60 * 60 * 1000);

        await createMutation.mutateAsync({
          programId: data.programId,
          data: {
            starts_at: start.toISOString(),
            ends_at: end.toISOString(),
          },
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.occurrences(props.editionId),
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.byEdition(props.editionId),
        });
        toast.success("Horário adicionado com sucesso!");
      } else if (data.type === "occurrence") {
        const oc = occurrences().find((o) => o.id === data.occurrenceId);
        if (!oc) return;

        const origStart = new Date(oc.starts_at);
        const newStart = new Date(day);
        newStart.setHours(origStart.getHours(), origStart.getMinutes(), 0, 0);

        if (isSameDay(origStart, newStart)) return;

        const durMs = Math.max(
          new Date(oc.ends_at).getTime() - origStart.getTime(),
          30 * 60 * 1000,
        );
        const newEnd = new Date(newStart.getTime() + durMs);

        await updateMutation.mutateAsync({
          id: oc.id,
          data: {
            starts_at: newStart.toISOString(),
            ends_at: newEnd.toISOString(),
            max_capacity: oc.max_capacity ?? undefined,
          },
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.occurrences(props.editionId),
        });
        void queryClient.invalidateQueries({
          queryKey: programKeys.byEdition(props.editionId),
        });
        toast.success("Horário reagendado!");
      }
    } catch {
      toast.error("Erro ao reagendar horário.");
    }
  };

  return (
    <DesktopOnly
      threshold={1200}
      title="Disponível apenas no computador"
      description="O editor de horários da programação foi projetado para telas a partir de 1200px de largura para permitir o uso da grade e organização dos eventos."
      actionLabel="Voltar aos programas"
      onAction={() =>
        navigate({
          to: "/admin/events/$eventId/editions/$editionId/programs",
          params: { eventId: props.eventId, editionId: props.editionId },
        })
      }
    >
      <div
        class="flex flex-col h-dvh w-full overflow-hidden bg-background"
        onDragOver={(e) => e.preventDefault()}
        onDrop={(e) => e.preventDefault()}
      >
        {/* Top Bar / Toolbar - Clean & Organized */}
        <header class="flex h-14 shrink-0 items-center justify-between border-b border-border bg-card px-4 sm:px-6 select-none z-30">
          {/* Left: Navigation & Date Info */}
          <div class="flex items-center gap-3">
            {/* Back Button */}
            <button
              type="button"
              onClick={() =>
                navigate({
                  to: "/admin/events/$eventId/editions/$editionId/programs",
                  params: { eventId: props.eventId, editionId: props.editionId },
                })
              }
              class="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md hover:bg-muted text-xs font-medium text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
            >
              <ArrowLeft class="size-4" />
              <span>Voltar aos programas</span>
            </button>

            <div class="h-4 w-px bg-border" />

            {/* Date Navigation */}
            <div class="flex items-center gap-1">
              <button
                type="button"
                onClick={handleToday}
                class="px-2.5 py-1 text-xs font-medium rounded-md border border-border hover:bg-muted text-foreground transition-colors cursor-pointer"
              >
                Hoje
              </button>
              <div class="flex items-center">
                <button
                  type="button"
                  onClick={handlePrev}
                  title="Anterior"
                  class="size-7 flex items-center justify-center rounded-md hover:bg-muted text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  <ChevronLeft class="size-4" />
                </button>
                <button
                  type="button"
                  onClick={handleNext}
                  title="Próximo"
                  class="size-7 flex items-center justify-center rounded-md hover:bg-muted text-muted-foreground hover:text-foreground transition-colors cursor-pointer"
                >
                  <ChevronRight class="size-4" />
                </button>
              </div>
            </div>

            {/* Current View Title */}
            <h1 class="text-sm sm:text-base font-semibold text-foreground tracking-tight capitalize pl-1">
              {titleText()}
            </h1>
          </div>

          {/* Right: View Switcher */}
          <div class="flex items-center">
            <div class="flex items-center rounded-lg border border-border bg-muted/30 p-0.5">
              {(["day", "week", "month", "year"] as const).map((v) => {
                const labels = { day: "Dia", week: "Semana", month: "Mês", year: "Ano" };
                const isActive = () => view() === v;
                return (
                  <button
                    type="button"
                    onClick={() => setView(v)}
                    class={`px-3 py-1 text-xs font-medium rounded-md transition-colors cursor-pointer ${
                      isActive()
                        ? "bg-background text-foreground font-semibold shadow-2xs"
                        : "text-muted-foreground hover:text-foreground"
                    }`}
                  >
                    {labels[v]}
                  </button>
                );
              })}
            </div>
          </div>
        </header>

        {/* Main layout */}
        <div class="flex flex-1 overflow-hidden">
          {/* Sidebar with mini calendar & program list (desktop only) */}
          <div class="hidden lg:flex w-64 flex-col border-r border-border bg-background p-3 gap-4 overflow-y-auto shrink-0 select-none">
            <MiniCalendar
              currentDate={currentDate()}
              onDateClick={(d) => setCurrentDate(d)}
              onPrevMonth={() =>
                setCurrentDate((d) => {
                  const nd = new Date(d);
                  nd.setMonth(nd.getMonth() - 1);
                  return nd;
                })
              }
              onNextMonth={() =>
                setCurrentDate((d) => {
                  const nd = new Date(d);
                  nd.setMonth(nd.getMonth() + 1);
                  return nd;
                })
              }
            />

            <button
              type="button"
              class="inline-flex items-center justify-center gap-1.5 px-4 py-2 rounded-full text-sm font-medium bg-primary text-primary-foreground hover:opacity-90 transition-opacity shadow-xs cursor-pointer"
              onClick={() => openNewOccurrence()}
            >
              <Plus class="size-4" /> Criar ocorrência
            </button>

            <div class="space-y-2 pt-2 border-t border-border">
              <div class="flex items-center justify-between">
                <span class="text-xs font-bold text-foreground uppercase tracking-wider">
                  Programas
                </span>
                <Show when={selectedProgramFilter() !== null}>
                  <button
                    type="button"
                    class="text-[10px] text-primary hover:underline cursor-pointer"
                    onClick={() => setSelectedProgramFilter(null)}
                  >
                    Limpar filtro
                  </button>
                </Show>
              </div>

              <p class="text-[11px] text-muted-foreground leading-snug">
                Arraste um programa para a grade para criar um horário.
              </p>

              <div class="space-y-1 mt-2">
                <For
                  each={programs()}
                  fallback={
                    <p class="text-xs text-muted-foreground/60 py-2">
                      Nenhum programa cadastrado nesta edição.
                    </p>
                  }
                >
                  {(prog) => {
                    const color = () => programColors()[prog.id] ?? FALLBACK_EVENT_COLOR;
                    const isFiltered = () => selectedProgramFilter() === prog.id;

                    return (
                      <div
                        draggable="true"
                        onDragStart={(e) => {
                          startCalendarDrag(e, {
                            type: "program",
                            programId: prog.id,
                          });
                        }}
                        onDragEnd={() => {
                          endCalendarDrag();
                        }}
                        onClick={() => {
                          setSelectedProgramFilter((prev) =>
                            prev === prog.id ? null : prog.id,
                          );
                        }}
                        class={`flex items-center gap-2 px-2.5 py-1.5 rounded-lg border text-xs font-medium cursor-grab active:cursor-grabbing transition-all select-none ${
                          isFiltered()
                            ? "ring-2 ring-primary border-primary font-semibold"
                            : "border-border/60 hover:bg-muted/50"
                        }`}
                        style={{
                          "border-left": `4px solid ${color().border}`,
                          background: isFiltered() ? color().bg : undefined,
                        }}
                      >
                        <GripVertical class="size-3 text-muted-foreground/50 shrink-0" />
                        <span class="truncate flex-1">{prog.name}</span>
                      </div>
                    );
                  }}
                </For>
              </div>
            </div>
          </div>

          {/* View container */}
          <div class="flex flex-1 flex-col overflow-hidden">
            <Show when={view() === "month"}>
              <MonthView
                currentDate={currentDate()}
                occurrences={visibleOccurrences()}
                programs={programs()}
                programColors={programColors()}
                onDateClick={(d) => {
                  setCurrentDate(d);
                  setView("day");
                }}
                onOccurrenceClick={openEditOccurrence}
                onDropDay={handleDropDay}
              />
            </Show>

            <Show when={view() === "week"}>
              <WeekView
                currentDate={currentDate()}
                occurrences={visibleOccurrences()}
                programs={programs()}
                programColors={programColors()}
                onSlotClick={(dateStr, hour) => openNewOccurrence(dateStr, hour)}
                onDayClick={(d) => {
                  setCurrentDate(d);
                  setView("day");
                }}
                onOccurrenceClick={openEditOccurrence}
                onDeleteOccurrence={handleDeleteOccurrence}
                onDropSlot={handleDropSlot}
              />
            </Show>

            <Show when={view() === "day"}>
              <DayView
                currentDate={currentDate()}
                occurrences={visibleOccurrences()}
                programs={programs()}
                programColors={programColors()}
                onSlotClick={(dateStr, hour) => openNewOccurrence(dateStr, hour)}
                onOccurrenceClick={openEditOccurrence}
                onDeleteOccurrence={handleDeleteOccurrence}
                onDropSlot={handleDropSlot}
              />
            </Show>

            <Show when={view() === "year"}>
              <YearView
                currentDate={currentDate()}
                occurrences={visibleOccurrences()}
                programColors={programColors()}
                onDateClick={(d) => {
                  setCurrentDate(d);
                  setView("day");
                }}
              />
            </Show>
          </div>
        </div>

        {/* Create/Edit Occurrence Dialog */}
        <ManageOccurrenceDialog
          open={dialogOpen()}
          onOpenChange={setDialogOpen}
          programs={programs()}
          initialProgramId={selectedProgramFilter() ?? undefined}
          occurrence={selectedOccurrence()}
          initialDate={newOccurrenceSlot()?.dateStr}
          initialHour={newOccurrenceSlot()?.hour}
          onSave={handleSaveOccurrence}
          onDelete={handleDeleteOccurrenceModal}
        />
      </div>
    </DesktopOnly>
  );
}
