// front/univents/src/features/calendar/ui/YearView.tsx
import { useMemo } from "react";
import type { EventColor, OccurrenceI } from "../model";
import { getMonthGrid, isSameDay, isToday } from "../lib/date";

interface YearViewProps {
  currentDate: Date;
  today: Date;
  occurrences: OccurrenceI[];
  programColors: Record<string, EventColor>;
  onDateClick: (date: Date) => void;
  onCardClick: (occurrenceId: string) => void;
}

const MONTH_NAMES = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
];

export function YearView({
  currentDate,
  occurrences,
  programColors,
  onDateClick,
}: YearViewProps) {
  const year = currentDate.getFullYear();

  const months = useMemo(() => {
    return Array.from({ length: 12 }, (_, m) => {
      const firstDay = new Date(year, m, 1);
      return getMonthGrid(firstDay);
    });
  }, [year]);

  const getOccurrencesForDay = (date: Date) => {
    return occurrences.filter((oc) => {
      const s = new Date(oc.starts_at);
      return isSameDay(s, date);
    });
  };

  return (
    <div className="flex-1 overflow-auto p-6">
      <div className="grid grid-cols-3 lg:grid-cols-4 gap-6">
        {months.map((weeks, monthIdx) => (
          <div
            key={monthIdx}
            className="border border-border/60 rounded-xl p-3 bg-card hover:shadow-sm transition-shadow"
          >
            <div className="text-sm font-semibold text-foreground mb-2">
              {MONTH_NAMES[monthIdx]}
            </div>
            <div className="grid grid-cols-7 gap-px">
              {["D", "S", "T", "Q", "Q", "S", "S"].map((d, index) => (
                <div
                  key={`${d}-${index}`}
                  className="text-center text-[10px] text-muted-foreground py-0.5"
                >
                  {d}
                </div>
              ))}
              {weeks.flat().map((day) => {
                const dayOccs = getOccurrencesForDay(day);
                const dayIsToday = isToday(day);
                const isOtherMonth = day.getMonth() !== monthIdx;
                const hasEvents = dayOccs.length > 0;

                return (
                  <div
                    key={day.toISOString()}
                    className={`relative text-center py-1 text-[11px] cursor-pointer rounded transition-colors ${
                      isOtherMonth
                        ? "text-muted-foreground/50"
                        : "text-foreground"
                    } ${dayIsToday ? "bg-primary text-primary-foreground font-medium" : "hover:bg-muted"}`}
                    onClick={() => onDateClick(day)}
                  >
                    {day.getDate()}
                    {hasEvents && !dayIsToday && (
                      <div
                        className="absolute bottom-0.5 left-1/2 -translate-x-1/2 w-1 h-1 rounded-full"
                        style={{
                          background:
                            programColors[dayOccs[0].program_id]?.border ||
                            "var(--primary)",
                        }}
                      />
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// front/univents-solid/src/features/calendar/ui/YearView.tsx
import type { JSX } from "@solidjs/web";
import { For, Show, createMemo } from "solid-js";

import { getMonthGrid, isToday, toISODate } from "../lib/date";
import type { EventColor, OccurrenceI } from "../model";

export interface YearViewProps {
  currentDate: Date;
  occurrences: OccurrenceI[];
  programColors: Record<string, EventColor>;
  onDateClick: (date: Date) => void;
}

const MONTH_NAMES = [
  "Janeiro",
  "Fevereiro",
  "Março",
  "Abril",
  "Maio",
  "Junho",
  "Julho",
  "Agosto",
  "Setembro",
  "Outubro",
  "Novembro",
  "Dezembro",
];

const DOW_LABELS = ["D", "S", "T", "Q", "Q", "S", "S"];

interface YearDayItem {
  date: Date;
  dayNum: number;
  isToday: boolean;
  isOtherMonth: boolean;
  hasEvents: boolean;
}

function MonthCard(props: {
  monthName: string;
  monthIndex: number;
  currentYear: number;
  occurrences: OccurrenceI[];
  onDateClick: (date: Date) => void;
}): JSX.Element {
  // Pre-calculate the entire month's days and event flags in a single memo
  // so individual cells don't register hundreds of separate reactive computations.
  const days = createMemo<YearDayItem[]>(() => {
    const firstDay = new Date(props.currentYear, props.monthIndex, 1);
    const grid = getMonthGrid(firstDay);

    const eventDates = new Set<string>();
    for (const oc of props.occurrences) {
      eventDates.add(toISODate(new Date(oc.starts_at)));
    }

    return grid.flat().map((day) => {
      const dateStr = toISODate(day);
      return {
        date: day,
        dayNum: day.getDate(),
        isToday: isToday(day),
        isOtherMonth: day.getMonth() !== props.monthIndex,
        hasEvents: eventDates.has(dateStr),
      };
    });
  });

  return (
    <div class="border border-border/70 rounded-xl p-3 bg-card shadow-2xs select-none">
      <h4 class="text-sm font-semibold text-foreground mb-2">
        {props.monthName}
      </h4>

      <div class="grid grid-cols-7 gap-1 text-center">
        <For each={DOW_LABELS}>
          {(label) => (
            <div class="text-[10px] font-semibold text-muted-foreground py-0.5">
              {label}
            </div>
          )}
        </For>

        <For each={days()}>
          {(day) => (
            <button
              type="button"
              onClick={() => props.onDateClick(day.date)}
              class={`relative size-7 mx-auto flex items-center justify-center rounded-full text-[11px] tabular-nums cursor-pointer transition-colors ${
                day.isToday
                  ? "bg-primary text-primary-foreground font-bold"
                  : day.hasEvents
                  ? "bg-primary/15 text-primary font-bold"
                  : day.isOtherMonth
                  ? "text-muted-foreground/30 hover:bg-muted/30"
                  : "text-foreground hover:bg-muted"
              }`}
            >
              {day.dayNum}
              <Show when={day.hasEvents && !day.isToday}>
                <span class="absolute bottom-0.5 size-1 rounded-full bg-primary" />
              </Show>
            </button>
          )}
        </For>
      </div>
    </div>
  );
}

export function YearView(props: YearViewProps): JSX.Element {
  const currentYear = () => props.currentDate.getFullYear();

  return (
    <div class="flex-1 overflow-auto p-6 bg-background">
      <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-6">
        <For each={MONTH_NAMES}>
          {(monthName, index) => (
            <MonthCard
              monthName={monthName}
              monthIndex={index()}
              currentYear={currentYear()}
              occurrences={props.occurrences}
              onDateClick={props.onDateClick}
            />
          )}
        </For>
      </div>
    </div>
  );
}
