// front/univents-solid/src/features/tickets/ui/AdminTicketCard.tsx
import type { JSX } from "@solidjs/web";
import { Show } from "solid-js";

import InfinityIcon from "~icons/lucide/infinity";
import KeyRoundIcon from "~icons/lucide/key-round";
import PencilIcon from "~icons/lucide/pencil";
import TicketIcon from "~icons/lucide/ticket";
import UsersIcon from "~icons/lucide/users";

import { Button, cn } from "@trieoh/ui-solid";
import { Reveal } from "@/shared/ui/Reveal";
import type { TicketI } from "../model";

const InfinityLucide = InfinityIcon as unknown as (props: { class?: string }) => JSX.Element;
const KeyRound = KeyRoundIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const Ticket = TicketIcon as unknown as (props: { class?: string }) => JSX.Element;
const Users = UsersIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminTicketCardProps {
  ticket: TicketI;
  index?: number;
  animate?: boolean;
  onEdit: (ticket: TicketI) => void;
}

function formatPrice(cents: number): string {
  if (cents === 0) return "Gratuito";
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL",
  }).format(cents / 100);
}

export function AdminTicketCard(props: AdminTicketCardProps): JSX.Element {
  const isFree = () => props.ticket.price_cents === 0;

  const handleEdit = () => props.onEdit(props.ticket);

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div
        role="button"
        tabindex={0}
        onClick={handleEdit}
        onKeyDown={(e) => {
          if (e.key === "Enter" || e.key === " ") {
            e.preventDefault();
            handleEdit();
          }
        }}
        class={cn(
          "group relative flex h-full w-full min-w-0 flex-col justify-between overflow-hidden rounded-xl border border-border border-t-[3px] border-t-primary bg-card bg-linear-to-b from-primary/[0.04] via-card to-card p-4 text-left shadow-xs transition-all duration-200",
          "hover:-translate-y-0.5 hover:border-foreground/20 hover:border-t-primary hover:shadow-md cursor-pointer",
          "focus:outline-none focus-visible:ring-2 focus-visible:ring-ring",
        )}
      >
        {/* Header: Title + Price + Edit button */}
        <div class="space-y-2">
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-center gap-2.5 min-w-0 flex-1">
              <div class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary transition-transform group-hover:scale-105">
                <Ticket class="size-4.5" />
              </div>
              <div class="min-w-0 flex-1">
                <h3
                  class="truncate text-sm font-semibold tracking-tight text-foreground transition-colors group-hover:text-primary"
                  title={props.ticket.name}
                >
                  {props.ticket.name}
                </h3>
                <p class={cn("text-xs font-semibold mt-0.5", isFree() ? "text-emerald-500 dark:text-emerald-400 font-medium" : "text-foreground")}>
                  {formatPrice(props.ticket.price_cents)}
                </p>
              </div>
            </div>

            <Button
              type="button"
              variant="ghost"
              size="icon"
              aria-label={`Editar ${props.ticket.name}`}
              title={`Editar ${props.ticket.name}`}
              onClick={(e) => {
                e.stopPropagation();
                handleEdit();
              }}
              class="size-7 shrink-0 text-muted-foreground opacity-60 transition-opacity hover:bg-muted hover:text-foreground group-hover:opacity-100"
            >
              <Pencil class="size-3.5" />
            </Button>
          </div>

          <p
            class="line-clamp-2 text-xs leading-relaxed text-muted-foreground min-h-[2rem]"
            title={props.ticket.description ?? ""}
          >
            {props.ticket.description || "Nenhuma descrição fornecida para este ingresso."}
          </p>
        </div>

        {/* Clean, sober specs footer */}
        <div class="mt-3 flex items-center justify-between border-t border-border/60 pt-2.5 text-[11px] text-muted-foreground">
          <div class="flex items-center gap-1.5 font-medium text-foreground/80">
            <KeyRound class="size-3 text-muted-foreground shrink-0" />
            <span>Acesso nível {props.ticket.access_level}</span>
          </div>

          <div class="flex items-center gap-1.5">
            <Show
              when={props.ticket.max_quantity != null}
              fallback={
                <span class="inline-flex items-center gap-1 text-muted-foreground" title="Vagas ilimitadas">
                  <InfinityLucide class="size-3" />
                  <span>Ilimitado</span>
                </span>
              }
            >
              <span class="inline-flex items-center gap-1 text-muted-foreground">
                <Users class="size-3 shrink-0" />
                <span>{props.ticket.max_quantity} vagas</span>
              </span>
            </Show>
          </div>
        </div>
      </div>
    </Reveal>
  );
}

// front/univents/src/features/tickets/ui/AdminTicketCard.tsx
import {
  Coins,
  Hash,
  Infinity as InfinityIcon,
  MoreVertical,
  PencilLine,
  Ticket,
} from "lucide-react";
import { motion } from "motion/react";
import type React from "react";
import type { TicketI } from "@/features/tickets/model";
import { cn } from "@/shared/lib/utils";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from "@/shared/ui/shadcn/context-menu";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/shared/ui/shadcn/dropdown-menu";

interface AdminTicketCardProps {
  ticket: TicketI;
  index?: number;
  onManage: (ticket: TicketI) => void;
}

function MenuItems({
  isContext = false,
  onManage,
}: {
  isContext?: boolean;
  onManage: () => void;
}) {
  const Item = isContext ? ContextMenuItem : DropdownMenuItem;
  const stop =
    (action?: () => void) => (e: React.MouseEvent | React.KeyboardEvent) => {
      e.preventDefault();
      e.stopPropagation();
      action?.();
    };

  return (
    <Item onClick={stop(onManage)}>
      <PencilLine className="size-4" />
      <span>Editar ticket</span>
    </Item>
  );
}

export default function AdminTicketCard({
  ticket,
  index = 0,
  onManage,
}: AdminTicketCardProps) {
  const handleEdit = () => onManage(ticket);

  const Article = (
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{
        delay: index * 0.05,
        duration: 0.35,
        ease: [0.25, 0.1, 0.25, 1],
      }}
      className={cn(
        "group relative flex w-full min-w-62.5 max-w-full flex-col overflow-hidden rounded-2xl bg-card text-left",
        "ring-1 ring-foreground/10 shadow-xs",
        "transform-gpu will-change-transform",
        "transition-all duration-300 ease-out",
        "hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm",
        "focus:outline-none focus-visible:outline-none focus-visible:ring-0",
      )}
      role="button"
      tabIndex={0}
      onClick={handleEdit}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          handleEdit();
        }
      }}
    >
      <div className="relative overflow-hidden bg-linear-to-br from-muted via-background to-muted/40 px-4 py-4">
        <div className="absolute inset-x-0 top-0 h-1 bg-linear-to-r from-primary/70 via-primary to-cyan-500/70" />

        <div className="absolute right-3 top-3">
          <DropdownMenu>
            <DropdownMenuTrigger
              render={
                <button
                  type="button"
                  onClick={(e) => e.stopPropagation()}
                  className={cn(
                    "inline-flex size-9 items-center justify-center rounded-full",
                    "bg-background/85 text-foreground shadow-sm backdrop-blur-sm",
                    "transition-colors hover:bg-background",
                  )}
                  aria-label={`Abrir ações de ${ticket.name}`}
                >
                  <MoreVertical className="size-4" />
                </button>
              }
            />
            <DropdownMenuContent align="end" className="w-56">
              <MenuItems onManage={handleEdit} />
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        <div className="flex items-start justify-between gap-3 pr-10">
          <div className="min-w-0 space-y-2">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="inline-flex items-center gap-1 rounded-full border border-sky-500/20 bg-sky-500/10 px-2 py-0.5 text-[10px] font-medium text-sky-700 backdrop-blur-sm">
                <Ticket className="size-3" />
                <span className="max-w-28 truncate">Ticket</span>
              </span>

              <span className="inline-flex items-center gap-1 rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2 py-0.5 text-[10px] font-medium text-emerald-700 backdrop-blur-sm">
                <Coins className="size-3" />

                <span className="max-w-28 truncate">
                  {ticket.price_cents > 0
                    ? `R$ ${(ticket.price_cents / 100).toFixed(2)}`
                    : "Gratuito"}
                </span>
              </span>
            </div>

            <div className="min-w-0 space-y-1">
              <h3 className="line-clamp-2 text-balance text-lg font-semibold leading-snug text-foreground transition-colors duration-300 group-hover:text-primary sm:text-xl">
                {ticket.name}
              </h3>
              {ticket.description && (
                <p className="line-clamp-1 text-sm text-muted-foreground">
                  {ticket.description}
                </p>
              )}
            </div>
          </div>
        </div>
      </div>

      <div className="flex items-center justify-between gap-3 p-4 pt-3 sm:p-5 sm:pt-4">
        <div className="min-w-0 flex-1 space-y-1.5">
          <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            <span className="inline-flex items-center gap-1.5">
              <Hash className="size-3.5 shrink-0" />
              <span>Nível de acesso: {ticket.access_level}</span>
            </span>

            <span className="inline-flex items-center gap-1.5">
              {ticket.max_quantity ? (
                <>
                  <Ticket className="size-3.5 shrink-0" />
                  <span>Máx. {ticket.max_quantity} ingressos</span>
                </>
              ) : (
                <>
                  <InfinityIcon className="size-3.5 shrink-0" />
                  <span>Quantidade ilimitada</span>
                </>
              )}
            </span>
          </div>

          {ticket.created_at && (
            <p className="text-[11px] text-muted-foreground/70">
              Criado em{" "}
              {new Date(ticket.created_at).toLocaleDateString("pt-BR")}
            </p>
          )}
        </div>
      </div>
    </motion.article>
  );

  return (
    <ContextMenu>
      <ContextMenuTrigger render={Article} />
      <ContextMenuContent className="w-56">
        <MenuItems isContext onManage={handleEdit} />
      </ContextMenuContent>
    </ContextMenu>
  );
}
