// Univents-UI/src/widgets/landing/ui/OrganizerView.tsx
import { motion } from 'motion/react'
import { FAQSection } from './FAQSection'
import { cn } from '@/shared/lib/utils'

const features = [
  {
    title: "Planejamento completo",
    desc: "Organize cronogramas, prazos e checklists com visão completa de cada etapa do evento."
  },
  {
    title: "Gestão de convidados",
    desc: "Controle listas de presença, convites e confirmações em tempo real."
  },
  {
    title: "Ingressos e inscrições",
    desc: "Venda ingressos, gerencie inscrições e acompanhe a receita do seu evento."
  },
  {
    title: "Fornecedores e logística",
    desc: "Centralize contratos, prazos e comunicação com todos os fornecedores."
  },
  {
    title: "Relatórios pós-evento",
    desc: "Analise resultados, feedbacks e métricas para melhorar seus próximos eventos."
  },
  {
    title: "Automações inteligentes",
    desc: "Automatize lembretes, e-mails e tarefas repetitivas do fluxo de trabalho."
  },
]

const steps = [
  { num: "01", title: "Configure seu evento", desc: "Defina detalhes, datas, equipe e fornecedores em poucos minutos com nossos templates prontos." },
  { num: "02", title: "Organize e gerencie", desc: "Acompanhe tarefas, convidados e logística em tempo real com visão unificada de tudo." },
  { num: "03", title: "Execute com confiança", desc: "No dia do evento, tenha controle total com check-ins, timeline ao vivo e comunicação integrada." },
]

const faqs = [
  {
    question: "Como funciona a taxa sobre vendas?",
    answer: "Cobramos apenas 10% sobre cada ingresso vendido. Não há taxas de setup, mensalidade mínima ou custos ocultos. Quanto mais você vende, melhores condições podemos oferecer."
  },
  {
    question: "Preciso pagar alguma mensalidade?",
    answer: "Não obrigatoriamente. Nosso plano Starter é gratuito. Planos pagos (Pro e Enterprise) oferecem recursos avançados, mas você só paga se quiser utilizá-los."
  },
  {
    question: "Quais tipos de eventos posso gerenciar?",
    answer: "Qualquer categoria: corporativos, sociais, culturais, esportivos, educacionais. Desde pequenas reuniões até grandes festivais com milhares de participantes."
  },
  {
    question: "Como recebo o dinheiro das vendas?",
    answer: "O repasse é automático para sua conta em até 2 dias úteis. Oferecemos também antecipação de recebíveis para eventos com fluxo de caixa planejado."
  },
  {
    question: "Posso cancelar a qualquer momento?",
    answer: "Sim. Sem contratos de fidelidade ou multas. Se estiver em um plano pago, você continua com acesso até o final do período contratado."
  },
  {
    question: "A plataforma oferece suporte para check-in no evento?",
    answer: "Sim. Temos aplicativo dedicado para check-in, leitura de QR Code offline, controle de múltiplas entradas e relatório de presença em tempo real."
  },
]

export function OrganizerView() {
  return (
    <div className="max-w-5xl mx-auto space-y-20 md:space-y-32">
      {/* Hero */}
      <section className="text-center max-w-2xl mx-auto space-y-4 md:space-y-6 px-2">
        <p className="text-base md:text-lg text-muted-foreground leading-relaxed">
          Planeje, organize e execute eventos de qualquer escala.
          Do briefing ao pós-evento, tudo em uma única plataforma.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 md:gap-4 justify-center pt-2 md:pt-4">
          <button className="px-5 py-2.5 md:px-6 md:py-3 bg-primary text-primary-foreground rounded-full text-sm font-medium hover:bg-primary/90 transition-colors">
            Começar gratuitamente
          </button>
          <button className="px-5 py-2.5 md:px-6 md:py-3 border border-border text-foreground rounded-full text-sm font-medium hover:border-foreground/50 transition-colors">
            Ver demonstração
          </button>
        </div>
        <p className="text-xs text-muted-foreground/70">Comece sem custo. Pague apenas uma pequena taxa sobre suas vendas.</p>
      </section>

      {/* Calendario Visual */}
      <section className="flex justify-center">
        <div className="flex gap-1 md:gap-2">
          {['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom'].map((day, idx) => (
            <div key={day} className="text-center">
              <div className={cn(
                "w-10 h-10 md:w-14 md:h-14 rounded-lg md:rounded-xl flex items-center justify-center text-xs md:text-sm font-medium mb-1 md:mb-2",
                idx === 2 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"
              )}>
                {idx + 10}
              </div>
              <span className="text-[10px] md:text-xs text-muted-foreground">{day}</span>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="space-y-8 md:space-y-12">
        <div className="text-center space-y-2">
          <p className="text-xs md:text-sm text-muted-foreground uppercase tracking-wider">Recursos</p>
          <h2 className="text-2xl md:text-4xl font-semibold text-foreground">
            Tudo para criar eventos<br className="hidden md:block" /> impecáveis.
          </h2>
        </div>

        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-x-6 gap-y-8 md:gap-x-8 md:gap-y-12">
          {features.map((f, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
              className="space-y-2"
            >
              <h3 className="text-base md:text-lg font-medium text-foreground">{f.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Como Funciona */}
      <section className="space-y-8 md:space-y-12">
        <div className="text-center">
          <h2 className="text-2xl md:text-4xl font-semibold text-foreground mb-2">Como funciona</h2>
          <p className="text-muted-foreground">Três passos para eventos perfeitos</p>
        </div>

        <div className="grid md:grid-cols-3 gap-6 md:gap-8">
          {steps.map((step, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.15 }}
              className="space-y-3 md:space-y-4"
            >
              <span className="text-3xl md:text-4xl font-semibold text-muted">{step.num}</span>
              <h3 className="text-lg md:text-xl font-medium text-foreground">{step.title}</h3>
              <p className="text-sm md:text-base text-muted-foreground leading-relaxed">{step.desc}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Modelo de Receita */}
      <section className="bg-muted rounded-2xl md:rounded-3xl p-6 md:p-12 space-y-6 md:space-y-8">
        <div className="text-center space-y-2">
          <p className="text-xs md:text-sm text-muted-foreground uppercase tracking-wider">Modelo transparente</p>
          <h2 className="text-2xl md:text-3xl font-semibold text-foreground">
            Sem mensalidades.<br />
            <span className="text-muted-foreground">Você só paga quando vende.</span>
          </h2>
        </div>

        <p className="text-center text-sm md:text-base text-muted-foreground max-w-2xl mx-auto">
          Cobramos apenas uma pequena porcentagem sobre cada produto vendido dentro da plataforma.
          Sem surpresas, sem taxas ocultas. Seu lucro cresce junto com o nosso.
        </p>

        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 md:gap-6">
          {[
            { title: "Taxa por transação", desc: "Uma porcentagem justa sobre cada venda realizada no seu evento." },
            { title: "Zero custo inicial", desc: "Crie sua conta, configure eventos e comece a vender sem pagar nada." },
            { title: "Escale sem limites", desc: "Quanto mais você vende, mais a plataforma trabalha por você." },
            { title: "Pagamento seguro", desc: "Processamento protegido com repasse direto para sua conta." },
          ].map((item, idx) => (
            <div key={idx} className="space-y-1 md:space-y-2">
              <h4 className="text-sm md:text-base font-medium text-foreground">{item.title}</h4>
              <p className="text-xs md:text-sm text-muted-foreground leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>

        {/* Exemplo de transação */}
        <div className="bg-card border border-border rounded-xl md:rounded-2xl p-4 md:p-6 max-w-md mx-auto">
          <p className="text-xs text-muted-foreground mb-3 md:mb-4 uppercase tracking-wider">Exemplo de transação</p>
          <div className="space-y-2 md:space-y-3 text-sm">
            <div className="flex justify-between">
              <span className="text-muted-foreground">Ingresso VIP — Show de Verão</span>
              <span className="font-medium text-foreground">R$ 150,00</span>
            </div>
            <div className="flex justify-between text-muted-foreground">
              <span>Taxa da plataforma</span>
              <span>- R$ 7,50</span>
            </div>
            <div className="h-px bg-border my-2" />
            <div className="flex justify-between font-medium text-foreground">
              <span>Você recebe</span>
              <span>R$ 142,50</span>
            </div>
            <p className="text-xs text-muted-foreground/70 text-right">95% para você</p>
          </div>
        </div>
      </section>

      {/* FAQ com Collapsible */}
      <section className="max-w-2xl mx-auto space-y-6 md:space-y-8">
        <div className="text-center space-y-2">
          <h2 className="text-2xl md:text-3xl font-semibold text-foreground">Perguntas frequentes</h2>
          <p className="text-sm text-muted-foreground">Tire suas dúvidas</p>
        </div>

        <FAQSection items={faqs} />
      </section>

      {/* CTA Final */}
      <section className="bg-foreground rounded-2xl md:rounded-3xl p-6 md:p-12 lg:p-16 text-center space-y-4 md:space-y-6">
        <h2 className="text-xl md:text-3xl font-semibold text-background">
          Seu próximo evento começa aqui
        </h2>
        <p className="text-sm md:text-base text-muted/80 max-w-md mx-auto">
          Crie sua conta gratuita e descubra como simplificar toda a gestão dos seus eventos.
        </p>
        <div className="flex flex-col sm:flex-row gap-3 justify-center pt-2">
          <button className="px-5 py-2.5 md:px-6 md:py-3 bg-background text-foreground rounded-full text-sm font-medium hover:bg-background/90 transition-colors">
            Começar gratuitamente
          </button>
          <button className="px-5 py-2.5 md:px-6 md:py-3 border border-muted/50 text-background rounded-full text-sm font-medium hover:border-muted transition-colors">
            Falar com vendas
          </button>
        </div>
        <p className="text-xs text-muted/60">Sem cartão de crédito. Cancele quando quiser.</p>
      </section>
    </div>
  )
}

// front/univents-solid/src/widgets/landing/ui/OrganizerView.tsx
import { For } from "solid-js";
import { FAQSection, type FAQItem } from "./FAQSection";
import { Reveal } from "@/shared/ui/Reveal";
const features = [
  [
    "Planejamento completo",
    "Organize cronogramas, prazos e checklists com visão completa de cada etapa do evento.",
  ],
  [
    "Gestão de convidados",
    "Controle listas de presença, convites e confirmações em tempo real.",
  ],
  [
    "Ingressos e inscrições",
    "Venda ingressos, gerencie inscrições e acompanhe a receita do seu evento.",
  ],
  [
    "Fornecedores e logística",
    "Centralize contratos, prazos e comunicação com todos os fornecedores.",
  ],
  [
    "Relatórios pós-evento",
    "Analise resultados, feedbacks e métricas para melhorar seus próximos eventos.",
  ],
  [
    "Automações inteligentes",
    "Automatize lembretes, e-mails e tarefas repetitivas do fluxo de trabalho.",
  ],
];
const steps = [
  [
    "01",
    "Configure seu evento",
    "Defina detalhes, datas, equipe e fornecedores em poucos minutos com nossos templates prontos.",
  ],
  [
    "02",
    "Organize e gerencie",
    "Acompanhe tarefas, convidados e logística em tempo real com visão unificada de tudo.",
  ],
  [
    "03",
    "Execute com confiança",
    "No dia do evento, tenha controle total com check-ins, timeline ao vivo e comunicação integrada.",
  ],
];
const faqs: FAQItem[] = [
  {
    question: "Como funciona a taxa sobre vendas?",
    answer:
      "Cobramos apenas 8% sobre cada ingresso vendido. Não há taxas de setup, mensalidade mínima ou custos ocultos.",
  },
  {
    question: "Preciso pagar mensalidade?",
    answer:
      "Não obrigatoriamente. Nosso plano Starter é gratuito. Planos pagos oferecem recursos avançados, mas você só paga se quiser utilizá-los.",
  },
  {
    question: "Quais tipos de eventos posso gerenciar?",
    answer:
      "Qualquer categoria: corporativos, sociais, culturais, esportivos e educacionais, desde pequenas reuniões até grandes festivais.",
  },
  {
    question: "Como recebo o dinheiro das vendas?",
    answer:
      "O repasse é automático para sua conta em até 2 dias úteis. Também oferecemos antecipação de recebíveis.",
  },
  {
    question: "Posso cancelar a qualquer momento?",
    answer:
      "Sim. Sem contratos de fidelidade ou multas. Você continua com acesso até o fim do período contratado.",
  },
  {
    question: "A plataforma oferece suporte para check-in no evento?",
    answer:
      "Sim. Temos aplicativo dedicado para check-in, leitura de QR Code offline, múltiplas entradas e relatório de presença em tempo real.",
  },
];
export function OrganizerView() {
  return (
    <Reveal>
      <div class="mx-auto max-w-5xl space-y-20 md:space-y-32">
        <section class="mx-auto max-w-2xl space-y-4 text-center">
          <p class="text-base text-muted-foreground leading-relaxed">
            Planeje, organize e execute eventos de qualquer escala. Do briefing
            ao pós-evento, tudo em uma única plataforma.
          </p>
          <p class="text-xs text-muted-foreground/70">
            Comece sem custo. Pague apenas uma pequena taxa sobre suas vendas.
          </p>
        </section>
        <section class="flex justify-center">
          <div class="flex gap-1 md:gap-2">
            <For each={["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"]}>
              {(day, index) => (
                <div class="text-center">
                  <div
                    class={`mb-1 flex h-10 w-10 items-center justify-center rounded-lg text-xs font-medium md:mb-2 md:h-14 md:w-14 md:rounded-xl md:text-sm ${index() === 2 ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}
                  >
                    {new Date().getDate() + index() - 2}
                  </div>
                  <span class="text-[10px] text-muted-foreground md:text-xs">
                    {day}
                  </span>
                </div>
              )}
            </For>
          </div>
        </section>
        <section class="space-y-8 md:space-y-12">
          <div class="space-y-2 text-center">
            <p class="text-xs uppercase tracking-wider text-muted-foreground md:text-sm">
              Recursos
            </p>
            <h2 class="text-2xl font-semibold md:text-4xl">
              Tudo para criar eventos
              <br class="hidden md:block" /> impecáveis.
            </h2>
          </div>
          <div class="grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            <For each={features}>
              {(feature) => (
                <div class="reveal-item space-y-2">
                  <h3 class="text-base font-medium md:text-lg">{feature[0]}</h3>
                  <p class="text-sm leading-relaxed text-muted-foreground">
                    {feature[1]}
                  </p>
                </div>
              )}
            </For>
          </div>
        </section>
        <section class="space-y-6 rounded-2xl bg-muted p-6 md:space-y-8 md:rounded-3xl md:p-12">
          <div class="space-y-2 text-center">
            <p class="text-xs uppercase tracking-wider text-muted-foreground md:text-sm">
              Modelo transparente
            </p>
            <h2 class="text-2xl font-semibold md:text-3xl">
              Sem mensalidades.
              <br />
              <span class="text-muted-foreground">
                Você só paga quando vende.
              </span>
            </h2>
          </div>
          <p class="mx-auto max-w-2xl text-center text-sm text-muted-foreground md:text-base">
            Cobramos apenas uma pequena porcentagem sobre cada produto vendido
            dentro da plataforma. Sem surpresas, sem taxas ocultas. Seu lucro
            cresce junto com o nosso.
          </p>
          <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            <For
              each={[
                [
                  "Taxa por transação",
                  "Uma porcentagem justa sobre cada venda realizada no seu evento.",
                ],
                [
                  "Zero custo inicial",
                  "Crie sua conta, configure eventos e comece a vender sem pagar nada.",
                ],
                [
                  "Escale sem limites",
                  "Quanto mais você vende, mais a plataforma trabalha por você.",
                ],
                [
                  "Pagamento seguro",
                  "Processamento protegido com repasse direto para sua conta.",
                ],
              ]}
            >
              {(item) => (
                <div class="space-y-2">
                  <h4 class="text-sm font-medium md:text-base">{item[0]}</h4>
                  <p class="text-xs leading-relaxed text-muted-foreground md:text-sm">
                    {item[1]}
                  </p>
                </div>
              )}
            </For>
          </div>
          <div class="mx-auto max-w-md space-y-3 rounded-2xl border border-border bg-card p-4 text-sm md:p-6">
            <p class="text-xs uppercase tracking-wider text-muted-foreground">
              Exemplo de transação
            </p>
            <div class="flex justify-between">
              <span class="text-muted-foreground">
                Ingresso VIP — Show de Verão
              </span>
              <span class="font-medium">R$ 150,00</span>
            </div>
            <div class="flex justify-between text-muted-foreground">
              <span>Taxa da plataforma</span>
              <span>- R$ 12,00</span>
            </div>
            <div class="h-px bg-border" />
            <div class="flex justify-between font-medium">
              <span>Você recebe</span>
              <span>R$ 138,00</span>
            </div>
            <p class="text-right text-xs text-muted-foreground/70">
              92% para você
            </p>
          </div>
        </section>
        <section class="space-y-8 md:space-y-12">
          <div class="text-center">
            <h2 class="text-2xl font-semibold md:text-4xl">Como funciona</h2>
            <p class="text-muted-foreground">
              Três passos para eventos perfeitos
            </p>
          </div>
          <div class="grid gap-6 md:grid-cols-3 md:gap-8">
            <For each={steps}>
              {(step) => (
                <div class="reveal-item space-y-3 md:space-y-4">
                  <span class="text-3xl font-semibold text-muted md:text-4xl">
                    {step[0]}
                  </span>
                  <h3 class="text-lg font-medium md:text-xl">{step[1]}</h3>
                  <p class="text-sm leading-relaxed text-muted-foreground md:text-base">
                    {step[2]}
                  </p>
                </div>
              )}
            </For>
          </div>
        </section>
        <section class="mx-auto max-w-2xl space-y-6">
          <div class="space-y-2 text-center">
            <h2 class="text-center text-2xl font-semibold md:text-3xl">
              Perguntas frequentes
            </h2>
            <p class="text-sm text-muted-foreground">Tire suas dúvidas</p>
          </div>
          <FAQSection items={faqs} />
        </section>
      </div>
    </Reveal>
  );
}
