// Univents-UI/src/features/payments/ui/PaymentProviderSelector.tsx
import { useState, useRef, useEffect } from "react"
import { MercadoPagoForm } from "./MercadoPago"
import { PaymentMethodSelector } from "./checkout/PaymentMethodSelector"
import { PaymentFormSheet } from "./checkout/PaymentFormSheet"
import type { PaymentProviderI, SubmitPaymentPayloadI, PaymentMethodI } from "../model"

interface PaymentProviderSelectorProps {
  provider?: PaymentProviderI
  amount: number
  handleSubmit: (data: SubmitPaymentPayloadI) => void
  sellerPublicKey: string
  onCancel?: () => void
}

export function PaymentProviderSelector({
  provider = "mercadopago",
  amount,
  handleSubmit,
  sellerPublicKey,
  onCancel,
}: PaymentProviderSelectorProps) {
  const isTooLowForCreditCard = amount < 100
  const [method, setMethod] = useState<PaymentMethodI | null>(null)
  const [sheetOpen, setSheetOpen] = useState(false)
  const [formReady, setFormReady] = useState(false)
  const closeTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Cleanup on unmount
  useEffect(() => {
    return () => {
      if (closeTimeoutRef.current) {
        clearTimeout(closeTimeoutRef.current)
      }
    }
  }, [])

  const handleSelectMethod = (m: PaymentMethodI) => {
    if (m === "credit_card" && isTooLowForCreditCard) return

    // Clear any pending cleanup from a previous close
    if (closeTimeoutRef.current) {
      clearTimeout(closeTimeoutRef.current)
      closeTimeoutRef.current = null
    }

    setMethod(m)
    setFormReady(false)
    setSheetOpen(true)
  }

  const handleClose = () => {
    setSheetOpen(false)
    setFormReady(false)

    if (closeTimeoutRef.current) {
      clearTimeout(closeTimeoutRef.current)
    }

    closeTimeoutRef.current = setTimeout(() => {
      setMethod(null)
      closeTimeoutRef.current = null
    }, 400)
  }

  switch (provider) {
    default:
      return (
        <>
          <PaymentMethodSelector
            amountCents={amount}
            selectedMethod={method}
            onSelectMethod={handleSelectMethod}
            onCancel={onCancel}
            isTooLowForCreditCard={isTooLowForCreditCard}
          />

          <PaymentFormSheet
            open={sheetOpen}
            method={method}
            onClose={handleClose}
            onReady={() => { setFormReady(true) }}
          >
            {method && formReady && (
              <MercadoPagoForm
                amount={amount}
                method={method}
                handleSubmit={(data) => {
                  handleSubmit(data)
                  handleClose()
                }}
                sellerPublicKey={sellerPublicKey}
              />
            )}
          </PaymentFormSheet>
        </>
      )
  }
}

// front/univents-solid/src/features/payments/ui/PaymentProviderSelector.tsx
import { createSignal, onCleanup } from "solid-js";
import type { CheckoutPayment } from "@/features/purchases/model/checkout";
import { PaymentFormSheet } from "./checkout/PaymentFormSheet";
import { PaymentMethodSelector } from "./checkout/PaymentMethodSelector";
import type { PaymentMethodI } from "./checkout/PaymentMethodSelector";
import { MercadoPagoForm } from "./MercadoPago";

interface Props {
  provider?: 'mercadopago';
  amount: number;
  handleSubmit: (data: CheckoutPayment) => void;
  sellerPublicKey: string;
}

export function PaymentProviderSelector(props: Props) {
  const isTooLowForCreditCard = () => props.amount < 100;
  const [method, setMethod] = createSignal<PaymentMethodI | null>(null);
  const [sheetOpen, setSheetOpen] = createSignal(false);
  const [formReady, setFormReady] = createSignal(false);
  let closeTimeout: ReturnType<typeof setTimeout> | null = null;

  onCleanup(() => {
    if (closeTimeout) clearTimeout(closeTimeout);
  });

  const handleSelectMethod = (m: PaymentMethodI) => {
    if (m === 'credit_card' && isTooLowForCreditCard()) return;

    if (closeTimeout) {
      clearTimeout(closeTimeout);
      closeTimeout = null;
    }

    setMethod(m);
    setFormReady(false);
    setSheetOpen(true);
  };

  const handleClose = () => {
    setSheetOpen(false);
    setFormReady(false);

    if (closeTimeout) clearTimeout(closeTimeout);

    closeTimeout = setTimeout(() => {
      setMethod(null);
      closeTimeout = null;
    }, 400);
  };

  return (
    <>
      <PaymentMethodSelector
        amountCents={props.amount}
        selectedMethod={method()}
        onSelectMethod={handleSelectMethod}
        isTooLowForCreditCard={isTooLowForCreditCard()}
      />

      <PaymentFormSheet
        open={sheetOpen()}
        method={method()}
        onClose={handleClose}
        onReady={() => setFormReady(true)}
      >
        {method() && formReady() && (
          <MercadoPagoForm
            amount={props.amount}
            method={method()!}
            handleSubmit={(data) => {
              props.handleSubmit(data);
              handleClose();
            }}
            sellerPublicKey={props.sellerPublicKey}
          />
        )}
      </PaymentFormSheet>
    </>
  );
}
