// front/univents-solid/src/routes/events/$slug/store.tsx
import { createFileRoute, Link } from "@tanstack/solid-router";
import { useQuery, useQueryClient } from "@trieoh/front-core-solid";
import { useAuth } from "@trieoh/identityx-sdk-ts-solid";
import type {
  Edition,
  Product,
  ProductVariant,
  StoreStockItem,
  TicketType,
  MyTicket,
} from "@trieoh/univents-api/schemas";
import {
  For,
  Loading,
  Show,
  createMemo,
  createSignal,
  untrack,
} from "solid-js";
import type { EventI } from "@/features/events/model";
import { storePageQueryOptions } from "@/features/products/api";
import { useInventoryStream } from "@/features/products/hooks/use-inventory-stream";
import { EventCart } from "@/features/products/ui/EventCart";
import { ProductCard } from "@/features/products/ui/ProductCard";
import { TicketCard } from "@/features/tickets/ui/TicketCard";

export const Route = createFileRoute("/events/$slug/store")({
  validateSearch: (search: Record<string, unknown>) => ({
    tab:
      search.tab === "products" ? ("products" as const) : ("tickets" as const),
  }),
  head: ({ params }) => ({
    meta: [{ title: `Loja ${params.slug} - Univents` }],
  }),
  component: StorePage,
});

function StorePage() {
  const params = Route.useParams();
  const search = Route.useSearch();
  const queryClient = useQueryClient();
  const { isAuthenticated } = useAuth();
  const dataQuery = useQuery(() => storePageQueryOptions(
    params().slug,
    isAuthenticated(),
    queryClient,
  ));
  const data = createMemo(() => dataQuery().data);

  return (
    <Loading fallback={<main class="min-h-screen animate-pulse bg-muted" />}>
      <Show
        when={data()}
        fallback={<main class="p-12 text-center">Evento não encontrado.</main>}
      >
        {(loaded) => (
          <Show
            when={loaded().edition}
            fallback={
              <main class="mx-auto max-w-3xl px-4 py-16 text-center">
                A loja não está disponível no momento.
              </main>
            }
          >
            {(edition) => (
              <StoreContent
                event={loaded().event}
                edition={edition()}
                tickets={loaded().tickets ?? []}
                products={loaded().products ?? []}
                initialStock={loaded().stock ?? []}
                heldTicket={loaded().heldTicket ?? null}
                initialTab={search().tab}
              />
            )}
          </Show>
        )}
      </Show>
    </Loading>
  );
}

function StoreContent(props: {
  event: EventI;
  edition: Edition;
  tickets: TicketType[];
  products: { product: Product; variants: ProductVariant[] }[];
  initialStock: StoreStockItem[];
  initialTab: "tickets" | "products";
  heldTicket: MyTicket | null;
}) {
  const { editionId, initialStock, initialTab, eventSlug } = (() => ({
    editionId: props.edition.id,
    initialStock: props.initialStock,
    initialTab: props.initialTab,
    eventSlug: props.event.slug,
  }))();
  const [tab, setTab] = createSignal(initialTab);
  const stock = useInventoryStream(editionId, initialStock);
  const stockById = createMemo(
    () => new Map(stock().map((item) => [item.id, item.stock])),
  );
  return (
    <main class="min-h-screen bg-background px-4 pb-24 pt-4 md:pt-6">
      <div class="mx-auto max-w-6xl">
        <header class="mx-auto max-w-3xl">
          <Link
            to="/events/$slug"
            params={{ slug: eventSlug }}
            class="text-sm font-medium text-muted-foreground"
          >
            ← Evento
          </Link>
          <div class="mt-5 text-center">
            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
              Loja do evento
            </p>
            <h1 class="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
              Ingressos e produtos
            </h1>
            <p class="mx-auto mt-3 max-w-xl text-muted-foreground">
              Encontre ingressos e produtos para {props.event.full_name}.
            </p>
          </div>
        </header>
        <div class="mt-10 flex gap-2 border-b border-border/60">
          <For each={["tickets", "products"] as const}>
            {(item) => (
              <button
                type="button"
                class={`border-b-2 px-4 py-3 text-sm font-medium ${tab() === item ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}
                onClick={() => setTab(item)}
              >
                {item === "tickets" ? "Ingressos" : "Produtos"}
              </button>
            )}
          </For>
        </div>
        <Show
          when={tab() === "tickets"}
          fallback={
            <div class="mt-8 flex flex-wrap justify-center gap-6 sm:justify-start">
              <For
                each={props.products.filter(({ variants }) => variants.length)}
              >
                {({ product, variants }) => (
                  <ProductCard
                    product={product}
                    variants={variants}
                    stock={stockById()}
                    editionId={props.edition.id}
                  />
                )}
              </For>
            </div>
          }
        >
          <div class="mt-8 flex flex-wrap justify-center gap-6 sm:justify-start">
            <For each={props.tickets}>
              {(ticket) => (
                <TicketCard
                  ticket={ticket}
                  editionId={props.edition.id}
                  stock={stockById().get(ticket.id)}
                  heldTicket={props.heldTicket}
                />
              )}
            </For>
          </div>
        </Show>
      </div>
      <EventCart
        editionId={props.edition.id}
        eventSlug={props.event.slug}
      />
    </main>
  );
}

// front/univents/src/routes/events/$slug/store.tsx
import { useQueries, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useAuth } from "@trieoh/identityx-sdk-ts/react";
import { ArrowLeft } from "lucide-react";
import { useState } from "react";
import { activeEditionQueryOptions } from "@/features/editions/api";
import { publicEventBySlugQueryOptions } from "@/features/events/api";
import {
  productsByEditionQueryOptions,
  productVariantsQueryOptions,
  storeStockQueryOptions,
} from "@/features/products/api";
import { useInventoryStream } from "@/features/products/hooks/use-inventory-stream";
import { EventCart } from "@/features/products/ui/EventCart";
import { ProductCardCompact } from "@/features/products/ui/ProductCardCompact";
import {
  allTicketsQueryOptions,
  myTicketQueryOptions,
} from "@/features/tickets/api";
import { TicketCard } from "@/features/tickets/ui/TicketCard";

export const Route = createFileRoute("/events/$slug/store")({
  validateSearch: (search: Record<string, unknown>) => ({
    tab: search.tab === "products" ? "products" : "tickets",
  }),
  loader: async ({ context, params }) => {
    const event = await context.queryClient.ensureQueryData(
      publicEventBySlugQueryOptions(params.slug),
    );
    if (!event) return null;
    return event;
  },
  component: StorePage,
});

function StorePage() {
  const event = Route.useLoaderData();
  const { tab } = Route.useSearch();
  const navigate = Route.useNavigate();
  const { isAuthenticated } = useAuth();
  const [activeTab, setActiveTab] = useState(tab);

  if (!event)
    return <main className="p-12 text-center">Evento não encontrado.</main>;

  const { data: edition } = useSuspenseQuery(
    activeEditionQueryOptions(event.id),
  );
  useInventoryStream(edition?.id ?? "");
  const { data: tickets = [] } = useSuspenseQuery(
    allTicketsQueryOptions(edition?.id ?? ""),
  );
  const { data: products = [] } = useSuspenseQuery(
    productsByEditionQueryOptions(edition?.id ?? ""),
  );
  const { data: stock = [] } = useSuspenseQuery(
    storeStockQueryOptions(edition?.id ?? ""),
  );
  const stockById = new Map(stock.map((item) => [item.id, item]));
  const variants = useQueries({
    queries: products.map((product) => productVariantsQueryOptions(product.id)),
  });
  const { data: heldTicket = null } = useQuery(
    myTicketQueryOptions(edition?.id ?? "", isAuthenticated),
  );

  if (!edition) {
    return (
      <main className="mx-auto max-w-3xl px-4 py-16 text-center">
        A loja não está disponível no momento.
      </main>
    );
  }

  const setTab = (next: "tickets" | "products") => {
    setActiveTab(next);
    void navigate({ search: { tab: next } });
  };

  return (
    <main className="min-h-screen bg-background px-4 pt-4 pb-24 md:pt-6">
      <div className="mx-auto max-w-6xl">
        <header className="mx-auto max-w-3xl">
          <Link
            to="/events/$slug"
            params={{ slug: event.slug }}
            className="inline-flex items-center gap-2 rounded-lg px-2 py-2 text-sm font-medium text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
          >
            <ArrowLeft className="size-4" /> Evento
          </Link>
          <div className="mt-5 text-center">
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">
              Loja do evento
            </p>
            <h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
              Ingressos e produtos
            </h1>
            <p className="mx-auto mt-3 max-w-xl text-muted-foreground">
              Encontre ingressos e produtos para {event.full_name}.
            </p>
          </div>
        </header>
        <div className="mt-10 flex gap-2 border-b border-border/60">
          {(["tickets", "products"] as const).map((item) => (
            <button
              key={item}
              type="button"
              onClick={() => setTab(item)}
              className={`border-b-2 px-4 py-3 text-sm font-medium ${activeTab === item ? "border-primary text-primary" : "border-transparent text-muted-foreground"}`}
            >
              {item === "tickets" ? "Ingressos" : "Produtos"}
            </button>
          ))}
        </div>
        {activeTab === "tickets" ? (
          tickets.length ? (
            <div className="mt-8 flex flex-wrap gap-6 sm:justify-start! justify-center">
              {tickets.map((ticket) => (
                <TicketCard
                  key={ticket.id}
                  ticket={ticket}
                  editionId={edition.id}
                  heldTicket={heldTicket}
                  stock={stockById.get(ticket.id)?.stock}
                />
              ))}
            </div>
          ) : (
            <p className="mt-8 text-muted-foreground">
              Nenhum ingresso disponível.
            </p>
          )
        ) : products.some(
            (_, index) => (variants[index]?.data ?? []).length > 0,
          ) ? (
          <div className="mt-8 flex flex-wrap gap-6 sm:justify-start! justify-center">
            {products.map((product, index) => {
              const productVariants = variants[index]?.data ?? [];
              return productVariants.length ? (
                <ProductCardCompact
                  key={product.id}
                  product={product}
                  variants={productVariants.map((variant) => {
                    const currentStock = stockById.get(variant.id);
                    return {
                      ...variant,
                      stock: currentStock ? currentStock.stock : variant.stock,
                    };
                  })}
                  editionId={edition.id}
                />
              ) : null;
            })}
          </div>
        ) : (
          <div className="mt-8 rounded-xl border border-dashed p-10 text-center">
            <h2 className="text-lg font-semibold">Nenhum produto disponível</h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Ainda não há produtos publicados para esta edição.
            </p>
            <Link
              to="/events/$slug"
              params={{ slug: event.slug }}
              className="mt-6 inline-flex text-sm font-medium text-primary hover:underline"
            >
              Voltar ao evento
            </Link>
          </div>
        )}
      </div>
      <EventCart
        editionId={edition.id}
        onCheckout={() =>
          navigate({
            to: "/events/$slug/checkout",
            params: { slug: event.slug },
          })
        }
        onExplore={() => setTab("products")}
      />
    </main>
  );
}
