// sdk/ts/identityx-solid/src/solid/components/Modern/Shared/FormError.tsx
export interface FormErrorProps {
  message?: string;
  class?: string;
  id?: string;
}
export function FormError(props: FormErrorProps) {
  return (
    <Show when={props.message}>
      <p
        id={props.id}
        class={`text-[11px] font-medium text-destructive tracking-tight leading-none px-1 mt-1.5 ${props.class ?? ""}`}
      >
        {props.message}
      </p>
    </Show>
  );
}
import { Show } from "solid-js";

// Univents-UI/src/shared/ui/form/FormError.tsx
import { motion, AnimatePresence } from "motion/react";
import { cn } from "@/shared/lib/utils";

interface PropsI {
  message?: string;
  className?: string;
}

const FormError = ({ message, className }: PropsI) => {
  return (
    <AnimatePresence>
      {message && (
        <motion.p
          initial={{ opacity: 0, height: 0, marginTop: 0 }}
          animate={{ opacity: 1, height: "auto", marginTop: 6 }}
          exit={{ opacity: 0, height: 0, marginTop: 0 }}
          transition={{ duration: 0.2, ease: "easeOut" }}
          className={cn(
            "text-[11px] font-medium text-destructive tracking-tight leading-none px-1 overflow-hidden",
            className
          )}
        >
          {message}
        </motion.p>
      )}
    </AnimatePresence>
  );
};

export default FormError;
