// front/univents-solid/src/features/calendar/ui/DraggableEvent.tsx
import type { JSX } from "@solidjs/web";
import { Show, createEffect, createSignal, onCleanup } from "solid-js";

import PencilIcon from "~icons/lucide/pencil";
import Trash2Icon from "~icons/lucide/trash-2";

import { formatTimeRange, getDurationMinutes } from "../lib/date";
import {
  endCalendarDrag,
  shouldIgnoreClick,
  startCalendarDrag,
} from "../lib/drag-state";
import type { EventColor, OccurrenceI, ProgramI } from "../model";

const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const Trash2 = Trash2Icon as unknown as (props: { class?: string }) => JSX.Element;

export interface DraggableEventProps {
  occurrence: OccurrenceI;
  program: ProgramI | undefined;
  color: EventColor;
  onClick: (occurrence: OccurrenceI) => void;
  onDelete?: (occurrenceId: string) => void;
  overlapIndex?: number;
  overlapCount?: number;
  isContinuation?: boolean;
  continuesNextDay?: boolean;
}

export function DraggableEvent(props: DraggableEventProps): JSX.Element {
  const [menuOpen, setMenuOpen] = createSignal(false);
  let menuRef: HTMLDivElement | null = null;

  const overlapIndex = () => props.overlapIndex ?? 0;
  const overlapCount = () => props.overlapCount ?? 1;

  const start = () => new Date(props.occurrence.starts_at);
  const startMins = () => start().getHours() * 60 + start().getMinutes();
  const durMins = () =>
    Math.max(
      15,
      getDurationMinutes(props.occurrence.starts_at, props.occurrence.ends_at),
    );

  // Absolute positioning in the 1440px day timeline (1 min = 1px)
  const top = () => startMins();
  const height = () =>
    Math.min(
      Math.max(22, durMins() - 2),
      24 * 60 - startMins(),
    );

  createEffect(
    () => menuOpen(),
    (open) => {
      if (!open) return;

      const handleClickOutside = (e: MouseEvent) => {
        if (menuRef && !menuRef.contains(e.target as Node)) {
          setMenuOpen(false);
        }
      };

      document.addEventListener("mousedown", handleClickOutside);
      onCleanup(() => {
        document.removeEventListener("mousedown", handleClickOutside);
      });
    },
  );

  return (
    <div
      draggable="true"
      onDragStart={(e) => {
        e.stopPropagation();
        startCalendarDrag(e, {
          type: "occurrence",
          occurrenceId: props.occurrence.id,
        });
      }}
      onDragEnd={() => {
        endCalendarDrag();
      }}
      class={`group absolute cursor-grab active:cursor-grabbing transition-shadow ${
        menuOpen() ? "z-30 overflow-visible" : "z-10 overflow-hidden"
      } ${
        props.isContinuation && props.continuesNextDay
          ? "rounded-none border-t-0 border-b-0"
          : props.isContinuation
          ? "rounded-b-md rounded-t-none border-t-0"
          : props.continuesNextDay
          ? "rounded-t-md rounded-b-none border-b-0"
          : "rounded-md"
      } hover:z-25 hover:shadow-md select-none flex flex-col justify-between`}
      style={{
        top: `${top()}px`,
        height: `${height()}px`,
        left: `calc(${(overlapIndex() * 100) / overlapCount()}% + 2px)`,
        width: `calc(${100 / overlapCount()}% - 4px)`,
        background: props.color.bg,
        "border-left": `3px solid ${props.color.border}`,
        color: props.color.text,
        padding: "2px 6px",
      }}
      onClick={(e) => {
        if (!shouldIgnoreClick()) {
          e.stopPropagation();
          props.onClick(props.occurrence);
        }
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        e.stopPropagation();
        setMenuOpen(true);
      }}
    >
      {/* Context Menu on right click */}
      <Show when={menuOpen()}>
        <div
          ref={(el) => (menuRef = el)}
          class="absolute right-1 top-1 z-50 min-w-28 rounded-lg border border-border bg-popover p-1 text-popover-foreground shadow-xl animate-in fade-in-50 zoom-in-95 pointer-events-auto"
          onPointerDown={(e) => e.stopPropagation()}
          onClick={(e) => e.stopPropagation()}
        >
          <button
            type="button"
            class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs hover:bg-accent cursor-pointer transition-colors"
            onClick={(e) => {
              e.stopPropagation();
              setMenuOpen(false);
              props.onClick(props.occurrence);
            }}
          >
            <Pencil class="size-3" />
            Alterar
          </button>
          <Show when={props.onDelete}>
            <button
              type="button"
              class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
              onClick={(e) => {
                e.stopPropagation();
                setMenuOpen(false);
                props.onDelete?.(props.occurrence.id);
              }}
            >
              <Trash2 class="size-3" />
              Excluir
            </button>
          </Show>
        </div>
      </Show>

      {/* Continuation indicator from previous day */}
      <Show when={props.isContinuation}>
        <div class="text-[9px] font-mono opacity-80 leading-none py-0.5 truncate text-primary font-bold">
          ↑ Continuação
        </div>
      </Show>

      {/* Card contents */}
      <div class="min-w-0 flex-1">
        <div class="text-[11px] font-semibold whitespace-nowrap overflow-hidden text-ellipsis leading-tight">
          {props.program?.name || "Atividade"}
        </div>
        <div class="text-[10px] opacity-80 whitespace-nowrap overflow-hidden text-ellipsis leading-tight">
          {formatTimeRange(props.occurrence.starts_at, props.occurrence.ends_at)}
        </div>
        <Show when={props.occurrence.max_capacity != null}>
          <div class="text-[10px] opacity-70 mt-px truncate">
            Cap: {props.occurrence.max_capacity}
          </div>
        </Show>
      </div>

      {/* Continuation indicator to next day */}
      <Show when={props.continuesNextDay}>
        <div class="text-[9px] font-mono opacity-80 leading-none py-0.5 truncate text-primary font-bold">
          Continua no dia seguinte ↓
        </div>
      </Show>
    </div>
  );
}

// front/univents/src/features/calendar/ui/DraggableEvent.tsx
import { useDraggable } from "@dnd-kit/core";
import { Pencil, Trash2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { formatTimeRange, getDurationMinutes } from "../lib/date";
import type { EventColor, OccurrenceI, ProgramI } from "../model";

interface DraggableEventProps {
  occurrence: OccurrenceI;
  program: ProgramI | undefined;
  color: EventColor;
  onClick: (occurrenceId: string) => void;
  onDelete?: (occurrenceId: string) => void;
  overlapIndex?: number;
  overlapCount?: number;
}

export function DraggableEvent({
  occurrence,
  program,
  color,
  onClick,
  onDelete,
  overlapIndex = 0,
  overlapCount = 1,
}: DraggableEventProps) {
  const [menuOpen, setMenuOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!menuOpen) return;
    const close = (event: MouseEvent) => {
      if (!menuRef.current?.contains(event.target as Node)) setMenuOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [menuOpen]);
  const { attributes, listeners, setNodeRef, transform, isDragging } =
    useDraggable({
      id: `event-${occurrence.id}`,
      data: { type: "occurrence", occurrenceId: occurrence.id },
    });

  const start = new Date(occurrence.starts_at);
  const startMins = start.getHours() * 60 + start.getMinutes();
  const durMins = getDurationMinutes(occurrence.starts_at, occurrence.ends_at);
  const top = startMins % 60;
  const height = Math.min(
    Math.max(22, (durMins / 60) * 60 - 2),
    24 * 60 - startMins,
  );

  const sourceAbsoluteTop = Math.floor(startMins / 60) * 60 + top;
  const maxTranslateY = 24 * 60 - sourceAbsoluteTop - height;
  const clampedY = transform
    ? Math.max(-top, Math.min(transform.y, maxTranslateY))
    : 0;
  const style = transform
    ? {
        transform: `translate3d(${transform.x}px, ${clampedY}px, 0)`,
        zIndex: 100,
      }
    : {};

  return (
    <div
      ref={setNodeRef}
      {...listeners}
      {...attributes}
      className={`group absolute rounded-md cursor-grab ${menuOpen ? "z-9999 overflow-visible" : "z-5 overflow-hidden"} hover:z-10 hover:shadow-lg transition-shadow`}
      style={{
        top: `${top}px`,
        height: `${height}px`,
        left: `calc(${(overlapIndex * 100) / overlapCount}% + 2px)`,
        width: `calc(${100 / overlapCount}% - 4px)`,
        background: color.bg,
        borderLeft: `3px solid ${color.border}`,
        color: color.text,
        padding: "2px 6px",
        opacity: isDragging ? 0 : 1,
        ...style,
      }}
      onClick={(e) => {
        if (!isDragging) {
          e.stopPropagation();
          onClick(occurrence.id);
        }
      }}
      onContextMenu={(e) => {
        e.preventDefault();
        e.stopPropagation();
        setMenuOpen(true);
      }}
    >
      {menuOpen && (
        <div
          ref={menuRef}
          className="absolute right-1 top-1 z-30 min-w-28 rounded-lg border border-border bg-popover p-1 text-popover-foreground shadow-xl"
          onPointerDown={(e) => e.stopPropagation()}
        >
          <button
            type="button"
            className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs hover:bg-accent"
            onClick={(e) => {
              e.stopPropagation();
              setMenuOpen(false);
              onClick(occurrence.id);
            }}
          >
            <Pencil className="size-3" />
            Alterar
          </button>
          <button
            type="button"
            className="flex w-full items-center gap-2 rounded px-2 py-1.5 text-left text-xs text-destructive hover:bg-destructive/10"
            onClick={(e) => {
              e.stopPropagation();
              setMenuOpen(false);
              onDelete?.(occurrence.id);
            }}
          >
            <Trash2 className="size-3" />
            Excluir
          </button>
        </div>
      )}
      <div className="text-[11px] font-semibold whitespace-nowrap overflow-hidden text-ellipsis leading-tight">
        {program?.name || "Evento"}
      </div>
      <div className="text-[10px] opacity-80 whitespace-nowrap overflow-hidden text-ellipsis leading-tight">
        {formatTimeRange(occurrence.starts_at, occurrence.ends_at)}
      </div>
      {occurrence.max_capacity && (
        <div className="text-[10px] opacity-65 mt-px">
          Cap: {occurrence.max_capacity}
        </div>
      )}
    </div>
  );
}
