// lib/ts/front-core-react/src/providers/posthog.tsx
import { useAuth } from "@trieoh/identityx-sdk-ts-react"
import posthog from "posthog-js"
import { PostHogProvider as BasePostHogProvider } from "posthog-js/react"
import { useEffect, type ReactNode } from "react"

export interface PostHogConfig {
  key: string
  host?: string
  /**
   * Pageview capture. Defaults to `"history_change"` - the SDK's own default
   */
  capturePageview?: boolean | "history_change"
  personProfiles?: "identified_only" | "always" | "never"
}

/**
 * Initialize and provide PostHog analytics.
 *
 * Usage:
 *   <PostHogProvider config={{ key: env.VITE_POSTHOG_KEY, host: env.VITE_POSTHOG_HOST }}>
 *     {children}
 *   </PostHogProvider>
 */
export function PostHogProvider({
  config,
  children,
}: {
  config: PostHogConfig
  children: ReactNode
}) {
  useEffect(() => {
    if (
      typeof window === "undefined" ||
      !config.key ||
      config.key === "phc_xxx" ||
      posthog.__loaded
    )
      return

    posthog.init(config.key, {
      api_host: config.host || "https://us.i.posthog.com",
      person_profiles: config.personProfiles ?? "identified_only",
      capture_pageview: config.capturePageview ?? "history_change",
      defaults: "2026-05-30",
    })
  }, [config.capturePageview, config.host, config.key, config.personProfiles])

  return <BasePostHogProvider client={posthog}>{children}</BasePostHogProvider>
}

export function AuthenticatedPostHogProvider({
  config,
  children,
}: {
  config: PostHogConfig
  children: ReactNode
}) {
  const { auth, isAuthenticated } = useAuth()
  const subject = isAuthenticated ? auth.profile() : null

  useEffect(() => {
    if (!posthog.__loaded) return

    if (subject?.id) {
      // The IdentityX subject has no display name - that lives in the actor's
      // profile document, so an app that loads it can follow up with
      // `posthog.people.set({ name })`.
      posthog.identify(subject.id, subject.email ? { email: subject.email } : undefined)
    } else if (posthog.get_property("$user_id")) {
      posthog.reset()
    }
  }, [subject?.id, subject?.email])

  return <PostHogProvider config={config}>{children}</PostHogProvider>
}

// lib/ts/front-core-solid/src/providers/posthog.tsx
import { useAuth } from "@trieoh/identityx-sdk-ts-solid"
import posthog from "posthog-js"
import { createEffect, onSettled, type ParentProps } from "solid-js"

export interface PostHogConfig {
  key: string
  host?: string
  /**
   * Pageview capture. Defaults to `"history_change"` - the SDK's own default
   */
  capturePageview?: boolean | "history_change"
  personProfiles?: "identified_only" | "always" | "never"
}

/**
 * Boot PostHog analytics.
 * Usage:
 *   <PostHogProvider config={{ key: import.meta.env.VITE_POSTHOG_KEY, host: import.meta.env.VITE_POSTHOG_HOST }}>
 *     {children}
 *   </PostHogProvider>
 */
export function PostHogProvider(props: ParentProps<{ config: PostHogConfig }>) {
  onSettled(() => initPostHog(props.config))

  return props.children
}

/**
 * {@link PostHogProvider} plus person identification: the IdentityX subject is
 * the distinct id, and its email travels with it as a person property.
 *
 * The subject carries no display name (id, email, project, capabilities and
 * free-form metadata only) — the name lives in the actor's profile document, so
 * an app that loads it can enrich the person afterwards with
 * `posthog.people.set({ name })`.
 */
export function AuthenticatedPostHogProvider(
  props: ParentProps<{ config: PostHogConfig }>,
) {
  onSettled(() => initPostHog(props.config))

  const { auth, isAuthenticated } = useAuth()

  createEffect(
    () => {
      const subject = isAuthenticated() ? auth.profile() : null
      return [subject?.id, subject?.email] as const
    },
    ([id, email]) => {
      if (!posthog.__loaded) return

      if (id) posthog.identify(id, email ? { email } : undefined)
      else if (posthog.get_property("$user_id")) posthog.reset()
    },
  )

  return props.children
}

function initPostHog(config: PostHogConfig) {
  // SSR renders the provider too, and a placeholder key means "not configured"
  if (
    typeof window === "undefined" ||
    !config.key ||
    config.key === "phc_xxx" ||
    posthog.__loaded
  ) {
    return
  }

  posthog.init(config.key, {
    api_host: config.host || "https://us.i.posthog.com",
    person_profiles: config.personProfiles ?? "identified_only",
    capture_pageview: config.capturePageview ?? "history_change",
    defaults: "2026-05-30",
  })
}
