// lib/ts/front-core/src/providers/tanstack-query.tsx
import {
  QueryClient,
  QueryClientProvider,
} from "@tanstack/react-query"
import { ApiError } from "@trieoh/identityx-sdk-ts"
import type { ReactNode } from "react"

export interface QueryClientConfig {
  /** Stale time in milliseconds (default: 5 minutes). */
  staleTime?: number
  /** Maximum retry count (default: 3). */
  maxRetries?: number
}

export class QueryError extends Error {
  readonly envelope: { code?: number; message: string };

  constructor(message: string, code?: number) {
    super(message);
    this.name = "QueryError";
    this.envelope = { message, code };
  }
}

function getErrorStatus(error: unknown): number | undefined {
  if (typeof error !== "object" || error === null) return undefined;

  if (error instanceof ApiError || error instanceof QueryError) {
    return error.envelope.code;
  }

  const candidate = error as {
    status?: unknown;
    response?: { status?: unknown };
  };
  const status = [
    candidate.status,
    candidate.response?.status,
  ].find((value): value is number => typeof value === "number");

  return status;
}

export function queryError(message: string, code?: number): QueryError {
  return new QueryError(message, code);
}

/**
 * Create a new QueryClient with standard TrieOH defaults.
 * The consumer should create this and pass to TanStackQueryProvider
 * to avoid version-mismatch issues with private fields.
 */
export function createQueryClient(config?: QueryClientConfig) {
  const {
    staleTime = 1000 * 60 * 5, // 5 minutes
    maxRetries = 3,
  } = config ?? {}

  return new QueryClient({
    defaultOptions: {
      queries: {
        retry: (failureCount, error) => {
          const status = getErrorStatus(error)
          if (status && status >= 400 && status < 500) return false
          return failureCount < maxRetries
        },
        staleTime,
        refetchOnMount: true,
        refetchOnWindowFocus: true,
        refetchOnReconnect: true,
      },
    },
  })
}

/**
 * TanStack Query provider.
 * Accepts a `queryClient` created by the consumer (avoids version-mismatch).
 *
 * Usage:
 *   const queryClient = createQueryClient()
 *   <TanStackQueryProvider queryClient={queryClient}>
 *     {children}
 *   </TanStackQueryProvider>
 */
export function TanStackQueryProvider({
  children,
  queryClient,
}: {
  children: ReactNode
  queryClient: QueryClient
}) {
  return (
    <QueryClientProvider client={queryClient}>{children}</QueryClientProvider>
  )
}

// lib/ts/front-core-solid/src/providers/tanstack-query.tsx
import { QueryClient } from "@tanstack/query-core"
import { createComponent, createContext, useContext, type ParentProps } from "solid-js"

const QueryClientContext = createContext<QueryClient>()

export { QueryClient }

export interface QueryClientConfig {
  staleTime?: number
  maxRetries?: number
  onError?: (error: unknown) => void
}

export class QueryError extends Error {
  readonly envelope: { code?: number; message: string }

  constructor(message: string, code?: number) {
    super(message)
    this.name = "QueryError"
    this.envelope = { message, code }
  }
}

export function queryError(message: string, code?: number) {
  return new QueryError(message, code)
}

export function createQueryClient(config?: QueryClientConfig) {
  return new QueryClient({
    defaultOptions: {
      queries: {
        staleTime: config?.staleTime ?? 1000 * 60 * 5,
        retry: config?.maxRetries ?? 3,
      },
      mutations: { onError: config?.onError },
    },
  })
}

export function TanStackQueryProvider(props: {
  client: QueryClient
  children: ParentProps["children"]
}) {
  return createComponent(QueryClientContext, {
    value: props.client,
    get children() {
      return props.children
    },
  })
}

export function useQueryClient() {
  const client = useContext(QueryClientContext)
  if (!client) throw new Error("useQueryClient must be used inside <TanStackQueryProvider>")
  return client
}
