// front/univents-solid/src/features/products/ui/AdminProductCard.tsx
import type { JSX } from "@solidjs/web";
import { Show } from "solid-js";

import CalendarIcon from "~icons/lucide/calendar";
import LayersIcon from "~icons/lucide/layers";
import PackageIcon from "~icons/lucide/package";
import PencilIcon from "~icons/lucide/pencil";
import ShieldCheckIcon from "~icons/lucide/shield-check";
import TrashIcon from "~icons/lucide/trash";

import { Button, cn } from "@trieoh/ui-solid";
import { Reveal } from "@/shared/ui/Reveal";
import type { ProductI, VariantI } from "../model";

const Calendar = CalendarIcon as unknown as (props: { class?: string }) => JSX.Element;
const Layers = LayersIcon as unknown as (props: { class?: string }) => JSX.Element;
const Package = PackageIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const ShieldCheck = ShieldCheckIcon as unknown as (props: { class?: string }) => JSX.Element;
const Trash = TrashIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminProductCardProps {
  product: ProductI;
  variants?: VariantI[];
  coverImage?: string | null;
  index?: number;
  animate?: boolean;
  onEdit: (product: ProductI) => void;
  onDelete: (product: ProductI) => void;
  onManageVariants: (product: ProductI) => void;
}

function formatDate(iso: string): string {
  try {
    return new Intl.DateTimeFormat("pt-BR", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }).format(new Date(iso));
  } catch {
    return "";
  }
}

export function AdminProductCard(props: AdminProductCardProps): JSX.Element {
  const isDeleted = () => props.product.deleted_at !== null;

  const firstImage = () => {
    if (props.coverImage) return props.coverImage;
    if (props.variants) {
      for (const v of props.variants) {
        if (v.gallery_urls && v.gallery_urls.length > 0 && v.gallery_urls[0]) {
          return v.gallery_urls[0];
        }
      }
    }
    return null;
  };

  const variantsCount = () => props.variants?.length;

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div
        role="region"
        aria-label={`Produto ${props.product.vendor_code}`}
        class={cn(
          "group relative flex h-full w-full min-w-0 flex-col justify-between overflow-hidden rounded-xl border border-border border-t-[3px] border-t-primary bg-card bg-linear-to-b from-primary/[0.04] via-card to-card p-4 text-left shadow-xs transition-all duration-200",
          "hover:-translate-y-0.5 hover:border-foreground/20 hover:border-t-primary hover:shadow-md",
          "focus-within:ring-2 focus-within:ring-ring",
          isDeleted() && "opacity-60 grayscale",
        )}
      >
        <div class="space-y-3">
          {/* Header with thumbnail, code, badges and actions */}
          <div class="flex items-start justify-between gap-3">
            <div class="flex items-center gap-2.5 min-w-0 flex-1">
              <div class="relative flex size-11 shrink-0 items-center justify-center overflow-hidden rounded-lg border border-border/70 bg-muted/60 transition-transform group-hover:scale-105">
                <Show
                  when={firstImage()}
                  fallback={
                    <div class="flex size-full items-center justify-center bg-primary/10 text-primary">
                      <Package class="size-5" />
                    </div>
                  }
                >
                  {(url) => (
                    <img
                      src={url()}
                      alt={props.product.vendor_code}
                      class="size-full object-cover"
                    />
                  )}
                </Show>
              </div>

              <div class="min-w-0 flex-1">
                <h3
                  class="truncate text-sm font-bold font-mono tracking-tight text-foreground transition-colors group-hover:text-primary"
                  title={props.product.vendor_code}
                >
                  {props.product.vendor_code}
                </h3>
                <div class="mt-0.5 flex flex-wrap items-center gap-1.5">
                  <Show
                    when={props.product.requires_registration}
                    fallback={
                      <span class="inline-flex items-center text-[10px] font-medium text-muted-foreground">
                        Livre
                      </span>
                    }
                  >
                    <span class="inline-flex items-center gap-1 text-[10px] font-medium text-primary">
                      <ShieldCheck class="size-3 shrink-0" />
                      Exige cadastro
                    </span>
                  </Show>

                  <Show when={variantsCount() != null && variantsCount()! > 0}>
                    <span class="text-[10px] text-muted-foreground/60">•</span>
                    <span class="inline-flex items-center gap-1 text-[10px] font-medium text-muted-foreground">
                      <Layers class="size-2.5" />
                      {variantsCount()} {variantsCount() === 1 ? "variação" : "variações"}
                    </span>
                  </Show>
                </div>
              </div>
            </div>

            {/* Actions */}
            <div class="flex items-center gap-0.5 shrink-0">
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Editar ${props.product.vendor_code}`}
                title="Editar produto"
                onClick={() => props.onEdit(props.product)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-muted hover:text-foreground group-hover:opacity-100 cursor-pointer"
              >
                <Pencil class="size-3.5" />
              </Button>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                aria-label={`Excluir ${props.product.vendor_code}`}
                title="Excluir produto"
                onClick={() => props.onDelete(props.product)}
                class="size-7 text-muted-foreground opacity-60 transition-opacity hover:bg-destructive/15 hover:text-destructive group-hover:opacity-100 cursor-pointer"
              >
                <Trash class="size-3.5" />
              </Button>
            </div>
          </div>

          <div class="flex items-center justify-between text-[11px] text-muted-foreground min-h-[1.25rem]">
            <span class="inline-flex items-center gap-1.5">
              <Calendar class="size-3 shrink-0 opacity-70" />
              <span>Criado em {formatDate(props.product.created_at)}</span>
            </span>
          </div>
        </div>

        {/* Footer: Manage Variants button */}
        <div class="mt-3 border-t border-border/60 pt-2.5">
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => props.onManageVariants(props.product)}
            class="w-full gap-1.5 text-xs font-medium cursor-pointer hover:bg-accent hover:text-accent-foreground"
          >
            <Layers class="size-3.5 text-muted-foreground" />
            Gerenciar variações
          </Button>
        </div>
      </div>
    </Reveal>
  );
}

// Univents-UI/src/features/products/ui/AdminProductCard.tsx
import { motion } from 'motion/react'
import { MoreVertical, Tag, Eye, EyeOff, Trash2, Pencil, Package, Calendar, Info } from 'lucide-react'
import type { ProductI } from '@/features/products/model'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/shared/ui/shadcn/dropdown-menu'
import { cn } from '@/shared/lib/utils'
import { StatusBadge } from '@/shared/ui'
import { formatDateRange } from '@/shared/lib/date'

interface AdminProductCardProps {
  product: ProductI
  index: number
  onEdit: (product: ProductI) => void
  onPublish: (product: ProductI) => void
  onSoftDelete: (product: ProductI) => void
  onRestore: (product: ProductI) => void
}

const typeLabels: Record<string, string> = {
  merchandise: 'Mercadoria',
  ticket: 'Ingresso',
  token: 'Token',
  bundle: 'Pacote',
}

export function AdminProductCard({
  product,
  index,
  onEdit,
  onPublish,
  onSoftDelete,
  onRestore,
}: AdminProductCardProps) {
  const handleAction = (type: 'edit' | 'publish' | 'delete' | 'restore') => {
    if (type === 'edit') onEdit(product)
    if (type === 'publish') onPublish(product)
    if (type === 'delete') onSoftDelete(product)
    if (type === 'restore') onRestore(product)
  }

  const isPublished = product.status === 'available'
  const isDeleted = product.deleted_at !== null

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.05 }}
      className={cn(
        'group relative flex flex-col bg-card border border-border rounded-xl overflow-hidden transition-all duration-200',
        'hover:border-primary/20 hover:shadow-sm',
        isDeleted && 'opacity-60 grayscale'
      )}
    >
      <div className="flex flex-col sm:flex-row gap-4 p-4">
        {/* Thumbnail */}
        <div className="w-full sm:w-24 h-40 sm:h-24 rounded-lg bg-muted shrink-0 overflow-hidden border border-border/50 flex items-center justify-center">
          {product.thumbnail_url ? (
            <img src={product.thumbnail_url} alt="" className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
          ) : (
            <Tag className="w-8 h-8 text-muted-foreground/30" />
          )}
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0 space-y-2">
          <div className="flex items-start justify-between gap-2">
            <div className="space-y-1 min-w-0">
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-base font-semibold text-foreground truncate">{product.name}</h3>
                <StatusBadge status={product.status === 'available' ? 'published' : product.status} />
              </div>
              <p className="text-sm text-muted-foreground line-clamp-1">{product.description}</p>
            </div>

            <div className="shrink-0">
              <DropdownMenu>
                <DropdownMenuTrigger
                  render={
                    <button className="flex items-center justify-center w-8 h-8 rounded-lg hover:bg-muted transition-colors">
                      <MoreVertical className="w-4 h-4 text-muted-foreground" />
                    </button>
                  }
                />
                <DropdownMenuContent align="end" className="w-48">
                  <DropdownMenuItem onClick={() => { handleAction('edit'); }}>
                    <Pencil className="mr-2 h-4 w-4" />
                    <span>Editar</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => { handleAction('publish'); }} disabled={isPublished}>
                    <Eye className="mr-2 h-4 w-4" />
                    <span>Publicar</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => { handleAction('delete'); }} disabled={isDeleted}>
                    <Trash2 className="mr-2 h-4 w-4" />
                    <span>Excluir</span>
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={() => { handleAction('restore'); }} disabled={!isDeleted}>
                    <EyeOff className="mr-2 h-4 w-4" />
                    <span>Restaurar</span>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3">
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Package className="w-3.5 h-3.5" />
              <span className="bg-muted px-1.5 py-0.5 rounded font-medium">{typeLabels[product.type] || product.type}</span>
            </div>

            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Info className="w-3.5 h-3.5" />
              <span className="font-semibold text-foreground">R$ {(product.price_cents / 100).toFixed(2)}</span>
            </div>

            {product.has_inventory && (
              <div className="flex items-center gap-1.5 text-xs text-muted-foreground col-span-2 sm:col-span-1">
                <Package className="w-3.5 h-3.5 text-primary/60" />
                <span className={cn(
                  "font-medium px-1.5 py-0.5 rounded",
                  product.inventory_remaining === 0 ? "bg-destructive/10 text-destructive" : "bg-primary/10 text-primary"
                )}>
                  {product.inventory_remaining} / {product.inventory_quantity}
                </span>
              </div>
            )}
          </div>

          {(product.available_from ?? product.available_until) && (
            <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
              <Calendar className="w-3.5 h-3.5 opacity-60" />
              <span>
                {product.available_from && product.available_until
                  ? formatDateRange(product.available_from, product.available_until)
                  : product.available_from
                    ? `Desde ${new Date(product.available_from).toLocaleDateString('pt-BR')}`
                    : product.available_until
                      ? `Até ${new Date(product.available_until).toLocaleDateString('pt-BR')}`
                      : null}
              </span>
            </div>
          )}
        </div>
      </div>
    </motion.div>
  )
}
