// front/univents/src/shared/ui/shadcn/accordion.tsx
import { Accordion as AccordionPrimitive } from "@base-ui/react/accordion";
import { ChevronDownIcon, ChevronUpIcon } from "lucide-react";
import { cn } from "@/shared/lib/utils";

function Accordion({ className, ...props }: AccordionPrimitive.Root.Props) {
  return (
    <AccordionPrimitive.Root
      data-slot="accordion"
      className={cn("flex w-full flex-col", className)}
      {...props}
    />
  );
}

function AccordionItem({ className, ...props }: AccordionPrimitive.Item.Props) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn("not-last:border-b", className)}
      {...props}
    />
  );
}

function AccordionTrigger({
  className,
  children,
  ...props
}: AccordionPrimitive.Trigger.Props) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          "group/accordion-trigger relative flex flex-1 items-start justify-between rounded-md border border-transparent py-4 text-left text-sm font-medium transition-all outline-none hover:underline focus:border-transparent focus:ring-0 focus-visible:border-transparent focus-visible:ring-0 focus-visible:after:border-transparent aria-disabled:pointer-events-none aria-disabled:opacity-50 **:data-[slot=accordion-trigger-icon]:ml-auto **:data-[slot=accordion-trigger-icon]:size-4 **:data-[slot=accordion-trigger-icon]:text-muted-foreground",
          className,
        )}
        {...props}
      >
        {children}
        <ChevronDownIcon
          data-slot="accordion-trigger-icon"
          className="pointer-events-none shrink-0 group-aria-expanded/accordion-trigger:hidden"
        />
        <ChevronUpIcon
          data-slot="accordion-trigger-icon"
          className="pointer-events-none hidden shrink-0 group-aria-expanded/accordion-trigger:inline"
        />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

function AccordionContent({
  className,
  children,
  ...props
}: AccordionPrimitive.Panel.Props) {
  return (
    <AccordionPrimitive.Panel
      data-slot="accordion-content"
      className="overflow-hidden text-sm data-open:animate-accordion-down data-closed:animate-accordion-up"
      {...props}
    >
      <div
        className={cn(
          "h-(--accordion-panel-height) pt-0 pb-4 data-ending-style:h-0 data-starting-style:h-0 [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground [&_p:not(:last-child)]:mb-4",
          className,
        )}
      >
        {children}
      </div>
    </AccordionPrimitive.Panel>
  );
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };

// front/univents-solid/src/shared/ui/Accordion.tsx
import { For, createSignal } from "solid-js";
import type { JSX } from "@solidjs/web";
import PlusIcon from "~icons/lucide/plus";

const Plus = PlusIcon as unknown as () => JSX.Element;

export interface AccordionItem {
  value: string;
  title: string;
  content: string;
}

export function Accordion(props: { items: AccordionItem[] }) {
  const [open, setOpen] = createSignal<string>();

  return (
    <div>
      <For each={props.items}>
        {(item) => {
          const isOpen = () => open() === item.value;
          return (
            <div class="border-b border-border last:border-b-0">
              <button
                type="button"
                aria-expanded={isOpen() ? "true" : "false"}
                class="flex w-full items-center justify-between py-4 text-left text-sm font-medium"
                onClick={() => setOpen(isOpen() ? undefined : item.value)}
              >
                {item.title}
                <span
                  class={`transition-transform duration-200 ${isOpen() ? "rotate-45" : ""}`}
                >
                  <Plus />
                </span>
              </button>
              <div
                class={`grid transition-[grid-template-rows,opacity] duration-250 ease-out ${isOpen() ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}
              >
                <div class="min-h-0 overflow-hidden">
                  <p class="pb-4 text-sm text-muted-foreground">
                    {item.content}
                  </p>
                </div>
              </div>
            </div>
          );
        }}
      </For>
    </div>
  );
}
