// IdentityX-UI/src/shared/ui/shadcn/accordion.tsx
import type * as React from "react"
import { ChevronDownIcon } from "lucide-react"
import { Accordion as AccordionPrimitive } from "radix-ui"

import { cn } from "@/shared/lib/utils"

function Accordion({
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Root>) {
  return <AccordionPrimitive.Root data-slot="accordion" {...props} />
}

function AccordionItem({
  className,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Item>) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn("border-b last:border-b-0", className)}
      {...props}
    />
  )
}

function AccordionTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Trigger>) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          "flex flex-1 items-start justify-between gap-4 rounded-md py-4 text-left text-sm font-medium transition-all outline-none hover:underline focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 [&[data-state=open]>svg]:rotate-180",
          className
        )}
        {...props}
      >
        {children}
        <ChevronDownIcon className="pointer-events-none size-4 shrink-0 translate-y-0.5 text-muted-foreground transition-transform duration-200" />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  )
}

function AccordionContent({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Content>) {
  return (
    <AccordionPrimitive.Content
      data-slot="accordion-content"
      className="overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
      {...props}
    >
      <div className={cn("pt-0 pb-4", className)}>{children}</div>
    </AccordionPrimitive.Content>
  )
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent }

// front/univents-solid/src/shared/ui/Accordion.tsx
import { For, createSignal } from "solid-js";
import type { JSX } from "@solidjs/web";
import PlusIcon from "~icons/lucide/plus";

const Plus = PlusIcon as unknown as () => JSX.Element;

export interface AccordionItem {
  value: string;
  title: JSX.Element;
  content: JSX.Element;
}

export function Accordion(props: {
  items: AccordionItem[];
  defaultValue?: string;
  multiple?: boolean;
}) {
  const [open, setOpen] = createSignal<string[]>(
    props.defaultValue ? [props.defaultValue] : [],
  );

  const isOpen = (value: string) =>
    open().includes(value);

  const toggle = (value: string) => {
    setOpen((current) => {
      if (props.multiple) {
        return current.includes(value)
          ? current.filter((item) => item !== value)
          : [...current, value];
      }

      return current.includes(value) ? [] : [value];
    });
  };

  return (
    <div>
      <For each={props.items}>
        {(item) => (
          <div class="border-b border-border last:border-b-0">
            <button
              type="button"
              aria-expanded={
                isOpen(item.value) ? "true" : "false"
              }
              class="flex w-full items-center justify-between gap-3 py-4 text-left text-sm font-medium"
              onClick={() => toggle(item.value)}
            >
              <span class="min-w-0 flex-1">
                {item.title}
              </span>

              <span
                class={`flex shrink-0 items-center justify-center transition-transform duration-200 [&>svg]:size-4 ${isOpen(item.value)
                    ? "rotate-45"
                    : ""
                  }`}
              >
                <Plus />
              </span>
            </button>

            <div
              class={`grid transition-[grid-template-rows,opacity] duration-250 ease-out ${isOpen(item.value)
                  ? "grid-rows-[1fr] opacity-100"
                  : "grid-rows-[0fr] opacity-0"
                }`}
            >
              <div class="min-h-0 overflow-hidden">
                <div class="pb-4">
                  {item.content}
                </div>
              </div>
            </div>
          </div>
        )}
      </For>
    </div>
  );
}
