// front/univents-solid/src/features/events/ui/AdminEventCard.tsx
import type { JSX } from "@solidjs/web";
import { Link } from "@tanstack/solid-router";
import { Show } from "solid-js";

import MailIcon from "~icons/lucide/mail";
import PencilIcon from "~icons/lucide/pencil";

import { Button, cn } from "@trieoh/ui-solid";

import { Reveal } from "@/shared/ui/Reveal";

import type { EventI } from "../model";

const Mail = MailIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as () => JSX.Element;

const STATUS_CONFIG: Record<EventI["status"], { label: string; dot: string }> = {
  draft: { label: "Rascunho", dot: "bg-amber-500" },
  active: { label: "Ativo", dot: "bg-emerald-500" },
  discontinued: { label: "Descontinuado", dot: "bg-rose-500" },
};

export interface AdminEventCardProps {
  event: EventI;
  index?: number;
  onEdit: (event: EventI) => void;
  /** Forwarded to `Reveal`; false when the row appeared because of a resize. */
  animate?: boolean;
}

export function AdminEventCard(props: AdminEventCardProps): JSX.Element {
  const status = () => STATUS_CONFIG[props.event.status];

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate}>
      <div class="group relative flex w-full min-w-0 items-center gap-3 rounded-xl bg-card p-3 ring-1 ring-border transition-colors hover:ring-foreground/25">
        <div class="relative size-10 shrink-0">
          <div class="flex size-10 items-center justify-center overflow-hidden rounded-lg bg-muted">
            <Show
              when={props.event.logo_url ?? props.event.banner_url}
              fallback={
                <span class="text-sm font-semibold text-muted-foreground/50">
                  {props.event.acronym?.charAt(0) ?? props.event.full_name.charAt(0)}
                </span>
              }
            >
              {(src) => <img src={src()} alt="" class="size-full object-cover" />}
            </Show>
          </div>
          <span
            title={status().label}
            class={cn(
              "absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full ring-2 ring-card",
              status().dot,
            )}
          />
        </div>

        <div class="min-w-0 flex-1 space-y-0.5">
          <h3 class="truncate text-sm font-medium leading-tight">
            {props.event.full_name}
          </h3>
          <div class="flex min-w-0 items-center gap-1 text-xs text-muted-foreground">
            <Show
              when={props.event.contact_email}
              fallback={<span class="truncate">/{props.event.slug}</span>}
            >
              {(email) => (
                <span class="inline-flex min-w-0 max-w-full items-center gap-1">
                  <Mail class="shrink-0" />
                  <span class="truncate">{email()}</span>
                </span>
              )}
            </Show>
          </div>
        </div>

        <Link
          to="/admin/events/$eventId"
          params={{ eventId: props.event.id }}
          aria-label={props.event.full_name}
          class="absolute inset-0 z-0 rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        />

        <Button
          type="button"
          variant="ghost"
          size="icon"
          aria-label={`Editar ${props.event.full_name}`}
          onClick={() => props.onEdit(props.event)}
          class="relative z-10 size-7 shrink-0 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100"
        >
          <Pencil />
        </Button>
      </div>
    </Reveal>
  );
}

// Univents-UI/src/features/events/ui/AdminEventCard.tsx
import { Link } from '@tanstack/react-router'
import { motion } from 'motion/react'
import {
  Pencil,
  MoreVertical,
  Eye,
  Users,
  ChevronRight,
  ArrowUpRight,
} from 'lucide-react'
import type { EventI, EventStatusI } from '@/features/events/model'
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/shared/ui/shadcn/drawer'
import { cn } from '@/shared/lib/utils'

const statusConfig: Record<EventStatusI, {
  label: string;
  dot: string;
}> = {
  draft: {
    label: 'Rascunho',
    dot: 'bg-muted-foreground'
  },
  active: {
    label: 'Ativo',
    dot: 'bg-primary'
  },
  archived: {
    label: 'Arquivado',
    dot: 'bg-muted-foreground'
  },
  discontinued: {
    label: 'Descontinuado',
    dot: 'bg-destructive'
  },
}

interface AdminEventCardProps {
  event: EventI
  index: number
  onEdit: (event: EventI) => void
  // onDelete: (event: EventI) => void
  onPublish: (event: EventI) => void
}

export default function AdminEventCard({
  event,
  index,
  onEdit,
  onPublish
}: AdminEventCardProps) {
  const isDraft = event.status === 'draft'
  const status = statusConfig[event.status]

  return (
    <motion.div
      initial={{ opacity: 0, y: 16 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: index * 0.04, duration: 0.25 }}
      className={cn(
        "group bg-card rounded-xl border p-4",
        "hover:border-foreground/20 hover:shadow-sm",
        "transition-all duration-200"
      )}
    >
      <div className="flex gap-3 items-center">
        <div className={cn(
          "w-12 h-12 rounded-lg shrink-0 overflow-hidden",
          "bg-muted ring-1 ring-border shadow-sm",
          "flex items-center justify-center",
          event.logo_url ? "bg-white" : "bg-secondary/30"
        )}>
          {event.logo_url ? (
            <img
              src={event.logo_url}
              alt=""
              className="w-full h-full object-cover"
            />
          ) : (
            <span className="text-sm font-bold text-secondary-foreground/50">
              {event.acronym?.slice(0, 2).toUpperCase() ?? event.name.slice(0, 2).toUpperCase()}
            </span>
          )}
        </div>

        <div className="flex-1 min-w-0 flex flex-col justify-center h-12">
          <h3 className="font-semibold text-foreground text-sm leading-tight truncate">
            {event.name}
          </h3>

          <div className="flex items-center gap-2 mt-0.5">
            <span className={cn(
              "w-1.5 h-1.5 rounded-full",
              status.dot
            )} />
            <span className="text-[11px] text-muted-foreground">
              {status.label} · {event.editions_count} {event.editions_count === 1 ? 'edição' : 'edições'}
            </span>
            {event.is_series && (
              <span className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded bg-muted text-muted-foreground text-[10px] font-medium">
                <Users className="w-3 h-3" />
                Série
              </span>
            )}
          </div>
        </div>
      </div>

      <div className="mt-3">
        <code className="text-[11px] text-muted-foreground font-mono bg-muted/50 px-1.5 py-0.5 rounded">
          {event.slug}
        </code>
      </div>

      <div className="flex items-center justify-between gap-2 pt-3 mt-3 border-t border-border/50">
        <div className="hidden sm:flex items-center gap-1">
          {isDraft ? (
            <button
              onClick={() => { onPublish(event); }}
              className={cn(
                "flex items-center gap-1.5 px-2.5 py-1 rounded-md",
                "bg-primary text-primary-foreground hover:bg-primary/90",
                "text-xs font-medium",
                "active:scale-95 transition-all"
              )}
            >
              <Eye className="w-3 h-3" />
              Publicar
            </button>
          ) : (
            <span className="text-[11px] text-muted-foreground">
              {event.editions_count} {event.editions_count === 1 ? 'edição' : 'edições'}
            </span>
          )}
        </div>

        <div className="hidden sm:flex items-center gap-0.5 ml-auto">
          <button
            onClick={() => { onEdit(event); }}
            className="p-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            title="Editar"
          >
            <Pencil className="w-3.5 h-3.5" />
          </button>


          <Link
            to="/admin/events/$eventId/editions"
            params={{ eventId: event.id }}
            className={cn(
              "ml-1 flex items-center gap-1 px-2.5 py-1 rounded-md",
              "bg-secondary/50 text-secondary-foreground hover:bg-secondary",
              "text-xs font-medium",
              "transition-colors"
            )}
          >
            Edições
            <ChevronRight className="w-3 h-3" />
          </Link>
        </div>

        <div className="sm:hidden flex items-center justify-between w-full">
          {isDraft ? (
            <button
              onClick={() => { onPublish(event); }}
              className={cn(
                "flex items-center gap-1.5 px-2.5 py-1 rounded-md",
                "bg-primary text-primary-foreground",
                "text-xs font-medium"
              )}
            >
              <Eye className="w-3 h-3" />
              Publicar
            </button>
          ) : (
            <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <span className={cn("w-1.5 h-1.5 rounded-full", status.dot)} />
              {status.label}
            </span>
          )}

          <Drawer>
            <DrawerTrigger asChild>
              <button className="p-1.5 rounded-md hover:bg-muted text-muted-foreground">
                <MoreVertical className="w-4 h-4" />
              </button>
            </DrawerTrigger>
            <DrawerContent className="z-50 rounded-t-2xl">
              <DrawerHeader className="border-b pb-4">
                <DrawerTitle className="text-base font-semibold line-clamp-1">
                  {event.name}
                </DrawerTitle>
              </DrawerHeader>
              <div className="p-3 space-y-1">
                {isDraft && (
                  <button
                    onClick={() => { onPublish(event); }}
                    className="w-full flex items-center gap-3 px-4 py-3 rounded-xl bg-primary text-primary-foreground hover:bg-primary/90 active:scale-95 transition-all"
                  >
                    <Eye className="w-5 h-5" />
                    <span className="font-medium">Publicar evento</span>
                  </button>
                )}

                <Link
                  to="/admin/events/$eventId/editions"
                  params={{ eventId: event.id }}
                  className="w-full flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-muted active:bg-muted/80 transition-colors"
                >
                  <ArrowUpRight className="w-5 h-5 text-muted-foreground" />
                  <span className="font-medium">Ver edições</span>
                </Link>

                <button
                  onClick={() => { onEdit(event); }}
                  className="w-full flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-muted active:bg-muted/80 transition-colors"
                >
                  <Pencil className="w-5 h-5 text-muted-foreground" />
                  <span className="font-medium">Editar evento</span>
                </button>

                <div className="h-px bg-border my-2" />
              </div>
            </DrawerContent>
          </Drawer>
        </div>
      </div>
    </motion.div>
  )
}
