// front/univents/src/features/events/ui/AdminEventMemberCard.tsx
import { ShieldCheck, Trash2, UserRound } from "lucide-react";
import { motion } from "motion/react";
import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/shadcn/button";
import type { EventMemberWithEmailI } from "../api/members";
import type { EventMemberRole } from "../model/member";

const roleConfig: Record<
  EventMemberRole,
  { label: string; pill: string; icon: typeof ShieldCheck }
> = {
  owner: {
    label: "Proprietário",
    pill: "border-violet-500/20 bg-violet-500/10 text-violet-700",
    icon: ShieldCheck,
  },
  admin: {
    label: "Administrador",
    pill: "border-blue-500/20 bg-blue-500/10 text-blue-700",
    icon: ShieldCheck,
  },
  staff: {
    label: "Equipe",
    pill: "border-emerald-500/20 bg-emerald-500/10 text-emerald-700",
    icon: UserRound,
  },
};

export interface AdminEventMemberCardProps {
  member: EventMemberWithEmailI;
  index?: number;
  onRemove: (member: EventMemberWithEmailI) => void;
}

export function AdminEventMemberCard({
  member,
  index = 0,
  onRemove,
}: AdminEventMemberCardProps) {
  const role = roleConfig[member.role];
  const RoleIcon = role.icon;
  const displayName = member.email ?? `Usuário ${member.user_id.slice(0, 8)}`;
  const initials = member.user_id.slice(0, 2).toUpperCase();

  return (
    <motion.article
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{
        delay: index * 0.05,
        duration: 0.35,
        ease: [0.25, 0.1, 0.25, 1],
      }}
      className={cn(
        "group relative flex w-full min-w-62.5 max-w-full flex-col overflow-hidden rounded-2xl bg-card text-left",
        "ring-1 ring-foreground/10 shadow-xs",
        "transform-gpu will-change-transform",
        "transition-all duration-300 ease-out",
        "hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm",
      )}
    >
      <div className="relative aspect-video overflow-hidden bg-muted">
        <div className="flex h-full w-full items-center justify-center bg-linear-to-br from-muted via-background to-muted/40">
          <div className="flex size-18 items-center justify-center rounded-full border border-border/70 bg-background/80 text-xl font-semibold text-muted-foreground/60 shadow-sm backdrop-blur-sm">
            {initials}
          </div>
        </div>

        <div className="absolute inset-0 bg-linear-to-t from-background/90 via-background/25 to-transparent" />

        <div className="absolute left-3 top-3">
          <span
            className={cn(
              "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium backdrop-blur-sm",
              role.pill,
            )}
          >
            <RoleIcon className="size-3" />
            {role.label}
          </span>
        </div>

        <div className="absolute inset-x-0 bottom-0 p-3 sm:p-4">
          <h3 className="truncate text-base font-semibold leading-tight text-foreground transition-colors duration-300 group-hover:text-primary sm:text-lg">
            {displayName}
          </h3>
          <p className="mt-0.5 truncate text-xs leading-5 text-muted-foreground">
            {member.email ?? "E-mail não encontrado"}
          </p>
        </div>
      </div>

      <div className="flex min-w-0 items-center justify-between gap-3 p-3 pt-2.5 sm:p-4 sm:pt-3">
        <span className="flex min-w-0 items-center gap-1 text-[11px] text-muted-foreground">
          <UserRound className="size-3 shrink-0" />
          <span className="truncate font-mono">{member.user_id}</span>
        </span>

        <Button
          type="button"
          variant="outline"
          size="sm"
          className="shrink-0 gap-1.5 text-destructive hover:text-destructive"
          onClick={() => onRemove(member)}
        >
          <Trash2 className="size-3.5" />
          Remover
        </Button>
      </div>
    </motion.article>
  );
}

// front/univents-solid/src/features/events/ui/AdminEventMemberCard.tsx
import type { JSX } from "@solidjs/web";
import { Show, createMemo, createSignal } from "solid-js";

import CheckIcon from "~icons/lucide/check";
import CopyIcon from "~icons/lucide/copy";
import TrashIcon from "~icons/lucide/trash";

import { Button, cn } from "@trieoh/ui-solid";
import { resolveStorageUrl } from "@/shared/lib/storage-url";
import { Reveal } from "@/shared/ui/Reveal";
import { toast } from "@/shared/ui/toast";
import { formatMemberViewModel, type EventMemberWithEmailI } from "../model/member";

const Trash = TrashIcon as unknown as (props: { class?: string }) => JSX.Element;
const Copy = CopyIcon as unknown as (props: { class?: string }) => JSX.Element;
const Check = CheckIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminEventMemberCardProps {
  member: EventMemberWithEmailI;
  index?: number;
  animate?: boolean;
  onRemove: (member: EventMemberWithEmailI) => void;
}

export function AdminEventMemberCard(props: AdminEventMemberCardProps): JSX.Element {
  const [copied, setCopied] = createSignal(false);
  const vm = createMemo(() => formatMemberViewModel(props.member));

  const copyUserId = async (e: MouseEvent) => {
    e.stopPropagation();
    try {
      await navigator.clipboard.writeText(props.member.user_id);
      setCopied(true);
      toast.success("ID do usuário copiado!");
      setTimeout(() => setCopied(false), 2000);
    } catch {
      toast.error("Erro ao copiar ID.");
    }
  };

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div class="group relative flex h-full w-full min-w-0 flex-col justify-between rounded-xl bg-card p-3 ring-1 ring-border transition-colors hover:ring-foreground/25">
        {/* Main identity row: Avatar + Identity Texts (Email + Role subtitle) + Trash */}
        <div class="flex items-center gap-2.5">
          {/* Avatar with Role Status Dot */}
          <div class="relative size-10 shrink-0 select-none">
            <div class="flex size-10 items-center justify-center overflow-hidden rounded-lg bg-muted text-xs font-semibold text-muted-foreground/70">
              <Show
                when={vm().pfpUrl}
                fallback={<span>{vm().initials}</span>}
              >
                {(src) => (
                  <img
                    src={resolveStorageUrl(src())}
                    alt={`Avatar de ${vm().primaryLabel}`}
                    class="size-full object-cover"
                  />
                )}
              </Show>
            </div>
            <span
              title={vm().roleLabel}
              class={cn(
                "absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full ring-2 ring-card",
                vm().roleDotClass,
              )}
            />
          </div>

          {/* Member Name/Email + Role subtitle */}
          <div class="min-w-0 flex-1 space-y-0.5">
            <h3
              class="truncate text-sm font-medium leading-tight text-foreground"
              title={props.member.email ?? props.member.user_id}
            >
              {vm().primaryLabel}
            </h3>

            <span class="block truncate text-xs text-muted-foreground/80">
              {vm().roleLabel}
            </span>
          </div>

          {/* Remove Member Button */}
          <Button
            type="button"
            variant="ghost"
            size="icon"
            aria-label={`Remover ${vm().primaryLabel}`}
            title={`Remover ${vm().primaryLabel}`}
            onClick={() => props.onRemove(props.member)}
            class="relative z-10 size-7 shrink-0 text-muted-foreground opacity-0 transition-opacity hover:bg-destructive/15 hover:text-destructive group-hover:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100"
          >
            <Trash class="size-3.5" />
          </Button>
        </div>

        {/* Footer info: User ID copy + Addition date */}
        <div class="mt-2.5 flex items-center justify-between border-t border-border/50 pt-2 text-[11px] text-muted-foreground">
          <button
            type="button"
            onClick={copyUserId}
            class="group/id inline-flex items-center gap-1 font-mono text-muted-foreground transition-colors hover:text-foreground"
            title="Clique para copiar o ID completo"
          >
            <span>ID: {vm().shortId}</span>
            <Show when={copied()} fallback={<Copy class="size-2.5 opacity-40 group-hover/id:opacity-100" />}>
              <Check class="size-2.5 text-emerald-500" />
            </Show>
          </button>

          <span title={`Adicionado em ${props.member.created_at}`}>
            {vm().formattedDate}
          </span>
        </div>
      </div>
    </Reveal>
  );
}
