// lib/ts/front-core/src/providers/auth-context.tsx
import { useRouter } from "@tanstack/react-router"
import { useAuth } from "@trieoh/identityx-sdk-ts/react"
import { useLayoutEffect } from "react"
import type { ReactNode } from "react"

/**
 * Keeps the TanStack Router context in sync with the IdentityX auth state.
 *
 * Must be rendered inside a `<Router>` and an `<AuthProvider>`.
 *
 * Usage:
 *   <AuthContextUpdater>
 *     {children}
 *   </AuthContextUpdater>
 */
export function AuthContextUpdater({ children }: { children: ReactNode }) {
  const auth = useAuth()
  const router = useRouter()

  useLayoutEffect(() => {
    const currentRouterAuth = router.options.context.auth

    if (currentRouterAuth !== auth) {
      router.update({
        context: {
          ...router.options.context,
          auth,
        },
      })

      if (currentRouterAuth?.isAuthenticated !== auth.isAuthenticated) {
        void router.invalidate()
      }
    }
  }, [auth, router])

  return <>{children}</>
}

// lib/ts/front-core/src/providers/auth-context.solid.tsx
import { useRouter } from "@tanstack/solid-router"
import { useAuth, type AuthService } from "@trieoh/identityx-sdk-ts-solid"
import { createEffect, type ParentProps } from "solid-js"

export type RouterAuth = {
  auth: AuthService
  isAuthenticated: boolean
}

/** Keeps the TanStack Router context in sync with IdentityX auth state. */
export function AuthContextUpdater(props: ParentProps) {
  const auth = useAuth()
  const router = useRouter()

  createEffect(
    () => {
      const context = router.options.context as { auth?: RouterAuth }
      return [auth.auth, auth.isAuthenticated(), context.auth, context] as const
    },
    ([authService, isAuthenticated, currentRouterAuth, context]) => {
      const currentAuth = {
        auth: authService,
        isAuthenticated,
      }

      if (
        currentRouterAuth?.auth !== currentAuth.auth ||
        currentRouterAuth?.isAuthenticated !== currentAuth.isAuthenticated
      ) {
        router.update({
          context: {
            ...context,
            auth: currentAuth,
          },
        })

        if (currentRouterAuth?.isAuthenticated !== currentAuth.isAuthenticated) {
          setTimeout(() => void router.invalidate(), 0)
        }
      }
    },
  )

  return props.children
}
