// front/univents-solid/src/features/editions/ui/AdminEditionCard.tsx
import type { JSX } from "@solidjs/web";
import { Link } from "@tanstack/solid-router";
import { Show } from "solid-js";

import CalendarDaysIcon from "~icons/lucide/calendar-days";
import MapPinIcon from "~icons/lucide/map-pin";
import PencilIcon from "~icons/lucide/pencil";

import { Button, cn } from "@trieoh/ui-solid";
import { Reveal } from "@/shared/ui/Reveal";
import type { EditionI, EditionStatus } from "../model";

const CalendarDays = CalendarDaysIcon as unknown as (props: { class?: string }) => JSX.Element;
const MapPin = MapPinIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;

const STATUS_CONFIG: Record<
  EditionStatus,
  { label: string; dot: string; pill: string }
> = {
  draft: {
    label: "Rascunho",
    dot: "bg-amber-500",
    pill: "border-amber-500/25 bg-amber-500/10 text-amber-700 dark:text-amber-300",
  },
  future: {
    label: "Futura",
    dot: "bg-sky-500",
    pill: "border-sky-500/25 bg-sky-500/10 text-sky-700 dark:text-sky-300",
  },
  active: {
    label: "Ativa",
    dot: "bg-emerald-500",
    pill: "border-emerald-500/25 bg-emerald-500/10 text-emerald-700 dark:text-emerald-300",
  },
  past: {
    label: "Encerrada",
    dot: "bg-slate-500",
    pill: "border-slate-500/25 bg-slate-500/10 text-slate-700 dark:text-slate-300",
  },
};

export interface AdminEditionCardProps {
  edition: EditionI;
  eventId: string;
  index?: number;
  animate?: boolean;
  onEdit: (edition: EditionI) => void;
}

function formatDateRange(startsAt: string, endsAt: string): string {
  try {
    const start = new Date(startsAt);
    const end = new Date(endsAt);
    const startStr = new Intl.DateTimeFormat("pt-BR", {
      day: "2-digit",
      month: "short",
    }).format(start).replace(".", "");
    const endStr = new Intl.DateTimeFormat("pt-BR", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    }).format(end).replace(".", "");
    return `${startStr} – ${endStr}`;
  } catch {
    return "";
  }
}

export function AdminEditionCard(props: AdminEditionCardProps): JSX.Element {
  const status = () => STATUS_CONFIG[props.edition.status] ?? STATUS_CONFIG.draft;
  const dateRange = () => formatDateRange(props.edition.starts_at, props.edition.ends_at);

  return (
    <Reveal delay={(props.index ?? 0) * 0.05} animate={props.animate} class="h-full">
      <div class="group relative flex h-full w-full min-w-0 flex-col justify-between rounded-xl bg-card p-3 ring-1 ring-border transition-colors hover:ring-foreground/25">
        {/* Main identity row: Banner/Logo + Name & Location + Status & Actions */}
        <div class="flex items-center gap-2.5">
          {/* Visual with Status Dot */}
          <div class="relative size-10 shrink-0 select-none">
            <div class="flex size-10 items-center justify-center overflow-hidden rounded-lg bg-muted text-xs font-semibold text-muted-foreground/70">
              <Show
                when={props.edition.banner_url ?? props.edition.logo_url}
                fallback={
                  <span class="text-sm font-semibold text-muted-foreground/50">
                    {props.edition.name.slice(0, 2).toUpperCase()}
                  </span>
                }
              >
                {(src) => (
                  <img
                    src={src()}
                    alt={props.edition.name}
                    class="size-full object-cover"
                  />
                )}
              </Show>
            </div>
            <span
              title={status().label}
              class={cn(
                "absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full ring-2 ring-card",
                status().dot,
              )}
            />
          </div>

          {/* Edition Name + Subtitle (location or status) */}
          <div class="min-w-0 flex-1 space-y-0.5">
            <h3 class="truncate text-sm font-medium leading-tight text-foreground">
              {props.edition.name}
            </h3>

            <div class="flex min-w-0 items-center gap-1 text-xs text-muted-foreground/80">
              <Show
                when={props.edition.location_name}
                fallback={<span class="truncate">{status().label}</span>}
              >
                {(loc) => (
                  <span class="inline-flex min-w-0 max-w-full items-center gap-1 truncate">
                    <MapPin class="size-3 shrink-0" />
                    <span class="truncate">{loc()}</span>
                  </span>
                )}
              </Show>
            </div>
          </div>

          {/* Edit button */}
          <Button
            type="button"
            variant="ghost"
            size="icon"
            aria-label={`Editar ${props.edition.name}`}
            title={`Editar ${props.edition.name}`}
            onClick={(e) => {
              e.stopPropagation();
              props.onEdit(props.edition);
            }}
            class="relative z-10 size-7 shrink-0 text-muted-foreground opacity-0 transition-opacity hover:bg-muted group-hover:opacity-100 focus-visible:opacity-100 [@media(hover:none)]:opacity-100"
          >
            <Pencil class="size-3.5" />
          </Button>
        </div>

        {/* Link covering the card */}
        <Link
          to="/admin/events/$eventId/editions/$editionId"
          params={{ eventId: props.eventId, editionId: props.edition.id }}
          aria-label={props.edition.name}
          class="absolute inset-0 z-0 rounded-xl focus:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        />

        {/* Footer info: Date range + Slug */}
        <div class="mt-2.5 flex items-center justify-between border-t border-border/50 pt-2 text-[11px] text-muted-foreground">
          <span class="inline-flex items-center gap-1">
            <CalendarDays class="size-3 shrink-0 opacity-70" />
            <span class="truncate">{dateRange()}</span>
          </span>

          <span class="truncate font-mono text-[11px]">
            /{props.edition.slug}
          </span>
        </div>
      </div>
    </Reveal>
  );
}

// front/univents/src/features/editions/ui/AdminEditionCard.tsx
import { useNavigate } from "@tanstack/react-router";
import {
  ArrowUpRight,
  Award,
  CalendarDays,
  FileText,
  Package,
  Pencil,
  Send,
  ShieldCheck,
} from "lucide-react";
import { motion } from "motion/react";
import type React from "react";
import { formatDateRange } from "@/shared/lib/date";
import { cn } from "@/shared/lib/utils";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from "@/shared/ui/shadcn/context-menu";
import type { EditionI } from "../model";

interface EditionCardProps {
  edition: EditionI;
  eventId: string;
  index: number;
  onEdit?: (edition: EditionI) => void;
  onPublish?: (edition: EditionI) => void;
}

const statusConfig: Record<
  EditionI["status"],
  { label: string; dot: string; pill: string }
> = {
  draft: {
    label: "Rascunho",
    dot: "bg-amber-500",
    pill: "bg-amber-500/10 text-amber-700 border-amber-500/20",
  },
  future: {
    label: "Futura",
    dot: "bg-sky-500",
    pill: "bg-sky-500/10 text-sky-700 border-sky-500/20",
  },
  active: {
    label: "Ativa",
    dot: "bg-emerald-500",
    pill: "bg-emerald-500/10 text-emerald-700 border-emerald-500/20",
  },
  past: {
    label: "Encerrada",
    dot: "bg-slate-500",
    pill: "bg-slate-500/10 text-slate-700 border-slate-500/20",
  },
};

function MenuItems({
  edition,
  onEdit,
  onPublish,
  eventId,
}: {
  edition: EditionI;
  onEdit?: () => void;
  onPublish?: () => void;
  eventId: string;
}) {
  const navigate = useNavigate();
  const Item = ContextMenuItem;
  const Separator = ContextMenuSeparator;
  const go = (to: string) => () => {
    void navigate({
      to,
      params: { eventId, editionId: edition.id },
    });
  };
  const openEdition = go("/admin/events/$eventId/editions/$editionId");
  const openCertifications = go(
    "/admin/events/$eventId/editions/$editionId/certifications",
  );
  const openSignatures = go(
    "/admin/events/$eventId/editions/$editionId/signatures",
  );
  const openProducts = go(
    "/admin/events/$eventId/editions/$editionId/products",
  );
  const openCheckpoints = go(
    "/admin/events/$eventId/editions/$editionId/checkpoints",
  );
  const stop = (action?: () => void) => (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    action?.();
  };

  return (
    <>
      <Item onClick={stop(openEdition)}>
        <ArrowUpRight className="size-4" />
        <span>Abrir edição</span>
      </Item>
      <Separator />
      {onEdit ? (
        <Item onClick={stop(onEdit)}>
          <Pencil className="size-4" />
          <span>Editar</span>
        </Item>
      ) : null}
      <Item onClick={stop(openCertifications)}>
        <Award className="size-4" />
        <span>Certificações</span>
      </Item>
      <Item onClick={stop(openSignatures)}>
        <FileText className="size-4" />
        <span>Assinaturas</span>
      </Item>
      <Item onClick={stop(openProducts)}>
        <Package className="size-4" />
        <span>Produtos</span>
      </Item>
      <Item onClick={stop(openCheckpoints)}>
        <ShieldCheck className="size-4" />
        <span>Checkpoints</span>
      </Item>
      {onPublish ? (
        <>
          <Separator />
          <Item onClick={stop(onPublish)}>
            <Send className="size-4" />
            <span>Publicar</span>
          </Item>
        </>
      ) : null}
    </>
  );
}

export function AdminEditionCard({
  edition,
  eventId,
  index,
  onEdit,
  onPublish,
}: EditionCardProps) {
  const navigate = useNavigate();
  const hasVisual = Boolean(edition.banner_url ?? edition.logo_url);
  const status = statusConfig[edition.status];

  const openEdition = () => {
    void navigate({
      to: "/admin/events/$eventId/editions/$editionId",
      params: { eventId, editionId: edition.id },
    });
  };
  const handleEdit = () => onEdit?.(edition);
  const handlePublish = () => onPublish?.(edition);

  return (
    <ContextMenu>
      <ContextMenuTrigger
        render={
          <motion.article
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
              delay: index * 0.05,
              duration: 0.35,
              ease: [0.25, 0.1, 0.25, 1],
            }}
            className={cn(
              "group relative flex w-full min-w-62.5 max-w-full flex-col overflow-hidden rounded-2xl bg-card text-left",
              "ring-1 ring-foreground/10 shadow-xs",
              "transform-gpu will-change-transform",
              "transition-all duration-300 ease-out",
              "hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm",
              "focus:outline-none focus-visible:outline-none focus-visible:ring-0",
            )}
            role="button"
            tabIndex={0}
            onClick={openEdition}
            onKeyDown={(e) => {
              if (e.key === "Enter" || e.key === " ") {
                e.preventDefault();
                openEdition();
              }
            }}
          >
            <div className="relative aspect-video overflow-hidden bg-muted">
              {hasVisual ? (
                <img
                  src={edition.banner_url ?? edition.logo_url ?? ""}
                  alt={edition.name}
                  className={cn(
                    "h-full w-full object-cover transition-transform duration-700 ease-out",
                    "group-hover:scale-105",
                  )}
                  loading={index < 4 ? "eager" : "lazy"}
                />
              ) : (
                <div className="flex h-full w-full items-center justify-center bg-linear-to-br from-muted via-background to-muted/40">
                  <div className="flex size-18 items-center justify-center rounded-full border border-border/70 bg-background/80 shadow-sm backdrop-blur-sm">
                    <CalendarDays className="size-7 text-muted-foreground/40" />
                  </div>
                </div>
              )}

              <div className="absolute inset-0 bg-linear-to-t from-background/90 via-background/35 to-transparent" />

              <div className="absolute left-3 top-3 flex flex-wrap items-center gap-1.5">
                <span
                  className={cn(
                    "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-medium backdrop-blur-sm",
                    status.pill,
                  )}
                >
                  <span className={cn("size-1.5 rounded-full", status.dot)} />
                  <span className="max-w-28 truncate">{status.label}</span>
                </span>
              </div>

              <div className="absolute right-3 top-3 z-20">
                {onEdit && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleEdit();
                    }}
                    className="inline-flex items-center gap-1.5 rounded-lg bg-background/85 px-3 py-1.5 text-xs font-medium text-foreground shadow-sm backdrop-blur-sm transition-colors hover:bg-background"
                  >
                    <Pencil className="size-3.5" />
                    Editar
                  </button>
                )}
              </div>

              <div className="absolute inset-x-0 bottom-0 p-3 sm:p-4">
                <div className="min-w-0 max-w-full space-y-0.5">
                  <h3 className="truncate text-base font-semibold leading-tight text-foreground transition-colors duration-300 group-hover:text-primary sm:text-lg">
                    {edition.name}
                  </h3>
                  {edition.tagline && (
                    <p className="truncate text-xs leading-5 text-muted-foreground">
                      {edition.tagline}
                    </p>
                  )}
                </div>
              </div>
            </div>

            <div className="flex min-w-0 items-center justify-between gap-3 p-3 pt-2.5 sm:p-4 sm:pt-3">
              <div className="min-w-0 flex-1 space-y-1">
                <div className="flex min-w-0 flex-wrap items-center gap-1.5 text-[11px] text-muted-foreground">
                  <span className="inline-flex min-w-0 max-w-full items-center gap-1">
                    <CalendarDays className="size-3 shrink-0" />
                    <span className="block min-w-0 truncate">
                      {formatDateRange(edition.starts_at, edition.ends_at)}
                    </span>
                  </span>
                </div>

                <p className="block min-w-0 truncate font-mono text-[11px] text-muted-foreground">
                  /{edition.slug}
                </p>
              </div>

            </div>
          </motion.article>
        }
      ></ContextMenuTrigger>

      <ContextMenuContent align="end" className="w-56">
        <MenuItems
          edition={edition}
          onEdit={onEdit ? handleEdit : undefined}
          onPublish={onPublish ? handlePublish : undefined}
          eventId={eventId}
        />
      </ContextMenuContent>
    </ContextMenu>
  );
}
