// front/univents/src/features/badges/ui/badge-preview.tsx
import QRCode from "qrcode";
import type { CSSProperties } from "react";
import { DEFAULT_BADGE_TEMPLATE } from "../default-template";
import {
  type BadgeElement,
  type BadgePrintItem,
  type BadgeProfileBadge,
  type BadgeTemplate,
  badgeDesignSchema,
} from "../model";

export function BadgePreview({
  badge,
  className = "relative h-40 w-auto",
  contain = false,
  framed = true,
  eventName,
  editionName,
  ticketName,
  participantName,
  location,
  actionUrl: actionUrlOverride,
  showVariables = false,
  style,
}: {
  badge: BadgeProfileBadge | BadgePrintItem | BadgeTemplate;
  className?: string;
  contain?: boolean;
  framed?: boolean;
  eventName?: string;
  editionName?: string;
  ticketName?: string;
  participantName?: string;
  location?: string;
  actionUrl?: string;
  showVariables?: boolean;
  style?: CSSProperties;
}) {
  const design = badgeDesignSchema.safeParse(badge.design_data).success
    ? badgeDesignSchema.parse(badge.design_data)
    : DEFAULT_BADGE_TEMPLATE.design_data;

  const qrElement = design.elements.find((element) => element.type === "qr");

  const qrValue =
    qrElement && typeof qrElement.value === "string"
      ? qrElement.value
      : undefined;

  const actionUrl =
    actionUrlOverride ??
    ("action_url" in badge ? badge.action_url : (qrValue ?? ""));

  const values: Record<string, string> = {
    event_name: eventName ?? ("event_name" in badge ? badge.event_name : ""),
    edition_name:
      editionName ?? ("edition_name" in badge ? badge.edition_name : ""),
    ticket_name:
      ticketName ?? ("ticket_name" in badge ? (badge.ticket_name ?? "") : ""),
    participant_name: participantName ?? "",
    location: location ?? "",
    checkin_url: actionUrl,
  };

  function textFor(element: Extract<BadgeElement, { type: "text" }>) {
    return element.paragraphs
      .flatMap((paragraph) => paragraph.runs.map((run) => run.text))
      .join("\n")
      .replace(/\{\{([^}]+)\}\}/g, (_, key: string) => {
        if (values[key]) return values[key];
        if (!showVariables) return "";
        return (
          {
            event_name: "Nome do evento",
            edition_name: "Nome da edição",
            ticket_name: "Nome do ingresso",
            participant_name: "Nome do participante",
            location: "Local da edição",
            checkin_url: "Link de check-in",
          }[key] ?? key
        );
      });
  }

  return (
    <div
      className={`${className} shrink-0 overflow-hidden rounded-md${framed ? " border shadow-sm" : ""}`}
      style={{
        aspectRatio: `${design.canvas.width} / ${design.canvas.height}`,
        containerType: "inline-size",
        backgroundColor: design.backgroundColor,
        backgroundImage: design.background
          ? `url(${design.background})`
          : undefined,
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        backgroundSize: "cover",
        ...(contain
          ? design.canvas.width >= design.canvas.height
            ? { width: "100%", height: "auto" }
            : { width: "auto", height: "100%" }
          : {}),
        ...style,
      }}
    >
      {design.elements.map((element) => (
        <BadgeElementPreview
          key={element.id}
          element={element}
          design={design}
          actionUrl={actionUrl}
          text={element.type === "text" ? textFor(element) : undefined}
        />
      ))}
    </div>
  );
}

function BadgeElementPreview({
  element,
  design,
  actionUrl,
  text,
}: {
  element: BadgeElement;
  design: typeof DEFAULT_BADGE_TEMPLATE.design_data;
  actionUrl: string;
  text?: string;
}) {
  const style = {
    left: `${(element.x / design.canvas.width) * 100}%`,
    top: `${(element.y / design.canvas.height) * 100}%`,
    width: `${(element.width / design.canvas.width) * 100}%`,
    height: `${(element.height / design.canvas.height) * 100}%`,
  };

  if (element.type === "image") {
    return (
      <img
        src={element.src}
        alt=""
        className="absolute transition-transform duration-700 ease-out"
        loading="lazy"
        decoding="async"
        style={{
          ...style,
          objectFit: element.fit,
          opacity: element.opacity,
          borderRadius: element.radius,
        }}
      />
    );
  }
  if (element.type === "qr") {
    return (
      <div className="absolute" style={style}>
        <PreviewQrCode element={element} value={actionUrl} />
      </div>
    );
  }
  return (
    <div
      className="absolute overflow-hidden whitespace-pre-wrap"
      style={{
        ...style,
        height: `calc(${(element.height / design.canvas.height) * 100}% + ${(6 / design.canvas.width) * 100}cqw)`,
        color: element.paragraphs[0]?.runs[0]?.color,
        fontWeight: element.paragraphs[0]?.runs[0]?.bold ? "bold" : "normal",
        fontSize: `${((element.paragraphs[0]?.runs[0]?.fontSize ?? 20) / design.canvas.width) * 100}cqw`,
        lineHeight: element.paragraphs[0]?.lineHeight,
        textAlign: element.paragraphs[0]?.align,
      }}
    >
      {text}
    </div>
  );
}

function PreviewQrCode({
  element,
  value,
}: {
  element: Extract<BadgeElement, { type: "qr" }>;
  value: string;
}) {
  const matrix = QRCode.create(
    value || "https://univents.app/check-in",
  ).modules;
  const margin = 2;
  const size = matrix.size + margin * 2;
  const modules = [];

  for (let row = 0; row < matrix.size; row++) {
    for (let column = 0; column < matrix.size; column++) {
      if (!matrix.get(row, column)) continue;
      const x = column + margin;
      const y = row + margin;
      modules.push(
        element.style === "dots" ? (
          <circle
            key={`${row}-${column}`}
            cx={x + 0.5}
            cy={y + 0.5}
            r="0.42"
            fill={element.foreground}
          />
        ) : (
          <rect
            key={`${row}-${column}`}
            x={x}
            y={y}
            width="1"
            height="1"
            rx={element.style === "rounded" ? 0.28 : 0}
            fill={element.foreground}
          />
        ),
      );
    }
  }

  return (
    <svg
      role="img"
      aria-label="QR Code de check-in"
      className="size-full"
      viewBox={`0 0 ${size} ${size}`}
      style={{ background: element.background }}
      shapeRendering={
        element.style === "square" ? "crispEdges" : "geometricPrecision"
      }
    >
      {modules}
    </svg>
  );
}

// front/univents-solid/src/features/badges/ui/BadgePreview.tsx
import type { JSX } from "@solidjs/web";
import { type Accessor, For, Show, createMemo, createSignal, onCleanup } from "solid-js";
import { QrRenderer } from "@/features/editor/qr-renderer";
import { StaticText } from "@/features/editor/static-text";
import { DEFAULT_BADGE_TEMPLATE } from "../default-template";
import {
  type BadgeDesign,
  type BadgeElement,
  type BadgePrintItem,
  type BadgeProfileBadge,
  type BadgeTemplate,
  badgeDesignSchema,
} from "../model";

export interface BadgePreviewProps {
  badge: BadgeProfileBadge | BadgePrintItem | BadgeTemplate;
  class?: string;
  className?: string;
  contain?: boolean;
  framed?: boolean;
  eventName?: string;
  editionName?: string;
  ticketName?: string;
  participantName?: string;
  location?: string;
  actionUrl?: string;
  showVariables?: boolean;
  style?: JSX.CSSProperties;
}

const FALLBACK_LABELS: Record<string, string> = {
  event_name: "Nome do evento",
  edition_name: "Nome da edição",
  ticket_name: "Nome do ingresso",
  ticket_type: "Nome do ingresso",
  ticket: "Nome do ingresso",
  participant_name: "Nome do participante",
  name: "Nome do participante",
  location: "Local da edição",
  checkin_url: "Link de check-in",
};

function previewText(
  element: Extract<BadgeElement, { type: "text" }>,
  v: Record<string, string>,
  show?: boolean,
) {
  return {
    ...element,
    paragraphs: element.paragraphs.map((paragraph) => ({
      ...paragraph,
      runs: paragraph.runs.map((run) => ({
        ...run,
        text: run.text.replace(/\{\{([^}]+)\}\}/g, (_, rawKey: string) => {
          const key = rawKey.trim();
          if (v[key] !== undefined && v[key] !== "") return v[key];
          if (!show) return "";
          return FALLBACK_LABELS[key] ?? key;
        }),
      })),
    })),
  };
}

export function BadgePreview(props: BadgePreviewProps): JSX.Element {
  const [containerWidth, setContainerWidth] = createSignal(0);
  let observer: ResizeObserver | undefined;

  onCleanup(() => {
    observer?.disconnect();
  });

  const setupContainer = (el: HTMLDivElement) => {
    const rect = el.getBoundingClientRect();
    if (rect.width > 0) {
      setContainerWidth(rect.width);
    }

    if (typeof ResizeObserver !== "undefined") {
      observer = new ResizeObserver(([entry]) => {
        if (entry && entry.contentRect.width > 0) {
          setContainerWidth(entry.contentRect.width);
        }
      });
      observer.observe(el);
    }
  };

  const design = createMemo<BadgeDesign>(() => {
    const raw = props.badge.design_data;
    const parsed = badgeDesignSchema.safeParse(raw);
    return parsed.success ? parsed.data : DEFAULT_BADGE_TEMPLATE.design_data;
  });

  const qrElement = createMemo(() =>
    design().elements.find((el) => el.type === "qr"),
  );

  const actionUrl = createMemo(() => {
    if (props.actionUrl) return props.actionUrl;
    if ("action_url" in props.badge && props.badge.action_url) {
      return props.badge.action_url;
    }
    const qr = qrElement();
    if (qr && qr.type === "qr" && qr.value) return qr.value;
    return "https://univents.app/check-in";
  });

  const values = createMemo<Record<string, string>>(() => {
    const b = props.badge;
    const ticketName =
      props.ticketName ??
      ("ticket_name" in b && b.ticket_name ? b.ticket_name : "");
    const eventName =
      props.eventName ??
      ("event_name" in b && b.event_name ? b.event_name : "");
    const editionName =
      props.editionName ??
      ("edition_name" in b && b.edition_name ? b.edition_name : "");
    const participantName = props.participantName ?? "";
    const location = props.location ?? "";
    const action = actionUrl();

    return {
      event_name: eventName,
      edition_name: editionName,
      ticket_name: ticketName,
      ticket_type: ticketName,
      ticket: ticketName,
      participant_name: participantName,
      name: participantName,
      location: location,
      checkin_url: action,
    };
  });

  const scale = createMemo(() => {
    const width = containerWidth();
    const canvasWidth = design().canvas.width;
    if (!width || !canvasWidth) return 1;
    return width / canvasWidth;
  });

  const framed = () => props.framed !== false;
  const cls = () => props.class ?? props.className ?? "relative h-40 w-auto";

  return (
    <div
      ref={setupContainer}
      class={`${cls()} shrink-0 overflow-hidden rounded-md${framed() ? " border shadow-xs" : ""}`}
      style={{
        "aspect-ratio": `${design().canvas.width} / ${design().canvas.height}`,
        position: "relative",
        ...(props.contain
          ? design().canvas.width > design().canvas.height
            ? { width: "100%", height: "auto" }
            : { width: "auto", height: "100%" }
          : {}),
        ...props.style,
      }}
    >
      <div
        class="absolute left-0 top-0 overflow-hidden select-none"
        style={{
          width: `${design().canvas.width}px`,
          height: `${design().canvas.height}px`,
          transform: `scale(${scale()})`,
          "transform-origin": "top left",
          "background-color": design().backgroundColor,
          "background-image": design().background
            ? `url(${design().background})`
            : undefined,
          "background-position": "center",
          "background-repeat": "no-repeat",
          "background-size": "cover",
        }}
      >
        <For each={design().elements}>
          {(element) => (
            <BadgeElementPreview
              element={element}
              values={values}
              showVariables={() => props.showVariables}
              actionUrl={actionUrl}
            />
          )}
        </For>
      </div>
    </div>
  );
}

function BadgeElementPreview(props: {
  element: BadgeElement;
  values: Accessor<Record<string, string>>;
  showVariables: Accessor<boolean | undefined>;
  actionUrl: Accessor<string>;
}): JSX.Element {
  const transformedElement = createMemo(() => {
    if (props.element.type === "text") {
      return previewText(
        props.element as Extract<BadgeElement, { type: "text" }>,
        props.values(),
        props.showVariables(),
      );
    }
    return props.element;
  });

  const style = createMemo(() => ({
    position: "absolute" as const,
    left: `${props.element.x}px`,
    top: `${props.element.y}px`,
    width: `${props.element.width}px`,
    height: `${props.element.height}px`,
  }));

  return (
    <Show
      when={props.element.type === "text"}
      fallback={
        <Show
          when={props.element.type === "image"}
          fallback={
            <div style={style()}>
              <QrRenderer
                value={props.actionUrl()}
                foreground={
                  props.element.type === "qr"
                    ? (props.element as Extract<BadgeElement, { type: "qr" }>).foreground
                    : "#000000"
                }
                background={
                  props.element.type === "qr"
                    ? (props.element as Extract<BadgeElement, { type: "qr" }>).background
                    : "#ffffff"
                }
                style={
                  props.element.type === "qr"
                    ? (props.element as Extract<BadgeElement, { type: "qr" }>).style
                    : "square"
                }
              />
            </div>
          }
        >
          {(() => {
            const img = props.element as Extract<BadgeElement, { type: "image" }>;
            return (
              <img
                src={img.src}
                alt=""
                class="absolute transition-transform duration-700 ease-out pointer-events-none"
                loading="lazy"
                decoding="async"
                style={{
                  ...style(),
                  "object-fit": img.fit,
                  opacity: img.opacity,
                  "border-radius": `${img.radius}px`,
                }}
              />
            );
          })()}
        </Show>
      }
    >
      <div class="absolute overflow-hidden" style={style()}>
        <StaticText
          paragraphs={
            (transformedElement() as Extract<BadgeElement, { type: "text" }>)
              .paragraphs
          }
          values={props.values()}
          showVariables={props.showVariables()}
        />
      </div>
    </Show>
  );
}
