// front/univents/src/features/programs/ui/ProgramSection.tsx
import { useSuspenseQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { cn } from "@/shared/lib/utils";
import { occurrencesQueryOptions, programsQueryOptions } from "../api";
import type { OccurrenceI, ProgramI } from "../model";
import { ProgramDayCard } from "./ProgramDayCard";

interface ProgramSectionProps {
  editionId?: string;
  eventSlug: string;
}

function groupByDay(programs: ProgramI[], occurrences: OccurrenceI[]) {
  const programById = new Map(programs.map((p) => [p.id, p]));

  const groups = new Map<
    string,
    { date: string; items: { program: ProgramI; occurrence: OccurrenceI }[] }
  >();

  for (const occurrence of occurrences) {
    const program = programById.get(occurrence.program_id);
    if (!program) continue;

    const dateKey = occurrence.starts_at.slice(0, 10);
    const existing = groups.get(dateKey);

    if (existing) {
      existing.items.push({ program, occurrence });
    } else {
      groups.set(dateKey, {
        date: occurrence.starts_at,
        items: [{ program, occurrence }],
      });
    }
  }

  return Array.from(groups.values())
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((group) => ({
      ...group,
      items: group.items.sort((a, b) =>
        a.occurrence.starts_at.localeCompare(b.occurrence.starts_at),
      ),
    }));
}

export function ProgramSection({ editionId, eventSlug }: ProgramSectionProps) {
  if (!editionId) return null;

  const { data: programs } = useSuspenseQuery(programsQueryOptions(editionId));
  const { data: occurrences } = useSuspenseQuery(
    occurrencesQueryOptions(editionId),
  );

  const days = groupByDay(programs, occurrences);

  if (days.length === 0) return null;

  const visibleDays = days.slice(0, 3);
  const visibilityClasses = ["flex", "hidden md:flex", "hidden lg:flex"];
  const separatorClasses = ["hidden md:block", "hidden lg:block"];

  return (
    <section className="w-full py-10">
      <div className="px-4">
        <div className="text-center mb-8">
          <h2 className="text-3xl font-semibold text-foreground tracking-tight">
            Programação
          </h2>
          <p className="mt-2 text-sm text-muted-foreground leading-relaxed max-w-xl mx-auto">
            Confira as atividades e checkpoints do evento.
          </p>
        </div>

        {/* Cards de dia com separador */}
        <div className="flex flex-nowrap justify-center gap-5 mx-auto">
          {visibleDays.map((day, index) => (
            <div
              key={day.date.slice(0, 10)}
              className={cn("items-start gap-5", visibilityClasses[index])}
            >
              <ProgramDayCard date={day.date} items={day.items} maxItems={3} />
              {index < visibleDays.length - 1 && (
                <div
                  className={cn(
                    "w-px self-stretch bg-border rounded-full",
                    separatorClasses[index],
                  )}
                />
              )}
            </div>
          ))}
        </div>

        <div className="mt-6 text-center">
          <Link
            to="/events/$slug/programs"
            params={{ slug: eventSlug }}
            className="inline-flex items-center gap-1.5 text-sm font-semibold text-primary hover:gap-2.5 transition-all duration-200"
          >
            Programação Completa
            <ArrowRight className="w-4 h-4" />
          </Link>
        </div>
      </div>
    </section>
  );
}

// front/univents-solid/src/features/programs/ui/ProgramSection.tsx
import type {
  MyParticipation,
  MyTicket,
  Program,
  ProgramOccurrence,
  ProgramParticipationStatus,
} from "@trieoh/univents-api/schemas";
import { For, createSignal, untrack } from "solid-js";
import {
  deregisterOccurrenceFn,
  registerOccurrenceFn,
} from "@/features/programs/api";
import { toast } from "@/shared/ui/toast";
import { ProgramDayCard } from "./ProgramDayCard";
import { Carousel } from "@/widgets/carousel/Carousel";
import { Link } from "@tanstack/solid-router";

export function ProgramSection(props: {
  programs: Program[];
  occurrences: ProgramOccurrence[];
  eventSlug: string;
  editionId: string;
  authenticated: boolean;
  heldTicket: MyTicket | null;
  participations: MyParticipation[];
  complete?: boolean;
}) {
  const {
    programItems,
    occurrenceItems,
    authenticated,
    heldTicket,
    participations,
    eventSlug,
    complete,
  } = untrack(() => ({
    programItems: props.programs,
    occurrenceItems: props.occurrences,
    authenticated: props.authenticated,
    heldTicket: props.heldTicket,
    participations: props.participations,
    eventSlug: props.eventSlug,
    complete: props.complete ?? false,
  }));
  const programs = new Map(
    programItems.map((program) => [program.id, program]),
  );
  const grouped = new Map<
    string,
    {
      date: string;
      items: { program: Program; occurrence: ProgramOccurrence }[];
    }
  >();
  for (const occurrence of occurrenceItems) {
    const program = programs.get(occurrence.program_id);
    if (!program) continue;
    const key = occurrence.starts_at.slice(0, 10);
    const group = grouped.get(key) ?? { date: occurrence.starts_at, items: [] };
    group.items.push({ program, occurrence });
    grouped.set(key, group);
  }
  const days = [...grouped.values()]
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((day) => ({
      ...day,
      items: day.items.sort((a, b) =>
        a.occurrence.starts_at.localeCompare(b.occurrence.starts_at),
      ),
    }))
    .slice(0, complete ? undefined : 3);
  const [statuses, setStatuses] = createSignal<
    ReadonlyMap<string, ProgramParticipationStatus>
  >(
    new Map(
      participations.map((participation) => [
        participation.occurrence_id,
        participation.status,
      ]),
    ),
  );
  const [pending, setPending] = createSignal<string>();
  const toggle = async (occurrenceId: string, registered: boolean) => {
    if (!authenticated) {
      window.location.href = `/auth?redirect=${encodeURIComponent(
        `/events/${eventSlug}`,
      )}`;
      return;
    }
    if (!heldTicket) {
      window.location.href = `/events/${eventSlug}/store?tab=tickets`;
      return;
    }
    setPending(occurrenceId);
    try {
      const participation = registered
        ? await deregisterOccurrenceFn(occurrenceId)
        : await registerOccurrenceFn(occurrenceId);
      setStatuses((current) => {
        const next = new Map(current);
        next.set(occurrenceId, participation.status);
        return next;
      });
      toast.success(registered ? "Inscrição cancelada" : "Inscrição realizada");
    } catch {
      toast.error(
        registered
          ? "Não foi possível cancelar a inscrição"
          : "Não foi possível realizar a inscrição",
      );
    } finally {
      setPending(undefined);
    }
  };
  const registration = {
    authenticated,
    heldTicket,
    statuses,
    pending,
    toggle: (occurrenceId: string, registered: boolean) =>
      void toggle(occurrenceId, registered),
  };

  const renderDay = (day: (typeof days)[number]) => (
    <ProgramDayCard
      date={day.date}
      items={day.items}
      maxItems={complete ? undefined : 3}
      showFullDescription={complete}
      registration={registration}
    />
  );

  return (
    <section class="w-full py-10">
      {!complete && <div class="mb-8 text-center">
        <h2 class="text-3xl font-semibold tracking-tight text-foreground">
          Programação
        </h2>
        <p class="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-muted-foreground">
          Confira as atividades e checkpoints do evento.
        </p>
      </div>}
      {days.length === 0 ? (
        <p class="mt-8 text-muted-foreground">Nenhuma atividade programada.</p>
      ) : complete ? (
        <Carousel
          items={days}
          itemMinWidth={320}
          itemMaxWidth={320}
          gap={24}
          scrollBy={"page"}
          arrowPosition="top"
          renderItem={renderDay}
          className="mx-auto max-w-7xl"
        />
      ) : <div class="mx-auto flex flex-nowrap justify-center gap-5">
        <For each={days}>
          {(day, index) => (
            <div
              class={
                index() === 1
                  ? "hidden items-start gap-5 md:flex"
                  : index() === 2
                    ? "hidden items-start gap-5 lg:flex"
                    : "flex items-start gap-5"
              }
            >
              {renderDay(day)}
              {index() < days.length - 1 && (
                <div
                  class={
                    index() === 0
                      ? "hidden w-px self-stretch rounded-full bg-border md:block"
                      : "hidden w-px self-stretch rounded-full bg-border lg:block"
                  }
                />
              )}
            </div>
          )}
        </For>
      </div>}
      {!complete && <div class="mt-6 text-center">
        <Link
          class="text-sm font-semibold text-primary"
          to="/events/$slug/programs"
          params={{ slug: props.eventSlug }}
        >
          Programação Completa →
        </Link>
      </div>}
    </section>
  );
}
