// front/univents-solid/src/features/auths/ui/AuthActionPage.tsx
import type { JSX } from "@solidjs/web";
import type { ParentProps } from "solid-js";
import { AuthLayout } from "@trieoh/identityx-sdk-ts-solid";
import Logo from "@/shared/ui/Logo";

export function AuthActionPage(
  props: ParentProps<{ title?: string; description?: string }>,
): JSX.Element {
  return (
    <div class="relative [&>main]:py-16 [&>main]:pt-52 md:[&>main]:pt-56 [&>main]:pb-28">
      <div class="absolute left-1/2 top-16 md:top-20 z-20 w-32 md:w-40 -translate-x-1/2">
        <Logo
          variant="complete"
          priority
          imgClassName="h-auto max-h-16 md:max-h-20"
        />
      </div>

      <AuthLayout>
        <div class="w-full max-w-md z-10 flex flex-col">
          <div class="text-center mb-6">
            {props.title && (
              <h1 class="font-heading text-3xl font-bold tracking-tight mb-2">
                {props.title}
              </h1>
            )}
            {props.description && (
              <p class="text-muted-foreground text-sm mb-4">
                {props.description}
              </p>
            )}
          </div>
          {props.children}
        </div>
      </AuthLayout>
    </div>
  );
}

// front/univents/src/features/auths/ui/auth-action-page.tsx
import { Link } from "@tanstack/react-router";
import { ArrowLeft } from "lucide-react";

export function AuthActionPage({
  title,
  description,
  children,
}: {
  title?: string;
  description?: string;
  children: React.ReactNode;
}) {
  return (
    <main className="flex min-h-dvh items-center justify-center bg-background px-4 pb-28 pt-12">
      <section className="w-full max-w-md rounded-xl border border-border bg-card p-6 shadow-lg">
        <Link
          to="/auth"
          search={{ redirect: "" }}
          className="mb-6 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" />
          Voltar ao login
        </Link>
        {title && (
          <div className="mb-6 text-center">
            <h1 className="font-heading text-3xl font-bold tracking-tight">
              {title}
            </h1>
            {description && (
              <p className="mt-2 text-sm text-muted-foreground">
                {description}
              </p>
            )}
          </div>
        )}
        {children}
      </section>
    </main>
  );
}
