// Univents-UI/src/routes/events/index.tsx
import { createFileRoute, Link } from '@tanstack/react-router'
import { useSuspenseQuery } from '@tanstack/react-query'
import { Search, SlidersHorizontal, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { motion } from 'motion/react'
import { EventCard } from '@/features/events/ui/EventCard'
import { eventsQueryOptions } from '@/features/events/api'
import { cn } from '@/shared/lib/utils'
import {
  Drawer,
  DrawerContent,
  DrawerHeader,
  DrawerTitle,
  DrawerTrigger,
} from '@/shared/ui/shadcn/drawer'

export const Route = createFileRoute('/events/')({
  component: EventsPage,
  loader: async ({ context }) => {
    await context.queryClient.ensureQueryData(eventsQueryOptions())
  },
})

const filterOptions = [
  { value: 'all', label: 'Todos os eventos' },
  { value: 'series', label: 'Apenas séries' },
] as const

function EventsPage() {
  const { data: events } = useSuspenseQuery(eventsQueryOptions())
  const [filter, setFilter] = useState<'all' | 'series'>('all')
  const [isFilterOpen, setIsFilterOpen] = useState(false)
  const isAdmin = true

  const filteredEvents = filter === 'series'
    ? events.filter(e => e.is_series)
    : events

  const handleFilterSelect = (value: 'all' | 'series') => {
    setFilter(value)
    setIsFilterOpen(false)
  }

  return (
    <div className="min-h-screen bg-background relative pb-20 md:pb-0">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between gap-2 h-14">
            <h1 className="text-lg md:text-xl font-semibold text-foreground shrink-0 flex items-center gap-2">
              Eventos
              <span className="text-sm font-normal text-muted-foreground">
                ({filteredEvents.length})
              </span>
            </h1>

            {/* Desktop */}
            <nav className="hidden sm:flex items-center bg-muted rounded-lg p-1 ml-auto">
              {filterOptions.map((option) => (
                <button
                  key={option.value}
                  onClick={() => { setFilter(option.value) }}
                  className={cn(
                    "px-3 py-1.5 text-sm rounded-md transition-all whitespace-nowrap",
                    filter === option.value
                      ? "bg-background text-foreground shadow-sm"
                      : "text-muted-foreground hover:text-foreground"
                  )}
                >
                  {option.label === 'Todos os eventos' ? 'Todos' : 'Séries'}
                </button>
              ))}
            </nav>

            {/* Mobile */}
            <div className="sm:hidden flex items-center gap-1 ml-auto">
              <Drawer open={isFilterOpen} onOpenChange={setIsFilterOpen}>
                <DrawerTrigger asChild>
                  <button
                    className={cn(
                      "flex items-center justify-center w-9 h-9 rounded-lg transition-colors",
                      "hover:bg-muted active:bg-muted/60",
                      isFilterOpen && "bg-muted"
                    )}
                    aria-label="Filtrar eventos"
                  >
                    <SlidersHorizontal className="w-5 h-5 text-foreground" />
                  </button>
                </DrawerTrigger>

                <DrawerContent className="z-60 rounded-t-2xl border-t border-border bg-card">
                  <DrawerHeader className="pb-4 border-b border-border">
                    <DrawerTitle className="text-base font-semibold text-left">
                      Filtrar eventos
                    </DrawerTitle>
                  </DrawerHeader>

                  <div className="p-2 pb-8 space-y-1">
                    {filterOptions.map((option) => (
                      <button
                        key={option.value}
                        onClick={() => { handleFilterSelect(option.value) }}
                        className={cn(
                          "w-full flex items-center justify-between px-4 py-3.5 rounded-xl text-sm transition-colors",
                          filter === option.value
                            ? "bg-primary/10 text-primary font-medium"
                            : "text-foreground hover:bg-muted"
                        )}
                      >
                        <span>{option.label}</span>
                        {filter === option.value && (
                          <motion.span
                            initial={{ scale: 0 }}
                            animate={{ scale: 1 }}
                            className="flex items-center justify-center w-5 h-5 bg-primary text-primary-foreground rounded-full text-xs"
                          >
                            ✓
                          </motion.span>
                        )}
                      </button>
                    ))}
                  </div>
                </DrawerContent>
              </Drawer>

              {isAdmin && (
                <Link
                  to="/admin/events"
                  className={cn(
                    "flex items-center justify-center",
                    "w-9 h-9 rounded-lg transition-all duration-200",
                    "text-muted-foreground hover:text-foreground",
                    "hover:bg-muted active:bg-muted/60"
                  )}
                  aria-label="Painel administrativo"
                >
                  <ShieldCheck className="w-5 h-5" />
                </Link>
              )}
            </div>

            {/* Desktop: Admin */}
            {isAdmin && (
              <Link
                to="/admin/events"
                className={cn(
                  "hidden sm:flex group relative items-center justify-center",
                  "w-9 h-9 rounded-lg transition-all duration-200",
                  "text-muted-foreground hover:text-foreground",
                  "hover:bg-muted active:bg-muted/60",
                  "shrink-0"
                )}
                aria-label="Painel administrativo"
              >
                <ShieldCheck className="w-5 h-5 transition-transform duration-200 group-hover:scale-110" />
                <span className={cn(
                  "pointer-events-none absolute -bottom-9 right-0",
                  "whitespace-nowrap rounded-md px-2 py-1",
                  "bg-popover text-popover-foreground border border-border",
                  "text-xs shadow-md",
                  "opacity-0 translate-y-1 group-hover:opacity-100 group-hover:translate-y-0",
                  "transition-all duration-150"
                )}>
                  Modo admin
                </span>
              </Link>
            )}
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
        {filteredEvents.length > 0 ? (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-6 md:gap-8">
            {filteredEvents.map((event, idx) => (
              <EventCard key={event.id} event={event} index={idx} />
            ))}
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center py-24 md:py-32 space-y-6">
            <div className="w-16 h-16 rounded-full bg-muted flex items-center justify-center">
              <Search className="w-8 h-8 text-muted-foreground/40" />
            </div>
            <div className="text-center space-y-1">
              <h3 className="text-lg font-medium text-foreground">
                Nenhum evento encontrado
              </h3>
              <p className="text-sm text-muted-foreground">
                Tente ajustar os filtros ou volte mais tarde.
              </p>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

// front/univents-solid/src/routes/events/index.tsx
import { createFileRoute } from "@tanstack/solid-router";
import { useQuery } from "@trieoh/front-core-solid";
import { For, Show, createMemo, createSignal } from "solid-js";
import type { JSX } from "@solidjs/web";
import SearchIcon from "~icons/lucide/search";
import SlidersIcon from "~icons/lucide/sliders-horizontal";
import { allPublicEventsQueryOptions } from "@/features/events/api";
import type { EventI } from "@/features/events/model";
import { EventCard } from "@/widgets/landing/ui/EventCard";
import Logo from "@/shared/ui/Logo";
import { Drawer } from "@/shared/ui/Drawer";

const Search = SearchIcon as unknown as () => JSX.Element;
const Sliders = SlidersIcon as unknown as () => JSX.Element;

export const Route = createFileRoute("/events/")({
  head: () => ({ meta: [{ title: "Eventos - Univents" }] }),
  component: EventsPage,
});

function EventsPage() {
  const eventsQuery = useQuery(() => allPublicEventsQueryOptions());
  const [filter, setFilter] = createSignal<"all" | "series">("all");
  const [drawerOpen, setDrawerOpen] = createSignal(false);

  const events = createMemo(() => eventsQuery().data ?? []);

  return (
    <Show
      when={eventsQuery().isSuccess}
      fallback={
        <EventsShell count="...">
          <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 md:gap-8">
            <For each={[1, 2, 3, 4]}>
              {() => (
                <div class="aspect-4/3 animate-pulse rounded-2xl bg-muted" />
              )}
            </For>
          </div>
        </EventsShell>
      }
    >
      <EventsContent
        events={events()}
        filter={filter}
        setFilter={setFilter}
        drawerOpen={drawerOpen}
        setDrawerOpen={setDrawerOpen}
      />
    </Show>
  );
}

function EventsContent(props: {
  events: EventI[];
  filter: () => "all" | "series";
  setFilter: (value: "all" | "series") => void;
  drawerOpen: () => boolean;
  setDrawerOpen: (value: boolean) => void;
}) {
  const filteredEvents = createMemo(() =>
    [...props.events]
      .sort(
        (a, b) =>
          new Date(b.created_at).getTime() - new Date(a.created_at).getTime(),
      )
      .filter(() => props.filter() === "all"),
  );

  return (
    <EventsShell
      count={String(filteredEvents().length)}
      actions={
        <>
          <div class="hidden rounded-lg bg-muted p-1 sm:flex">
            <FilterButton
              active={props.filter() === "all"}
              onClick={() => props.setFilter("all")}
            >
              Todos
            </FilterButton>
            <FilterButton
              active={props.filter() === "series"}
              onClick={() => props.setFilter("series")}
            >
              Séries
            </FilterButton>
          </div>
          <button
            type="button"
            aria-label="Filtrar eventos"
            class={`flex size-9 items-center justify-center rounded-lg sm:hidden ${props.drawerOpen() ? "bg-muted" : "hover:bg-muted"}`}
            onClick={() => props.setDrawerOpen(true)}
          >
            <Sliders />
          </button>
          <Drawer
            open={props.drawerOpen()}
            title="Filtrar eventos"
            onClose={() => props.setDrawerOpen(false)}
          >
            <div class="space-y-1">
              <FilterButton
                active={props.filter() === "all"}
                onClick={() => {
                  props.setFilter("all");
                  props.setDrawerOpen(false);
                }}
              >
                Todos os eventos
              </FilterButton>
              <FilterButton
                active={props.filter() === "series"}
                onClick={() => {
                  props.setFilter("series");
                  props.setDrawerOpen(false);
                }}
              >
                Apenas séries
              </FilterButton>
            </div>
          </Drawer>
        </>
      }
    >
      <Show
        when={filteredEvents().length > 0}
        fallback={
          <div class="flex flex-col items-center justify-center space-y-6 py-12 md:py-16">
            <div class="flex size-16 items-center justify-center rounded-full bg-muted">
              <Search />
            </div>
            <div class="space-y-1 text-center">
              <h2 class="text-lg font-medium">Nenhum evento encontrado</h2>
              <p class="text-sm text-muted-foreground">
                Tente ajustar os filtros ou volte mais tarde.
              </p>
            </div>
          </div>
        }
      >
        <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 md:gap-8">
          <For each={filteredEvents()}>
            {(event, index) => <EventCard event={event} index={index()} />}
          </For>
        </div>
      </Show>
    </EventsShell>
  );
}

function FilterButton(props: {
  active: boolean;
  onClick: () => void;
  children: string;
}) {
  return (
    <button
      type="button"
      class={`rounded-md px-3 py-1.5 text-sm transition-all ${props.active ? "bg-background text-foreground shadow-sm" : "text-muted-foreground hover:text-foreground"}`}
      onClick={() => props.onClick()}
    >
      {props.children}
    </button>
  );
}

function EventsShell(props: {
  count: string;
  actions?: JSX.Element;
  children: JSX.Element;
}) {
  return (
    <div class="min-h-screen bg-background pb-24">
      <header class="sticky top-0 z-30 border-b border-border bg-background/80 backdrop-blur-xl">
        <div class="mx-auto flex h-14 max-w-7xl items-center justify-between gap-2 px-4">
          <div class="flex items-center gap-3">
            <div class="size-8">
              <Logo variant="icon" imgClassName="object-left" />
            </div>
            <h1 class="border-l border-border pl-3 text-lg font-semibold md:text-xl">
              Eventos{" "}
              <span class="ml-2 text-sm font-normal text-muted-foreground">
                ({props.count})
              </span>
            </h1>
          </div>
          <div class="ml-auto flex items-center gap-2">{props.actions}</div>
        </div>
      </header>
      <main class="mx-auto max-w-7xl px-4 py-8 md:py-12">{props.children}</main>
    </div>
  );
}
