// lib/ts/ui-base/src/toolbar-combobox.tsx
import { Check, ChevronsUpDown, Search } from "lucide-react";
import type { ReactNode } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { cn } from "./cn";

export interface ToolbarComboboxOption {
  value: string;
  label: string;
  description?: string;
}

export interface ToolbarComboboxProps {
  value?: string;
  options: readonly ToolbarComboboxOption[];
  placeholder: string;
  searchPlaceholder?: string;
  disabled?: boolean;
  icon?: ReactNode;
  iconOnly?: boolean;
  className?: string;
  triggerClassName?: string;
  dropdownClassName?: string;
  onChange: (value: string) => void;
}

export function ToolbarCombobox({
  value,
  options,
  placeholder,
  searchPlaceholder = "Buscar…",
  disabled = false,
  icon,
  iconOnly = false,
  className,
  triggerClassName,
  dropdownClassName,
  onChange,
}: ToolbarComboboxProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [highlightedIndex, setHighlightedIndex] = useState(0);
  const selectedOption = options.find((option) => option.value === value);
  const visibleOptions = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    return options.filter((option) =>
      `${option.label} ${option.description ?? ""}`
        .toLowerCase()
        .includes(normalized),
    );
  }, [options, query]);

  useEffect(() => {
    if (!open) return;
    const close = (event: MouseEvent) => {
      if (!containerRef.current?.contains(event.target as Node)) setOpen(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [open]);

  useEffect(() => setHighlightedIndex(0), [open, query]);

  return (
    <div
      ref={containerRef}
      className={cn(
        "relative min-w-0 shrink-0 rounded-md border border-border",
        className,
      )}
    >
      <button
        type="button"
        disabled={disabled}
        aria-haspopup="listbox"
        aria-expanded={open}
        className={cn(
          "flex h-7 items-center rounded-md bg-background text-xs transition-colors hover:bg-muted disabled:pointer-events-none disabled:opacity-45",
          triggerClassName,
          iconOnly
            ? "w-7 justify-center p-0"
            : "w-full justify-between gap-2 px-2",
        )}
        onClick={() => setOpen((current) => !current)}
      >
        {iconOnly ? (
          icon
        ) : (
          <>
            <span
              className={cn(
                "truncate",
                !selectedOption && "text-muted-foreground",
              )}
            >
              {selectedOption?.label ?? placeholder}
            </span>
            <ChevronsUpDown className="size-3 shrink-0 text-muted-foreground" />
          </>
        )}
      </button>
      {open ? (
        <div
          className={cn(
            "absolute top-full left-0 z-50 mt-1 w-full min-w-0 max-w-full overflow-hidden rounded-lg border border-border bg-popover text-popover-foreground shadow-lg",
            iconOnly && "w-64 max-w-none",
            dropdownClassName,
          )}
        >
          <div className="flex items-center gap-2 border-b border-border px-2 py-1.5">
            <Search className="size-3.5 shrink-0 text-muted-foreground" />
            <input
              autoFocus
              value={query}
              placeholder={searchPlaceholder}
              className="h-7 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
              onChange={(event) => setQuery(event.target.value)}
              onKeyDown={(event) => {
                if (event.key === "Escape") setOpen(false);
                if (event.key === "ArrowDown") {
                  event.preventDefault();
                  setHighlightedIndex((index) =>
                    Math.min(index + 1, Math.max(visibleOptions.length - 1, 0)),
                  );
                }
                if (event.key === "ArrowUp") {
                  event.preventDefault();
                  setHighlightedIndex((index) => Math.max(index - 1, 0));
                }
                if (event.key === "Enter" && visibleOptions[highlightedIndex]) {
                  onChange(visibleOptions[highlightedIndex].value);
                  setOpen(false);
                  setQuery("");
                }
              }}
            />
          </div>
          <ul className="max-h-56 overflow-y-auto py-1">
            {visibleOptions.length === 0 ? (
              <li className="px-3 py-2 text-xs text-muted-foreground">
                Nenhum resultado encontrado
              </li>
            ) : (
              visibleOptions.map((option, index) => (
                <li key={option.value}>
                  <button
                    type="button"
                    role="option"
                    aria-selected={option.value === value}
                    className={cn(
                      "flex w-full items-center justify-between gap-2 px-3 py-2.5 text-left text-sm transition-colors",
                      index === highlightedIndex
                        ? "bg-primary/10"
                        : "hover:bg-muted",
                    )}
                    onMouseEnter={() => setHighlightedIndex(index)}
                    onClick={() => {
                      onChange(option.value);
                      setOpen(false);
                      setQuery("");
                    }}
                  >
                    <span className="min-w-0">
                      <span className="block truncate">{option.label}</span>
                      {option.description ? (
                        <span className="block truncate text-xs text-muted-foreground">
                          {option.description}
                        </span>
                      ) : null}
                    </span>
                    {option.value === value ? (
                      <Check className="size-3.5 shrink-0" />
                    ) : null}
                  </button>
                </li>
              ))
            )}
          </ul>
        </div>
      ) : null}
    </div>
  );
}

// front/univents-solid/src/features/editor/toolbar-combobox.tsx
import type { JSX } from "@solidjs/web";
import {
  For,
  Show,
  createEffect,
  createMemo,
  createSignal,
} from "solid-js";
import CheckIcon from "~icons/lucide/check";
import ChevronsUpDownIcon from "~icons/lucide/chevrons-up-down";
import SearchIcon from "~icons/lucide/search";
import { cn } from "@trieoh/ui-solid";

const Check = CheckIcon as unknown as (props: { class?: string }) => JSX.Element;
const ChevronsUpDown = ChevronsUpDownIcon as unknown as (props: {
  class?: string;
}) => JSX.Element;
const Search = SearchIcon as unknown as (props: { class?: string }) => JSX.Element;

export interface ToolbarComboboxOption {
  value: string;
  label: string;
  description?: string;
}

export interface ToolbarComboboxProps {
  value?: string;
  options: readonly ToolbarComboboxOption[];
  placeholder: string;
  searchPlaceholder?: string;
  disabled?: boolean;
  icon?: JSX.Element;
  iconOnly?: boolean;
  class?: string;
  className?: string;
  triggerClass?: string;
  triggerClassName?: string;
  dropdownClass?: string;
  dropdownClassName?: string;
  onChange: (value: string) => void;
}

export function ToolbarCombobox(props: ToolbarComboboxProps): JSX.Element {
  let containerRef: HTMLDivElement | undefined;
  const [open, setOpen] = createSignal(false, { ownedWrite: true } as any);
  const [query, setQuery] = createSignal("", { ownedWrite: true } as any);
  const [highlightedIndex, setHighlightedIndex] = createSignal(0, {
    ownedWrite: true,
  } as any);

  const normalizedQuery = createMemo(() => query().trim().toLowerCase());
  const selectedOption = createMemo(() =>
    props.options.find((option) => option.value === props.value),
  );

  const visibleOptions = createMemo(() => {
    if (!normalizedQuery()) return props.options;
    return props.options.filter((option) =>
      `${option.label} ${option.description ?? ""}`
        .toLowerCase()
        .includes(normalizedQuery()),
    );
  });

  createEffect(
    () => open(),
    (isOpen) => {
      if (!isOpen) return;

      function closeOnOutsideClick(event: MouseEvent) {
        if (!containerRef?.contains(event.target as Node)) {
          setOpen(false);
        }
      }

      document.addEventListener("mousedown", closeOnOutsideClick);
      return () => {
        document.removeEventListener("mousedown", closeOnOutsideClick);
      };
    },
  );

  createEffect(
    () => [open(), query()],
    () => {
      setHighlightedIndex(0);
    },
  );

  function select(option: ToolbarComboboxOption) {
    props.onChange(option.value);
    setOpen(false);
    setQuery("");
  }

  return (
    <div
      ref={(el) => (containerRef = el)}
      class={cn(
        "relative min-w-0 shrink-0 rounded-md border border-border",
        props.class,
        props.className,
      )}
    >
      <button
        type="button"
        disabled={props.disabled}
        aria-haspopup="listbox"
        aria-expanded={open() ? "true" : "false"}
        aria-label={props.iconOnly ? props.placeholder : undefined}
        title={props.iconOnly ? props.placeholder : undefined}
        class={cn(
          "flex h-7 items-center rounded-md bg-background text-xs transition-colors hover:bg-muted disabled:pointer-events-none disabled:opacity-45 cursor-pointer",
          props.triggerClass,
          props.triggerClassName,
          props.iconOnly
            ? "w-7 justify-center p-0"
            : "w-full justify-between gap-2 px-2",
        )}
        onClick={() => setOpen((current) => !current)}
      >
        <Show
          when={!props.iconOnly}
          fallback={props.icon}
        >
          <span
            class={cn(
              "truncate",
              !selectedOption() && "text-muted-foreground",
            )}
          >
            {selectedOption()?.label ?? props.placeholder}
          </span>
          <ChevronsUpDown class="size-3 shrink-0 text-muted-foreground" />
        </Show>
      </button>

      <Show when={open()}>
        <div
          class={cn(
            "absolute top-full left-0 z-50 mt-1 w-full min-w-0 max-w-full overflow-hidden rounded-lg border border-border bg-popover text-popover-foreground shadow-lg",
            props.iconOnly && "w-64 max-w-none",
            props.dropdownClass,
            props.dropdownClassName,
          )}
        >
          <div class="flex items-center gap-2 border-b border-border px-2 py-1.5">
            <Search class="size-3.5 shrink-0 text-muted-foreground" />
            <input
              value={query()}
              placeholder={props.searchPlaceholder ?? "Buscar…"}
              class="h-7 min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
              onInput={(event) => setQuery(event.currentTarget.value)}
              onKeyDown={(event) => {
                if (event.key === "ArrowDown") {
                  event.preventDefault();
                  setHighlightedIndex((index) =>
                    Math.min(index + 1, Math.max(visibleOptions().length - 1, 0)),
                  );
                } else if (event.key === "ArrowUp") {
                  event.preventDefault();
                  setHighlightedIndex((index) => Math.max(index - 1, 0));
                } else if (event.key === "Enter") {
                  event.preventDefault();
                  const list = visibleOptions();
                  if (list.length > 0 && list[highlightedIndex()]) {
                    select(list[highlightedIndex()]);
                  }
                } else if (event.key === "Escape") {
                  setOpen(false);
                }
              }}
            />
          </div>
          <ul class="max-h-56 overflow-y-auto py-1">
            <Show
              when={visibleOptions().length > 0}
              fallback={
                <li class="px-3 py-2 text-xs text-muted-foreground">
                  Nenhum resultado encontrado
                </li>
              }
            >
              <For each={visibleOptions()}>
                {(option, index) => (
                  <li>
                    <button
                      type="button"
                      role="option"
                      aria-selected={option.value === props.value ? "true" : "false"}
                      class={cn(
                        "flex w-full items-center justify-between gap-2 px-3 py-2.5 text-left text-sm transition-colors cursor-pointer",
                        index() === highlightedIndex()
                          ? "bg-primary/10"
                          : "hover:bg-muted",
                      )}
                      onMouseEnter={() => setHighlightedIndex(index())}
                      onClick={() => select(option)}
                    >
                      <span class="min-w-0">
                        <span class="block truncate">{option.label}</span>
                        <Show when={option.description}>
                          <span class="block truncate text-xs text-muted-foreground">
                            {option.description}
                          </span>
                        </Show>
                      </span>
                      <Show when={option.value === props.value}>
                        <Check class="size-3.5 shrink-0" />
                      </Show>
                    </button>
                  </li>
                )}
              </For>
            </Show>
          </ul>
        </div>
      </Show>
    </div>
  );
}
