// front/univents/src/features/certifications/ui/AdminCertificationTemplateCard.tsx
import { Copy, FileText, MoreVertical, Pencil, Trash2 } from "lucide-react";
import { motion } from "motion/react";
import { cn } from "@/shared/lib/utils";
import {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuTrigger,
} from "@/shared/ui/shadcn/context-menu";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/shared/ui/shadcn/dropdown-menu";
import type { CertificationTemplateI } from "../model";

interface AdminCertificationTemplateCardProps {
  template: CertificationTemplateI;
  index?: number;
  onEdit: () => void;
  onDelete: () => void;
  onView: () => void;
  onDuplicate: () => void;
}

function MenuItems({
  isContext = false,
  onEdit,
  onView,
  onDelete,
  onDuplicate,
}: {
  isContext?: boolean;
  onEdit: () => void;
  onView: () => void;
  onDelete: () => void;
  onDuplicate: () => void;
}) {
  const Item = isContext ? ContextMenuItem : DropdownMenuItem;
  const stop =
    (action: () => void) => (e: React.MouseEvent | React.KeyboardEvent) => {
      e.preventDefault();
      e.stopPropagation();
      action();
    };

  return (
    <>
      <Item onClick={stop(onView)}>
        <FileText className="size-4" />
        <span>Ver template</span>
      </Item>
      <Item onClick={stop(onEdit)}>
        <Pencil className="size-4" />
        <span>Editar template</span>
      </Item>
      <Item onClick={stop(onDuplicate)}>
        <Copy className="size-4" />
        <span>Duplicar template</span>
      </Item>
      <Item
        onClick={stop(onDelete)}
        className="text-destructive focus:text-destructive"
      >
        <Trash2 className="size-4" />
        <span>Excluir template</span>
      </Item>
    </>
  );
}

export function AdminCertificationTemplateCard({
  template,
  index = 0,
  onEdit,
  onDelete,
  onView,
  onDuplicate,
}: AdminCertificationTemplateCardProps) {
  const handleEdit = () => onEdit();
  const handleView = () => onView();

  return (
    <ContextMenu>
      <ContextMenuTrigger
        render={
          <motion.article
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{
              delay: index * 0.05,
              duration: 0.35,
              ease: [0.25, 0.1, 0.25, 1],
            }}
            className={cn(
              "group relative flex w-full min-w-62.5 max-w-full flex-col overflow-hidden rounded-2xl bg-card text-left",
              "ring-1 ring-foreground/10 shadow-xs",
              "transform-gpu will-change-transform",
              "transition-all duration-300 ease-out",
              "hover:-translate-y-0.5 hover:ring-foreground/20 hover:shadow-sm",
              "focus:outline-none focus-visible:outline-none focus-visible:ring-0",
            )}
            role="button"
            tabIndex={0}
            onClick={handleView}
            onKeyDown={(event) => {
              if (event.key === "Enter" || event.key === " ") {
                event.preventDefault();
                handleView();
              }
            }}
          >
            <div className="relative h-24 overflow-hidden bg-muted">
              {template.design_data.background ? (
                <img
                  src={template.design_data.background}
                  alt={template.name}
                  className="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-[1.03]"
                  loading={index < 4 ? "eager" : "lazy"}
                />
              ) : (
                <div className="flex h-full w-full items-center justify-center bg-linear-to-br from-muted via-background to-muted/40">
                  <div className="flex size-12 items-center justify-center rounded-full border border-dashed border-border/70 bg-background/80 shadow-sm backdrop-blur-sm">
                    <FileText className="size-5 text-muted-foreground/40" />
                  </div>
                </div>
              )}

              <div className="absolute inset-0 bg-linear-to-t from-background/90 via-background/35 to-transparent" />

              <div className="absolute left-3 top-3 flex flex-wrap items-center gap-1.5">
                <span className="inline-flex items-center gap-1 rounded-full border border-border/60 bg-background/75 px-2 py-0.5 text-[10px] font-medium text-muted-foreground backdrop-blur-sm">
                  <FileText className="size-3.5" />
                  Template
                </span>
              </div>

              <div className="absolute right-2 top-2">
                <DropdownMenu>
                  <DropdownMenuTrigger
                    render={
                      <button
                        type="button"
                        onClick={(e) => e.stopPropagation()}
                        className={cn(
                          "inline-flex size-8 items-center justify-center rounded-full",
                          "bg-background/85 text-foreground shadow-sm backdrop-blur-sm",
                          "transition-colors hover:bg-background",
                        )}
                        aria-label={`Abrir ações de ${template.name}`}
                      >
                        <MoreVertical className="size-4" />
                      </button>
                    }
                  />
                  <DropdownMenuContent align="end" className="w-56">
                    <MenuItems
                      onEdit={handleEdit}
                      onView={handleView}
                      onDelete={onDelete}
                      onDuplicate={onDuplicate}
                    />
                  </DropdownMenuContent>
                </DropdownMenu>
              </div>
            </div>

            <div className="flex items-center justify-between gap-3 p-3">
              <div className="min-w-0 flex-1 space-y-2">
                <div className="min-w-0 space-y-1">
                  <h3 className="line-clamp-2 text-sm font-semibold leading-snug text-foreground transition-colors duration-300 group-hover:text-primary">
                    {template.name}
                  </h3>
                  <p className="text-[11px] text-muted-foreground">
                    {template.design_data.background
                      ? "Com fundo configurado"
                      : "Sem fundo"}
                  </p>
                  {template.description ? (
                    <p className="line-clamp-2 text-xs text-muted-foreground">
                      {template.description}
                    </p>
                  ) : null}
                </div>
              </div>
            </div>
          </motion.article>
        }
      />
      <ContextMenuContent className="w-56">
        <MenuItems
          isContext
          onEdit={handleEdit}
          onView={handleView}
          onDelete={onDelete}
          onDuplicate={onDuplicate}
        />
      </ContextMenuContent>
    </ContextMenu>
  );
}

// front/univents-solid/src/features/certifications/ui/AdminCertificationTemplateCard.tsx
import type { JSX } from "@solidjs/web";
import { Show, createSignal } from "solid-js";
import CopyIcon from "~icons/lucide/copy";
import EyeIcon from "~icons/lucide/eye";
import MoreVerticalIcon from "~icons/lucide/more-vertical";
import PencilIcon from "~icons/lucide/pencil";
import Trash2Icon from "~icons/lucide/trash-2";

import { cn } from "@trieoh/ui-solid";
import { AlertModal } from "@/widgets/ui/AlertModal";
import { Reveal } from "@/shared/ui/Reveal";
import type { CertificationTemplateI } from "../model";
import { CertificatePreview } from "./CertificatePreview";

const Copy = CopyIcon as unknown as (props: { class?: string }) => JSX.Element;
const Eye = EyeIcon as unknown as (props: { class?: string }) => JSX.Element;
const MoreVertical = MoreVerticalIcon as unknown as (props: { class?: string }) => JSX.Element;
const Pencil = PencilIcon as unknown as (props: { class?: string }) => JSX.Element;
const Trash2 = Trash2Icon as unknown as (props: { class?: string }) => JSX.Element;

export interface AdminCertificationTemplateCardProps {
  template: CertificationTemplateI;
  index?: number;
  animate?: boolean;
  onEdit?: () => void;
  onView?: () => void;
  onDuplicate?: () => void;
  onDelete?: () => void;
}

export function AdminCertificationTemplateCard(
  props: AdminCertificationTemplateCardProps,
): JSX.Element {
  const [deleteOpen, setDeleteOpen] = createSignal(false);
  const [menuOpen, setMenuOpen] = createSignal(false);

  const title = () => props.template.name;
  const subtitle = () =>
    props.template.description ||
    (props.template.design_data?.background
      ? "Com imagem de fundo"
      : "Certificado padrão");

  const canvas = () => props.template.design_data?.canvas;

  return (
    <>
      <Reveal
        delay={(props.index ?? 0) * 0.04}
        animate={props.animate}
        class="h-full"
      >
        <article
          class={cn(
            "group relative flex h-full w-full min-w-0 flex-col rounded-lg border border-border/60 bg-card text-left transition-colors duration-150 hover:border-border shadow-xs overflow-hidden",
          )}
        >
          {/* Top row: certificate preview & actions */}
          <div class="relative flex h-36 sm:h-40 w-full items-center justify-center overflow-hidden rounded-t-lg bg-muted/20 p-2.5 sm:p-3 border-b border-border/40">
            <span class="absolute left-2 top-2 z-10 inline-flex items-center rounded border border-border/60 bg-background/90 px-1.5 py-0.5 text-[10px] font-medium text-muted-foreground shadow-xs backdrop-blur-xs">
              Template
            </span>

            <CertificatePreview
              template={props.template}
              contain
              framed={false}
              showVariables={true}
              class="max-h-full max-w-full shadow-sm transition-transform duration-200 group-hover:scale-[1.02]"
            />

            {/* Actions Dropdown for templates */}
            <div class="absolute top-2 right-2 z-10">
              <div class="relative">
                <button
                  type="button"
                  onClick={() => setMenuOpen(!menuOpen())}
                  class="flex size-7 items-center justify-center rounded-md border border-border/60 bg-background/90 text-muted-foreground shadow-xs backdrop-blur-xs transition-colors hover:border-border hover:bg-background hover:text-foreground cursor-pointer"
                  aria-label={`Opções do modelo ${title()}`}
                >
                  <MoreVertical class="size-4" />
                </button>

                <Show when={menuOpen()}>
                  <div
                    class="absolute right-0 top-8 z-30 min-w-36 rounded-md border border-border bg-popover p-1 shadow-md"
                    onFocusOut={(e) => {
                      if (!e.currentTarget.contains(e.relatedTarget as Node)) {
                        setMenuOpen(false);
                      }
                    }}
                  >
                    <Show when={props.onView}>
                      <button
                        type="button"
                        onClick={() => {
                          setMenuOpen(false);
                          props.onView?.();
                        }}
                        class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                      >
                        <Eye class="size-3.5 text-muted-foreground" />
                        <span>Visualizar</span>
                      </button>
                    </Show>
                    <Show when={props.onEdit}>
                      <button
                        type="button"
                        onClick={() => {
                          setMenuOpen(false);
                          props.onEdit?.();
                        }}
                        class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                      >
                        <Pencil class="size-3.5 text-muted-foreground" />
                        <span>Editar</span>
                      </button>
                    </Show>
                    <Show when={props.onDuplicate}>
                      <button
                        type="button"
                        onClick={() => {
                          setMenuOpen(false);
                          props.onDuplicate?.();
                        }}
                        class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-xs text-foreground hover:bg-accent cursor-pointer transition-colors"
                      >
                        <Copy class="size-3.5 text-muted-foreground" />
                        <span>Duplicar</span>
                      </button>
                    </Show>
                    <Show when={props.onDelete}>
                      <button
                        type="button"
                        onClick={() => {
                          setMenuOpen(false);
                          setDeleteOpen(true);
                        }}
                        class="flex w-full items-center gap-2 rounded px-2 py-1.5 text-xs text-destructive hover:bg-destructive/10 cursor-pointer transition-colors"
                      >
                        <Trash2 class="size-3.5" />
                        <span>Excluir</span>
                      </button>
                    </Show>
                  </div>
                </Show>
              </div>
            </div>
          </div>

          {/* Info Content */}
          <div class="flex flex-1 flex-col justify-between p-3">
            <div class="space-y-0.5">
              <div class="flex items-center justify-between gap-2">
                <h4
                  class="truncate text-xs font-semibold text-foreground leading-tight"
                  title={title()}
                >
                  {title()}
                </h4>
              </div>
              <p
                class="truncate text-[11px] text-muted-foreground"
                title={subtitle()}
              >
                {subtitle()}
              </p>
            </div>

            {/* Footer */}
            <div class="mt-2.5 flex items-center justify-between border-t border-border/40 pt-2 text-[11px] text-muted-foreground">
              <span>
                {canvas()?.width ?? 1484} × {canvas()?.height ?? 1060} px
              </span>
              <Show when={props.onEdit}>
                <button
                  type="button"
                  onClick={() => props.onEdit?.()}
                  aria-label={`Editar template ${title()}`}
                  class="text-[11px] font-medium text-foreground hover:text-primary transition-colors cursor-pointer"
                >
                  Editar
                </button>
              </Show>
            </div>
          </div>
        </article>
      </Reveal>

      {/* Delete Confirmation Modal */}
      <AlertModal
        open={deleteOpen()}
        onOpenChange={setDeleteOpen}
        title="Excluir modelo de certificado"
        description={`Tem certeza que deseja remover o modelo "${title()}"? Esta ação não pode ser desfeita.`}
        confirmLabel="Excluir modelo"
        variant="destructive"
        onConfirm={() => {
          setDeleteOpen(false);
          props.onDelete?.();
        }}
      />
    </>
  );
}
