// front/univents/src/routes/admin/events/$eventId_.editions.$editionId/badges/index.tsx
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { EmptyState, PaginatedContainer } from "@trieoh/ui-react";
import {
  BadgeCheck,
  CalendarClock,
  FileText,
  Plus,
  Printer,
  QrCode,
} from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  badgeEmissionsQueryOptions,
  badgePrintQueryOptions,
  badgeTemplatesQueryOptions,
} from "@/features/badges/api";
import { useDeleteBadgeTemplateMutation } from "@/features/badges/api/mutations";
import type { BadgePrintItem, BadgeTemplate } from "@/features/badges/model";
import { selectBadgePrintItems } from "@/features/badges/model/print-selection";
import AdminBadgeCard from "@/features/badges/ui/AdminBadgeCard";
import {
  PrintableBadge,
  PrintableQr,
} from "@/features/badges/ui/printable-badge";
import { ToolbarCombobox } from "@/features/certifications/editor/ui/toolbar-combobox";
import { allAdminEditionsQueryOptions } from "@/features/editions/api";
import { useActorDisplayNames } from "@/features/profile/api/actor-display-names";
import { allTicketsQueryOptions } from "@/features/tickets/api";
import { printElement } from "@/shared/lib/print-element";
import { cn } from "@/shared/lib/utils";
import { Button } from "@/shared/ui/shadcn/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/shared/ui/shadcn/dialog";
import { Input } from "@/shared/ui/shadcn/input";

export const Route = createFileRoute(
  "/admin/events/$eventId_/editions/$editionId/badges/",
)({ component: RouteComponent });

function RouteComponent() {
  const { eventId, editionId } = Route.useParams();
  const navigate = useNavigate();
  const remove = useDeleteBadgeTemplateMutation();
  const [filter, setFilter] = useState("");
  const [emissionFilter, setEmissionFilter] = useState("");
  const [activeSection, setActiveSection] = useState<"templates" | "emissions">(
    "templates",
  );
  const [printMode, setPrintMode] = useState<"badges" | "qrs">("badges");
  const [printedAfter, setPrintedAfter] = useState("");
  const [printPending, setPrintPending] = useState(false);
  const [qrSizeMm, setQrSizeMm] = useState(48);
  const [printQrSizeMm, setPrintQrSizeMm] = useState(48);
  const [customQrSize, setCustomQrSize] = useState("48");
  const [dateDialogOpen, setDateDialogOpen] = useState(false);
  const [qrDialogOpen, setQrDialogOpen] = useState(false);
  const printRootRef = useRef<HTMLDivElement>(null);
  const presetQrSizes = [30, 48, 60, 210];
  const selectedPreset = presetQrSizes.includes(Number(customQrSize))
    ? customQrSize
    : "";
  const { data: templates = [] } = useQuery(
    badgeTemplatesQueryOptions(editionId),
  );
  const printQuery = useQuery(badgePrintQueryOptions(editionId));
  const { data: emissions = [] } = useQuery(
    badgeEmissionsQueryOptions(editionId),
  );
  const { data: editions = [] } = useQuery(
    allAdminEditionsQueryOptions(eventId),
  );
  const { data: tickets = [] } = useQuery(allTicketsQueryOptions(editionId));
  const filtered = useMemo(
    () =>
      templates.filter((item) =>
        item.name.toLowerCase().includes(filter.trim().toLowerCase()),
      ),
    [filter, templates],
  );
  const ticketNames = new Map(
    tickets.map((ticket) => [ticket.id, ticket.name]),
  );
  const printItems = printQuery.data ?? [];
  const printableItems = useMemo(
    () => selectBadgePrintItems(printItems, emissions, printedAfter),
    [emissions, printItems, printedAfter],
  );
  const printActorIds = [
    ...new Set(printableItems.map((item) => item.user_id)),
  ];
  const { data: participantNames = {}, isPending: participantNamesPending } =
    useActorDisplayNames(printActorIds);
  const location =
    editions.find((edition) => edition.id === editionId)?.location_name ?? "";
  const filteredPrintItems = useMemo(() => {
    const search = emissionFilter.trim().toLowerCase();
    if (!search) return printableItems;
    return printableItems.filter((item) =>
      [item.event_name, item.edition_name, item.ticket_name, item.template_name]
        .filter(Boolean)
        .some((value) => value?.toLowerCase().includes(search)),
    );
  }, [emissionFilter, printableItems]);

  async function printQrs() {
    const sizeMm = customQrSize ? Number(customQrSize) : qrSizeMm;
    if (!Number.isFinite(sizeMm) || sizeMm < 20 || sizeMm > 210) return;
    setPrintQrSizeMm(sizeMm);
    const result = await printQuery.refetch();
    if (result.data) {
      setQrDialogOpen(false);
      setPrintMode("qrs");
      setPrintPending(true);
    }
  }

  useEffect(() => {
    if (
      !printPending ||
      qrDialogOpen ||
      !printQuery.data ||
      participantNamesPending
    )
      return;

    let cancelled = false;
    const prepare = async () => {
      await new Promise<void>((resolve) =>
        requestAnimationFrame(() => requestAnimationFrame(() => resolve())),
      );
      if (cancelled || !printRootRef.current) return;
      await printElement(printRootRef.current, "Crachás");
      setPrintPending(false);
    };
    void prepare();
    return () => {
      cancelled = true;
    };
  }, [participantNamesPending, printPending, printQuery.data, qrDialogOpen]);
  return (
    <>
      <div
        ref={printRootRef}
        data-badge-print-root
        className="hidden print:block"
      >
        <div className="flex flex-wrap content-start gap-[4mm] p-[10mm] print:p-0">
          {printMode === "badges"
            ? printableItems.map((badge) => (
                <PrintableBadge
                  key={badge.emission_id}
                  badge={badge}
                  participantName={participantNames[badge.user_id]}
                  location={location}
                />
              ))
            : printableItems.map((badge) => (
                <PrintableQr
                  key={badge.emission_id}
                  badge={badge}
                  size={(printQrSizeMm / 25.4) * 96}
                  participant={participantNames[badge.user_id]}
                />
              ))}
        </div>
      </div>
      <div className="p-6 pb-28 print:hidden">
        <nav className="mb-6 flex gap-1 border-b border-border">
          {(["templates", "emissions"] as const).map((section) => (
            <button
              key={section}
              type="button"
              onClick={() => setActiveSection(section)}
              className={cn(
                "inline-flex items-center gap-2 whitespace-nowrap border-b-2 px-3 py-2.5 text-sm font-medium",
                activeSection === section
                  ? "border-primary text-primary"
                  : "border-transparent text-muted-foreground",
              )}
            >
              {section === "templates" ? (
                <>
                  <FileText className="size-4" /> Templates
                </>
              ) : (
                <>
                  <BadgeCheck className="size-4" /> Crachás emitidos
                </>
              )}
            </button>
          ))}
        </nav>
        {activeSection === "templates" ? (
          <PaginatedContainer<BadgeTemplate>
            items={filtered}
            layout="grid"
            minItemWidth="16rem"
            pageSize={8}
            gap="6"
            filterValue={filter}
            onFilterChange={setFilter}
            filterPlaceholder="Buscar templates..."
            itemLabel="templates"
            headerActions={
              <Link
                to="/admin/events/$eventId/editions/$editionId/badges/editor"
                params={{ eventId, editionId }}
                search={{ templateId: "", duplicate: false }}
                className={cn(
                  "inline-flex h-9 items-center justify-center gap-2 rounded-lg bg-primary px-4 text-sm font-medium text-primary-foreground",
                )}
              >
                <Plus className="size-4" />
                Novo template
              </Link>
            }
            emptyState={
              <EmptyState
                icon={BadgeCheck}
                eyebrow="Crachás"
                title="Nenhum template encontrado"
                description="Crie um template totalmente personalizado ou parta do padrão do sistema."
                className="border-0 bg-transparent"
              />
            }
            renderItems={(slice) =>
              slice.map((template, i) => (
                <AdminBadgeCard
                  key={template.id}
                  item={template}
                  kind="template"
                  index={i}
                  ticketName={
                    template.ticket_type_id
                      ? (ticketNames.get(template.ticket_type_id) ??
                        "Ingresso associado")
                      : "Padrão da edição"
                  }
                  location={location}
                  onView={() =>
                    void navigate({
                      to: "/admin/events/$eventId/editions/$editionId/badges/editor",
                      params: { eventId, editionId },
                      search: { templateId: template.id, duplicate: false },
                    })
                  }
                  onEdit={() =>
                    void navigate({
                      to: "/admin/events/$eventId/editions/$editionId/badges/editor",
                      params: { eventId, editionId },
                      search: { templateId: template.id, duplicate: false },
                    })
                  }
                  onDuplicate={() =>
                    void navigate({
                      to: "/admin/events/$eventId/editions/$editionId/badges/editor",
                      params: { eventId, editionId },
                      search: { templateId: template.id, duplicate: true },
                    })
                  }
                  onDelete={() =>
                    remove.mutate({ editionId, templateId: template.id })
                  }
                />
              ))
            }
          />
        ) : (
          <PaginatedContainer<BadgePrintItem>
            items={filteredPrintItems}
            layout="grid"
            minItemWidth="16rem"
            pageSize={8}
            gap="6"
            filterValue={emissionFilter}
            onFilterChange={setEmissionFilter}
            filterPlaceholder="Buscar crachá..."
            itemLabel="crachás"
            headerActions={
              <div className="flex flex-wrap items-center gap-2">
                <Dialog open={dateDialogOpen} onOpenChange={setDateDialogOpen}>
                  <DialogTrigger
                    render={
                      <Button
                        variant={printedAfter ? "default" : "outline"}
                        className="h-9"
                      >
                        <CalendarClock className="size-4" />
                        Filtrar data
                      </Button>
                    }
                  />
                  {dateDialogOpen && (
                    <DialogContent className="w-[calc(100%-2rem)] sm:max-w-sm">
                      <DialogHeader>
                        <DialogTitle>Filtrar crachás por data</DialogTitle>
                        <DialogDescription>
                          Exiba e imprima somente os crachás gerados a partir da
                          data e hora escolhidas.
                        </DialogDescription>
                      </DialogHeader>
                      <label
                        htmlFor="badges-printed-after"
                        className="space-y-2 text-sm font-medium"
                      >
                        Gerados a partir de
                        <Input
                          id="badges-printed-after"
                          type="datetime-local"
                          value={printedAfter}
                          onChange={(event) =>
                            setPrintedAfter(event.target.value)
                          }
                          className="mt-2 h-10 w-full min-w-0 text-base sm:text-sm"
                        />
                      </label>
                      <div className="flex gap-2">
                        {printedAfter ? (
                          <Button
                            variant="outline"
                            className="flex-1"
                            onClick={() => setPrintedAfter("")}
                          >
                            Limpar
                          </Button>
                        ) : null}
                        <Button
                          className="flex-1"
                          onClick={() => setDateDialogOpen(false)}
                        >
                          Aplicar
                        </Button>
                      </div>
                    </DialogContent>
                  )}
                </Dialog>
                <Button
                  variant="default"
                  disabled={
                    printQuery.isFetching || printableItems.length === 0
                  }
                  onClick={async () => {
                    const result = await printQuery.refetch();
                    if (result.data) {
                      setPrintMode("badges");
                      setPrintPending(true);
                    }
                  }}
                  className={cn(
                    "inline-flex h-9 items-center justify-center gap-2 rounded-lg",
                  )}
                >
                  <Printer className="size-4" />
                  {printQuery.isFetching ? "Preparando…" : "Imprimir crachás"}
                </Button>
                <Dialog open={qrDialogOpen} onOpenChange={setQrDialogOpen}>
                  <DialogTrigger
                    render={
                      <Button
                        variant="outline"
                        className="h-9"
                        disabled={
                          printQuery.isFetching || printableItems.length === 0
                        }
                      >
                        <QrCode className="size-4" />
                        Imprimir QR codes
                      </Button>
                    }
                  />
                  {qrDialogOpen && (
                    <DialogContent className="print:hidden sm:max-w-md">
                      <DialogHeader>
                        <DialogTitle>
                          Configurar impressão dos QR codes
                        </DialogTitle>
                        <DialogDescription>
                          Escolha o tamanho exato de cada QR code na impressão.
                        </DialogDescription>
                      </DialogHeader>
                      <div className="space-y-2">
                        <span className="text-sm font-medium">
                          Tamanho do QR code
                        </span>
                        <ToolbarCombobox
                          value={selectedPreset}
                          options={[
                            { value: "30", label: "Pequeno - 30 × 30 mm" },
                            { value: "48", label: "Médio - 48 × 48 mm" },
                            { value: "60", label: "Grande - 60 × 60 mm" },
                            {
                              value: "210",
                              label: "Largura A4 - 210 × 210 mm",
                            },
                          ]}
                          placeholder="Selecione o tamanho"
                          searchPlaceholder="Buscar tamanho..."
                          onChange={(value) => {
                            setQrSizeMm(Number(value));
                            setCustomQrSize(value);
                          }}
                          className="w-full"
                          triggerClassName="h-10"
                        />
                        <p className="pt-2 text-xs text-muted-foreground">
                          Ou informe um tamanho personalizado entre 20 e 210 mm.
                        </p>
                        <Input
                          type="number"
                          min={20}
                          max={210}
                          step={1}
                          value={customQrSize}
                          onChange={(event) => {
                            const value = event.target.value;
                            setCustomQrSize(value);
                            if (value !== "") setQrSizeMm(Number(value));
                          }}
                          placeholder="Ex.: 200"
                          className="h-10"
                        />
                      </div>
                      <Button
                        className="h-10 w-full"
                        disabled={
                          printQuery.isFetching ||
                          (customQrSize !== "" &&
                            (!Number.isFinite(Number(customQrSize)) ||
                              Number(customQrSize) < 20 ||
                              Number(customQrSize) > 210))
                        }
                        onClick={() => void printQrs()}
                      >
                        {printQuery.isFetching
                          ? "Preparando impressão…"
                          : "Confirmar e imprimir"}
                      </Button>
                      {customQrSize !== "" &&
                      Number(customQrSize) >= 20 &&
                      Number(customQrSize) < 30 ? (
                        <p className="text-xs text-amber-600">
                          QR codes menores que 30 mm podem não ser lidos por
                          alguns scanners.
                        </p>
                      ) : null}
                    </DialogContent>
                  )}
                </Dialog>
              </div>
            }
            emptyState={
              <EmptyState
                title="Nenhum crachá emitido"
                description="As emissões aparecerão aqui."
              />
            }
            renderItems={(slice) =>
              slice.map((badge, i) => (
                <AdminBadgeCard
                  key={badge.emission_id}
                  item={badge}
                  kind="emission"
                  index={i}
                  participantName={participantNames[badge.user_id]}
                  location={location}
                  onView={() => undefined}
                />
              ))
            }
          />
        )}
      </div>
    </>
  );
}

// front/univents-solid/src/routes/admin/events/$eventId_.editions.$editionId/badges/index.tsx
import type { JSX } from "@solidjs/web";
import { createFileRoute, useNavigate } from "@tanstack/solid-router";
import { useQuery } from "@trieoh/front-core-solid";
import { useAuth } from "@trieoh/identityx-sdk-ts-solid";
import {
  Button,
  EmptyState,
  PaginatedContainer,
  type SortState,
  cn,
} from "@trieoh/ui-solid";
import { For, Show, createEffect, createMemo, createSignal } from "solid-js";

import BadgeCheckIcon from "~icons/lucide/badge-check";
import CalendarClockIcon from "~icons/lucide/calendar-clock";
import FileTextIcon from "~icons/lucide/file-text";
import PlusIcon from "~icons/lucide/plus";
import PrinterIcon from "~icons/lucide/printer";
import QrCodeIcon from "~icons/lucide/qr-code";

import {
  badgeEmissionsQueryOptions,
  badgePrintQueryOptions,
  badgeTemplatesQueryOptions,
} from "@/features/badges/api";
import { useDeleteBadgeTemplateMutation } from "@/features/badges/api/mutations";
import type {
  BadgeEditionEmission,
  BadgePrintItem,
  BadgeTemplate,
} from "@/features/badges/model";
import { selectBadgePrintItems } from "@/features/badges/model/print-selection";
import {
  AdminBadgeCard,
  AdminCreateBadgeCard,
  DateFilterDialog,
  PrintableBadge,
  PrintableQr,
  QrPrintDialog,
} from "@/features/badges/ui";
import { allAdminEditionsQueryOptions } from "@/features/editions/api";
import { asUniventsProfile, profileDisplayName } from "@/features/profile/model/profile-data";
import { allTicketsQueryOptions } from "@/features/tickets/api";
import { printElement } from "@/shared/lib/print-element";
import { toast } from "@/shared/ui/toast";

const BadgeCheck = BadgeCheckIcon as unknown as (props: { class?: string }) => JSX.Element;
const CalendarClock = CalendarClockIcon as unknown as (props: { class?: string }) => JSX.Element;
const FileText = FileTextIcon as unknown as (props: { class?: string }) => JSX.Element;
const Plus = PlusIcon as unknown as (props: { class?: string }) => JSX.Element;
const Printer = PrinterIcon as unknown as (props: { class?: string }) => JSX.Element;
const QrCode = QrCodeIcon as unknown as (props: { class?: string }) => JSX.Element;

export const Route = createFileRoute(
  "/admin/events/$eventId_/editions/$editionId/badges/",
)({
  head: () => ({
    meta: [{ title: "Crachás - Admin Univents" }],
  }),
  component: AdminEditionBadgesRoute,
});

function AdminTemplateBadgeItem(props: {
  template: BadgeTemplate;
  index: number;
  animate?: boolean;
  ticketNames: () => Map<string, string>;
  location: () => string;
  onEdit: () => void;
  onDuplicate: () => void;
  onDelete: () => void;
}): JSX.Element {
  const ticketName = createMemo(() => {
    if (!props.template.ticket_type_id) return "Padrão da edição";
    return props.ticketNames().get(props.template.ticket_type_id) ?? "Ingresso associado";
  });

  return (
    <AdminBadgeCard
      item={props.template}
      kind="template"
      index={props.index}
      animate={props.animate}
      ticketName={ticketName()}
      location={props.location()}
      onEdit={props.onEdit}
      onDuplicate={props.onDuplicate}
      onDelete={props.onDelete}
    />
  );
}

function AdminEmissionBadgeItem(props: {
  badge: BadgePrintItem;
  index: number;
  animate?: boolean;
  participantNames: () => Record<string, string>;
  location: () => string;
}): JSX.Element {
  const participantName = createMemo(() => props.participantNames()[props.badge.user_id]);

  return (
    <AdminBadgeCard
      item={props.badge}
      kind="emission"
      index={props.index}
      animate={props.animate}
      participantName={participantName()}
      location={props.location()}
    />
  );
}

function PrintableQrItem(props: {
  badge: BadgePrintItem;
  printQrSizeMm: () => number;
  participantNames: () => Record<string, string>;
}): JSX.Element {
  const size = createMemo(() => (props.printQrSizeMm() / 25.4) * 96);
  const participant = createMemo(() => props.participantNames()[props.badge.user_id] ?? props.badge.user_id.slice(0, 8));

  return (
    <PrintableQr
      badge={props.badge}
      size={size()}
      participant={participant()}
    />
  );
}

function PrintableBadgeItem(props: {
  badge: BadgePrintItem;
  participantNames: () => Record<string, string>;
  location: () => string;
}): JSX.Element {
  const participantName = createMemo(() => props.participantNames()[props.badge.user_id] ?? "");

  return (
    <PrintableBadge
      badge={props.badge}
      participantName={participantName()}
      location={props.location()}
    />
  );
}

function AdminEditionBadgesRoute(): JSX.Element {
  const navigate = useNavigate();
  const params = Route.useParams();
  const eventId = () => params().eventId;
  const editionId = () => params().editionId;
  const { auth } = useAuth();

  // Queries
  const templatesQuery = useQuery(() => badgeTemplatesQueryOptions(editionId()));
  const emissionsQuery = useQuery(() => badgeEmissionsQueryOptions(editionId()));
  const printQuery = useQuery(() => badgePrintQueryOptions(editionId()));
  const editionsQuery = useQuery(() => allAdminEditionsQueryOptions(eventId()));
  const ticketsQuery = useQuery(() => allTicketsQueryOptions(editionId()));

  // Mutations
  const deleteMutation = useDeleteBadgeTemplateMutation();

  // State
  const [activeSection, setActiveSection] = createSignal<"templates" | "emissions">("templates");
  const [templateFilter, setTemplateFilter] = createSignal("");
  const [emissionFilter, setEmissionFilter] = createSignal("");
  const [templateSort, setTemplateSort] = createSignal<SortState<BadgeTemplate>>({
    field: "name",
    direction: "asc",
  });
  const [emissionSort, setEmissionSort] = createSignal<SortState<BadgePrintItem>>({
    field: "template_name",
    direction: "asc",
  });
  const [printedAfter, setPrintedAfter] = createSignal("");
  const [printMode, setPrintMode] = createSignal<"badges" | "qrs">("badges");
  const [printQrSizeMm, setPrintQrSizeMm] = createSignal(48);
  const [isPrinting, setIsPrinting] = createSignal(false);

  // Dialogs
  const [dateDialogOpen, setDateDialogOpen] = createSignal(false);
  const [qrDialogOpen, setQrDialogOpen] = createSignal(false);

  let printRootRef: HTMLDivElement | undefined;

  // Data helpers
  const templates = createMemo(() => (templatesQuery().data ?? []) as BadgeTemplate[]);
  const emissions = createMemo(() => (emissionsQuery().data ?? []) as BadgeEditionEmission[]);
  const printItems = createMemo(() => (printQuery().data ?? []) as BadgePrintItem[]);
  const editions = createMemo(() => (editionsQuery().data ?? []) as any[]);
  const tickets = createMemo(() => (ticketsQuery().data ?? []) as any[]);

  const ticketNames = createMemo(() => {
    const map = new Map<string, string>();
    for (const t of tickets()) {
      map.set(t.id, t.name);
    }
    return map;
  });

  const location = createMemo(() => {
    const ed = editions().find((e) => e.id === editionId());
    return ed?.location_name ?? "";
  });

  const filteredTemplates = createMemo(() => {
    const list = templates();
    const query = templateFilter().trim().toLowerCase();
    if (!query) return list;
    const result: BadgeTemplate[] = [];
    for (const item of list) {
      if (item.name.toLowerCase().includes(query)) {
        result.push(item);
      }
    }
    return result;
  });

  const printableItems = createMemo(() =>
    selectBadgePrintItems(printItems(), emissions(), printedAfter()),
  );

  const printActorIds = createMemo(() => [
    ...new Set(printableItems().map((item) => item.user_id)),
  ]);

  const [participantNames, setParticipantNames] = createSignal<Record<string, string>>({});

  createEffect(
    () => printActorIds(),
    (ids) => {
      if (!ids || ids.length === 0) return;
      void (async () => {
        const result: Record<string, string> = {};
        await Promise.all(
          ids.map(async (id) => {
            try {
              const res = await auth.getActorProfile(id);
              if (res.success && res.data) {
                const p = asUniventsProfile(res.data.profile ?? {});
                result[id] = profileDisplayName(p);
              }
            } catch {
              // ignore
            }
          }),
        );
        setParticipantNames((prev) => ({ ...prev, ...result }));
      })();
    },
  );

  const filteredPrintItems = createMemo(() => {
    const list = printableItems();
    const query = emissionFilter().trim().toLowerCase();
    if (!query) return list;
    const result: BadgePrintItem[] = [];
    for (const item of list) {
      const match =
        (item.event_name && item.event_name.toLowerCase().includes(query)) ||
        (item.edition_name && item.edition_name.toLowerCase().includes(query)) ||
        (item.ticket_name && item.ticket_name.toLowerCase().includes(query)) ||
        (item.template_name && item.template_name.toLowerCase().includes(query));
      if (match) {
        result.push(item);
      }
    }
    return result;
  });

  // Handlers
  const handleOpenEditor = (templateId?: string, duplicate?: boolean) => {
    navigate({
      to: "/admin/events/$eventId/editions/$editionId/badges/editor",
      params: { eventId: eventId(), editionId: editionId() },
      search: {
        templateId: templateId ?? undefined,
        duplicate: duplicate ? true : undefined,
      },
    });
  };

  const handleDeleteTemplate = async (template: BadgeTemplate) => {
    try {
      await deleteMutation.mutateAsync({
        editionId: editionId(),
        templateId: template.id,
      });
      toast.success("Template excluído com sucesso.");
    } catch {
      toast.error("Erro ao excluir template. Tente novamente.");
    }
  };

  const handlePrintBadges = async () => {
    if (printableItems().length === 0 || !printRootRef) return;
    setPrintMode("badges");
    setIsPrinting(true);
    try {
      // Allow DOM to update printable elements
      await new Promise((resolve) => setTimeout(resolve, 150));
      await printElement(printRootRef, "Crachás");
    } catch {
      toast.error("Erro ao preparar impressão.");
    } finally {
      setIsPrinting(false);
    }
  };

  const handlePrintQrs = async (sizeMm: number) => {
    if (printableItems().length === 0 || !printRootRef) return;
    setPrintQrSizeMm(sizeMm);
    setPrintMode("qrs");
    setIsPrinting(true);
    try {
      await new Promise((resolve) => setTimeout(resolve, 150));
      await printElement(printRootRef, "QR Codes dos Crachás");
    } catch {
      toast.error("Erro ao preparar impressão dos QR codes.");
    } finally {
      setIsPrinting(false);
    }
  };

  return (
    <>
      {/* Hidden container for printing */}
      <div class="hidden print:block">
        <div ref={(el) => (printRootRef = el)}>
          <Show
            when={printMode() === "badges"}
            fallback={
              <For each={printableItems()}>
                {(badge) => (
                  <PrintableQrItem
                    badge={badge}
                    printQrSizeMm={printQrSizeMm}
                    participantNames={participantNames}
                  />
                )}
              </For>
            }
          >
            <For each={printableItems()}>
              {(badge) => (
                <PrintableBadgeItem
                  badge={badge}
                  participantNames={participantNames}
                  location={location}
                />
              )}
            </For>
          </Show>
        </div>
      </div>

      {/* Main Admin UI */}
      <div class="mx-auto max-w-7xl space-y-6 print:hidden">
        {/* Header with Title & Description */}
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 class="text-xl sm:text-2xl font-bold tracking-tight text-foreground">
              Crachás da Edição
            </h1>
            <p class="text-xs sm:text-sm text-muted-foreground">
              Crie templates visuais e gerencie as credenciais e impressões dos participantes.
            </p>
          </div>
        </div>

        {/* Navigation Tabs */}
        <nav class="flex gap-1 border-b border-border overflow-x-auto scrollbar-none">
          <button
            type="button"
            onClick={() => setActiveSection("templates")}
            class={cn(
              "inline-flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-2.5 text-sm font-medium transition-colors cursor-pointer",
              activeSection() === "templates"
                ? "border-primary text-primary"
                : "border-transparent text-muted-foreground hover:text-foreground",
            )}
          >
            <FileText class="size-4" />
            <span>Templates</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSection("emissions")}
            class={cn(
              "inline-flex items-center gap-2 whitespace-nowrap border-b-2 px-4 py-2.5 text-sm font-medium transition-colors cursor-pointer",
              activeSection() === "emissions"
                ? "border-primary text-primary"
                : "border-transparent text-muted-foreground hover:text-foreground",
            )}
          >
            <BadgeCheck class="size-4" />
            <span>Crachás emitidos</span>
            <Show when={emissions().length > 0}>
              <span class="ml-1 rounded-full bg-muted px-2 py-0.5 text-[11px] text-muted-foreground">
                {emissions().length}
              </span>
            </Show>
          </button>
        </nav>

        {/* Content: Templates */}
        <Show when={activeSection() === "templates"}>
          <PaginatedContainer<BadgeTemplate>
            items={filteredTemplates()}
            layout="grid"
            minItemWidth="16rem"
            maxRows={(columns) => (columns === 1 ? 8 : 4)}
            gap="2"
            sort={templateSort()}
            onSortChange={setTemplateSort}
            sortFields={[
              {
                key: "name",
                label: "Nome",
                ascLabel: "A → Z",
                descLabel: "Z → A",
              },
              {
                key: "created_at",
                label: "Data de criação",
                ascLabel: "Mais antigos primeiro",
                descLabel: "Mais recentes primeiro",
                comparator: (a, b) =>
                  new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
              },
            ]}
            filterValue={templateFilter()}
            onFilterChange={setTemplateFilter}
            filterPlaceholder="Buscar por nome do template..."
            itemLabel="templates"
            headerActions={
              <Button
                variant="default"
                size="sm"
                class="h-9 gap-1.5 px-3 text-xs cursor-pointer"
                onClick={() => handleOpenEditor()}
              >
                <Plus class="size-4" />
                <span>Novo template</span>
              </Button>
            }
            emptyState={
              <EmptyState
                class="border-0 bg-transparent px-0 py-4 shadow-none"
                icon={<BadgeCheck class="size-6 text-foreground/70" />}
                eyebrow="Crachás da edição"
                title="Nenhum template cadastrado"
                description={
                  templateFilter()
                    ? "Nenhum template corresponde à busca informada."
                    : "Crie o primeiro modelo para começar a emitir crachás nesta edição."
                }
                action={
                  <Button
                    variant="outline"
                    class="gap-2 rounded-sm py-4 cursor-pointer"
                    onClick={() => handleOpenEditor()}
                  >
                    <Plus class="size-4" />
                    Novo template
                  </Button>
                }
              />
            }
            renderItems={(slice, options) => (
              <>
                <AdminCreateBadgeCard
                  index={0}
                  animate={options.animate}
                  onCreate={() => handleOpenEditor()}
                />
                <For each={slice}>
                  {(template, index) => (
                    <AdminTemplateBadgeItem
                      template={template}
                      index={index() + 1}
                      animate={options.animate}
                      ticketNames={ticketNames}
                      location={location}
                      onEdit={() => handleOpenEditor(template.id)}
                      onDuplicate={() => handleOpenEditor(template.id, true)}
                      onDelete={() => handleDeleteTemplate(template)}
                    />
                  )}
                </For>
              </>
            )}
          />
        </Show>

        {/* Content: Emissions */}
        <Show when={activeSection() === "emissions"}>
          <PaginatedContainer<BadgePrintItem>
            items={filteredPrintItems()}
            layout="grid"
            minItemWidth="16rem"
            maxRows={(columns) => (columns === 1 ? 8 : 4)}
            gap="2"
            sort={emissionSort()}
            onSortChange={setEmissionSort}
            sortFields={[
              {
                key: "template_name",
                label: "Template",
                ascLabel: "A → Z",
                descLabel: "Z → A",
              },
              {
                key: "user_id",
                label: "Participante",
                ascLabel: "A → Z",
                descLabel: "Z → A",
              },
            ]}
            filterValue={emissionFilter()}
            onFilterChange={setEmissionFilter}
            filterPlaceholder="Buscar por evento, edição ou template..."
            itemLabel="crachás"
            headerActions={
              <div class="flex flex-wrap items-center gap-1.5 sm:gap-2">
                <Button
                  variant={printedAfter() ? "default" : "outline"}
                  size="sm"
                  onClick={() => setDateDialogOpen(true)}
                  class="relative h-9 gap-1.5 px-2.5 sm:px-3 text-xs cursor-pointer"
                >
                  <CalendarClock class="size-3.5 sm:size-4" />
                  <span class="hidden sm:inline">Filtrar data</span>
                  <span class="sm:hidden">Data</span>
                  <Show when={printedAfter()}>
                    <span class="size-1.5 rounded-full bg-primary-foreground" />
                  </Show>
                </Button>

                <Button
                  variant="default"
                  size="sm"
                  disabled={isPrinting() || printableItems().length === 0}
                  onClick={handlePrintBadges}
                  class="h-9 gap-1.5 px-2.5 sm:px-3 text-xs cursor-pointer"
                >
                  <Printer class="size-3.5 sm:size-4" />
                  <span>{isPrinting() && printMode() === "badges" ? "Preparando..." : "Crachás"}</span>
                </Button>

                <Button
                  variant="outline"
                  size="sm"
                  disabled={isPrinting() || printableItems().length === 0}
                  onClick={() => setQrDialogOpen(true)}
                  class="h-9 gap-1.5 px-2.5 sm:px-3 text-xs cursor-pointer"
                >
                  <QrCode class="size-3.5 sm:size-4" />
                  <span class="hidden sm:inline">Imprimir </span>
                  <span>QR codes</span>
                </Button>
              </div>
            }
            emptyState={
              <EmptyState
                class="border-0 bg-transparent px-0 py-4 shadow-none"
                icon={<BadgeCheck class="size-6 text-foreground/70" />}
                eyebrow="Crachás emitidos"
                title="Nenhum crachá emitido"
                description="Os crachás serão gerados automaticamente quando os participantes confirmarem suas inscrições."
              />
            }
            renderItems={(slice, options) => (
              <For each={slice}>
                {(badge, index) => (
                  <AdminEmissionBadgeItem
                    badge={badge}
                    index={index()}
                    animate={options.animate}
                    participantNames={participantNames}
                    location={location}
                  />
                )}
              </For>
            )}
          />
        </Show>
      </div>

      {/* Dialogs */}
      <DateFilterDialog
        open={dateDialogOpen()}
        onOpenChange={setDateDialogOpen}
        printedAfter={printedAfter()}
        onApply={setPrintedAfter}
      />

      <QrPrintDialog
        open={qrDialogOpen()}
        onOpenChange={setQrDialogOpen}
        loading={isPrinting()}
        onConfirmPrint={handlePrintQrs}
      />
    </>
  );
}
