// front/univents/src/features/badges/editor/badge-canvas.tsx
import { Maximize, Minus, Plus } from "lucide-react";
import QRCode from "qrcode";
import type { CSSProperties, PointerEvent as ReactPointerEvent } from "react";
import { useEffect, useMemo, useRef, useState } from "react";
import { useElementSize } from "../../certifications/editor/hooks/use-element-size";
import {
  type TextElementAdapter,
  TextElementView,
} from "../../certifications/editor/ui/elements/text-element-view";
import type { BadgeElement, BadgeTemplateCreate } from "../model";
import { BadgeElementFrame } from "./badge-element-frame";

const CHECKERBOARD: CSSProperties = {
  backgroundColor: "#e5e7eb",
  backgroundImage:
    "linear-gradient(45deg, #d1d5db 25%, transparent 25%), linear-gradient(-45deg, #d1d5db 25%, transparent 25%), linear-gradient(45deg, transparent 75%, #d1d5db 75%), linear-gradient(-45deg, transparent 75%, #d1d5db 75%)",
  backgroundSize: "16px 16px",
  backgroundPosition: "0 0, 0 8px, 8px -8px, -8px 0",
};

function QrPreview({
  element,
}: {
  element: Extract<BadgeElement, { type: "qr" }>;
}) {
  const matrix = useMemo(
    () => QRCode.create("https://univents.app/check-in/example").modules,
    [],
  );
  const margin = 2;
  const size = matrix.size + margin * 2;
  const modules = [];
  for (let row = 0; row < matrix.size; row++) {
    for (let column = 0; column < matrix.size; column++) {
      if (!matrix.get(row, column)) continue;
      const x = column + margin;
      const y = row + margin;
      modules.push(
        element.style === "dots" ? (
          <circle
            key={`${row}-${column}`}
            cx={x + 0.5}
            cy={y + 0.5}
            r="0.42"
            fill={element.foreground}
          />
        ) : (
          <rect
            key={`${row}-${column}`}
            x={x}
            y={y}
            width="1"
            height="1"
            rx={element.style === "rounded" ? 0.28 : 0}
            fill={element.foreground}
          />
        ),
      );
    }
  }
  return (
    <svg
      role="img"
      aria-label="QR Code de check-in"
      className="size-full"
      viewBox={`0 0 ${size} ${size}`}
      style={{ background: element.background }}
      shapeRendering={
        element.style === "square" ? "crispEdges" : "geometricPrecision"
      }
    >
      {modules}
    </svg>
  );
}

function BadgeElementView({
  element,
  editing,
  adapter,
  previewValues,
}: {
  element: BadgeElement;
  editing: boolean;
  adapter: TextElementAdapter;
  previewValues: Record<string, string>;
}) {
  if (element.type === "image")
    return (
      <img
        src={element.src}
        alt=""
        draggable={false}
        className="size-full"
        style={{
          objectFit: element.fit,
          borderRadius: element.radius,
          opacity: element.opacity,
        }}
      />
    );
  if (element.type === "qr") return <QrPreview element={element} />;
  const previewElement = editing
    ? element
    : {
        ...element,
        paragraphs: element.paragraphs.map((paragraph) => ({
          ...paragraph,
          runs: paragraph.runs.map((run) => ({
            ...run,
            text: run.text.replace(
              /\{\{([^}]+)\}\}/g,
              (match, key: string) => previewValues[key] || match,
            ),
          })),
        })),
      };
  return (
    <TextElementView
      element={previewElement}
      editing={editing}
      adapter={adapter}
    />
  );
}

interface BadgeCanvasProps {
  design: BadgeTemplateCreate["design_data"];
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onChangeElement: (id: string, changes: Partial<BadgeElement>) => void;
  onDeleteElement: (id: string) => void;
  textAdapter: TextElementAdapter;
  previewValues: Record<string, string>;
}

export function BadgeCanvas({
  design,
  selectedId,
  onSelect,
  onChangeElement,
  onDeleteElement,
  textAdapter,
  previewValues,
}: BadgeCanvasProps) {
  const { ref: stageRef, size: viewport } = useElementSize<HTMLDivElement>();
  const [zoom, setZoom] = useState(1);
  const [panning, setPanning] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const effectiveTextAdapter = useMemo(
    () => ({ ...textAdapter, stopEditing: () => setEditingId(null) }),
    [textAdapter],
  );
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const panStart = useRef<{
    pointerX: number;
    pointerY: number;
    x: number;
    y: number;
  } | null>(null);

  const fitScale = useMemo(() => {
    if (!viewport.width || !viewport.height) return 0.62;
    return Math.min(
      (viewport.width - 96) / design.canvas.width,
      (viewport.height - 96) / design.canvas.height,
      2,
    );
  }, [design.canvas, viewport]);
  const scale = fitScale * zoom;

  useEffect(() => {
    const stage = stageRef.current;
    if (!stage) return;
    const wheel = (event: WheelEvent) => {
      event.preventDefault();
      setZoom((value) =>
        Math.min(4, Math.max(0.25, value * (event.deltaY < 0 ? 1.1 : 0.9))),
      );
    };
    stage.addEventListener("wheel", wheel, { passive: false });
    return () => stage.removeEventListener("wheel", wheel);
  }, [stageRef]);

  function startPan(event: ReactPointerEvent<HTMLDivElement>) {
    const target = event.target as HTMLElement;
    if (target.closest("[data-badge-element], [data-canvas-controls]")) return;
    onSelect(null);
    setEditingId(null);
    panStart.current = {
      pointerX: event.clientX,
      pointerY: event.clientY,
      ...pan,
    };
    setPanning(true);
    event.currentTarget.setPointerCapture(event.pointerId);
  }

  function finishPan(event: ReactPointerEvent<HTMLDivElement>) {
    panStart.current = null;
    setPanning(false);
    if (event.currentTarget.hasPointerCapture(event.pointerId)) {
      event.currentTarget.releasePointerCapture(event.pointerId);
    }
  }

  return (
    <main
      ref={stageRef}
      className={`relative min-w-90 flex-1 touch-none overflow-hidden ${panning ? "cursor-grabbing" : "cursor-grab"}`}
      style={CHECKERBOARD}
      onPointerDown={startPan}
      onPointerMove={(event) => {
        const start = panStart.current;
        if (!start) return;
        setPan({
          x: start.x + event.clientX - start.pointerX,
          y: start.y + event.clientY - start.pointerY,
        });
      }}
      onPointerUp={finishPan}
      onPointerCancel={finishPan}
    >
      <div
        data-canvas-controls
        className="absolute bottom-4 left-1/2 z-50 flex -translate-x-1/2 select-none items-center gap-1 rounded-lg border border-muted bg-card p-1 shadow-lg"
        onPointerDown={(event) => event.stopPropagation()}
      >
        <button
          type="button"
          className="rounded p-1.5 hover:bg-muted"
          aria-label="Diminuir zoom"
          onClick={() => setZoom((value) => Math.max(0.25, value / 1.2))}
        >
          <Minus className="size-4" />
        </button>
        <span className="w-14 text-center text-xs tabular-nums">
          {Math.round(scale * 100)}%
        </span>
        <button
          type="button"
          className="rounded p-1.5 hover:bg-muted"
          aria-label="Aumentar zoom"
          onClick={() => setZoom((value) => Math.min(4, value * 1.2))}
        >
          <Plus className="size-4" />
        </button>
        <button
          type="button"
          className="rounded p-1.5 hover:bg-muted"
          aria-label="Ajustar à tela"
          onClick={() => {
            setZoom(1);
            setPan({ x: 0, y: 0 });
          }}
        >
          <Maximize className="size-4" />
        </button>
      </div>

      <div
        className="absolute left-1/2 top-1/2 shadow-2xl ring-1 ring-muted"
        style={{
          width: design.canvas.width * scale,
          height: design.canvas.height * scale,
          transform: `translate(calc(-50% + ${pan.x}px), calc(-50% + ${pan.y}px))`,
        }}
      >
        <div
          className="relative overflow-hidden"
          style={{
            width: design.canvas.width,
            height: design.canvas.height,
            transform: `scale(${scale})`,
            transformOrigin: "top left",
            backgroundColor: design.backgroundColor,
            backgroundImage: design.background
              ? `url(${design.background})`
              : undefined,
            backgroundSize: "cover",
            backgroundPosition: "center",
          }}
        >
          {design.elements.map((element, index) => (
            <BadgeElementFrame
              key={element.id}
              bounds={element}
              scale={scale}
              zIndex={index + 1}
              canvas={design.canvas}
              minSize={element.type === "qr" ? 32 : 4}
              overflowAllowance={element.type === "image" ? 0.5 : 0}
              selected={selectedId === element.id}
              editing={editingId === element.id}
              onSelect={() => {
                if (editingId && editingId !== element.id) setEditingId(null);
                onSelect(element.id);
              }}
              onDoubleClick={
                element.type === "text"
                  ? () => setEditingId(element.id)
                  : undefined
              }
              onChangeBounds={(bounds) => onChangeElement(element.id, bounds)}
              onDelete={
                element.type === "qr"
                  ? undefined
                  : () => onDeleteElement(element.id)
              }
            >
              <BadgeElementView
                element={element}
                editing={editingId === element.id}
                adapter={effectiveTextAdapter}
                previewValues={previewValues}
              />
            </BadgeElementFrame>
          ))}
        </div>
      </div>
    </main>
  );
}

// front/univents-solid/src/features/badges/editor/BadgeCanvas.tsx
import type { JSX } from "@solidjs/web";
import {
  For,
  Show,
  createEffect,
  createMemo,
  createSignal,
} from "solid-js";
import {
  EditableText,
  EditorElementFrame,
  QrRenderer,
  StaticText,
  type ElementBounds,
  type TextElementAdapter,
} from "@/features/editor";
import type { BadgeDesign, BadgeElement } from "../model";

export interface BadgeCanvasProps {
  design: BadgeDesign;
  selectedId: string | null;
  onSelect: (id: string | null) => void;
  onChangeElement: (id: string, element: Partial<BadgeElement>) => void;
  onDeleteElement?: (id: string) => void;
  textAdapter?: TextElementAdapter;
  previewValues?: Record<string, string>;
}

export function BadgeCanvas(props: BadgeCanvasProps): JSX.Element {
  let containerRef: HTMLDivElement | undefined;
  const [scale, setScale] = createSignal(1, { ownedWrite: true });
  const [editingId, setEditingId] = createSignal<string | null>(null, {
    ownedWrite: true,
  });

  const elementIds = createMemo(() => props.design.elements.map((e) => e.id));

  createEffect(
    () => ({
      width: props.design.canvas.width,
      height: props.design.canvas.height,
    }),
    ({ width, height }) => {
      if (!containerRef) return;
      const { clientWidth, clientHeight } = containerRef;
      const padding = 64;
      const availW = Math.max(100, clientWidth - padding);
      const availH = Math.max(100, clientHeight - padding);
      const scaleW = availW / width;
      const scaleH = availH / height;
      setScale(Math.min(1.5, Math.max(0.2, Math.min(scaleW, scaleH))));
    },
  );

  return (
    <div
      ref={(el) => (containerRef = el)}
      class="relative flex flex-1 items-center justify-center overflow-auto p-8 select-none"
      style={{
        background:
          "radial-gradient(circle, var(--color-muted) 1px, transparent 1px)",
        "background-size": "16px 16px",
      }}
      onPointerDown={(event) => {
        if (event.target === event.currentTarget) {
          props.onSelect(null);
          setEditingId(null);
        }
      }}
    >
      <div
        class="relative shadow-2xl transition-all duration-150"
        style={{
          width: `${props.design.canvas.width}px`,
          height: `${props.design.canvas.height}px`,
          transform: `scale(${scale()})`,
          "transform-origin": "center center",
          "background-color": props.design.backgroundColor,
          "background-image": props.design.background
            ? `url(${props.design.background})`
            : undefined,
          "background-size": "cover",
          "background-position": "center",
        }}
        onPointerDown={(event) => {
          if (event.target === event.currentTarget) {
            props.onSelect(null);
            setEditingId(null);
          }
        }}
      >
        <For each={elementIds()}>
          {(id) => (
            <CanvasElementItem
              id={id}
              design={() => props.design}
              scale={scale}
              selectedId={() => props.selectedId}
              editingId={editingId}
              onSelect={(selectedId) => {
                props.onSelect(selectedId);
                if (editingId() && editingId() !== selectedId) {
                  setEditingId(null);
                }
              }}
              onStartEditing={(editId) => {
                props.onSelect(editId);
                setEditingId(editId);
              }}
              onStopEditing={() => setEditingId(null)}
              onChangeBounds={(bounds) => props.onChangeElement(id, bounds)}
              onDeleteElement={
                props.onDeleteElement ? () => props.onDeleteElement?.(id) : undefined
              }
              previewValues={props.previewValues}
              textAdapter={props.textAdapter}
            />
          )}
        </For>
      </div>
    </div>
  );
}

function CanvasElementItem(props: {
  id: string;
  design: () => BadgeDesign;
  scale: () => number;
  selectedId: () => string | null;
  editingId: () => string | null;
  onSelect: (id: string) => void;
  onStartEditing: (id: string) => void;
  onStopEditing: () => void;
  onChangeBounds: (bounds: ElementBounds) => void;
  onDeleteElement?: () => void;
  previewValues?: Record<string, string>;
  textAdapter?: TextElementAdapter;
}): JSX.Element {
  const element = createMemo(() =>
    props.design().elements.find((e) => e.id === props.id),
  );
  const index = createMemo(() =>
    props.design().elements.findIndex((e) => e.id === props.id),
  );
  const isSelected = createMemo(() => props.selectedId() === props.id);
  const isEditing = createMemo(() => props.editingId() === props.id);

  return (
    <Show when={element()}>
      {(el) => (
        <EditorElementFrame
          bounds={el()}
          scale={props.scale()}
          canvas={props.design().canvas}
          zIndex={index() + 1}
          selected={isSelected()}
          editing={isEditing()}
          onSelect={() => props.onSelect(props.id)}
          onDoubleClick={() => {
            if (el().type === "text") {
              props.onStartEditing(props.id);
            }
          }}
          onChangeBounds={props.onChangeBounds}
          onDelete={el().type !== "qr" ? props.onDeleteElement : undefined}
        >
          <Show
            when={el().type === "text"}
            fallback={
              <Show
                when={el().type === "image"}
                fallback={
                  <div class="h-full w-full pointer-events-none">
                    <QrRenderer
                      value="https://univents.app/check-in"
                      foreground={
                        el().type === "qr"
                          ? (el() as Extract<BadgeElement, { type: "qr" }>).foreground
                          : "#000000"
                      }
                      background={
                        el().type === "qr"
                          ? (el() as Extract<BadgeElement, { type: "qr" }>).background
                          : "#ffffff"
                      }
                      style={
                        el().type === "qr"
                          ? (el() as Extract<BadgeElement, { type: "qr" }>).style
                          : "square"
                      }
                    />
                  </div>
                }
              >
                {(() => {
                  const img = () =>
                    el() as Extract<BadgeElement, { type: "image" }>;
                  return (
                    <img
                      src={img().src}
                      alt=""
                      class="h-full w-full pointer-events-none select-none"
                      style={{
                        "object-fit": img().fit,
                        opacity: img().opacity,
                        "border-radius": `${img().radius}px`,
                      }}
                      draggable={false}
                    />
                  );
                })()}
              </Show>
            }
          >
            {(() => {
              const txt = () =>
                el() as Extract<BadgeElement, { type: "text" }>;

              return (
                <div
                  class="relative h-full w-full cursor-text"
                  onDblClick={(e) => {
                    e.stopPropagation();
                    props.onStartEditing(props.id);
                  }}
                >
                  <Show
                    when={isEditing()}
                    fallback={
                      <StaticText
                        paragraphs={txt().paragraphs}
                        values={props.previewValues}
                        showVariables={false}
                      />
                    }
                  >
                    <EditableText
                      element={txt()}
                      adapter={props.textAdapter}
                      onStopEditing={props.onStopEditing}
                    />
                  </Show>
                </div>
              );
            })()}
          </Show>
        </EditorElementFrame>
      )}
    </Show>
  );
}
